### ISSUE TITLE
pki bundle is not being backed up

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke#1007]
**RKE version:** 
v0.1.11

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1855.5.0
VERSION_ID=1855.5.0
BUILD_ID=2018-10-22-2305
PRETTY_NAME="Container Linux by CoreOS 1855.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

```
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 3h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```

I can see that the etcd-rolling-snapshots container is running but i am unable to find the backed up pki bundle when it runs.
