### ISSUE TITLE
Kubernetes etcd vulnerability (Ports 2380 and 2379) Sweet32 CVE-2016-2183

### ISSUE THREAD

**Issue by rstpv** [rancher/rke#1008]
**RKE version:** 0.1.11

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

uname -r: 4.18.5-1.el7.elrepo.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 
VirtualBox

**cluster.yml file:**
```
network:
  plugin: flannel
nodes:
- address: rancher-master-01
  user: user
  role: [controlplane,etcd]
- address: rancher-master-02
  user: user
  role: [controlplane,etcd]
- address: rancher-master-03
  user: user
  role: [controlplane,etcd]
- address: rancher-worker-01
  user: user
  role: [worker]
- address: rancher-worker-02
  user: user
  role: [worker]
- address: rancher-worker-03
  user: user
  role: [worker]
system_images:
    etcd: quay.io/coreos/etcd:v3.3.10
services:
  etcd:
    extra_args:
      cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"

  kube-api:
    extra_args:
      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
  kubelet:
    extra_args:
      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
  kube-controller:
    extra_args:
      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
```
**Steps to Reproduce:**
The issue is the same as in: https://github.com/rancher/rancher/issues/10354 but on a different port.

If you test with a default yml, without the changed etcd image and the cipher suites ports 2380 and 2379 are vulnerables to:

-  SWEET32 (CVE-2016-2183, CVE-2016-6329)    VULNERABLE, uses 64 bit block ciphers

-  LUCKY13 (CVE-2013-0169), experimental     potentially VULNERABLE, uses cipher block chaining (CBC) ciphers with TLS. Check patches 

According to testssl report https://github.com/drwetter/testssl.sh

**Results:**
Using the coreos etcd v3.3.10 which has fixed the weak ciphers using the arg cipher-suites (Since version 3.3.7) the vulnerability goes away.

I want to know if this is the way to go. Everything seems to be working but I'm not sure if there are any implications of using an etcd image outside rancher docker hub (And of upgrading the etcd docker image version as the latest etcd image on rancher docker hub is 3.2.4).

I appreciate any guidance or recommendations on this.
