### ISSUE TITLE
Etcd snapshots continue to be saved even after disabling snapshots 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rke#1014]
**RKE version:**
rke version v0.1.12-rc3
**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Steps to Reproduce:**
1. Create an RKE cluster using "./rke up" command with the below config:
**cluster.yml file:**
```
auth:
  strategy: x509
nodes:
  - address: abcd
    user: root
    role: [etcd,controlplane,worker]
  - address: defg
    user: root
    role: [etcd, controlplane, worker]
  - address: hijk
    user: root
    role: [etcd, controlplane, worker]
services:
  etcd:
    snapshot: true  # enables recurring etcd snapshots
    creation: 5m0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```
2. Ensure `etcd-rolling-snapshots` container is running snapshots are taken every 5 mins in the directory `/opt/rke/etcd-snapshots`
3. Edit the config file with snapshot=false
4. Re-run rke up command
etcd snapshots continue to be saved every 5 minutes in directory `/opt/rke/etcd-snapshots`
Snapshots should not be saved after it has been disabled
