### ISSUE TITLE
Support for configuring cloud-provider

### ISSUE THREAD

**Issue by de13** [rancher/rke#102]
I ask while I trying to figure out where to set the option:
```
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {--cloud-provider=aws}
[...]
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {--cloud-provider=aws}
    cluster_domain: cluster.local
```
