### ISSUE TITLE
Error response from daemon: chown /etc/resolv.conf: operation not permitted 

### ISSUE THREAD

**Issue by keigohtr** [rancher/rke#1029]
**RKE version:**
v0.1.11

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.5

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Private Cloud (OpenStack)

**cluster.yml file:**
```
nodes:
  - address: [Our private DNS name]
    user: [Our private user]
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

**Steps to Reproduce:**
`rke up --config ./rancher-cluster.yml`

**Results:**
`[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [Our private DNS name]: Error response from daemon: chown /etc/resolv.conf: operation not permitted`
