### ISSUE TITLE
Clusters created from rke are getting stuck in "waiting for server-url setting to be set"

### ISSUE THREAD

**Issue by tibers** [rancher/rke#1052]
**RKE version:**
rke version v0.1.12

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.03.1-ce, build 9ee9f40
Docker version 17.xxxxx (both seem to do it)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="RancherOS"
VERSION=v1.4.2
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.2
PRETTY_NAME="RancherOS v1.4.2"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
With Docker 18 I need the first line, I was experimenting to see if using k8s 1.12 or 1.11 made a difference or Docker 17 or 18. Basically I can reproduce this across any combination of docker and kubernetes, using centos or rancheros. Replace 10.x.x.x with real IPs.

```
ignore_docker_version: true
kubernetes_version: v1.12.1-rancher1-1

nodes:
  - address: 10.x.x.x
    user: rancher
    role: [controlplane,worker,etcd]
    ssh_key_path: ./rancher.rsa
  - address: 10.x.x.x
    user: rancher
    role: [controlplane,worker,etcd]
    ssh_key_path: ./rancher.rsa
  - address: 10.x.x.x
    user: rancher
    role: [controlplane,worker,etcd]
    ssh_key_path: ./rancher.rsa
```

**Steps to Reproduce:**
`rke up --config myconfig.yaml`

**Results:**
Two of the rancher pods look happy, but one of them will repeatedly say:
```
2018/12/04 13:58:48 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/12/04 14:03:04 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
```

`curl`ing the pod like so: `curl -s -k https://10.245.49.68/login --header 'Host: myhost.com'` results in a 404. It's like the cluster is never coming up to ready, so how do we do an HA install? :(
