### ISSUE TITLE
RKE should allow setting extra_env/etc. on the ingress provider

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1104]
Currently, it is not possible to set extra_env/extra_binds on the ingress provider. We should allow this functionality, in order to allow users to perform customizations to the nginx ingress controller. This can include things like adding proxies, adding custom file-based certs, etc.

**Comment by superseb** [comment]
https://github.com/rancher/rancher/issues/16868

**Comment by cloudnautique** [comment]
This should be under similar keys to the upstream helm chart: https://github.com/helm/charts/tree/master/stable/nginx-ingress

Specifically the functionality introduced by:
`controller.extraVolumeMounts`
`controller.extraEnvs`

**Comment by mrajashree** [comment]
The ingress config now accepts three more fields: ExtraEnvs, ExtraVolumes and ExtraVolumeMounts.
They refer the k8s native types EnvVar, Volume and VolumeMount respectively.

For example:
```
  ingress:
    provider: nginx
    extra_envs:
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: testenvvar
        value: testvalue
    extra_volume_mounts:
      - mountPath: /testmountpath
        name: testvol
    extra_volumes:
      - emptyDir: {}
        name: testvol
```

This should result in creating 2 env vars in the ingress nginx pod:
1. $MY_NODE_NAME with the node name on which it's running as the value
2. $testenvvar with `testvalue` as value.
3. A dir named testmountpath will be created within the pod at `/testmountpath`

**Comment by soumyalj** [comment]
Tested with rancher version v2.3-head from Nov 11
Created a DO cluster and specified the extra_envs, extra_volume_mounts, extra_volumes in cluster.yml 
```
ingress:
    provider: nginx
    extra_envs:
      - name: soumyanode1
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: testenvvar
        value: testvalue
    extra_volume_mounts:
      - mountPath: /testmountpath
        name: testvol
    extra_volumes:
      - emptyDir: {}
        name: testvol
```
The cluster got created successfully. In the pod , `nginx-ingress-controller-g8jqp`, the volume mount `/testmountpath` was created as expected. Read/Write to the volume was successful. 
The env variables were also verified as below in the pod by typing `env` command
```
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=soumyanode1
DEFAULT_HTTP_BACKEND_PORT_80_TCP_PROTO=tcp
POD_NAME=nginx-ingress-controller-g8jqp
POD_NAMESPACE=ingress-nginx
soumyanode1=soumyanode1
PWD=/etc/nginx
DEFAULT_HTTP_BACKEND_SERVICE_HOST=abcd
HOME=/var/www
KUBERNETES_PORT_443_TCP=tcp://abcd:443
DEFAULT_HTTP_BACKEND_PORT_80_TCP_ADDR=abcd
testenvvar=testvalue
TERM=xterm-256color
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=abcd
KUBERNETES_SERVICE_HOST=abcd
``

**Comment by sangeethah** [comment]
@soumyalj  `v1.0.0-rc3` has the fix for testing rke cli use case.

**Comment by soumyalj** [comment]
Tested with rke version v1.0.0-rc3
Created a rke cluster using the cluster.yml file below:
```
auth:
  strategy: x509
nodes:
  - address: abcd
    user: root
    role: [etcd,controlplane,worker]
  - address: efgh
    user: root
    role: [etcd,controlplane,worker]
  - address: ijkl
    user: root
    role: [etcd,controlplane,worker]
ingress:
    provider: nginx
    extra_envs:
      - name: MYNODENAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: testenvvar
        value: testvalue
    extra_volume_mounts:
      - mountPath: /data
        name: testvol
    extra_volumes:
      - emptyDir: {}
        name: testvol
```
Cluster came up successfully. rancher/nginx-ingress-controller  pod was created successfully on each node. Exec'ed into each of the containers and verified that the volume mount /data exists. 
Write and read to the volume was successful.
