### ISSUE TITLE
ExternalTrafficPolicy:Local doesn't work when Weave is selected as the network add-on (config fix available)

### ISSUE THREAD

**Issue by jiphex** [rancher/rke#1114]
**RKE version: 0.1.15**
**Docker version: 1.13.1 (centos-7)**
**Operating system and kernel: 3.10.0-862.el7.x86_64**
**Type/provider of hosts: Bare-metal**
**cluster.yml file:**
```
...snip...
network:
  plugin: weave
system_images:
  weave_node: weaveworks/weave-kube:2.5.0
  weave_cni: weaveworks/weave-npc:2.5.0
addons: (MetalLB, HAProxy Ingress Controller)
...snip...
```

**Steps to Reproduce:**
* Deploy RKE, select Weave as the CNI
* Create a service, set service.spec.externalTrafficPolicy: Local

**Results:**
When I define a service when externalTrafficPolicy: Local (using MetalLB to direct external traffic to the nodes), I'd expect the real connecting IP address of a client to make it through to the pods exposed by the service.

Due to a [bug](https://github.com/weaveworks/weave/issues/2924) in Weave, this wasn't originally possible. The issue was fixed in weave v2.4.0 but a flag (environment variable on the weave-kube container in the Weave DS) is [required to make this work properly](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#configuration-options).

Would it be possible to add an option for the Weave network plugin in the style of the other CNI [options](https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/network-plugins/) to enable this in the [template](https://github.com/rancher/rke/blob/eedec3c1e9a76708c4821d1172f0ed842b3c9e47/templates/weave.go#L51)?
