### ISSUE TITLE
rke canal cni flannel options

### ISSUE THREAD

**Issue by pasikarkkainen** [rancher/rke#1125]
rke network-plugins documentation:
https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/network-plugins/

paste from the documentation:

Canal Network Plug-in Options
```
network:
    plugin: canal
    options:
        canal_iface: eth1
        canal_flannel_backend_type: vxlan
```
But the question is how to configure other "canal_flannel_backend" options? For example if one sets "canal_flannel_backend_type" to "ipsec" (https://github.com/coreos/flannel/blob/master/Documentation/backends.md#ipsec), one needs to also configure "PSK", which is a required setting, and optionally also "UDPEncap" and "ESPProposal" settings.

Is it currently possible to use and configure canal_flannel_backend_types other than vxlan?

In some scenarios it's a requirement to encrypt all the networking between the kubernetes nodes, thus for example flannel ipsec backend would allow doing that.

Thanks!
