### ISSUE TITLE
job rke-network-plugin-deploy-job never complete (LXC)

### ISSUE THREAD

**Issue by tlvenn** [rancher/rke#1139]
**RKE version:**
0.1.15
**Docker version: (`docker version`,`docker info` preferred)**
17.03.3-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 9 (stretch) [4.15.18-9-pve]
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
LXC
**cluster.yml file:**
```
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 178.32.115.164
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./infra/ssh/id_rsa
  labels: {}
- address: 178.32.116.113
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./infra/ssh/id_rsa
  labels: {}
- address: 178.32.116.114
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./infra/ssh/id_rsa
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: null
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.2.18
  alpine: rancher/rke-tools:v0.1.15
  nginx_proxy: rancher/rke-tools:v0.1.15
  cert_downloader: rancher/rke-tools:v0.1.15
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.15
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.10
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.11.6-rancher1
  flannel: rancher/coreos-flannel:v0.10.0
  flannel_cni: rancher/coreos-flannel-cni:v0.3.0
  calico_node: rancher/calico-node:v3.1.3
  calico_cni: rancher/calico-cni:v3.1.3
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.1.3
  canal_cni: rancher/calico-cni:v3.1.3
  canal_flannel: rancher/coreos-flannel:v0.10.0
  wave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.16.2-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
  metrics_server: rancher/metrics-server-amd64:v0.2.1
ssh_key_path: ./infra/ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
monitoring:
  provider: ""
  options: {}
```
**Steps to Reproduce:**
rke up
**Results:**
```
INFO[0618] [worker] Successfully started Worker Plane..
INFO[0618] [sync] Syncing nodes Labels and Taints
INFO[0626] [sync] Successfully synced nodes Labels and Taints
DEBU[0626] Host: 178.32.115.164 has role: controlplane
DEBU[0626] Host: 178.32.115.164 has role: worker
DEBU[0626] Host: 178.32.115.164 has role: etcd
DEBU[0626] Host: 178.32.116.113 has role: controlplane
DEBU[0626] Host: 178.32.116.113 has role: worker
DEBU[0626] Host: 178.32.116.113 has role: etcd
DEBU[0626] Host: 178.32.116.114 has role: controlplane
DEBU[0626] Host: 178.32.116.114 has role: worker
DEBU[0626] Host: 178.32.116.114 has role: etcd
INFO[0626] [network] Setting up network plugin: canal
INFO[0626] [addons] Saving addon ConfigMap to Kubernetes
INFO[0627] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin
INFO[0627] [addons] Executing deploy job..
DEBU[0629] [k8s] waiting for job rke-network-plugin-deploy-job to complete..
FATA[0676] Failed to get job complete status: <nil>
```

**Additional Info:**
`kubectl --kubeconfig kube_config_cluster.yml get nodes`
```
NAME             STATUS     ROLES                      AGE   VERSION
178.32.115.164   NotReady   controlplane,etcd,worker   8m    v1.11.6
178.32.116.113   NotReady   controlplane,etcd,worker   8m    v1.11.6
178.32.116.114   NotReady   controlplane,etcd,worker   8m    v1.11.6
```

`kubectl --kubeconfig kube_config_cluster.yml describe jobs -n kube-system`
```
Name:           rke-network-plugin-deploy-job
Namespace:      kube-system
Selector:       controller-uid=7c7fd071-30cb-11e9-98a1-024257e77bce
Labels:         controller-uid=7c7fd071-30cb-11e9-98a1-024257e77bce
                job-name=rke-network-plugin-deploy-job
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Fri, 15 Feb 2019 12:43:33 +1000
Pods Statuses:  1 Running / 0 Succeeded / 6 Failed
Pod Template:
  Labels:           controller-uid=7c7fd071-30cb-11e9-98a1-024257e77bce
                    job-name=rke-network-plugin-deploy-job
  Service Account:  rke-job-deployer
  Containers:
   rke-network-plugin-pod:
    Image:      rancher/hyperkube:v1.11.6-rancher1
    Port:       <none>
    Host Port:  <none>
    Command:
      kubectl
      apply
      -f
      /etc/config/rke-network-plugin.yaml
    Environment:  <none>
    Mounts:
      /etc/config from config-volume (rw)
  Volumes:
   config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rke-network-plugin
    Optional:  false
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  10m    job-controller  Created pod: rke-network-plugin-deploy-job-hh7nc
  Normal  SuccessfulCreate  10m    job-controller  Created pod: rke-network-plugin-deploy-job-2ffls
  Normal  SuccessfulCreate  9m39s  job-controller  Created pod: rke-network-plugin-deploy-job-7tf64
  Normal  SuccessfulCreate  8m53s  job-controller  Created pod: rke-network-plugin-deploy-job-zdgsv
  Normal  SuccessfulCreate  7m29s  job-controller  Created pod: rke-network-plugin-deploy-job-4gngt
  Normal  SuccessfulCreate  6m9s   job-controller  Created pod: rke-network-plugin-deploy-job-d7dnw
  Normal  SuccessfulCreate  3m29s  job-controller  Created pod: rke-network-plugin-deploy-job-nwrsn
```

`kubectl --kubeconfig kube_config_cluster.yml -n kube-system get pods`
```
NAME                                  READY   STATUS   RESTARTS   AGE
rke-network-plugin-deploy-job-2ffls   0/1     Error    0          23m
rke-network-plugin-deploy-job-4gngt   0/1     Error    0          20m
rke-network-plugin-deploy-job-7tf64   0/1     Error    0          22m
rke-network-plugin-deploy-job-d7dnw   0/1     Error    0          19m
rke-network-plugin-deploy-job-hh7nc   0/1     Error    0          23m
rke-network-plugin-deploy-job-nwrsn   0/1     Error    0          16m
rke-network-plugin-deploy-job-q24sn   0/1     Error    0          11m
rke-network-plugin-deploy-job-qfgwq   0/1     Error    0          5m
rke-network-plugin-deploy-job-zdgsv   0/1     Error    0          21m
```

`kubectl --kubeconfig kube_config_cluster.yml -n kube-system describe pod rke-network-plugin-deploy-job-qfgwq`
```
Name:               rke-network-plugin-deploy-job-qfgwq
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               178.32.115.164/178.32.115.164
Start Time:         Fri, 15 Feb 2019 13:02:14 +1000
Labels:             controller-uid=7c7fd071-30cb-11e9-98a1-024257e77bce
                    job-name=rke-network-plugin-deploy-job
Annotations:        <none>
Status:             Failed
IP:                 178.32.115.164
Controlled By:      Job/rke-network-plugin-deploy-job
Containers:
  rke-network-plugin-pod:
    Container ID:  docker://3baa897c6fbc76732175c91b6503e5429b230ae9a0a1fe31aed37a98e877f819
    Image:         rancher/hyperkube:v1.11.6-rancher1
    Image ID:      docker-pullable://rancher/hyperkube@sha256:f32396be10eb0f55d7ee30af4aad1bb7e6376b3549405772f04864d3c82e3676
    Port:          <none>
    Host Port:     <none>
    Command:
      kubectl
      apply
      -f
      /etc/config/rke-network-plugin.yaml
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 15 Feb 2019 13:02:30 +1000
      Finished:     Fri, 15 Feb 2019 13:02:30 +1000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rke-job-deployer-token-6gqr8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rke-network-plugin
    Optional:  false
  rke-job-deployer-token-6gqr8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rke-job-deployer-token-6gqr8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/controlplane:NoSchedule
                 node-role.kubernetes.io/etcd:NoExecute
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason   Age    From                     Message
  ----    ------   ----   ----                     -------
  Normal  Pulled   5m34s  kubelet, 178.32.115.164  Container image "rancher/hyperkube:v1.11.6-rancher1" already present on machine
  Normal  Created  5m22s  kubelet, 178.32.115.164  Created container
  Normal  Started  5m19s  kubelet, 178.32.115.164  Started container
```

`kubectl --kubeconfig kube_config_cluster.yml -n kube-system logs rke-network-plugin-deploy-job-qfgwq`
```
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "/etc/config/rke-network-plugin.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
```

My issue seems very similar to this closed one: #318  however I tried the suggested workaround with iptables=false flag with docker and ended up with the same result.

Let me know if you need additional information and thanks in advance for some help.
