### ISSUE TITLE
Nodeselector for dns providers aren't applied

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1146]
**RKE version:**
master 2/20

Steps to reproduce:
- Create `cluster.yml` with DNS provider configured and a node selector:

```
nodes:
- address: x.x.x.x
  user: root
  role: [controlplane,worker,etcd]
  labels:
    app: dns

dns:
  provider: kube-dns
  node_selector:
    app: dns
```

Result:
Node selector is not present in Deployment.
