### ISSUE TITLE
Manifests fromats

### ISSUE THREAD

**Issue by blaggacao** [rancher/rke#1149]
https://github.com/rancher/rke/blob/40cd80a20864aad8003575c89c2ec74e996ee118/cluster/addons.go#L149-L177

Manifest such as https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/local/default.yaml
do neither have `---` prefix nor do they terminate with `\n`.

Both should be checked and auto-completed when missing to avoid obscure error due to malformed concatenated yaml bytestring.
This should work for both, http and local files.

**Comment by azbpa** [comment]
Can confirm this issue when using i.e. https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml in `cluster.yml` after another addon:

```yaml
addons_include:
  - /etc/rke/addons/myapp.yaml
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```

Result is something like this where `Service` is the last resource of the first addon and `Namespace` is the first resource of the second file:

```yaml
...
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
    name: http
  selector:
    app: myapp
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage
...
```

**Comment by deniseschannon** [comment]
Available with v0.3.0-rc6

**Comment by bmdepesa** [comment]
rke 0.3.0-rc6

Tested with multiple manifests:
* No ---, No \n, admin-user-1
* No ---, \n, admin-user-2
* ---, No \n, admin-user-3
* ---, \n, admin-user-4

cluster.yml
```
nodes:
  - address: node_address
    user: ubuntu
    role: [controlplane, etcd, worker]

addons_include:
  - manifest1.yml
  - manifest2.yml
  - manifest3.yml
  - manifest4.yml
```

manifest.yml (without dashes or newlines)
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-x
  namespace: kube-system
```

All service accounts are created successfully:
```
kubectl get serviceaccounts -n kube-system | grep admin-user
admin-user-1                         1         2m17s
admin-user-2                         1         2m17s
admin-user-3                         1         2m17s
admin-user-4                         1         2m17s
```

RKE logs show formatting occurs:
```

DEBU[0022] Yaml does not start with dashes
DEBU[0022] Yaml does not end with newline
DEBU[0022] Yaml does not start with dashes
DEBU[0022] Yaml does not end with newline
DEBU[0022] Yaml does not end with newline
DEBU[0022] Yaml does not end with newline
...

DEBU[0022] [addons] Compiled addons yaml: ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-1
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-2
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-3
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-4
  namespace: kube-system
```
