### ISSUE TITLE
netwrokPolicy namespaceSelector: {} is blocking call from kube-api server

### ISSUE THREAD

**Issue by depohmel** [rancher/rke#1178]
**RKE version:**
v0.1.16

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 24
 Running: 10
 Paused: 0
 Stopped: 14
Images: 11
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.5.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.53GiB
Name: master-rke-testcluster
ID: FJVV:CVUM:E55X:Q3LJ:WIVE:XE5L:ML6C:WEXG:2SNF:JD7G:4VKJ:4EEM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
uname -r
3.10.0-957.5.1.el7.x86_64

cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**cluster.yml file:**
```
nodes:
- address: public-ip
  port: "22"
  internal_address: 10.138.0.127
  role:
  - controlplane
  - etcd
  hostname_override: master-rke-testcluster
  user: ilya
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: path_to_key
  labels: {}
- address: public-ip
  port: "22"
  internal_address: 10.138.0.50
  role:
  - worker
  hostname_override: node0-rke-testcluster
  user: ilya
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: path_to_key
  labels: {}
- address: public-ip
  port: "22"
  internal_address: 10.138.0.121
  role:
  - worker
  hostname_override: node1-rke-testcluster
  user: ilya
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: path_to_key
  labels: {}
- address: public-ip
  port: "22"
  internal_address: 10.138.0.124
  role:
  - worker
  hostname_override: node2-rke-testcluster
  user: ilya
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: path_to_key
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: null
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 172.30.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.128.0.0/14
    service_cluster_ip_range: 172.30.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: ""
    infra_container_image: ""
    cluster_dns_server: 172.30.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: calico
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.2.18
  alpine: rancher/rke-tools:v0.1.15
  nginx_proxy: rancher/rke-tools:v0.1.15
  cert_downloader: rancher/rke-tools:v0.1.15
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.15
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.10
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.12.6-rancher1
  flannel: rancher/coreos-flannel:v0.10.0
  flannel_cni: rancher/coreos-flannel-cni:v0.3.0
  calico_node: rancher/calico-node:v3.1.3
  calico_cni: rancher/calico-cni:v3.1.3
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.1.3
  canal_cni: rancher/calico-cni:v3.1.3
  canal_flannel: rancher/coreos-flannel:v0.10.0
  wave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.16.2-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
  metrics_server: rancher/metrics-server-amd64:v0.2.1
ssh_key_path: /home/ilya/.ssh/google_compute_engine
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: "v1.12.6-rancher1-2"
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
monitoring:
  provider: ""
  options: {}
```

**Steps to Reproduce:**
test-objects.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-np-1
  labels:
    name: test-np
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test-np-1
  labels:
    test: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        test: nginx
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: test-nginx
  namespace: test-np-1
spec:
  selector:
    test: nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: http
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    apiserver: "true"
    test: nginx
  name: v1alpha1.test.np.api.rke
spec:
  group: test.np.api.rke
  groupPriorityMinimum: 2000
  insecureSkipTLSVerify: true
  service:
    name: test-nginx
    namespace: test-np-1
  version: v1alpha1
  versionPriority: 10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-nginx
  namespace: test-np-1
  labels:
    test: nginx
spec:
  podSelector:
    matchLabels:
     test: nginx
  ingress:
    - from:
      - namespaceSelector: {}
```

kubectl apply -f test-objects.yaml

kubectl get apiservice
```
v1alpha1.test.np.api.rke               test-np-1/test-nginx         False (FailedDiscoveryCheck)   54s
```

Describe will show a timeout error to service ip address

```
kubectl describe apiservice v1alpha1.test.np.api.rke
Name:         v1alpha1.test.np.api.rke
Labels:       apiserver=true
              test=nginx
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Spec:
  Group:                     test.np.api.rke
  Group Priority Minimum:    2000
  Insecure Skip TLS Verify:  true
  Service:
    Name:            test-nginx
    Namespace:       test-np-1
  Version:           v1alpha1
  Version Priority:  10
Status:
  Conditions:
    Last Transition Time:  2019-03-07T01:26:20Z
    Message:               no response from https://172.30.146.73:443: Get https://172.30.146.73:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```
This timeout error indecates that kube-api server can not connect to the service.

Change network policy to allow ingress from everywhere.
```
kubectl patch -n test-np-1 networkpolicy test-nginx -p '{"spec":{"ingress":[{"from":[]}]}}'
```

Now error in ```kubectl describe apiservice v1alpha1.test.np.api.rke```  will change to 
```Status:
  Conditions:
    Last Transition Time:  2019-03-07T01:26:20Z
    Message:               no response from https://172.30.146.73:443: Get https://172.30.146.73:443: http: server gave HTTP response to HTTPS client
```
This means kube-api can now reach the service, but it returns a wrong response. Incorect response error is expected.
