### ISSUE TITLE
etcd member can not rejoin the cluster

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rke#1192]
**RKE version:**
v0.2.0-rc9

**Docker version: (`docker version`,`docker info` preferred)**
18.09
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE
**cluster.yml file:**
```
nodes:
- address: <pub_ip1>
  port: "22"
  internal_address: 10.240.0.4
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: bill-rancher-rke-000
  user: wmaxwell
  docker_socket: /var/run/docker.sock
- address: <pub_ip2>
  port: "22"
  internal_address: 10.240.0.68
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: bill-rancher-rke-001
  user: wmaxwell
  docker_socket: /var/run/docker.sock
- address: <pub_ip3>
  port: "22"
  internal_address: 10.240.0.70
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: bill-rancher-rke-002
  user: wmaxwell
  docker_socket: /var/run/docker.sock
network:
  plugin: flannel
```
**Steps to Reproduce:**
1. In a 3 node cluster
1. Stop one of the nodes. 
1. Start back up. (Node public IP is reconfigured. Private stays consistent)
1. Edit cluster.yml and add nodes new public ip
1. Run `rke up`
1. run `rke cert rotate`

**Results:**
Etcd node doesn't rejoin.
