### ISSUE TITLE
Fix redundant ssh tunneling for hosts with more than one role

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#120]
**RKE version:**
v0.0.8-dev
**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos and Ubuntu
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
```
---
ssh_key_path: ~/.ssh/id_rsa

auth:
  strategy: x509

network:
  plugin: flannel

nodes:
  - address: x.x.x.x
    user: ec2-user
    role: [controlplane,worker,etcd]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
```
**Steps to Reproduce:**
start rke with node that has multiple roles
**Results:**
```
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [ssh] Setup tunnel for host [x.x.x.x] 
INFO[0001] [ssh] Setup tunnel for host [x.x.x.x] 
INFO[0002] [ssh] Setup tunnel for host [x.x.x.x]
```
