### ISSUE TITLE
Support for openstack [Networking] in cloud config

### ISSUE THREAD

**Issue by alexandrem** [rancher/rke#1210]
RKE doesn't support the [Networking] cloud config header as documented in

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/provider-configuration.md#networking

This should be added to the rke_types so we can use it like 

```yaml
cloud_provider:
  name: openstack
  openstackCloudProvider:
    networking:
      ...
```
