### ISSUE TITLE
Add ability to select Default PodSecurityPolicy in cluster.yml

### ISSUE THREAD

**Issue by cartyc** [rancher/rke#1219]
It would be great if we could specify the default PodSecurityPolicy within cluster.yml in addition.

If this is already possible by any other means let me know, I haven't found any docs for it.

For example:

```
nodes:
  - address: node1
    user: user
    ssh_key_path: /home/user/.ssh/id_rsa
    role: [controlplane,etcd, worker]
ignore_docker_version: true
kubernetes_version: "v1.13.4-rancher1-1"
cluster_name: sandbox
services:
  kube-api:
    pod_security_policy: true
    pod_secuirty_policy_path: /path/to/my/policy // having a similar toggle would be great.
```

gz#10864
