### ISSUE TITLE
RKE failing for Docker in Docker configuration

### ISSUE THREAD

**Issue by finchr** [rancher/rke#1224]
**RKE version:** v0.1.16

**Docker version: (`docker version`,`docker info` preferred)** N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

  N/A but trying to run in Docker in Docker for a test kitchen

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

  Docker in Docker

**cluster.yml file:**

```
nodes:
- address: 127.0.0.1
  port: 8022
  internal_address: 172.28.128.11
  role:
  - controlplane
  - etcd
  hostname_override: fcs-lsk8smaster-001
  user: kitchen
  docker_socket: /var/run/docker.sock
- address: 127.0.0.1
  port: 8023
  internal_address: 172.28.128.12
  role:
  - worker
  hostname_override: fcs-lsk8slb-001
  user: kitchen
  docker_socket: /var/run/docker.sock
ssh_key_path: .kitchen/docker_id_rsa
```

**Steps to Reproduce:**

rke up --config=cluster.yaml

**Results:**

INFO[0000] Building Kubernetes cluster
FATA[0000] Failed to validate cluster: Cluster can't have duplicate node: 127.0.0.1

**Comment by galal-hussein** [comment]
docker in docker feature is available in rke, you can test that using:

rke up --dind --config cluster.yml

however make sure that each node has different name, for example:
```
nodes:
- address: test1
  role:
  - controlplane
  - etcd
  hostname_override: fcs-lsk8smaster-001
  user: kitchen
- address: test2
  role:
  - worker
  hostname_override: fcs-lsk8slb-001
  user: kitchen
  docker_socket: /var/run/docker.sock
```
