### ISSUE TITLE
0.2.0 rke up failed with etcd snapshot enabled

### ISSUE THREAD

**Issue by willmao** [rancher/rke#1230]
RKE version: 0.2.0

Docker version: 17.03.2

Operating system and kernel: ubuntu 16.04

Type/provider of hosts: Bare-metal

cluster.yml:

set with etcd snapshot enabled

```
  etcd:
    snapshot: true
    creation: 5m0s
    retention: 24h
```

Steps to Reproduce:

rke up

Results:
failed with the following logs:

FATA[0008] [etcd] Failed to bring up Etcd Plane: Can't remove Docker container [etcd-rolling-snapshots] for host [*.*.*.*]: Error response from daemon: removal of container etcd-rolling-snapshots is already in progress

**Comment by willmao** [comment]
update etcd snapshot config according to 0.2.0 docs

```
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
```
run `rke up` also failed
