### ISSUE TITLE
RKE assuming its always safe to concatenate all the manifests in addons_include section

### ISSUE THREAD

**Issue by jlamillan** [rancher/rke#1251]
**RKE version:**

rke version v0.2.1

RKE appears to be assuming it can safely concatenate/append all the manifests in the `addons_include` section if each YAML document / file is valid.

However, because many YAML files are squashed into a single config-map, if one or more of those individual manifest files do not _begin_ with three dashes "---"  (which I am not positive is even technically required to be valid YAML) - the rke-user-includes-addons ends up mashing the tail end of one document with the start of the next together e.g.:

```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: manifest-file-A.yaml
namespace: kube-system 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: manifest-file-B-does-not.start.w.three.dashes.yaml
namespace: kube-system
``` 

**Steps to Reproduce:**

```
addons_include:
    - https://github.com/manifest-file-A.yaml
    - https://github.com/manifest-file-B-does-not.start.w.three.dashes.yaml
```

**Results:**

One of the two resources (ServiceAccount and Deployment) will be created while the other is silently ignored resulting in confusion.

**Comment by deniseschannon** [comment]
@bmdepesa I don't think this was ever tested based on the history here. Can you check it out?

**Comment by bmdepesa** [comment]
rke 0.3.0-rc6

Tested with multiple manifests:
* No ---, No \n, admin-user-1
* No ---, \n, admin-user-2
* ---, No \n, admin-user-3
* ---, \n, admin-user-4

cluster.yml
```
nodes:
  - address: node_address
    user: ubuntu
    role: [controlplane, etcd, worker]

addons_include:
  - manifest1.yml
  - manifest2.yml
  - manifest3.yml
  - manifest4.yml
```

manifest.yml (without dashes or newlines)
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-x
  namespace: kube-system
```

All service accounts are created successfully:
```
kubectl get serviceaccounts -n kube-system | grep 
admin-user-1                         1         2m17s
admin-user-2                         1         2m17s
admin-user-3                         1         2m17s
admin-user-4                         1         2m17s
```

RKE logs show formatting occurs:
```

DEBU[0022] Yaml does not start with dashes
DEBU[0022] Yaml does not end with newline
DEBU[0022] Yaml does not start with dashes
DEBU[0022] Yaml does not end with newline
DEBU[0022] Yaml does not end with newline
DEBU[0022] Yaml does not end with newline
...

DEBU[0022] [addons] Compiled addons yaml: ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-1
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-2
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-3
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-4
  namespace: kube-system
```
