### ISSUE TITLE
Weave deployment is missing designation for critical pods

### ISSUE THREAD

**Issue by janeczku** [rancher/rke#1253]
**RKE version:**
Master

Like Canal and Flannel, the Weave deployment must use the `scheduler.alpha.kubernetes.io/critical-pod` annotation to prevent these critical pods to be evicted when a node reaches capacity.

**Comment by deniseschannon** [comment]
Available to test in RKE CLI and in Rancher master.

**Comment by deniseschannon** [comment]
Available with v0.3.0-rc6

**Comment by bmdepesa** [comment]
rke 0.3.0-rc6

* Created `cluster.yml` with weave network
```
nodes:
  - address: 54.183.14.204
    user: ubuntu
    role: [controlplane, etcd, worker]
network:
    plugin: weave
```
* weave-net pods and daemonset are created, but are missing the `critical-pod` annotation:

From `weave-net` daemonset:
```
template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]'
      creationTimestamp: null
      labels:
        name: weave-net
```
