### ISSUE TITLE
RKE up will not recreate system add-ons that have been deleted from cluster

### ISSUE THREAD

**Issue by jlamillan** [rancher/rke#1278]
RKE `up` does not appear to recreate / re-apply system add-ons that have been deleted /updated in the cluster since the last `up`.

**RKE version:**

v0.2.1

**Docker version: (`docker version`,`docker info` preferred)**

18.09

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

4.14.35-1818.3.3.el7uek.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

```
# Kubernetes nodes
nodes:
    - address: redacted
      ssh_key_path: /path/to/id_rsa
      internal_address: 10.0.10.3
      role:
        - controlplane
        - etcd
      labels:
    - address: redacted
      ssh_key_path: /path/to/id_rsa
      internal_address: 10.0.10.2
      role:
        - worker
network:
    plugin: flannel
monitoring:
    provider: none
kubernetes_version: v1.12.7-rancher1-2
  kubeproxy:
    extra_args:
      healthz-bind-address: 0.0.0.0
```

**Steps to Reproduce:**

1. Bring the cluster up:
`rke up --config cluster.yml`

2. Delete / update one or more system add-ons installed by RKE:
`kubectl delete deployment kube-dns kube-dns-autoscaler -n kube-system`
`kubectl delete namespace ingress-nginx`
``

3. Run up command again (notice log message):
```
rke up --config cluster.yml
...
DEBU[0049] [k8s] Job rke-ingress-controller-deploy-job already exists..
DEBU[0049] [k8s] Job rke-kube-dns-addon-deploy-job already exists.. 
...
INFO[0039] Finished building Kubernetes cluster successfully 
```

**Results:**

4. Deployments associated with system add-ons  (e.g. `ingress-nginx`, `kube-dns`, `kube-dns-autoscaler`) are not re-created.

```
kubectl get deployment kube-dns kube-dns-autoscaler -n kube-system
Error from server (NotFound): deployments.extensions "kube-dns" not found
Error from server (NotFound): deployments.extensions "kube-dns-autoscaler" not found
dev:ci-rke-cluster jemillan$ kubectl get namespace  ingress-nginx
Error from server (NotFound): namespaces "ingress-nginx" not found
```

4. Jobs associated with system add-ons have were not run the second time around:
```
$ kubectl get jobs --all-namespaces
NAMESPACE     NAME                                  COMPLETIONS   DURATION   AGE
kube-system   rke-ingress-controller-deploy-job     1/1           2s         58m
kube-system   rke-kube-dns-addon-deploy-job         1/1           3s         58m
kube-system   rke-network-plugin-deploy-job         1/1           3s         58m
kube-system   rke-user-includes-addons-deploy-job   1/1           2s         58m
```
