### ISSUE TITLE
Allow unique kubelet flags per node

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#1285]
Several members of the open source community have requested the ability to have unique kubelet flags per node. One example is being able to specify a node specific value for the  `--provider-id` flag. Other flags such as `--register-with-taints` and storage related flags may also vary on each node.

gz#5910

**Comment by tardich** [comment]
That's quite an important feature to be able to provide different flags (or anything like it) to different kubelet instances. We may have, for example, to pass some flags related to hardware (may be missleading, but I'm thinking about some nodes who would need to pass along some hardware features (cpu pinning, huge-memory pages, anything like it)). May or may not be a regular use-case, but it will mostly be a required feature for many use-cases.

**Comment by jlamillan** [comment]
Thanks for filing this. Defiantly an important feature to us.

**Comment by pasikarkkainen** [comment]
Yes indeed, this is an important feature to have in rke. I need this feature aswell, especially for: https://github.com/rancher/rke/issues/900

**Comment by dje4om** [comment]
+1, could be nice to be able to hide dedicated masters nodes with `--register-node=false` flag !

**Comment by dinhanhhuy** [comment]
@superseb Please help me review this PR https://github.com/rancher/rke/pull/2698
This will config the kubelet on host "xxx.xxx.xxx" have params max-pods set to 200
```
- address: yyy.yyy.yyy
...
- address: xxx.xxx.xxx
  kubelet:
    extra_args:
      max-pods: '200'
...
services:
  kubelet:
    extra_args:
      max-pods: '250'
```
