### ISSUE TITLE
Support specifying folder when backing up to bucket

### ISSUE THREAD

**Issue by Nyximus** [rancher/rke#1306]
**RKE version:**
v0.2.0

**Docker version: (`docker version`,`docker info` preferred)**
18.9.3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
Ubuntu 16.04.5 LTS 4.4.0-142-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
bucket_name: testfolder/master-cluster-backup

**Steps to Reproduce:**
If you define folder/bucket within bucket_name, RKE etcd backup will fail with an error that 

**Results:**
FATA[0001] Failed to take one-time snapshot, exit code [1]: time="2019-04-24T13:20:57Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:testfolder/master-cluster-backup, err:Bucket name contains invalid characters"

**Comment by superseb** [comment]
The bucket name validation fails here as the parameter is bucket_name and not folder. When a folder is being used, it is prepended to the filename `folder/file` to create a directory. This was not considered when implementing this, we can add support for it in a next version where we let the user optionally specify a folder for both RKE CLI and Rancher. Specifying the folder in the filename today would work if RKE would create the folder in the snapshot directory which it doesn't, when you manually create that directory it already works as a "folder" is just a prefix with a slash.

**Comment by Nyximus** [comment]
The workaround that you have suggested will only work for manually triggered backups with `--name` specified, correct?

I can't see a similar option for recurring backups specified within our rke.yaml.

Currently it looks like the only workaround for our recurring backups is to have multiple buckets configured per environment until this functionality has been added.

**Comment by superseb** [comment]
Correct, it is not implemented and support for it will be added in a next release.

**Comment by alena1108** [comment]
We need to test the upgrade scenario from k8s 1.13/1.14 to k8s 1.15. Per @superseb there is some migration logic to be taken care of.

**Comment by sowmyav27** [comment]
Verified using `folder` parameter in the YAML file
```
services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: S3_ACCESS_KEY
        secret_key: S3_SECRET_KEY
        bucket_name: s3-bucket-name
        region: ""
        folder: "foldername"
        endpoint: s3.amazonaws.com
```
