### ISSUE TITLE
Apply etcd client issue workaround on kube-apiserver

### ISSUE THREAD

**Issue by ahmadalli** [rancher/rke#1311]
**RKE version:** 0.2.2

**Docker version: (`docker version`,`docker info` preferred)** 18.09

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**cluster.yml file:** 

**Steps to Reproduce:** 
1. create a 3 node cluster, all of them `worker,etcd,controlpane`
1. disconnect the first node from the other nodes

**Results:**
cluster fails because of the etcdclient library bug detailed on https://github.com/kubernetes/kubernetes/issues/72102

there's a workaround for this issue which is change to order of etcd nodes on each host: https://github.com/kubernetes/kubernetes/issues/72102#issuecomment-478834647

**Comment by superseb** [comment]
The certificates for etcd already contain all IPs, the steps provided do not reproduce the issue. Please supply exact steps and logging seen at what point. Also the exact `cluster.yml` used and the DNS entries in the certificate (`openssl x509 -in /etc/kubernetes/ssl/kube-etcd-$IP.pem -noout -text | grep DNS`)

**Comment by ahmadalli** [comment]
@superseb it's not an issue with about etcd server. it's a etcd client library (which is used on kube-apiserver) bug

**Comment by ahmadalli** [comment]
this is my cluster.yml:

```yaml
nodes:
  - address: node1
    port: "22"
    role: [controlplane,worker,etcd]
    user: ubuntu
  - address: node2
    port: "22"
    role: [controlplane,worker,etcd]
    user: ubuntu
  - address: node3
    port: "22"
    role: [worker]
    user: ubuntu

services:
  etcd:
    snapshot: true
    creation: 3h
    retention: 72h
  kubelet:
    extra_args:
      read-only-port: 10255
  
dns:
  provider: coredns

monitoring:
    provider: none
```

**Steps to Reproduce:** 
1. deploy the cluster
1. disconnect the first node from the other nodes by running `service docker stop`
1. restart docker on `node2`: `service docker restart`

**Results:**
kube-apiserver container fails to start with this error:

```
Unable to create storage backend: config (&{etcd3 /registry [https://node1:2379 https://node2:2379] /etc/kubernetes/ssl/kube-node-key.pem /etc/kubernetes/ssl/kube-node.pem /etc/kubernetes/ssl/kube-ca.pem true 0xc000500c60 <nil> 5m0s 1m0s}), err (dial tcp node1:2379: connect: connection refused)
```

this is because of a known etcd client issue and is discussed in https://github.com/kubernetes/kubernetes/issues/72102

Currently there's a workaround for this by changing the order of the etcd nodes per each host: https://github.com/kubernetes/kubernetes/issues/72102#issuecomment-478834647
