### ISSUE TITLE
"Failed to reconcile etcd plane" when updating RKE binary

### ISSUE THREAD

**Issue by bentastic27** [rancher/rke#1319]
**RKE version:**
v0.1.17 and v0.2.1+

**Docker version: (`docker version`,`docker info` preferred)**
18.9.4

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Kernel Version: 4.4.0-142-generic
Ubuntu 16.04.5 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**cluster.yml file:**

I recreated with similar:

```
nodes: 
- address: 127.0.0.1 
  user: root 
  port: 22
  role: 
  - controlplane 
  - etcd
  - worker

kubernetes_version: v1.12.6-rancher1-1
```

**Steps to Reproduce:**

1. create cluster with rke 0.1.17 and kubernetes version 1.12.6
2. upgrade rke binary to 0.2.1
3. run rke up to upgrade kubernetes to 1.12.7

**Results:**

The customer got this output (via ansible, but shouldn't be relavent)

```
"time=\"2019-04-25T11:27:50+02:00\" level=info msg=\"[reconcile] host [localhost] is active master on the cluster\"", 
"time=\"2019-04-25T11:27:50+02:00\" level=info msg=\"[certificates] Successfully deployed kubernetes certificates to Cluster nodes\"", 
"time=\"2019-04-25T11:27:50+02:00\" level=info msg=\"[reconcile] Reconciling cluster state\"", 
"time=\"2019-04-25T11:27:50+02:00\" level=info msg=\"[reconcile] Check etcd hosts to be deleted\"", 
"time=\"2019-04-25T11:27:50+02:00\" level=warning msg=\"Etcd plane nodes are replaced. Stopping provisioning. Please restore your cluster from backup.\"", 
"time=\"2019-04-25T11:27:50+02:00\" level=fatal msg=\"Failed to reconcile etcd plane: Etcd plane nodes are replaced. Stopping provisioning. Please restore your cluster from backup.\""
```

**Comment by deniseschannon** [comment]
Duplicate of :https://github.com/rancher/rke/issues/1244#issuecomment-485991428

But would like this use case tested explicitly

**Comment by deniseschannon** [comment]
This will be available in v0.2.3-rc2

**Comment by mtparet** [comment]
Tested with -rc2 but I still get the same issue. (Details in the support to ticket)

**Comment by jiaqiluo** [comment]
I cannot reproduce the bug with both rke  v0.2.1 and v0.2.3-rc2

Steps:
- create the `rancher-cluster.yml` file
```
nodes:
  - address: node-address
    internal_address: node-private-address
    user: ubuntu
    role: [controlplane, etcd, worker] 
    ssh_key_path: path-to-my-key
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
kubernetes_version: v1.12.6-rancher1-1
``` 
- use rke:v0.1.17 to run `rke up --config ./rancher-cluster.yml`  and get the cluster running up successfully.
- confirm the k8s version is v1.12.6 
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- edit version in the `rancher-cluster.yml` file
```
nodes:
  - address: node-address
    internal_address: node-private-address
    user: ubuntu
    role: [controlplane, etcd, worker] 
    ssh_key_path: path-to-my-key
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
kubernetes_version: v1.12.7-rancher1-2
```
- use rke:v0.2.1 to upgrade the cluster 
```
➜  rkes  ~/Downloads/rkes/rke-0.2.1 --version
rke version v0.2.1
➜  rkes  ~/Downloads/rkes/rke-0.2.1 up -config rancher-cluster.yml
```

Result:
- the cluster is up and the k8s version is v1.12.7
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

@bentastic27 @mtparet  Is your step different with mine?

**Comment by bentastic27** [comment]
Interestingly enough, I came back to this and it seems to be working on a 16.04 droplet @jiaqiluo :

```
root@ben-rke-test:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

ben@ben-vm:~/tmp/rketest$ rke-v0.1.17 -v
rke version v0.1.17

ben@ben-vm:~/tmp/rketest$ cat cluster.yml 
nodes: 
- address: ip.of.droplet
  user: root 
  port: 22
  role: 
  - controlplane 
  - etcd
  - worker

kubernetes_version: v1.12.6-rancher1-1

ben@ben-vm:~/tmp/rketest$ rke-v0.1.17 up --config cluster.yml 

ben@ben-vm:~/tmp/rketest$ export KUBECONFIG=/home/ben/tmp/rketest/kube_config_cluster.yml 
ben@ben-vm:~/tmp/rketest$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

ben@ben-vm:~/tmp/rketest$ rke -v
rke version v0.2.2

ben@ben-vm:~/tmp/rketest$ grep kubernetes_version cluster.yml 
kubernetes_version: v1.12.7-rancher1-2

ben@ben-vm:~/tmp/rketest$ rke up --config cluster.yml 

ben@ben-vm:~/tmp/rketest$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

I am wondering what I did differently in my testing.

**Comment by mtparet** [comment]
Ok I found the issue, because of a previous issue (same ticket support) , we had to switch the address from `127.0.0.1` to `localhost` and so we were using this cluster.yaml with `v0.1.17` :
```
nodes:
  - address: 127.0.0.1
    user: honestica
    port: 2222
    role:
      - controlplane
      - etcd
kubernetes_version: v1.12.6-rancher1-1
services:
  etcd:
    snapshot: true
    creation: 30m
    retention: 96h # 4 * 24h
```

and when upgrading with rke 0.2.2, config was:
```
nodes:
  - address: localhost
    user: honestica
    port: 2222
    role:
      - controlplane
      - etcd
kubernetes_version: v1.12.6-rancher1-1
services:
  etcd:
    snapshot: true
    creation: 30m
    retention: 96h # 4 * 24h
```

When switching the address to `localhost` also with rke `0.1.17`, the upgrade is working next with `0.2.2`
