### ISSUE TITLE
'rke up' fails to get current full cluster state

### ISSUE THREAD

**Issue by garyhuang123** [rancher/rke#1338]
**RKE version:**
v0.2.2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.5.1804 (Core)
3.10.0-957.10.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**cluster.yml file:**
```
nodes:
- address: xxxx01           # air gap node external IP
  user: rancher
  role: [ "controlplane", "etcd", "worker" ]
ignore_docker_version: true
private_registries:
- url: docker.xxx.com/infra
  user: xxx
  password: xxx
  is_default: true
services:
  etcd:
    snapshot: true
    retention: "24h"
    creation: "6h0s"
```

**Steps to Reproduce:**
1. rke(0.2.2) up to strike up a new cluster
2. remove rkestate file
3. rke up to retrieve the rkestate
4. get rke error, 
FATA[0202] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy
5. reuse the previous rkestate file, it works again.

**Results:**
Fail to get current rkestate file with error, 
*FATA[0202] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy*
Seems the certs are regenerated.

**Expected Result:**
'rke up' using the same kubeconfig should be able to get the previous rkestate.
