### ISSUE TITLE
Support ssh_proxy_command at the node level

### ISSUE THREAD

**Issue by jlamillan** [rancher/rke#1340]
Although RKE config options already has support for setting a `bastion_host`, it would be helpful to support setting a `ssh_proxy_command` at the node level so that users could specify an SSH proxy for example (there are other examples as well):

```
nodes:
    - address: 1.1.1.1
      user: ubuntu
      role:
        - controlplane
      ssh_key_path: /home/user/.ssh/id_rsa
      ssh_proxy_command: nc -X connect -x some-proxy.foo.com %h %p
```

$ rke -v
rke version v0.1.18
