### ISSUE TITLE
s3 rke not allowing sub directory 

### ISSUE THREAD

**Issue by janavenkat** [rancher/rke#1351]
**RKE version:**
v0.2.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.09.5, build e8ff056

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

``` NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Openstack
Installed on HA

**cluster.yml file:**

added etcd section 

``` 
  etcd:
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: true
    retention: "24h"
    creation: "5m0s"
    backup_config:
      interval_hours: 1
      retention: 6
      s3backupconfig:
        access_key: *******
        secret_key: *********************
        bucket_name: ****************
        region: *******
        endpoint: ********** 
```

**Steps to Reproduce:**
1. Try to backup/restore using s3 with a subdirectory, for example, ```s3://testrkeb/ja```

**Results:**
![Screenshot from 2019-05-21 16-05-42a](https://user-images.githubusercontent.com/28565699/58103470-537cef00-7be3-11e9-8748-19430f5a90ab.png)
