### ISSUE TITLE
SSH tunneling is not working for Root user on CentOS/RHEL

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#136]
using openssh 7.0+, root user is not allowed to ssh tunnel to docker socket on the CentOS/RHEL hosts, however normal users work normally with RKE.

**Comment by moelsayed** [comment]
https://bugs.centos.org/view.php?id=14291

**Comment by moelsayed** [comment]
This is a regression in OpenSSH. We tested using OpenSSH 7.5 and it works fine. Older version should be updated to versions with the back-ported fix.

**Comment by leodotcloud** [comment]
@galal-hussein I encountered this issue on Ubuntu 14.04.

```
root@leo-k8s-c1-n0:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
root@leo-k8s-c1-n0:~#
```

```
root@leo-k8s-c1-n0:~# ssh -V
OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014
root@leo-k8s-c1-n0:~#
```

On my OSX machine:
```
ssh -V
OpenSSH_7.4p1, LibreSSL 2.5.0
```

cluster.yaml:
```
network:
  plugin: canal

ssh_key_path: ~/.ssh/id_rsa
enforce_docker_version: false

nodes:
  - address: 1.1.1.1
    user: root
    role: [controlplane, etcd]
  - address: 2.2.2.2
    user: root
    role: [worker]
  - address: 3.3.3.3
    user: root
    role: [worker]
  - address: 4.4.4.4
    user: root
    role: [worker]
```
