### ISSUE TITLE
kubedns not auto-discoverable by Datadog

### ISSUE THREAD

**Issue by mjpitz** [rancher/rke#1396]
**RKE version:**

```
$ rke -v
rke version v0.2.2
```

By default, DataDog looks for the kubedns metrics on 10055 as per the comment here: https://github.com/DataDog/datadog-agent/issues/1514#issuecomment-375741930

When looking into the RKE setup of DNS, it binds the metrics port to be 10054 instead of their default port. This unfortunately causes a good number of valuable metrics to be missed by the collectors. Please add the following annotations to the kube-dns pod to enable auto-discovery by datadog:

```
metadata:
  annotations:
    service-discovery.datadoghq.com/kubedns.check_names: '["kube_dns"]'
    service-discovery.datadoghq.com/kubedns.init_configs: '[{}]'
    service-discovery.datadoghq.com/kubedns.instances: '[[{"prometheus_endpoint":"http://%%host%%:10055/metrics", "tags":["dns-pod:%%host%%"]}]]'
```

Reference Documentation Here:
https://github.com/DataDog/integrations-core/tree/master/kube_dns

gz#14409
