### ISSUE TITLE
Feature request: allow specifying default-ssl-certificate for ingress controller

### ISSUE THREAD

**Issue by shubb30** [rancher/rke#1408]
**RKE version:**  v0.2.4

**Docker version: (`docker version`,`docker info` preferred)**  18.9.2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**  Ubuntu VM

Rancher/Kubernetes has the option to configure a specific workload to be the alternate "default backend" if no other Ingress matches the hostname of the request.  This works great for providing the web content, but you cannot change the SSL certificate that is applied to this via the "Ingress" option in Rancher.

Kubernetes allows you to specify a [default ssl certificate](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate) that will be used along with the default backend.  In RKE, currently, the only option available to configure the ingress controller is the `provider` flag, so we have no way to configure this.

I manually edited the `nginx-ingress-controller` workload for my cluster, and added the option 
`--default-ssl-certificate=default/default-ssl-cert` and saved the config.  I had to restart each of the pods in the DaemonSet, but after that, then the default backend was showing the certificate that I wanted.  This would work fine except for the next time I run `rke up` it will overwrite the command when the workload is updated.

The request is to have this available as an option in the RKE `ingress` section of the cluster yaml file to make this change persistent.

**Comment by Wadlazky** [comment]
We also run in same problem. We want to code our cluster setups in ansible / bash scripts.
Now we deploy an extra ingress to set the default-ssl-certificate arg and replace the rancher ingress.
But we would rather use the included ingress, especially for compatibility with future releases.

**Comment by avluis** [comment]
Found this a bit late, but in order to do what you are asking for;
- edit your cluster and click on the edit as YAML button
- under ingress add:

```yaml
  ingress:
    extra_args:
      default-ssl-certificate: <namespace>/<secret>
```

Using the above method, I also enable SSL passthrough and a few other options.
For example; here is a snippet of my configuration:

```yaml
  ingress:
    extra_args:
      default-ssl-certificate: ingress-nginx/default-cert
      enable-ssl-passthrough: ''
    options:
      map-hash-bucket-size: '128'
      proxy-add-original-uri-header: 'true'
      proxy-body-size: 150M
      proxy-set-headers: ingress-nginx/custom-headers
      use-forwarded-headers: 'true'
      use-geoip2: 'true'
    provider: nginx
```

The above results in the following command:
`/nginx-ingress-controller --default-backend-service=\$\(POD_NAMESPACE\)/default-http-backend --configmap=\$\(POD_NAMESPACE\)/nginx-configuration --tcp-services-configmap=\$\(POD_NAMESPACE\)/tcp-services --udp-services-configmap=\$\(POD_NAMESPACE\)/udp-services --annotations-prefix=nginx.ingress.kubernetes.io --default-ssl-certificate=ingress-nginx/default-cert --enable-ssl-passthrough`
