### ISSUE TITLE
RKE generated custom certificates fail when starting etcd, missing X509v3 Extended Key Usage

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#1414]
**RKE version:**
v0.2.4
**Docker version: (`docker version`,`docker info` preferred)**
N/A
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
MacOS
```
$ uname -r
18.6.0
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
```
authentication:
    sans:
      - "dnoland-rancher-ha-lb-90ecd17a34a6a9b7.elb.us-west-2.amazonaws.com"
      - "18.237.153.201"
      - "18.237.185.250"
      - "54.214.223.93"

kubernetes_version: v1.14.1-rancher1-2
nodes:
  - address: 18.237.153.201
    internal_address: 10.0.0.10
    user: rancher
    role: [controlplane,worker,etcd]
  - address: 18.237.185.250
    internal_address: 10.0.0.11
    user: rancher
    role: [controlplane,worker,etcd]
  - address: 54.214.223.93
    internal_address: 10.0.0.12
    user: rancher
    role: [controlplane,worker,etcd]

ssh_agent_auth: true

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```
**Steps to Reproduce:**
rke cert generate-csr --config ./rancher-cluster.yml

**Results:**
The etcd CSRs do not have the ` X509v3 Extended Key Usage` set to `TLS Web Client Authentication, TLS Web Server Authentication` only the SANs:
```
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:18.237.153.201, IP Address:10.0.0.10, IP Address:18.237.185.250, IP Address:10.0.0.11, IP Address:54.214.223.93, IP Address:10.0.0.12, IP Address:127.0.0.1, IP Address:10.43.0.1
```
When trying to use the rke generated certs, etcd fails to start with error:
```
2019-06-19 13:07:32.894878 I | etcdmain: rejected connection from "10.0.0.10:40880" (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "dummy.rancher.com")
```
