### ISSUE TITLE
Error: Can't find node by name

### ISSUE THREAD

**Issue by musabmirza** [rancher/rke#1416]
**RKE version:**
0.2.4

**Docker version: (`docker version`,`docker info` preferred)** 
18.09

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMs on GCE

**cluster.yml file:**
```
nodes:

  - address: <publicip>
    internal_address: 10.0.1.4
    role: [controlplane,etcd,worker]
    user: deploy
    hostname_override: master

  - address: <publicip>
    internal_address: 10.0.1.5
    role: [worker, etcd]
    user: deploy
    hostname_override: worker1

  - address: <publicip>
    internal_address: 10.0.1.3
    role: [worker, etcd]
    user: deploy
    hostname_override: worker2

  - address: <publicip>
    internal_address: 10.0.1.2
    role: [worker]
    user: deploy
    hostname_override: worker3

ssh_key_path: deploy.pem

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

private_registries:
  - url: docker.registry:5000
    user: xxxx
    password: xxxx 
    is_default: true

```

**Steps to Reproduce:**
`./rke --debug up --config test-cluster-config.yaml`

**Results:**
```
...
INFO[0077] [sync] Syncing nodes Labels and Taints
DEBU[0077] worker [1] starting sync for node [master]
DEBU[0077] worker [9] starting sync for node [worker1]
DEBU[0077] worker [5] starting sync for node [worker2]
DEBU[0077] worker [2] starting sync for node [worker3]
DEBU[0077] [hosts] Can't find node by name [worker2], retrying..
DEBU[0077] [hosts] Can't find node by name [worker3], retrying..
DEBU[0077] [hosts] Can't find node by name [worker1], retrying..
DEBU[0079] [hosts] Can't find node by name [worker2], retrying..
DEBU[0079] [hosts] Can't find node by name [worker1], retrying..
DEBU[0079] [hosts] Can't find node by name [worker3], retrying..
DEBU[0081] [hosts] Can't find node by name [worker2], retrying..
DEBU[0081] [hosts] Can't find node by name [worker3], retrying..
DEBU[0081] [hosts] Can't find node by name [worker1], retrying..
DEBU[0084] [hosts] Can't find node by name [worker3], retrying..
DEBU[0084] [hosts] Can't find node by name [worker2], retrying..
DEBU[0084] [hosts] Can't find node by name [worker1], retrying..
DEBU[0086] [hosts] Can't find node by name [worker3], retrying..
DEBU[0086] [hosts] Can't find node by name [worker2], retrying..
DEBU[0086] [hosts] Can't find node by name [worker1], retrying..
DEBU[0088] [hosts] Can't find node by name [worker3], retrying..
DEBU[0088] [hosts] Can't find node by name [worker2], retrying..
DEBU[0088] [hosts] Can't find node by name [worker1], retrying..
FATA[0090] [ "worker3" not found]
```

Everything works well, the etcd controlplane and workers all come up, but at this step it fails. I am unable for find any more documentation. 

Note: I have also tried this without `hostname_override` set on each node
