### ISSUE TITLE
Option to Disable Kube-proxy Deploy

### ISSUE THREAD

**Issue by bensallen** [rancher/rke#1432]
Requesting a configuration option to disable deploying kube-proxy. This will allow alternatives options to be configured. 

An example is kube-router's built-in service proxy functionality which makes use of ipvs: https://www.kube-router.io/docs/how-it-works/#service-proxy-and-load-balancing.

Ref in code: https://github.com/rancher/rke/blob/master/cluster/plan.go#L68

Related to #312.

**Comment by travisghansen** [comment]
I'm also interested in this for giving cilium a try..

**Comment by iwilltry42** [comment]
@travisghansen https://github.com/rancher/rke/pull/1831 I did the same thing also for cilium. Didn't push a PR though because it builds in top of the one I linked.

**Comment by travisghansen** [comment]
@iwilltry42 awesome! How did cilium go?

**Comment by iwilltry42** [comment]
@travisghansen both kube-router and cilium worked just fine after being deployed wit RKE. We just went with kube-router after all, because we're running on an old kernel version which didn't go well with all the cilium features.

**Comment by travisghansen** [comment]
Just a follow-up for anyone following along. I wanted to use/trial all the fancy features of cilium like replacing `kube-proxy` and using `DSR` mode etc. I also wanted to use `rke` so I approached the situation slightly differently and ended up creating a wrapper `kube-proxy` script, copying to all host nodes and then bind mounting it into the container. Alternatively, a 'noop' image could be used to completely replace/override the `kube-proxy` container image. In either case `rke` does health checks so it needs to implement that in some shape or form until this ticket is implemented.

`cluster.yml`

```yaml
  kubeproxy:
    # image:
    extra_env:
      - "KUBE_PROXY_NOOP=1"
      - "PATH=/opt/custom/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    extra_binds:
      - "/opt/custom/bin:/opt/custom/bin"
```

`kube-proxy` script as placed in `/opt/custom/bin`

```sh
#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

trap "exit 0" SIGTERM SIGINT SIGHUP SIGQUIT SIGKILL

if [[ ${KUBE_PROXY_NOOP} -eq 1 ]];then
  clean-install netcat
  
  # mimic healthz server
  while true; do
    DATE="$(date -u "+%F %T.%N %z %Z m=+")$(perl -w -MTime::HiRes=clock_gettime,CLOCK_MONOTONIC -E 'say clock_gettime(CLOCK_MONOTONIC)')"
    CONTENT="{\"lastUpdated\": \"${DATE}\",\"currentTime\": \"${DATE}\"}"
    cat << EOF | perl -pe 'chomp if eof' | nc -s 127.0.0.1 -lp 10256 -q 1
HTTP/1.1 200 OK$(printf "\r")
Content-Type: application/json$(printf "\r")
X-Content-Type-Options: nosniff$(printf "\r")
Date: $(date -u)$(printf "\r")
Content-Length: $((${#CONTENT}+0))$(printf "\r")
$(printf "\r")
${CONTENT}
EOF

  done
else
  # /usr/local/bin/kube-proxy
  exec kube-proxy "$@"
fi
```

**Comment by ulm0** [comment]
This should be more like `Add cilium as CNI plugin`, because cilium can run along with kube-proxy as well, and sure most of us want a kube-proxyless k8s, but we could have different behaviors for cilium deployment within the options block

e.g.

```yaml
...
network:
  plugin: cilium
  options:
    kube-proxy-replacement: "probe" # Deploys kube-proxy in ipvs mode along with cilium
    ...
...
```

```yaml
...
network:
  plugin: cilium
  options:
    kube-proxy-replacement: "strict" # Deploys cilium only
    ...
...
```
