### ISSUE TITLE
HA - rke - tls: bad certificate

### ISSUE THREAD

**Issue by branislav-brujic** [rancher/rke#1446]
**RKE version:** v.0.2.4

**Docker version: (`docker version`,`docker info` preferred)**  18.09.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 18 LTS 4.15.0-47-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**cluster.yml file:**
```
nodes:
    - address: **.**.**.21
      ssh_key_path: key.pem
      user: someuser
      role:
        - controlplane
        - etcd
    - address: **.**.**.20
      ssh_key_path: key.pem
      user: someuser
      role:
        - controlplane
        - etcd
    - address: **.**.**.106
      ssh_key_path: key.pem
      user: someuser
      role:
        - worker
    - address: **.**.**.58
      ssh_key_path: key.pem
      user: someuser
      role:
        - worker

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

**Steps to Reproduce:**
`rke --debug up --update-only --config cluster.yml`

**Results:**
```
INFO[0123] [etcd] Successfully started [rke-log-linker] container on host [ **.**.**.20] 
DEBU[0123] [remove/rke-log-linker] Checking if container is running on host [ **.**.**..20] 
DEBU[0126] [remove/rke-log-linker] Removing container on host [ **.**.**.20] 
INFO[0126] [remove/rke-log-linker] Successfully removed container on host [ **.**.**..20] 
DEBU[0126] [etcd] Successfully created log link for Container [etcd] on host [ **.**.**..20] 
INFO[0126] [etcd] Successfully started etcd plane.. Checking etcd cluster health 
DEBU[0126] [etcd] Check etcd cluster health             
DEBU[0128] Failed to get /health for host [ **.**.**..21]: Get https:// **.**.**..21:2379/health: remote error: tls: bad certificate 
DEBU[0138] Failed to get /health for host [ **.**.**..21]: Get https:// **.**.**..21:2379/health: remote error: tls: bad certificate 
DEBU[0148] Failed to get /health for host [ **.**.**..21]: Get https:// **.**.**.:2379/health: remote error: tls: bad certificate 
DEBU[0153] [etcd] Check etcd cluster health             
DEBU[0155] Failed to get /health for host [ **.**.**..20]: Get https://.20:2379/health: remote error: tls: bad certificate 
DEBU[0168] Failed to get /health for host [ **.**.**.20]: Get https:// **.**.**..20:2379/health: remote error: tls: bad certificate 
DEBU[0177] Failed to get /health for host [ **.**.**.20]: Get https:// **.**.**.20:2379/health: remote error: tls: bad certificate 
FATA[0182] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy 
```

---------------------------------------------------------
Everything works good I just cant add one new node to cluster because of this `bad certificate` issue.
I using rancher self signed certificate
