### ISSUE TITLE
Feature request: able to save etcd snapshot into subdirectory of s3 bucket

### ISSUE THREAD

**Issue by vukor** [rancher/rke#1449]
**RKE version:**
```
$ rke --version
rke version v0.2.4
```

**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**cluster.yml file:**
```
nodes:
- address: x.x.x.x
  port: ""
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: xxx
  docker_socket: ""
  ssh_key: |
    -----BEGIN RSA PRIVATE KEY-----
    xxx
    -----END RSA PRIVATE KEY-----

network:
    plugin: canal
```

**Steps to Reproduce:**
1. create cluster:
```
$ rke up
```

2. create backup:
```
$ rke etcd snapshot-save --name backup-1 \
--s3 \
--access-key xxx \
--secret-key xxx \
--bucket-name xxx \
--s3-endpoint s3.amazonaws.com
...
INFO[0009] Finished saving snapshot [backup-1] on all etcd hosts
```

**Results:**
```
$ aws s3 ls s3://xxx/
2019-07-02 19:38:46    4472864 backup-1
```

It would be great to be able to save backup to s3://xxx/dev/ or s3://xxx/stg/ path for example.
