### ISSUE TITLE
Ingress pods fail to start when PSP is enabled for cluster

### ISSUE THREAD

**Issue by janeczku** [rancher/rke#1474]
**RKE version:**
v0.25

**cluster.yml file:**
```
nodes:
  - address: 167.71.xx.xx
    user: rancher
    role: [controlplane,worker,etcd]
  - address: 167.71.xx.xx
    user: rancher
    role: [controlplane,worker,etcd]
  - address: 207.154.xx.xx
    user: rancher
    role: [controlplane,worker,etcd]

services:
  kube-api:
    pod_security_policy: true
```

**Steps to Reproduce:**
Create cluster with above configuration, enabling pod security policy.

**Expected Result:**

Enabling PSP for a cluster should not break any of the workloads natively deployed by RKE.

The service account in the `ingress-nginx` namespace is assigned a role that allows replica set controller to use a predefined pod security policy to create required pods.
See: https://github.com/rancher/rke/blob/74b81a8766b7316c70f1d6dadcf794263539e60e/templates/authz.go#L73

**Actual Results:**
Ingress controller and default-backend pods fail to start:

```
Warning   FailedCreate  replicaset/default-http-backend-5954bd5d8c
Error creating: pods "default-http-backend-5954bd5d8c-" is forbidden: unable to validate against any pod security policy: []
```

**Comment by dehotot** [comment]
+1 for a fix on this; it's blocking deployment of RBAC'ed end-user clusters.

**Comment by dehotot** [comment]
FYI I was seeing this problem when using `plugin: flannel`.

Now I've switched to `plugin: canal` I don't seem to be able to trigger the problem.

**Comment by deniseschannon** [comment]
Available with v0.3.0-rc6

**Comment by sowmyav27** [comment]
### Reproduced issue with rke v0.2.5
**Cluster.yml file:**
```
nodes:
  - address: x.x.x.x
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: y.y.y.y
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: z.z.z.z
    user: ubuntu
    role: [controlplane,worker,etcd]

services:
  kube-api:
    pod_security_policy: true
```
- Do an rke up
- Result: No pods are seen running in `ingress-nginx` namespace
```
Sowmyas-MBP:import_cluster sowmyaviswanathan$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   canal-d6jx9                               2/2     Running     0          2m53s
kube-system   canal-pt2vh                               2/2     Running     0          2m53s
kube-system   canal-ztzs2                               2/2     Running     0          2m53s
kube-system   coredns-86bc4b7c96-zrxq7                  1/1     Running     0          2m49s
kube-system   coredns-autoscaler-5d5d49b8ff-6jsf2       1/1     Running     0          2m48s
kube-system   metrics-server-7f6bd4c888-vcpmg           1/1     Running     0          2m42s
kube-system   rke-coredns-addon-deploy-job-8q87c        0/1     Completed   0          2m50s
kube-system   rke-ingress-controller-deploy-job-477zr   0/1     Completed   0          2m39s
kube-system   rke-metrics-addon-deploy-job-dxsnp        0/1     Completed   0          2m45s
kube-system   rke-network-plugin-deploy-job-rgvqg       0/1     Completed   0          2m56s
```

### Verified in rke `0.3.0-rc6`
- `pod_security_policy` is set true in cluster.yml
- Do an rke up.
- nginx-ingress-controller pods are seen up and Running
```
Sowmyas-MBP:import_cluster_final sowmyaviswanathan$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY   STATUS      RESTARTS   AGE
ingress-nginx   default-http-backend-8456b47798-7bh58     1/1     Running     0          4m4s
ingress-nginx   nginx-ingress-controller-6kn47            1/1     Running     0          4m4s
ingress-nginx   nginx-ingress-controller-8zvcq            1/1     Running     0          4m4s
ingress-nginx   nginx-ingress-controller-bhzxr            1/1     Running     0          4m4s
kube-system     canal-b2l7z                               2/2     Running     0          4m30s
kube-system     canal-xxdcq                               2/2     Running     0          4m30s
kube-system     canal-zlrhd                               2/2     Running     0          4m30s
kube-system     coredns-5678df9bcc-vvsz8                  1/1     Running     0          4m26s
kube-system     coredns-autoscaler-57bc9c9bd-jrnxn        1/1     Running     0          4m25s
kube-system     metrics-server-dbcdc5bc9-hwhpj            1/1     Running     0          4m16s
kube-system     rke-coredns-addon-deploy-job-pdcns        0/1     Completed   0          4m28s
kube-system     rke-ingress-controller-deploy-job-nfn9f   0/1     Completed   0          4m11s
kube-system     rke-metrics-addon-deploy-job-4j5hm        0/1     Completed   0          4m22s
kube-system     rke-network-plugin-deploy-job-sq9pt       0/1     Completed   0          4m33s

```
