### ISSUE TITLE
etcd snapshots in s3 with custom names can't start with the same string

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1486]
**RKE version:**
master 7/19 (`217e1b4`)

**cluster.yml file:**
```
nodes:
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]

services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: x
        secret_key: x
        bucket_name: bucket
        endpoint: endpoint
```

**Steps to Reproduce:**
- run `rke up`
- run `rke etcd snapshot-save --name myname`
- run `rke etcd snapshot-save --name myname1`
- run `rke etcd snapshot-restore --name myname`

**Results:**
The prefix match matches all occurrences and errors out:

```
FATA[0007] Failed to download etcd snapshot from s3, exit code [1]: time="2019-07-19T10:09:14Z" level=fatal msg="failed to download s3 backup: found multiple backups with the same name: [myname.zip myname1.zip]"
```

**Comment by sowmyav27** [comment]
verified with rke `v0.3.0-rc5`

**cluster.yml file:**
```
nodes:
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]

services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: x
        secret_key: x
        bucket_name: bucket
        endpoint: endpoint
```

**Steps to Reproduce:**
1. run `rke up`
2. run `rke etcd snapshot-save --name myname`
3. run `rke etcd snapshot-save --name myname1`
4. run `rke etcd snapshot-restore --name myname`

**Result:**
Snapshot is restored.
S3 bucket has the snapshots stored.
No errors seen.
