### ISSUE TITLE
How to Manually rotate when certs are expired.

### ISSUE THREAD

**Issue by ibigpapa** [rancher/rke#1487]
**RKE version: v0.1.8-rc11** 

**Docker version: Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
(`docker version`,`docker info` preferred)**

**Operating system and kernel: Ubuntu 16.04.4 LTS,4.4.0-130-generic
 (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts:VMWare (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:
```
ssh_key_path: {PATH}
nodes:
  - address: {IP-1}
    user: root
    role:
      - controlplane
      - etcd
      - worker
  - address: {IP-2}
    user: root
    role:
      - controlplane
      - etcd
      - worker
  - address: {IP-3}
    user: root
    role:
      - controlplane
      - etcd
      - worker
  - address: {IP-4}
    user: root
    role:
      - worker
  - address: {IP-5}
    user: root
    role:
      - worker    
  - address: {IP-6}
    user: root
    role:
      - worker
ignore_docker_version: false
cluster_name: arm
kubernetes_version: "v1.10.3-rancher2-1"
addon_job_timeout: 30
authentication: 
  strategy: "x509"
ingress: 
  provider: "nginx"
network: 
  plugin: "canal"
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube_api: 
    pod_security_policy: false
  kubelet: 
    fail_swap_on: false
    extra_args:
      authentication-token-webhook: true
ssh_agent_auth: false
```
**

**Steps to Reproduce: kubectl version**

**Results:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate has expired or is not yet valid
```**
Since my version of rancher isn't supported in the 2.0 version of rke and my certs are expired so i can't upgrade the version which means i can't use the cert rotate command.  How would you do this manually?
