### ISSUE TITLE
Enabling --feature-gates="VolumeSubpathEnvExpansion=true" on RKE does not work (in order to use subpath)

### ISSUE THREAD

**Issue by bart2001** [rancher/rke#1490]
Hello, I would like to [use subPath with expanded environment variables](https://v1-13.docs.kubernetes.io/docs/concepts/storage/volumes/#using-subpath-with-expanded-environment-variables) in order to prevent pods(with replicas) writing on same file.

For example, I want to deploy pods with deployments mounting on same hostpath for writing logs to the node(host machine).

Here is my deployment yaml file with [using subPath with expanded environment variables](https://v1-13.docs.kubernetes.io/docs/concepts/storage/volumes/#using-subpath-with-expanded-environment-variables) which all pods mounts hostpath of `/home/myuser/logs` and uses subpath for each pod such as `/home/myuser/logs/$(POD_NAME)`

`subpath.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subpath-deployment
  labels:
    app: subpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subpath
  template:
    metadata:
      labels:
        app: subpath
    spec:
      containers:
        - name: container1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: busybox
          command: [ "sh", "-c", "while [ true ]; do echo 'Hello'; sleep 10; done | tee -a /logs/hello.txt" ]
          volumeMounts:
            - name: workdir1
              mountPath: /logs
              subPath: $(POD_NAME) #log path for each pod on /home/myuser/logs/$(POD_NAME)
      volumes:
        - name: workdir1
          hostPath:
            path: /home/myuser/logs
            type: "DirectoryOrCreate"
```

According to [using subPath with expanded environment variables in Kubernetes v1.13 docs](https://v1-13.docs.kubernetes.io/docs/concepts/storage/volumes/#using-subpath-with-expanded-environment-variables), it says enable `VolumeSubpathEnvExpansion` feature gate in order to use `subPath with expanded environment variables`.

I have tested on minkube with `minikube start --kubernetes-version=v1.13.5 --feature-gates=VolumeSubpathEnvExpansion=true` and `kubectl apply -f subpath.yaml` command successfully deployed pods and each pod creates subpath directories and appends "hello" string in "hello.txt" file on hostpath of `/home/myuser/logs/$(each POD_NAME)/hello.txt`.

However, on my bare-metal servers with RKE(details below), $(POD_NAME) directory is not even created on host machine.
I have ssh into my pod with `kubectl exec -it $(one of my pod name) /bin/sh` and checked the pod is successfully writing hello strings on `/logs/hello.txt` .

Is there something I missed on my `rancher-cluster.yaml`with enabling `VolumeSubpathEnvExpansion` feature gate?

**RKE version:**
v0.2.4 (Kubernetes Version v1.13.5)

**Docker version: (`docker version`,`docker info` preferred)**
18.09.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```yaml
nodes:
  - address: 10.10.10.1
    user: myuser
    role: [controlplane,worker,etcd]
  - address: 10.10.10.2
    user: myuser
    role: [worker]
  - address: 10.10.10.3
    user: myuser
    role: [controlplane,worker,etcd]
  - address: 10.10.10.4
    user: myuser
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
  kube-api:
    extra_args:
      feature-gates: "VolumeSubpathEnvExpansion=true"
  kubelet:
    extra_args:
      feature-gates: "VolumeSubpathEnvExpansion=true"
  kube-controller:
    extra_args:
      feature-gates: "VolumeSubpathEnvExpansion=true"
  scheduler:
    extra_args:
      feature-gates: "VolumeSubpathEnvExpansion=true"
  kubeproxy:
    extra_args:
      feature-gates: "VolumeSubpathEnvExpansion=true"
prefix_path: /home1/work/rke
```
**Steps to Reproduce:**
1. `rke up --conifg rancher-cluster.yaml`
2. (with provisioned kubeconfig) `kubectl apply -f subpath.yaml`
3. pods are in Running state
4. `cd /home/myuser/logs/` on host machine of pod

**Results:**
no podname related directories found in /home/myuser/logs/

**Comment by mathisub** [comment]
Hi Li, I'm glad that  you are able to use  "subPathExpr" feature. Do we have to you enable  feature-gates "VolumeSubpathEnvExpansion=true" ? Can you share some info about the process? I am using kubernetes 1.14.6. Thanks.

**Comment by aemneina** [comment]
The example @Li-Yanzhi cites works, the key being the path under /var/log/pods. This issue seems related to https://github.com/rancher/rancher/issues/14836

@mathisub you will still need to enable the feature gate. Do you use RKE to build your clusters?

**Comment by ryansann** [comment]
### Feature Gate

The feature gate `VolumeSubpathEnvExpansion=true` can be set to enable environment variable expansion in the `subPathExpr` field in kubernetes version v1.14

The feature gate went beta in v1.15 and got a default value of `true`, so, in subsequent versions, would only need to be set if you wanted to remove the env expansion functionaltiy and ability to use the `subPathExpr` field. 

NOTE: You should be using the `subPathExpr` field rather than the `subPath` field for env expansion. See [this document](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20181029-volume-subpath-env-expansion.md) for more information.

Here is a table:

| Feature                   | Default | Stage | Since | Until |
|---------------------------|---------|-------|-------|-------|
| VolumeSubpathEnvExpansion | false   | alpha | 1.14  | 1.14  |
| VolumeSubpathEnvExpansion | true    | beta  | 1.15  | 1.16  |
| VolumeSubpathEnvExpansion | true    | GA    | 1.17  | -     |

[Source](https://v1-17.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)

### Why this doesn't work

Due to the containerized kubelet being deprecated, this functionality won't work with hostPath volumes. The correct directory is created inside the kubelet container, but since the kubelet does not have access back to the host's root fs, it cannot create the hostPath/subPathExpr there. You can see [this related issue](https://github.com/rancher/rancher/issues/14836) for more details.

**Comment by maggieliu** [comment]
The detailed analysis has been communicated to the customer. Closing this since there is no further actions required.

**Comment by nova-lu** [comment]
> ### Feature Gate
> The feature gate `VolumeSubpathEnvExpansion=true` can be set to enable environment variable expansion in the `subPathExpr` field in kubernetes version v1.14
> 
> The feature gate went beta in v1.15 and got a default value of `true`, so, in subsequent versions, would only need to be set if you wanted to remove the env expansion functionaltiy and ability to use the `subPathExpr` field.
> 
> NOTE: You should be using the `subPathExpr` field rather than the `subPath` field for env expansion. See [this document](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20181029-volume-subpath-env-expansion.md) for more information.
> 
> Here is a table:
> 
> Feature	Default	Stage	Since	Until
> VolumeSubpathEnvExpansion	false	alpha	1.14	1.14
> VolumeSubpathEnvExpansion	true	beta	1.15	1.16
> VolumeSubpathEnvExpansion	true	GA	1.17	-
> [Source](https://v1-17.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)
> 
> ### Why this doesn't work
> Due to the containerized kubelet being deprecated, this functionality won't work with hostPath volumes. The correct directory is created inside the kubelet container, but since the kubelet does not have access back to the host's root fs, it cannot create the hostPath/subPathExpr there. You can see [this related issue](https://github.com/rancher/rancher/issues/14836) for more details.

I'm confused about how do I turn on this feature gates on my 1.14 version of k8S
I already add "- --feature-gates=VolumeSubpathEnvExpansion=true" parameters in my kube-apiserver, kube-controller, kube-scheduler
But when I was create this deployment like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            preference:
              matchExpressions:
              - key: accelerator
                operator: DoesNotExist
      containers:
      - name: web-api
        image: ***
        resources:
          requests:
            memory: "500Mi"
        ports:
        - containerPort: 23014
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: MY_POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        volumeMounts:
        - name: cgc-local-pvc-log
          subPathExpr: $(MY_NODE_NAME)_$(MY_POD_NAMESPACE)
          mountPath: /app/log
      volumes:
      - name: cgc-local-pvc-log
        persistentVolumeClaim:
          claimName: pvc-local
      imagePullSecrets:
      - name: **-secret

still get this error:
```
# kubectl describe pod web-api-***
...
    State:          Waiting
      Reason:       CreateContainerConfigError...

 Warning  Failed     6s (x3 over 8s)  kubelet, master-captest  Error: volume subpath expansion is disabled
...
```

```
