### ISSUE TITLE
Backport etcd snapshots in s3 with custom names can't start with the same string

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1498]
Backport https://github.com/rancher/rke/issues/1486

**Comment by alena1108** [comment]
Can be tested with v0.2.7-rc1

**Comment by sowmyav27** [comment]
verified with rke `v0.2.7-rc1`

**cluster.yml file:**
```
nodes:
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]

services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: x
        secret_key: x
        bucket_name: bucket
        endpoint: endpoint
```

**Steps to Reproduce:**
1. run `rke up`
2. run `rke etcd snapshot-save --name myname`
3. run `rke etcd snapshot-save --name myname1`
4. run `rke etcd snapshot-restore --name myname`

**Result:**
Snapshot is restored.
S3 bucket has the snapshots stored.
