### ISSUE TITLE
rke snapshot-restore failed with a node docker daemon connection

### ISSUE THREAD

**Issue by wusphinx** [rancher/rke#1506]
**RKE version:**
```
rke version v0.2.6
```

**Docker version: (`docker version`,`docker info` preferred)**
`docker version`:
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
`docker info`
```
Containers: 79
 Running: 19
 Paused: 0
 Stopped: 60
Images: 204
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.12.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: test-docker02
ID: DQWT:AWMM:PASR:UJBK:G6VI:A6MF:WS6T:FW4C:DKCI:ZWGD:HDVK:C25B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`cat /etc/os-release`
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
`uname -r` 
```
3.10.0-957.12.1.el7.x86_64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
aliyun ecs
```
**cluster.yml file:**
```
network:
  plugin: calico

nodes:
  - address: 10.1.25.199
    internal_address: 10.1.25.199
    user: operadmin
    role: [controlplane,worker,etcd]
    port: 15388
  - address: 10.1.25.200
    internal_address: 10.1.25.200
    user: operadmin
    role: [controlplane,worker,etcd]
    port: 15388
  - address: 10.1.25.201
    internal_address: 10.1.25.201
    user: operadmin
    role: [controlplane,worker,etcd]
    port: 15388
  - address: 10.1.25.209
    internal_address: 10.1.25.209
    user: operadmin
    role: [worker]
    port: 15388
  - address: 10.1.25.208
    internal_address: 10.1.25.208
    user: operadmin
    role: [worker]
    port: 15388
  - address: 10.1.25.210
    internal_address: 10.1.25.210
    user: operadmin
    role: [worker]
    port: 15388
  - address: 10.1.25.203
    internal_address: 10.1.25.203
    user: operadmin
    role: [worker]
    port: 15388
  - address: 10.1.25.204
    internal_address: 10.1.25.204
    user: operadmin
    role: [worker]
    port: 15388
  - address: 10.1.25.205
    internal_address: 10.1.25.205
    user: operadmin
    role: [worker]
    port: 15388
  - address: 10.1.25.206
    internal_address: 10.1.25.206
    user: operadmin
    role: [worker]
    port: 15388

services:
  kube-controller:
    cluster_cidr: 10.1.64.0/19

  etcd:
    snapshot: true
    creation: 6h
    retention: 48h
```

**Steps to Reproduce:**
restore from etcd snapshot
```
rke --debug etcd snapshot-restore --name 2019-07-25T02:20:45Z_etcd --config /home/rancher/rancher-cluster.yml
```

**Results:**
```
DEBU[0119] [remove/nginx-proxy] Container doesn't exist on host [10.1.25.201]
DEBU[0119] [remove/service-sidekick] Checking if container is running on host [10.1.25.201]
DEBU[0119] [remove/service-sidekick] Container doesn't exist on host [10.1.25.201]
FATA[0119] [Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
```
but, when I login `10.1.25.201`, 
```
Redirecting to /bin/systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─docker-dns.conf, docker-options.conf
   Active: active (running) since Tue 2019-07-02 15:57:03 CST; 3 weeks 2 days ago
     Docs: http://docs.docker.com
 Main PID: 3830 (dockerd)
    Tasks: 581
```
The docker is running, also, I can ssh to the node `10.1.25.201` successfully.
some log below:
```
DEBU[0067] [etcd] No pull necessary, image [rancher/rke-tools:v0.1.34] exists on host [10.1.25.201]
INFO[0068] [etcd] Successfully started [etcd-checksum-checker] container on host [10.1.25.201]
```
So, I'm confused about what's wrong with it.
