### ISSUE TITLE
Feature Request - Use Variables for addons

### ISSUE THREAD

**Issue by vikas027** [rancher/rke#1514]
As of now AFAIK there is no way to use variables in the yaml files in `addons_include` section. It would be great if we can have a variable something like this

```yaml
addons_variables:
   linkerd_version: 2.3.2
   traefik_version: 1.7.12
```
