### ISSUE TITLE
loadblancing for kube api server

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/rke#1526]
I need to use an external load balancer to load balance traffic over three master nodes for API requests.

As per this post:

https://blog.heptio.com/kubernetes-ha-under-x-ray-5d05f552c9f

How can I provide configuration to RKE to use external name ( that will point to load balancer ) as advertise address?

Is there some other way to do it?

**Comment by piwi91** [comment]
@iahmad-khan use the `extra_args` option, but do you really want to route all API traffic over the external VIP?

```
services:
  kube-api:
    extra_args:
      advertise-address: xxx.xxx.xxx.xxx
```

When you only want to have a valid certificate, change the `authentication` option:

```
authentication:
    strategy: x509
    sans:
      - "xxx.xxx.xxx.xxx"
      - "api.domain.tld"
```
