### ISSUE TITLE
Ability to set node affinity and/or tolerations on RKE-deployed addon manifests

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1529]
RKE does not currently allow you to set tolerations or affinity rules on the deployment/daemonset manifests that it deploys, for components like CoreDNS, kube-dns, nginx-ingress, etc.

This is a critical feature required in order to allow for architecting robust highly available clusters when planning for minimizing noisy neighbor problems.

Related issues to this are: 
https://github.com/rancher/rke/issues/1066
https://github.com/rancher/rke/issues/1365

**Comment by ekristen** [comment]
Big +1 to get this added ASAP. Thanks!

**Comment by olegTarassov** [comment]
+1 for us as well. We have master nodes that act as etcd + controlplane node but run our critical stuf like coredns and ingress on those 2 nodes. Easier to create Load balancing and troubleshooting.

Given this limitation, we spin cluster using RKE then modify the daemonset config to allow tolerations for etcd + controlepane and with the node_selection set, the pods lift on the master nodes. the downside, we never touch RKE after the deployments to not overwrite daemonset configs.

hope this makes it soon enough.

**Comment by olegTarassov** [comment]
Updating to latest discovery.
Investigated CoreDNS and Ingress-Nginx deployments and found that tolerations were good:

e.g CoreDNS Deployment

```yaml
tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists

...

nodeSelector:
        beta.kubernetes.io/os: linux
        dns_nodes: coredns

``` 

The problem is in the Affinity declaration:

```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
```

Setting this to `- key: node-role.kubernetes.io/controlplane` resolved the issue.

**Comment by dankeder** [comment]
I wonder why is there `NoExecute` and `NoSchedule` in tolerations?

```yaml
tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
```

If I understand it correctly it means that coredns may be scheduled on cordoned nodes which may become unavailable e.g. due to the OS upgrade or other system maintenance. Or am I missing something?
