### ISSUE TITLE
etcdsnapshot pulls wrong rke-tools tag if custom system images is used 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rke#1551]
```
system_images:
  alpine: "husseingalal/rke-tools:dev"
  nginx_proxy: "husseingalal/rke-tools:dev"
  cert_downloader: "husseingalal/rke-tools:dev"
  kubernetes_services_sidecar: "husseingalal/rke-tools:dev"
``` 
rke fails with: 
WARN[0097] [etcd] Can't pull Docker image [husseingalal/rke-tools:v0.1.40] on host [34.217.43.55]: Error response from daemon: manifest for husseingalal/rke-tools:v0.1.40 not found 
FATA[0097] [etcd] Failed to bring up Etcd Plane: Failed to pull image [husseingalal/rke-tools:v0.1.40] on host [34.217.43.55]: Error response from daemon: manifest for husseingalal/rke-tools:v0.1.40 not found 

it is still trying to get 0.1.40 tag.
