### ISSUE TITLE
Failed to get job complete status for job rke-coredns-addon-deploy-job

### ISSUE THREAD

**Issue by lentzi90** [rancher/rke#1576]
I got the following warning when upgrading to v0.2.7:
> WARN[0187] Failed to deploy addon execute job [rke-coredns-addon]: Failed to get job complete status for job rke-coredns-addon-deploy-job in namespace kube-system

Everything seemed to work just fine anyway, but I still felt like reporting it.
The job pods failed a few times but actually did complete successfully:
```
NAME                                COMPLETIONS   DURATION   AGE
rke-coredns-addon-deploy-job        1/1           114s       23m

NAME                                      READY   STATUS      RESTARTS   AGE
rke-coredns-addon-deploy-job-2nfz6        0/1     Error       0          22m
rke-coredns-addon-deploy-job-fd4b8        0/1     Error       0          22m
rke-coredns-addon-deploy-job-pqkvc        0/1     Error       0          22m
rke-coredns-addon-deploy-job-psdnf        0/1     Error       0          22m
rke-coredns-addon-deploy-job-sqq2d        0/1     Completed   0          20m
```

The logs from the failed pods look like this:
```
serviceaccount/coredns unchanged
clusterrole.rbac.authorization.k8s.io/system:coredns unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:coredns unchanged
configmap/coredns unchanged
deployment.apps/coredns unchanged
deployment.apps/coredns-autoscaler unchanged
serviceaccount/coredns-autoscaler unchanged
clusterrole.rbac.authorization.k8s.io/system:coredns-autoscaler unchanged
The Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.43.0.10": provided IP is already allocated
clusterrolebinding.rbac.authorization.k8s.io/system:coredns-autoscaler unchanged
```
The successful pod have these logs:
```
serviceaccount/coredns unchanged
clusterrole.rbac.authorization.k8s.io/system:coredns unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:coredns unchanged
configmap/coredns unchanged
deployment.apps/coredns unchanged
service/kube-dns created
deployment.apps/coredns-autoscaler unchanged
serviceaccount/coredns-autoscaler unchanged
clusterrole.rbac.authorization.k8s.io/system:coredns-autoscaler unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:coredns-autoscaler unchanged
```

Is this OK? Do I need to take any action to fix CoreDNS?

**RKE version:**
```
$ rke version --config rancher-cluster.yml
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
$ rke --version
rke version v0.2.7
```

**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker info
Containers: 58
 Running: 29
 Paused: 0
 Stopped: 29
Images: 54
Server Version: 18.06.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.122-rancher
Operating System: RancherOS v1.5.2
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.49GiB
Name: ip-10-1-0-4.eu-north-1.compute.internal
ID: D6HN:5N2H:DPFA:VMHS:SE4I:PD5J:VDQH:CZWR:XZHK:5KSB:CEES:PUR3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:24:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release
NAME="RancherOS"
VERSION=v1.5.2
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.2
PRETTY_NAME="RancherOS v1.5.2"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
$ uname -r
4.14.122-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```yaml
cluster_name: <redacted>

ssh_key_path: ssh/id_rsa

cloud_provider:
  name: aws

nodes:
  - address: 13.53.211.34
    internal_address: 10.1.0.4
    user: rancher
    role: [controlplane,worker,etcd]
  - address: 13.53.142.40
    internal_address: 10.1.1.4
    user: rancher
    role: [controlplane,worker,etcd]
  - address: 13.53.211.219
    internal_address: 10.1.2.4
    user: rancher
    role: [controlplane,worker,etcd]

authentication:
  strategy: x509
  sans:
    - "<redacted>"

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

```

**Steps to Reproduce:** unknown

**Results:** Things seem to work normally.

**Comment by superseb** [comment]
On upgrade, kube-dns is replace with CoreDNS. As kube-dns has the service IP for DNS, and it is deleted, it sometimes takes a bit longer to remove the IP allocation so CoreDNS can be deployed. I've seen this before and is caught by the retry mechanism of the jobs. If it would prevent deployment, we would need to make this more reliable but we haven't seen it fail.

**Comment by lentzi90** [comment]
Thanks for the clarification!

**Comment by mwatermolen** [comment]
> we would need to make this more reliable but we haven't seen it fail.

@superseb Oh man can I say we managed that! Cluster with the following YAML for IP changes and a Calico Has been stalled for ~2 hours now

Error:
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Failed to get job complete status for job rke-coredns-addon-deploy-job in namespace kube-system
```

**EDIT:** This seems to be happening when Changing the service IP CIDR w/ Calico upon provisioning


```yaml
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: lnk-rke-cnppx
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy:
        rolling_update: {}
    options: null
    reversecidrs: null
    stubdomains: null
    tolerations: null
    update_strategy: {}
    upstreamnameservers: null
  ignore_docker_version: true
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    provider: nginx
  kubernetes_version: v1.20.11-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: calico
  restore:
    restore: false
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_cluster_ip_range: 10.51.0.0/16
      service_node_port_range: 30000-32767
    kube-controller:
      cluster_cidr: 10.50.0.0/16
      service_cluster_ip_range: 10.51.0.0/16
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
```
