### ISSUE TITLE
[question] [nginx controller] using capture group at rewrite target 

### ISSUE THREAD

**Issue by jinsamkim** [rancher/rke#1599]
**RKE version:**
0.2.7
**Docker version: (`docker version`,`docker info` preferred)**
*
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
*
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
*
**cluster.yml file:**
*
**Steps to Reproduce:**
*
**Results:**

**Question:**

Hi. 
First of all, thank you for your efforts. I love RKE! It is so powerful.
I want to use regex capture group in nginx ingress path.
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/v$1/query
spec:
  rules:
    - http:
        paths:
        - path: /api/v([0-9.]{3,5}])/query
          backend:
            serviceName: my-service
            servicePort: 80
```
I tried to use regex capture group in path for API versioning, but it isn't working.
I found a doc for capture group in path [Rewrite](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/rewrite)
It says, supported at nginx-ingress-controller v0.22.0. 
When are you going to apply `nginx-ingress-controller v0.22.0`.
