### ISSUE TITLE
The kubelet container can't automate reload the `/etc/resolv.conf` content

### ISSUE THREAD

**Issue by Aisuko** [rancher/rke#1609]
**RKE version:**
v0.2.7
**Docker version: (`docker version`,`docker info` preferred)**

```
NAME      STATUS                     ROLES               AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION              CONTAINER-RUNTIME
master1   Ready                      controlplane,etcd   9d    v1.14.5   10.16.18.32   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.9.7
master2   Ready                      controlplane,etcd   9d    v1.14.5   10.16.18.33   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.9.7
woker1    Ready,SchedulingDisabled   worker              9d    v1.14.5   10.16.18.34   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.9.7
woker2    Ready                      worker              9d    v1.14.5   10.16.18.35   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.9.7
woker3    Ready                      worker              9d    v1.14.5   10.16.18.36   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.9.7
woker4    Ready                      worker              9d    v1.14.5   10.16.18.37   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-957.5.1.el7.x86_64   docker://18.9.7

```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
```
nodes:
    - address: 10.16.18.32
      user: rancher
      role:
        - controlplane
        - etcd
      hostname_override: master1
      # internal_address: 172.16.22.11
      # ssh_key_path: /home/user/.ssh/id_rsa
      # port: 2222
    - address: 10.16.18.33
      user: rancher
      role:
        - controlplane
        - etcd
      hostname_override: master2
      # internal_address: 172.16.22.12
      # ssh_key: |-
      #   -----BEGIN RSA PRIVATE KEY-----

      #   -----END RSA PRIVATE KEY-----
      #- address: 10.16.18.23
      #user: rancher
      #role:
      #  - controlplane
      #  - etcd
      #hostname_override: master3
      # internal_address: 172.16.22.13

    - address: 10.16.18.34
      user: rancher
      role:
        - worker
      hostname_override: woker1

    - address: 10.16.18.35
      user: rancher
      role:
        - worker
      hostname_override: woker2

    - address: 10.16.18.36
      user: rancher
      role:
        - worker
      hostname_override: woker3
    - address: 10.16.18.37
      user: rancher
      role:
        - worker
      hostname_override: woker4
    # - address: 10.16.18.28
    #   user: rancher
    #   role:
    #     - worker
    #   hostname_override: woker5
    # - address: 10.16.18.29
    #   user: rancher
    #   role:
    #     - worker
    #   hostname_override: woker6



# If set to true, RKE will not fail when unsupported Docker version are found
ignore_docker_version: false

# Cluster level SSH private key
# Used if no ssh information is set for the node
# ssh_key_path: ~/.ssh/test

# Enable use of SSH agent to use SSH private keys with passphrase
# This requires the environment `SSH_AUTH_SOCK` configured pointing to your SSH agent which has the private key added
# ssh_agent_auth: true

# List of registry credentials
# If you are using a Docker Hub registry, you can omit the `url` or set it to `docker.io`
# private_registries:
#     - url: registry.com
#       user: Username
#       password: password

# Bastion/Jump host configuration
# bastion_host:
#     address: x.x.x.x
#     user: ubuntu
#     port: 22
#     ssh_key_path: /home/user/.ssh/bastion_rsa
# or
#   ssh_key: |-
#     -----BEGIN RSA PRIVATE KEY-----
#
#     -----END RSA PRIVATE KEY-----

# Set the name of the Kubernetes cluster
cluster_name: rancherHA

services:
  etcd:
    snapshot: true
    creation: 120m0s
    retention: 12h

    # Need S3 and did not be related with RKE version.
    # backup_config:
    #   interval_hours: 12
    #   retention: 6

  kubelet:
    extra_args:
      volume-plugin-dir: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
    extra_binds:
      - "/usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec"




authentication:
    strategy: x509

# Kubernetes Authorization mode
# Use `mode: rbac` to enable RBAC
# Use `mode: none` to disable authorization
authorization:
    mode: rbac

# Add-ons are deployed using kubernetes jobs. RKE will give up on trying to get the job status after this timeout in seconds..
addon_job_timeout: 40


# There are several network plug-ins that work, but we default to canal
network:
    plugin: canal

# Specify DNS provider (coredns or kube-dns)
dns:
    provider: coredns

# Currently only nginx ingress provider is supported.
# To disable ingress controller, set `provider: none`

ingress:
    provider: nginx

# addons_include:
    # - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/common.yaml
    # - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/operator.yaml
    # - https://raw.githubusercontent.com/rook/rook/release-1.0/cluster/examples/kubernetes/ceph/cluster-test.yaml
    # - https://raw.githubusercontent.com/rook/rook/release-1.0/cluster/examples/kubernetes/ceph/toolbox.yaml
    # - /path/to/manifest
```
**Steps to Reproduce:**

I'm not sure that can be reproduced 100%, I just edit the `/etc/resolv.conf` by manually. But the `kubelet` container didn't reload the config. Please see `Other information we need to know`

**Results:**

**Other information we need to know**

```
[rancher@qtsz-demo-k8s-n01 ~]$ docker exec -it 4d5d8ef605f3 cat /etc/resolv.conf
# Generated by NetworkManager
search sz.iquantex.com
# nameserver 10.116.18.50
# nameserver 10.16.18.50
nameserver 10.116.18.67
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
# nameserver 114.114.114.114
```

The kubelet container
```
4d5d8ef605f3        rancher/hyperkube:v1.14.5-rancher1   "/opt/rke-tools/entr…"   3 days ago          Up 39 minutes                                     kubelet
```

I have to restart the `kubelet` container by manually, but I believe that the `etc/resov.conf` should be automated load into the container. so, it there anything I didn't notice?

```
[rancher@qtsz-demo-k8s-n01 ~]$ docker restart 4d5d8ef605f3
4d5d8ef605f3
[rancher@qtsz-demo-k8s-n01 ~]$ docker exec -it 4d5d8ef605f3 cat /etc/resolv.conf
# Generated by NetworkManager
search sz.iquantex.com
nameserver 10.116.18.50
nameserver 10.16.18.50
nameserver 114.114.114.114
```
