### ISSUE TITLE
kube-apiserver gets recreated at random due to reordering etcd-servers parameter

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1616]
**RKE version:**
`v0.3.0-rc8`
**Docker version: (`docker version`,`docker info` preferred)**
n/a
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
n/a
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n/a
**cluster.yml file:**
```
nodes:
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: x
  internal_address: x
  user: ubuntu
  role: [controlplane,worker,etcd]
```
**Steps to Reproduce:**
1. Run `rke --debug up` with `cluster.yml` as above (more than 1 etcd node at least)
1. Run `rke --debug up` again

**Results:**
kube-apiserver randomly gets recreated because the `etcd-servers` gets reordered

```
DEBU[0032] slice is not equal, showing data in new value which is not in old value: map[--etcd-servers=https://x:2379,https://x:2379,https://x:2379:{}]                                                                                                                           [1440/4666]
DEBU[0032] [controlplane] Container [kube-apiserver] is eligible for upgrade on host [35.180.199.30]
```

This was added in https://github.com/rancher/rke/pull/1361
