### ISSUE TITLE
s3backupconfig: How to pass the custom CA to "etcd-rolling-snapshots"?

### ISSUE THREAD

**Issue by hasonhai** [rancher/rke#1628]
**RKE version:**
RKE version 0.2.8

When we configuring rolling snapshot to store backup in s3 compatible storage in cluster.yml, I would like to know how to pass the custom CA to the container "etcd-rolling-snapshots" for it to auto do the snapshot??? I have tried a few ways but none of them works as expected.

```
services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: "FEGCB5XXXXXXXXXX1IK7R"
        secret_key: "IfLBWAWWXXXXXXXXXchFrHuaa6YGcM1fLqJ3"
        bucket_name: kubernetes-aaptest-cluster2-etcd-backups
        region: ""
        endpoint: rgw.example.com
        endpoint_ca: |
          -----BEGIN CERTIFICATE-----
          MIIJrzCCB5egAwIBAgITEQB2hKMXkhBpiC3qGwACAHaEozANBgkqhkiG9w0BAQsF
          ADCB3TELMAkGA1UEBhMCR08xFjAUBgNVBAgTDU5vcnRoIEhvbGxhbmQxEjAQBgNV
          BAcTCUFtc3RlcmRhbTErMCkGA1UEChMiS1BNRyBJbnRlcm5hbCBDZXJ0aWZpY2F0
          ZSBTZXJ2aWNlczEfMB0GA1UECxMWS1BNRyBIaWdoIEFzc3VyYW5jZSBDQTEmMCQG
          A1UEAxMdS1BNRyBJbnRlcm5hbCBJc3N1aW5nIENBIEdPMDMxLDAqBgkqhkiG9w0B
          CQEWHWdvLWZtaXRzZ2xvYmFsY2VydGlmQGtwbWcuY29tMB4XDTE4MDYyNTA3NTgz
          MloXDTIwMDYyNDA3NTgzMlowcjELMAkGA1UEBhMCREUxDzANBgNVBAgTBkJlcmxp
```

**Comment by moelsayed** [comment]
@hasonhai You are almost there, use `endpoint_ca: |-`.

**Comment by hasonhai** [comment]
Not work at all. The argument for endpoint-ca is left empty.

`time="2019-10-14T13:22:29Z" level=error msg="failed to set s3 server: failed to check s3 bucket:kubernetes-aaptest-cluster2-etcd-backups, err:Get https://rgw.example.com/kubernetes-aaptest-cluster2-etcd-backups/?location=: x509: certificate signed by unknown authority" s3-accessKey=FEGCB5XXXXXXXXXX1IK7R s3-bucketName=kubernetes-aaptest-cluster2-etcd-backups s3-endpoint=rgw.example.com s3-endpoint-ca= s3-folder= s3-region=`

**Comment by MAHDTech** [comment]
Didn't work for me either, I was originally using endpoint_ca due to finding this however turns out should be custom_ca.

on the command line the flag is `--s3-endpoint-ca`

The documentation found [HERE](https://rancher.com/docs/rke/latest/en/etcd-snapshots/recurring-snapshots/) was unclear for me so thankfully this is open source :)

If using yaml, this works.

```yaml
      s3backupconfig:
        bucket_name: "mybucket"
        folder: "etcd-snapshots"
        access_key: "access_key"
        secret_key: "secret_key"
        endpoint: "minio.mydomain.com"
        custom_ca: |-
        -----BEGIN CERTIFICATE-----
        snip
        -----END CERTIFICATE-----
```
