### ISSUE TITLE
Finished building Kubernetes cluster successfully.But,kubectl: command not found.

### ISSUE THREAD

**Issue by zhanhaibin** [rancher/rke#164]
**RKE version:**
v0.0.8-dev
**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.13.1, build 092cba3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware
**cluster.yml file:**
```
---

auth:
  strategy: x509
  options:
    foo: bar

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS, use the network plugin config option:
# 'calico_cloud_provider: aws'
network:
  plugin: flannel
  options:
    foo: bar

ssh_key_path: ~/.ssh/id_rsa
ignore_docker_version: false

# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization

authorization:
  mode: rbac
  options:

nodes:
  - address: 10.10.64.140
    user: ubuntu
    role: [controlplane,etcd]
    ssh_key_path: ~/.ssh/id_rsa
  - address: 10.10.64.141
    user: ubuntu
    role: [worker]
    ssh_key: |-

#      -----BEGIN RSA PRIVATE KEY-----

#      -----END RSA PRIVATE KEY-----
#  - address: example.com
#    user: ubuntu
#    role: [worker]
#    hostname_override: node3
#    internal_address: 192.168.1.6

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {"fail-swap-on":"false"}
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2


#system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0

# all addon manifests MUST specify a namespace
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-nginx
      namespace: default
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
 
```
**Steps to Reproduce:**
ubuntu@master:/srv/k8s$ kubectl get no
kubectl: command not found
**Results:**
ubuntu@master:/srv/k8s$ ./rke_linux-amd64 up --config clustersignle.yml
INFO[0000] Building Kubernetes cluster
INFO[0000] [ssh] Setup tunnel for host [10.10.64.140]
INFO[0000] [ssh] Setup tunnel for host [10.10.64.140]
INFO[0000] [ssh] Setup tunnel for host [10.10.64.141]
INFO[0000] [certificates] Generating kubernetes certificates
INFO[0000] [certificates] Generating CA kubernetes certificates
INFO[0001] [certificates] Generating Kubernetes API server certificates
INFO[0001] [certificates] Generating Kube Controller certificates
INFO[0001] [certificates] Generating Kube Scheduler certificates
INFO[0001] [certificates] Generating Kube Proxy certificates
INFO[0001] [certificates] Generating Node certificate
INFO[0002] [certificates] Generating admin certificates and kubeconfig
INFO[0002] [reconcile] Reconciling cluster state
INFO[0002] [reconcile] This is newly generated cluster
INFO[0002] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0028] Successfully Deployed local admin kubeconfig at [./.kube_config_clustersignle.yml]
INFO[0028] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0028] [etcd] Building up Etcd Plane..
INFO[0028] [etcd] Pulling Image on host [10.10.64.140]
INFO[0035] [etcd] Successfully pulled [etcd] image on host [10.10.64.140]
INFO[0036] [etcd] Successfully started [etcd] container on host [10.10.64.140]
INFO[0036] [etcd] Successfully started Etcd Plane..
INFO[0036] [controlplane] Building up Controller Plane..
INFO[0036] [controlplane] Pulling Image on host [10.10.64.140]
INFO[0043] [controlplane] Successfully pulled [kube-api] image on host [10.10.64.140]
INFO[0044] [controlplane] Successfully started [kube-api] container on host [10.10.64.140]
INFO[0044] [controlplane] Pulling Image on host [10.10.64.140]
INFO[0051] [controlplane] Successfully pulled [kube-controller] image on host [10.10.64.140]
INFO[0051] [controlplane] Successfully started [kube-controller] container on host [10.10.64.140]
INFO[0051] [controlplane] Pulling Image on host [10.10.64.140]
INFO[0059] [controlplane] Successfully pulled [scheduler] image on host [10.10.64.140]
INFO[0059] [controlplane] Successfully started [scheduler] container on host [10.10.64.140]
INFO[0059] [controlplane] Successfully started Controller Plane..
INFO[0059] [worker] Building up Worker Plane..
INFO[0059] [worker] Pulling Image on host [10.10.64.140]
INFO[0067] [worker] Successfully pulled [kubelet] image on host [10.10.64.140]
INFO[0068] [worker] Successfully started [kubelet] container on host [10.10.64.140]
INFO[0068] [worker] Pulling Image on host [10.10.64.140]
INFO[0075] [worker] Successfully pulled [kube-proxy] image on host [10.10.64.140]
INFO[0075] [worker] Successfully started [kube-proxy] container on host [10.10.64.140]
INFO[0075] [worker] Container [nginx-proxy] is already running on host [10.10.64.141]
INFO[0075] [worker] Container [kubelet] is already running on host [10.10.64.141]
INFO[0075] [worker] Container [kube-proxy] is already running on host [10.10.64.141]
INFO[0075] [worker] Successfully started Worker Plane..
INFO[0075] [certificates] Save kubernetes certificates as secrets
INFO[0093] [certificates] Successfuly saved certificates as kubernetes secret [k8s-certs]
INFO[0093] [state] Saving cluster state to Kubernetes
INFO[0094] [state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state
INFO[0094] [network] Setting up network plugin: flannel
INFO[0094] [addons] Saving addon ConfigMap to Kubernetes
INFO[0094] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin
INFO[0094] [addons] Executing deploy job..
INFO[0099] [addons] Setting up KubeDNS
INFO[0099] [addons] Saving addon ConfigMap to Kubernetes
INFO[0099] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-kubedns-addon
INFO[0099] [addons] Executing deploy job..
INFO[0104] [addons] KubeDNS deployed successfully..
INFO[0104] [addons] Setting up user addons..
INFO[0104] [addons] Saving addon ConfigMap to Kubernetes
INFO[0104] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-user-addon
INFO[0104] [addons] Executing deploy job..
INFO[0109] [addons] User addon deployed successfully..
INFO[0109] Finished building Kubernetes cluster successfully

ubuntu@master:/srv/k8s$ docker ps
```
CONTAINER ID        IMAGE                                                                                                COMMAND                  CREATED              STATUS              PORTS                              NAMES
80fcd91d5d8a        gcr.io/google_containers/pause-amd64:3.0                                                             "/pause"                 7 seconds ago        Up 6 seconds                                           k8s_POD_kube-dns-778977457c-5wrzt_kube-system_fcc9cbd8-e40d-11e7-971b-000c294d273e_0
f3316b7c29ad        gcr.io/google_containers/pause-amd64:3.0                                                             "/pause"                 8 seconds ago        Up 6 seconds                                           k8s_POD_kube-dns-autoscaler-5cb4f55974-l9zjf_kube-system_fcac0850-e40d-11e7-971b-000c294d273e_0
ae122f33da95        gcr.io/google_containers/pause-amd64:3.0                                                             "/pause"                 11 seconds ago       Up 10 seconds                                          k8s_POD_my-nginx_default_ffb6e721-e40d-11e7-971b-000c294d273e_0
b69615819841        quay.io/coreos/flannel-cni@sha256:77bf1017845afb65e2603d8573e9a2d649eb645a4f7fe4843f17e276b8126968   "/install-cni.sh"        28 seconds ago       Up 27 seconds                                          k8s_install-cni_kube-flannel-d44cx_kube-system_f9a13283-e40d-11e7-971b-000c294d273e_0
c9733d3ed1a4        quay.io/coreos/flannel@sha256:60d77552f4ebb6ed4f0562876c6e2e0b0e0ab873cb01808f23f55c8adabd1f59       "/opt/bin/flanneld..."   28 seconds ago       Up 27 seconds                                          k8s_kube-flannel_kube-flannel-d44cx_kube-system_f9a13283-e40d-11e7-971b-000c294d273e_0
781f6e2b4dbc        gcr.io/google_containers/pause-amd64:3.0                                                             "/pause"                 28 seconds ago       Up 27 seconds                                          k8s_POD_kube-flannel-d44cx_kube-system_f9a13283-e40d-11e7-971b-000c294d273e_0
22c0e9484f44        rancher/k8s:v1.8.3-rancher2                                                                          "kube-proxy --v=2 ..."   48 seconds ago       Up 47 seconds                                          kube-proxy
6acb6c63c8e4        rancher/k8s:v1.8.3-rancher2                                                                          "kubelet --v=2 --a..."   56 seconds ago       Up 55 seconds                                          kubelet
2dd234f5f631        rancher/k8s:v1.8.3-rancher2                                                                          "kube-scheduler --..."   About a minute ago   Up About a minute                                      scheduler
e9484730fea6        rancher/k8s:v1.8.3-rancher2                                                                          "kube-controller-m..."   About a minute ago   Up About a minute                                      kube-controller
5d7bb1c8813f        rancher/k8s:v1.8.3-rancher2                                                                          "kube-apiserver --..."   About a minute ago   Up About a minute                                      kube-api
ceb4bebc08e3        quay.io/coreos/etcd:latest                                                                           "/usr/local/bin/et..."   About a minute ago   Up About a minute   0.0.0.0:2379-2380->2379-2380/tcp   etcd
```
