### ISSUE TITLE
Unable to pull the images from Private Registry

### ISSUE THREAD

**Issue by mmuruganandam** [rancher/rke#167]
Hi,
Using the docker secret in the kubernetes yaml file, the images are not pulled.  It is failing with http code of 401 (unauthorized).

Error on the dashboard.
"**Failed to pull image "xxxxxxxxxxxxxxxxxxxx/test-service:latest": rpc error: code = Unknown desc = unauthorized: authentication required
Error syncing pod**"

```
kubectl create secret docker-registry docker-secret --docker-server=<docker registry server> --docker-username=<user> --docker-password=<password> --docker-email=<email>
```

Yaml:
```
      imagePullSecrets:
      - name: docker-secret 

```

**Comment by galal-hussein** [comment]
Can you make sure that you are using the right credentials, i can't reproduce the problem:

on kubernetes node
```
root@hussein-1612-10acre-1:# docker pull husseingalal/private
Using default tag: latest
Pulling repository docker.io/husseingalal/private
Error: image husseingalal/private:latest not found
```
create the secret

```
kubectl create secret docker-registry regsecret --docker-server=index.docker.io --docker-username=husseingalal --docker-password=xxxxx ....
```
then pod.yml
```
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: husseingalal/private
  imagePullSecrets:
  - name: regsecret
```

```
kubectl get pods     
NAME          READY     STATUS    RESTARTS   AGE
private-reg   1/1       Running   0          22s
```
