### ISSUE TITLE
Cluster name not being set

### ISSUE THREAD

**Issue by caiges** [rancher/rke#1671]
**RKE version:**
v0.2.8

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

`3.10.0-957.27.2.el7.x86_64`
`CentOS Linux release 7.7.1908 (Core)`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

KVM VMs

**cluster.yml file:**
```
cluster_name: tacoman

nodes:
  - address: master-001.tacoman.com
    user: rancher
    role: [etcd,controlplane]
  - address: master-002.tacoman.com
    user: rancher
    role: [etcd,controlplane]
  - address: master-003.tacoman.com
    user: rancher
    role: [etcd,controlplane]
  - address: node-001.tacoman.com
    user: rancher
    role: [worker]
  - address: node-002.tacoman.com
    user: rancher
    role: [worker]
  - address: node-003.tacoman.com
    user: rancher
    role: [worker]

ssh_key_path: rancher
kubernetes_version: v1.14.6-rancher1-1

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

addons: |-
  ---
  apiVersion: v1
  data:
    tls.crt: |
      <cert>
      
    tls.key: |
      <key>

  kind: Secret
  metadata:
    creationTimestamp: null
    name: ingress-default-cert
    namespace: ingress-nginx
  type: kubernetes.io/tls
```
**Steps to Reproduce:**
1. Use `rke` to create the rancher cluster using the above config file.

**Results:**
The cluster name should be `tacoman` but is set to `local`.
