### ISSUE TITLE
Error message when pulling new images should be removed

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#1684]
**RKE version:**
```
$ rke -v
rke version v0.3.0
```
**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
MacOS 10.14.6 (rke cli)
RancherOS 1.5.4 (nodes)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```yaml
authentication:
    sans:
      - "52.26.2.20"
      - "52.12.153.84"
      - "54.202.231.16"
nodes:
  - address: 52.26.2.20
    internal_address: 10.0.1.10
    user: rancher
    role:
      - worker
      - controlplane
      - etcd

  - address: 52.12.153.84
    internal_address: 10.0.1.11
    user: rancher
    role:
      - worker
      - controlplane
      - etcd

  - address: 54.202.231.16
    internal_address: 10.0.1.12
    user: rancher
    role:
      - worker
      - controlplane
      - etcd

ssh_agent_auth: true

services:
  etcd:
    snapshot: true
    creation: 1h
    retention: 240h
```
**Steps to Reproduce:**
run rke up

**Results:**
Appears in 0.3, first time images are pulled, it shows an "Error":
```
INFO[0000] Checking if image [rancher/rke-tools:v0.1.50] exists on host [52.26.2.20], try #1



INFO[0000] Image [rancher/rke-tools:v0.1.50] does not exist on host [52.26.2.20]: Error: No such image: rancher/rke-tools:v0.1.50
INFO[0000] Pulling image [rancher/rke-tools:v0.1.50] on host [52.26.2.20], try rancher/rke#1
```
Specifically, `Error: No such image: rancher/rke-tools:v0.1.50` should be removed. It's misleading to state there is an error the first time you run rke and it needs to pull images.

In RKE 0.2, the message was:
```
INFO[0030] [state] Pulling image [rancher/rke-tools:v0.1.42] on host [34.212.178.64]
INFO[0037] [state] Successfully pulled image [rancher/rke-tools:v0.1.42] on host [34.212.178.64]
```
