### ISSUE TITLE
[forwardport] system_images is empty when running `rke config` 

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1719]
Forwardport https://github.com/rancher/rke/issues/1685

**Comment by kinarashah** [comment]
https://github.com/rancher/rke/issues/1710

**Comment by aaronRancher** [comment]
Tested on rke `v0.3.2`

Run `rke config` using defaults
System images are populated in resulting `cluster.yml`
```
system_images:
  etcd: rancher/coreos-etcd:v3.3.15-rancher1
  alpine: rancher/rke-tools:v0.1.51
  nginx_proxy: rancher/rke-tools:v0.1.51
  ...
```
Kubernetes Docker image is populated in defaults:
`[+] Kubernetes Docker image [rancher/hyperkube:v1.16.3-rancher1]: `
