### ISSUE TITLE
hostPath volume doesn't work

### ISSUE THREAD

**Issue by zeppelinux** [rancher/rke#172]
**RKE version:**
v0.0.8-dev
**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
---
nodes:
  - address: 192.168.2.208
    user: rancher
    role: [controlplane]
  - address: 192.168.2.216
    user: rancher
    role: [worker]
  - address: 192.168.2.7
    user: rancher
    role: [etcd]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.5-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.5-rancher2
  scheduler:
    image: rancher/k8s:v1.8.5-rancher2
  kubelet:
    image: rancher/k8s:v1.8.5-rancher2
    extra_args:
       fail-swap-on: false
  kubeproxy:
    image: rancher/k8s:v1.8.5-rancher2
**Steps to Reproduce:**
add hostPath like this:

 volumes:
      - name: plex-data
        hostPath:
          path: /mnt/storage

Check is /mnt/storage exists on the host

**Results:**
deployment fails with lstat: /mnt/storage doesn't exists

Kubelet can't find the path probably because kubelet is running as a container and there is no /mnt/storage mounted.

**Comment by galal-hussein** [comment]
@zeppelinux I don't think the error related to rke or kubelet, i wasn't able to reproduce:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /mnt/storage
```
```
kubectl get pods
NAME                    READY     STATUS    RESTARTS   AGE
test-pd                 1/1       Running   0          4s

```
