### ISSUE TITLE
[backport] ssh-agent-auth requires a ssh-key-file with bastion host

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1746]
Backport https://github.com/rancher/rke/issues/1670

**Comment by jiaqiluo** [comment]
The bug is reproduced with RKE v0.2.8
```
➜  rke --v
rke version v0.2.8
```

Steps:
- in my local machine, use `ssh-add` to add the private key to ssh-agent.
- use `ssh-add -l` to verify the key is added 
- rename the private key and public key files
- use `ssh_agent_auth` and `bastion_host` in the rancher-cluster.yml file  
```
ssh_agent_auth: true
bastion_host:
    address: [public-ip]
    user: ubuntu
    port: 22
nodes:
  - address: [private-ip]
    user: ubuntu
    role: [etcd, controlplane, worker]   
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
  kube-api:
    pod_security_policy: false
```

- user `rke up ` to provision the cluster

Result:
the following error shows
```
INFO[0000] Initiating Kubernetes cluster
FATA[0000] Error while reading SSH key file: open /Users/jiaqi/.ssh/id_rsa: no such file or directory
```
