### ISSUE TITLE
cluster's encryption provider configuration log message seen in cluster without the feature enabled               

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1749]
**RKE version:**
master (https://github.com/rancher/rke/commit/1bee3e452fef70082fcf8b0a9d41a29107ecbf72)

**Steps to Reproduce:**
Run `rke up` against a single node cluster with all roles (just having `nodes` directive in `cluster.yml`)

**Results:**
Log message on cluster's encryption provider configuration is shown while its not active.

```
INFO[0039] [controlplane] Reconciling cluster's encryption provider configuration..                
```

**Comment by alena1108** [comment]
@sangeethah the fix was applied as a part of functional fixes in the area.

**Comment by sowmyav27** [comment]
verified with rke version `rke version v1.0.0-rc6`
**Scenario#1**
-Cluster.yml with NO secrets_encryption_config
- `INFO[0039] [controlplane] Reconciling cluster's encryption provider configuration..  ` is not seen in the logs

**Scenario#2**
- CLuster.yml with secrets_encryption_config - enabled, do an rke up.
- `INFO[0039] [controlplane] Reconciling cluster's encryption provider configuration..  ` was not seen.
- Do another rke up.
- `INFO[0039] [controlplane] Reconciling cluster's encryption provider configuration..  ` was not seen in the logs.
```
nodes:
  - address: ip
    internal_address: ip
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: <path>

services:
  etcd:
    snapshot: true
    creation: 1h
    retention: 24h
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-jgxw9
                secret: QkNEQTRGRUMyMTExOUM4M0FBNjY4MTlDNTBDQTY4RkE=
          - identity: {}
```
