### ISSUE TITLE
Cluster deployment successful but `failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file`

### ISSUE THREAD

**Issue by papanito** [rancher/rke#1764]
**RKE version:** `0.3.2`

**Docker version: (`docker version`,`docker info` preferred)**

```bash
Client:
 Debug Mode: false

Server:
 Containers: 27
  Running: 16
  Paused: 0
  Stopped: 11
 Images: 21
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: node001
 ID: XSHX:3C4H:BZIQ:EBKK:DED5:XXOF:5VHV:FORZ:3K4Y:3GXI:VWLS:E7LV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

`Linux node001 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

`Bare-Metal`

**cluster.yml file:**

```yaml
nodes:
  - address: x.x.x.x
    internal_address: 192.168.100.1
    user: ansible
    role: [controlplane,worker,etcd]
  - address: y.y.y.y
    internal_address: 192.168.100.2
    user: ansible
    role: [controlplane,worker,etcd]

cluster_name: dev-cluster

dns:
    provider: coredns
    upstreamnameservers:
    - 1.1.1.1
    - 8.8.8.8
    - 8.8.4.4

ingress:
    provider: nginx

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 48h
ignore_docker_version: true
```
**Steps to Reproduce:**

Run `rke up --config myconfig.yml`

**Results:**

```bash
F1109 16:50:12.580123   32732 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
```
