### ISSUE TITLE
[forwardport] Ability to set base directory for private registry 

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1775]
Forwardport https://github.com/rancher/rke/issues/1232

**Comment by deniseschannon** [comment]
Available with RKE CLI v1.1.0-rc1

**Comment by soumyalj** [comment]
Tested with master-head branch
1. Create a private registry and load  images(master-head)  required for rke cluster creation
2. Create a custom cluster through UI and in the cluster.yml file provide the private registry info with the base directory as below
```
private_registries:
    - url: registry.com/qa/test
      user: Username
      password: password

```
Cluster creation was successful. Workloads got created fine. The Cluster API had the private registry field set
