### ISSUE TITLE
[CentOS 8][Debian 10] No network connectivity outside of pod or to other pods with Canal and Calico

### ISSUE THREAD

**Issue by papanito** [rancher/rke#1788]
I've successfully installed kubernetes 1.16 with rke 0.3.2 however, there is no connection from the pods to outside nor to other pods.

**RKE version:** 

`v0.3.2`

**Docker version: (`docker version`,`docker info` preferred)**

```bash
vdocker info
Client:
 Debug Mode: false

Server:
 Containers: 31
  Running: 22
  Paused: 0
  Stopped: 9
 Images: 25
 Server Version: 18.09.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.19GiB
 Name: node002
 ID: EDFH:4JPU:JZ26:T5CH:N2TS:FUBG:QKIC:I7WA:C5A5:LN4A:424G:VFAX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

`4.18.0-80.11.2.el8_0.x86_64` (CentOS 8)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

`Bare-metal`

**cluster.yml file:**

```yaml
# 
# Cluster Config
# 
enable_cluster_alerting: true
enable_cluster_monitoring: true
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true

nodes:
  - address: y.y.y.8
    internal_address: 192.168.100.1
    user: ansible
    role: [controlplane,worker,etcd]
  - address: x.x.x.14
    internal_address: 192.168.100.2
    user: ansible
    role: [controlplane,worker,etcd]

cluster_name: dev-cluster
kubernetes_version: "v1.16.2-rancher1-1" # rke config --list-version --all

# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 90
  authentication:
    strategy: x509
  ignore_docker_version: true

dns:
  provider: coredns
  upstreamnameservers:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4
  - 213.133.100.100
  - 213.133.99.99
  - 213.133.98.98
  #- 2a01:4f8:0:1::add:1010
  #- 2a01:4f8:0:1::add:9898
  #- 2a01:4f8:0:1::add:9999

network:
  plugin: canal
  options:
      #canal_iface: enp4s0.4000
      canal_flannel_backend_type: vxlan

ingress:
    provider: nginx

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 48h
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
```

**Steps to Reproduce:**

1. install new cluster
      `rke up --config config.yaml`
2. Run `multitool` container
     ```
     kubectl run multitool --image=praqma/network-multitool --restart Never
     kubectl exec -it multitool  -- bash
     ```

**Results:**
***connection from pod***

```bash
bash-5.0# traceroute 172.217.168.14
traceroute to 172.217.168.14 (172.217.168.14), 30 hops max, 46 byte packets
 1  x.x.x.14 (x.x.x.14)  0.012 ms  0.098 ms  0.004 ms
 2  *  *  *
 3  *  *  *
 4  *  *  *
 5  *c^C
 
bash-5.0# curl 172.217.168.14
curl: (7) Failed to connect to 172.217.168.14 port 80: Operation timed out
```
***connection from node***

The connection on the hosts seems fine

```bash
[user@node001 ~]$ ping google.com
PING google.com(fra16s25-in-x0e.1e100.net (2a00:1450:4001:825::200e)) 56 data bytes
64 bytes from fra16s25-in-x0e.1e100.net (2a00:1450:4001:825::200e): icmp_seq=1 ttl=57 time=4.84 ms
64 bytes from fra16s25-in-x0e.1e100.net (2a00:1450:4001:825::200e): icmp_seq=2 ttl=57 time=4.86 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 2ms
rtt min/avg/max/mdev = 4.836/4.850/4.864/0.014 ms

[user@node001 ~]$ curl 172.217.168.14
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

Here my `ip route` output on the node

```bash
default via x.x.x.1 dev enp4s0 proto static metric 100 
x.x.x.1 dev enp4s0 proto static scope link metric 100 
x.x.x.14 dev enp4s0 proto kernel scope link src x.x.x.14 metric 100 
10.42.0.3 dev calie0ef90acfad scope link 
10.42.0.4 dev cali6d09fa47963 scope link 
10.42.0.5 dev calicfe92e547cd scope link 
10.42.0.6 dev cali83e218e70ab scope link 
10.42.1.0/24 via 10.42.1.0 dev flannel.1 onlink 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.100.0/24 dev enp4s0.4000 proto kernel scope link src 192.168.100.2 metric 400 
```

The k8s nodes themselves to not run firewalld and I checked several things which seem fine

***selinux disabled***

```bash
[user@node001 ~]$ cat /etc/sysconfig/selinux

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
# SELINUX=enforcing
SELINUX=disabled
# SELINUXTYPE= can take one of these three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted
```

***sysctl***

```bash
[user@node001 ~]$ sysctl net.bridge
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
....
[user@node001 ~]$ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
[user@node001 ~]$ sysctl net.ipv6.ip_forward
net.ipv6.conf.all.forwarding = 1
```

***iptables***

```bash
sudo iptables -L -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 145K 6575K DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 145K 6575K DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  190 18756 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   63  3780 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
  296 15245 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  296 15245 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
 145K 6575K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

Maybe also useful to know, I use a multitool container for debugging, this is the config

```bash
 kubectl get pods -o wide
NAME        READY   STATUS    RESTARTS   AGE   IP          NODE        NOMINATED NODE   READINESS GATES
multitool   1/1     Running   1          20h   10.42.0.4   x.x.x.14    <none>           <none>
```
and this is the `ip addr list` in the container

```bash
bash-5.0# ip addr list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if106528: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ca:49:03:ec:75:43 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.0.4/32 scope global eth0
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
```

**Comment by papanito** [comment]
Switching* to `calico` results in the same problem

*) complete teardown of cluster, cleaning nodes and spin up new cluster

**Comment by ekarlso** [comment]
I am trying on a brand new Centos 8 installed cluster to run Canal but my canal instances on the nodes are not coming up.

**Comment by johnjcool** [comment]
same problem.

fixed it by adding `FELIX_IPTABLESBACKEND=NFT` to calico-node like mentioned in this thread https://github.com/projectcalico/calico/issues/2322

**Comment by papanito** [comment]
@johnjcool you mean by adding an environment variable in the pod?

**Comment by johnjcool** [comment]
Yes, on DeamonSet.

**Comment by papanito** [comment]
By change do you know how the rke `config.yaml` should look like?

**Comment by papanito** [comment]
For now I've manually updated the `deployment`

```
....
Pod Template:
  Labels:           k8s-app=calico-kube-controllers
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod: 
  Service Account:  calico-kube-controllers
  Containers:
   calico-kube-controllers:
    Image:      rancher/calico-kube-controllers:v3.8.1
    Port:       <none>
    Host Port:  <none>
    Readiness:  exec [/usr/bin/check-status -r] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ENABLED_CONTROLLERS:    node
      DATASTORE_TYPE:         kubernetes
      FELIX_IPTABLESBACKEND:  NFT
...
```
However, the ping from my multitool container fails.

**Comment by papanito** [comment]
I've updated the dameonset

```yaml
....
    Environment:
      FELIX_IPTABLESBACKEND:              NFT
....
```
and new pods were created
```bash
calico-node-82s74                          1/1     Running     0          70s
calico-node-qv7fg                          1/1     Running     0          48s
```

However, when I issue a ping from my `multitool`container the ping still fails

```bash
bash-5.0# ping google.com
PING google.com (216.58.207.78) 56(84) bytes of data.
^C
--- google.com ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 144ms
```
However, name resolution now works!
