### ISSUE TITLE
Kubelet pod doesn't respond after installing with rke

### ISSUE THREAD

**Issue by jdor521** [rancher/rke#1806]
**RKE version: 0.3.1**

**Docker version: 18.06.3-ce**

**Operating system and kernel: Debian 9.4 4.9.0-6-amd64**

**Type/provider of hosts: vSphere 6.7**

**cluster.yml file:**
```
nodes:
    - address: node1.ip
      user: root
      role: [ "controlplane", "etcd", "worker" ]
      ssh_key_file: /root/.ssh/id_rsa
    - address: node2.ip
      user: root
      role: [ "controlplane", "etcd", "worker" ]
      ssh_key_file: /root/.ssh/id_rsa
    - address: node3.ip
      user: root
      role: [ "controlplane", "etcd", "worker" ]
      ssh_key_file: /root/.ssh/id_rsa

private_registries:
    - url: private.registry:5000
      is_default: yes
system_images:
    kubernetes: private.registry:5000/rancher/hyperkube:v1.15.5-rancher1
```

**Steps to Reproduce:**
installing successfully the cluster but when I try to reach kubelet with:
```
curl  -sk https://localhost:10250/pods
```
I receive "Unauthorized". 
**Situation:**

I work in an Air-Gap environment (that's why I couldn't provide the full docker info) and I can't reach and query my kubelet pod. 
Tried basically everything - tried to apply these two flags "--authorization-mode=AllowAll" "--anonymous-auth=true" to its configuration file or to the cluster.yml but it didn't work and the configuration hadn't changed. Tried to make a request using the generated keys but it had no use.
Is there something I am missing? a way to update the configuration? not using the correct keys? change the keys' format? add additional fields to my curl command?

Thank you for your help
