### ISSUE TITLE
Setup tunnel for host failed

### ISSUE THREAD

**Issue by qianlifu12345** [rancher/rke#184]
**RKE version:**
rke version v0.0.8-dev

**Docker version: (`docker version`,`docker info` preferred)**
```
root@rke1:~# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aliyun
**cluster.yml file:**
```

---
auth:
  strategy: x509
  options:
    foo: bar

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS, use the network plugin config option:
# 'calico_cloud_provider: aws'
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

ssh_key_path: /root/.ssh
ignore_docker_version: false
# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization
authorization:
  mode: rbac
  options:

nodes:
  - address: 172.18.168.29
    user: root
    role: [controlplane, etcd]
    ssh_key_path: /root/.ssh
  - address: 172.18.168.30
    user: root
    role: [worker]
    ssh_key_path: /root/.ssh
  - address: 172.18.168.31
    user: root
    role: [worker]
    ssh_key_path: /root/.ssh

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2


system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: registry.cn-hangzhou.aliyuncs.com/google_containers/cluster-proportional-autoscaler-amd64:1.0.0

# all addon manifests MUST specify a namespace
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-nginx
      namespace: default
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80

```
**Steps to Reproduce:**
`rke up --config config.yml`
**Results:**
```

root@rke1:~# rke up --config config.yml
INFO[0000] Building Kubernetes cluster
INFO[0000] [ssh] Setup tunnel for host [172.18.168.29]
panic: runtime error: invalid memory address or nil pointer dereference
---
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xefb683]

goroutine 18 [running]:
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.publicKeyCallback.auth(0xc420171320, 0xc4201715a0, 0x20, 0x20, 0xc4202d0810, 0x4, 0x18688a0, 0xc420410160, 0x1859f60, 0xc4200195f0, ...)
	/go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client_auth.go:193 +0xb3
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc42025a300, 0xc4200743c0, 0x0, 0xa)
	/go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client_auth.go:36 +0x369
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc42025a300, 0xc4202d1fc0, 0x10, 0xc4200743c0, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:112 +0x2e6
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.NewClientConn(0x18752c0, 0xc42000c1e8, 0xc4202d1fc0, 0x10, 0xc420074300, 0x18752c0, 0xc42000c1e8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:82 +0xfa
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.Dial(0x118400c, 0x3, 0xc4202d1fc0, 0x10, 0xc420074300, 0x0, 0x0, 0x1000000000000)
	/go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:176 +0xb3
github.com/rancher/rke/hosts.(*dialer).Dial(0xc4201711e0, 0x118400c, 0x3, 0xc4201712e0, 0x17, 0x40fe5c, 0x18fab00, 0xc4204eca58, 0x0)
	/go/src/github.com/rancher/rke/hosts/dialer.go:39 +0x1b2
github.com/rancher/rke/hosts.(*dialer).Dial-fm(0x118400c, 0x3, 0xc4201712e0, 0x17, 0xc4204eca58, 0x18fab00, 0xc4204eca60, 0x6dc70d)
	/go/src/github.com/rancher/rke/hosts/dialer.go:66 +0x52
net/http.(*Transport).dial(0xc42038a2d0, 0x1871860, 0xc4200125e0, 0x118400c, 0x3, 0xc4201712e0, 0x17, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:852 +0x7b
net/http.(*Transport).dialConn(0xc42038a2d0, 0x1871860, 0xc4200125e0, 0x0, 0x11845fb, 0x4, 0xc4201712e0, 0x17, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1008 +0x1c4c
net/http.(*Transport).getConn.func4(0xc42038a2d0, 0x1871860, 0xc4200125e0, 0xc42043a630, 0xc420361da0)
	/usr/local/go/src/net/http/transport.go:908 +0x78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:910 +0x3a3
```
