### ISSUE TITLE
[kind/question]rke don't support secondary scheduler?

### ISSUE THREAD

**Issue by pan87232494** [rancher/rke#1858]
rke 0.3.2, tried add secondary scheduler, but the pods with second scheduler  is always in pendding status.
follow [the guide in offical kubernetes page] (https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/)
rke website give none document how to apply multiple scheudler, I guess this is no supported?

[lab@k8s-demo-slave1 kubernetes]$ kubectl get pods 
NAME                                 READY   STATUS    RESTARTS   AGE
annotation-second-scheduler          0/1     Pending   0          16h

**Comment by pan87232494** [comment]
```yml
#my-scheduler-pod.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: my-scheduler
      containers:
      - command:
        - /usr/local/bin/kube-scheduler
        - --address=0.0.0.0
        - --leader-elect=false
        - --scheduler-name=my-scheduler
        image: gcr.io/my-gcp-project/my-kube-scheduler:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10251
          initialDelaySeconds: 15
        name: kube-second-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10251
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
```
