### ISSUE TITLE
Problem deploying CoreDNS when upgrading from k8s 1.13.5 to 1.16.3

### ISSUE THREAD

**Issue by switchboardOp** [rancher/rke#1880]
**RKE version:**
```
INFO[0000] Running RKE version: v1.0.0
```
**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="RancherOS"
VERSION=v1.5.4
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.4
PRETTY_NAME="RancherOS v1.5.4"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```
```
4.14.138-rancher
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AHV
**cluster.yml file:**
```
cluster_name: rancher
ssh_agent_auth: true
ssh_key_path: ~/path/to/key
kubernetes_version: v1.16.3-rancher1-1

nodes:
  - address: xxx.xxx.xxx.xxx
    user: rancher
    role: [controlplane,worker,etcd]
  - address: xxx.xxx.xxx.xxx
    user: rancher
    role: [controlplane,worker,etcd]
  - address: xxx.xxx.xxx.xxx
    user: rancher
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    retention: 24h
    creation: 6h
  kube-api:
    service_cluster_ip_range: 10.6.32.0/20
    pod_security_policy: true
  kube-controller:
    cluster_cidr: 10.6.0.0/19
    service_cluster_ip_range: 10.6.32.0/20
  kubelet:
    fail_swap_on: true
    cluster_dns_server: 10.6.32.10
  authorization:
    mode: rbac
```
**Steps to Reproduce:**
- `rke up` cluster with `kubernetes_version: v1.13.5-rancher1-2`
- Change to `kubernetes_version: v1.16.3-rancher1-1` and run `rke up`

**Results:**
```
INFO[0038] [dns] removing DNS provider kube-dns         
WARN[0103] Failed to deploy DNS addon execute job for provider coredns: Failed to get job complete status for job rke-kube-dns-addon-delete-job in namespace kube-system 
```

Failed job pods had error message about not finding Deployments matching `extentions/v1beta1` or `apps/v1beta1`

I inspected the job and kube-dns manifests. With the upgrade to 1.16 the `kube-dns` and `kube-dns-autoscaler` deployments had `apiVersion: apps/v1`.

I edited the `rke-kube-dns-addon` configmap in the `kube-system` namespace, changing apiVersion to `apps/v1` for both deployments and ran `rke up` again. This workaround seemed to solve the problem. There were no errors and after kube-dns was deleted, CoreDNS deployed without issue.

I suspect this is related to the [deprecation](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals) of these apiVersions in k8s v1.16.0
