### ISSUE TITLE
RKE always uses last node's IP as the 'server' in the kubeconfig.

### ISSUE THREAD

**Issue by Ripolak** [rancher/rke#1882]
Hi there, so I tried using RKE to deploy an HA cluster with 5 nodes, currently all are cp, etcd and workers but I'll separate them in the future. My yaml file looks roughly like this:

```yaml
nodes:
    - address: 1.2.3.4
      user: root
      role:
        - controlplane
        - etcd
        - worker
    - address: 1.2.3.5
      user: root
      role:
        - controlplane
        - etcd
        - worker
    - address: 1.2.3.6
      user: root
      role:
        - controlplane
        - etcd
        - worker
    - address: 1.2.3.7
      user: root
      role:
        - controlplane
        - etcd
        - worker
    - address: 1.2.3.8
      user: root
      role:
        - controlplane
        - etcd
        - worker
```

Once I run `rke up`, the setup succeeds, however I notice that if I check the resulted kubeconfig file, the `server` key has the IP address of the last node, aka 1.2.3.8 in this case. That means that should this node go down, the entire cluster goes down with it since, or at least I am unable to update or create new objects in it. 

I was able to surpass this by using a virtual IP address on the last node, and configured it to move between the nodes should it go down, and now I am indeed able to power off the last node without killing the cluster, but I have a feeling that this is not the ideal solution.

Are there any guidelines about how to go about this issue?
Thanks ahead!
