### ISSUE TITLE
"audit log policy found in cluster.yml" seen when its not configured

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1903]
**RKE version:**
v1.0.0

**Steps to Reproduce:**
`rke up` with minimal `cluster.yml`:

```
nodes:
- address: x
  internal_address: x
  user: ubuntu
  role: [etcd, controlplane, worker]
```

**Results:**
Log seen 
```
time="2020-02-05T12:37:41+01:00" level=debug msg="audit log policy found in cluster.yml"
```
