### ISSUE TITLE
etcd snapshot-restore failed by " Error: snapshot missing hash but --skip-hash-check=false"

### ISSUE THREAD

**Issue by fisherwei** [rancher/rke#1914]
**RKE version:**

`1.0.0 and 1.0.4`

**Docker version: (`docker version`,`docker info` preferred)**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="RancherOS"
VERSION=v1.5.5
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.5
PRETTY_NAME="RancherOS v1.5.5"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

`vmware esxi`

**cluster.yml file:**
```
nodes:
  -
    address: 192.168.66.201
    user: rancher
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: id_rsa
    port: 22
    hostname_override: IDC1SK201
    labels:
      app: ingress
ignore_docker_version: true
network:
  plugin: calico
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 720h
  kubelet:
    image: ""
    extra_args:
      volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    extra_binds:
      - '/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins'
      - "/var/lib/kubelet/plugins:/var/lib/kubelet/plugins"
      - "/var/lib/kubelet/plugins_registry:/var/lib/kubelet/plugins_registry"
      - "/var/lib/kubelet/pods:/var/lib/kubelet/pods:shared,z"
ingress:
  provider: nginx
  node_selector:
    app: ingress
```

**Steps to Reproduce:**

```
./rke remove --config  ./cluster-restore.yml
./rke etcd snapshot-restore --name 2020-02-15T03:29:26Z_etcd --config ./cluster-restore.yml
```

**Results:**
rke 1.0.0
```
FATA[0020] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 128, container logs: Error: snapshot missing hash but --skip-hash-check=false 
```

rke 1.0.4
```
FATA[0019] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 1, container logs: {"level":"info","ts":1581993488.0529532,"caller":"snapshot/v3_snapshot.go:287","msg":"restoring snapshot","path":"/opt/rke/etcd-snapshots/2020-02-15T03:29:26Z_etcd","wal-dir":"/opt/rke/etcd-snapshots-restore/member/wal","data-dir":"/opt/rke/etcd-snapshots-restore/","snap-dir":"/opt/rke/etcd-snapshots-restore/member/snap"}
Error: snapshot missing hash but --skip-hash-check=false 
```
