### ISSUE TITLE
[PSP] Service account isn't authorized after enabled PSP on local cluster

### ISSUE THREAD

**Issue by nickngch** [rancher/rke#1924]
**RKE version:**
v1.0.4

**Docker version: (`docker version`,`docker info` preferred)**
19.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```
nodes:
  - address: 1.1.1.1
    internal_address: 2.2.2.2
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: 3.3.3.3
    internal_address: 4.4.4.4
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: 5.5.5.5
    internal_address: 6.6.6.6
    user: ubuntu
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
  kube-api:
     pod_security_policy: true
```
**Steps to Reproduce:**
1. Enable PSP on local cluster
2. Enable Project Monitoring or create a Workload on Default Project 

**Results:**
The Pod cannot create
"Pod x is forbidden: unable to validate against any pod security policy"

***Workaround:***
Authorized all authenticated users
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:default-psp
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - default-psp # the psp we are giving access to
  verbs:
  - use
---
# This applies psp/restricted to all authenticated users
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:default-psp
subjects:
- kind: Group
  name: system:authenticated # All authenticated users
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: psp:default-psp # A references to the role above
  apiGroup: rbac.authorization.k8s.io
```
