### ISSUE TITLE
When a control node is powered off, the worker nodes are upgraded in smaller batches

### ISSUE THREAD

**Issue by soumyalj** [rancher/rke#1934]
Version: rke version v1.1.0-rc8

Steps to Reproduce:

1. Create a RKE Cluster(with k8s 1.16.7) with 3 control planes, 1 etcd node and 4 worker nodes(NW1 to NW5)
2. Power OFF one controlnode NW2
3. Upgrade to a new K8s version v1.17.3-rancher1-1 using the below upgrade strategy
```
upgrade_strategy:
  max_unavailable_worker: 3
  max_unavailable_controlplane: 2
  drain: true
  node_drain_input:
    force: false
    ignore_daemonsets: true
    delete_local_data: false
    grace_period: -1
    timeout: 120
```

Worker nodes are found to get upgraded in batches of two instead of 3 as shown below though we have  max_unavailable_worker: 3 

<img width="644" alt="Screen Shot 2020-02-28 at 5 11 50 PM" src="https://user-images.githubusercontent.com/18536626/75598032-ec337b80-5a4d-11ea-85d5-fadcb51660d3.png">

Also, when the maxUnavailable is reset for control plane, it does not mention that it is reset for 
max_Unavailable_controlplane

Observed RKE logs :

```
INFO[0067] [controlplane] Building up Controller Plane.. 
INFO[0067] [controlplane] Successfully started Controller Plane.. 
INFO[0067] [controlplane] Processing controlplane hosts for upgrade one at a time 
INFO[0067] [controlplane] Parameters provided to drain command: "Force: false, IgnoreAllDaemonSets: true, DeleteLocalData: false, Timeout: 2m0s, GracePeriodSeconds: -1" 
INFO[0067] Resetting maxUnavailable to 1 since 1 host(s) are found to be inactive/unavailable prior to upgrade 

```

Note: When  control node is not powered OFF, the worker nodes get upgraded correctly in batches of 3 for the above configuration.

**Comment by sowmyav27** [comment]
On latest master-head, the following behavior is seen

- Cluster is deployed with 1 etcd, 3 control plane and 2 worker
- maxUnavailable control plane is 1, maxUnavailable_worker = 10% (default)
- Power off one control plane
- edit cluster - change the k8s version to 1.16 from 1.15
- The cluster is stuck in Updating state with error: `2020/02/29 23:06:57 [ERROR] ClusterController c-lf8fc [cluster-provisioner-controller] failed with : [controlPlane] Failed to upgrade Control Plane: cannot proceed with upgrade of controlplane since 1 host(s) are found to be inactive prior to upgrade`
- Only etcd components get upgraded in this case.
- Now, edit cluster, maxUnavailable control plane is 2
- The other two Active control planes - get upgraded. - all the components including control plane and worker plane components.
- ETcd node has not upgraded.
- Error seen: `[workerPlane] Failed to upgrade Worker Plane: cannot proceed with upgrade of worker since 1 host(s) are found to be inactive prior to upgrade; [workerPlane] Failed to upgrade Worker Plane: cannot proceed with upgrade of worker since 1 host(s) are found to be inactive prior to upgrade`

@soumyalj Did you see the etcd node in your case getting upgraded before the worker?

**Comment by mrajashree** [comment]
Available to test with v1.1.0-rc9

**Comment by soumyalj** [comment]
Tested with RKE CLI version v1.1.0-rc9

1. Create a RKE Cluster(with k8s 1.16.7) with 3 control planes, 1 etcd node and 4 worker nodes(NW1 to NW5)
2. Power OFF one controlnode NW2
3. Upgrade to a new K8s version v1.17.3-rancher1-1 using the below upgrade strategy

```
upgrade_strategy:
  max_unavailable_worker: 3
  max_unavailable_controlplane: 2
  drain: true
  node_drain_input:
    force: false
    ignore_daemonsets: true
    delete_local_data: false
    grace_period: -1
    timeout: 120

```
Worker nodes are found to get upgraded in batches of 3  as expected:
<img width="513" alt="Screen Shot 2020-03-02 at 12 07 06 PM" src="https://user-images.githubusercontent.com/18536626/75713262-5df20c00-5c7e-11ea-8055-de02299e3bf8.png">

max_Unavailable_controlplane is reset correctly
```
Resetting max_unavailable_controlplane to 1 since 1 host(s) are found to be inactive prior to upgrade 
```
