### ISSUE TITLE
Setting enable_network_policy:true has no effect

### ISSUE THREAD

**Issue by michael-127** [rancher/rke#1956]
**RKE version:** 
v1.0.4

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Debug Mode: false

Server:
 Containers: 39
  Running: 26
  Paused: 0
  Stopped: 13
 Images: 18
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.21.3.el7.x86_64
 Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.5GiB
 Name: vvm2922
 ID: MK5P:UZGC:TZCT:VPQH:MONP:VZ4D:ATSK:DTRS:XEQ4:WMCC:PJGE:2THK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:[...]
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-957.21.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
virtual machine

**cluster.yml file:**
```
ssh_key_path: ./id_rsa

nodes:
  - address: vvm2922
    port: "22"
    internal_address: ""
    role:
      - controlplane
      - worker
      - etcd
    hostname_override: ""
    user: devopsinstall
    docker_socket: /var/run/docker.sock
    labels: {}

enable_network_policy: true
    
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    snapshot: true
    creation: 6h
    retention: 24h
  kube-api:
    image: ""
    extra_args:
    # Enable audit log to stdout
    #audit-log-path: "-"
    # Increase number of delete workers
    #delete-collection-workers: 3
    # Set the level of log output to debug-level
    #v: 4
    extra_binds: []
    extra_env: []
    # IP range for any services created on Kubernetes
    # This must match the service_cluster_ip_range in kube-controller
    service_cluster_ip_range: 10.33.0.0/16
    # Expose a different port range for NodePort services
    service_node_port_range: 30000-32767
    pod_security_policy: true

  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.32.0.0/16
    service_cluster_ip_range: 10.33.0.0/16

  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []

  kubelet:
    image: ""
    extra_args:
    #      max-pods: 250
    # Optionally define additional volume binds to a service
    extra_binds:
    #      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
    extra_env: []
    # Base domain for the cluster
    cluster_domain: cluster.local
    infra_container_image: ""
    # IP address for the DNS service endpoint
    cluster_dns_server: 10.33.0.10
    # Fail if swap is on
    fail_swap_on: false

  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []

network:
  plugin: canal
  options: {}
  
authentication:
  strategy: x509
  options: {}
  sans: []

kubernetes_version: "v1.17.2-rancher1-2"

system_images:

ssh_agent_auth: false

authorization:
  mode: rbac
  options: {}

ignore_docker_version: true

private_registries:
  - url: [...]
    is_default: true

ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: 
    default-ssl-certificate: "ingress-nginx/ingress-tls"

cluster_name: rancher_cluster

cloud_provider:
  name: ""

prefix_path: ""

bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""

monitoring:
  provider: ""
  options: {}

addon_job_timeout: 120
```

**Steps to Reproduce:**
Following the docs https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#enable-network-policy
and add 

enable_network_policy: true

to your cluster config. Run with

rke up --config cluster.yml

Check if rancher project isolation (network policies) exist for any namespace, for example by

kubectl get netpol --all-namespaces

**Results:**
Expecting an np-default and hn-nodes network policy for each namespace, but none exists.
