### ISSUE TITLE
validate service args (feature request)

### ISSUE THREAD

**Issue by dhrp** [rancher/rke#196]
**RKE version:**

0.0.9-dev

**Docker version: (`docker version`,`docker info` preferred)**

not relevant

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

not relevant

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

any

**cluster.yml file:**

```
nodes:
  - address: <some_ip>
    user: root
    role: [controlplane,worker,etcd]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    extra-args: 
      flex-volume-plugin-dir: "/var/flexbinary/flexvolumes"
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra-args:
      volume-plugin-dir: "/var/flexbinary/flexvolumes"
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
```

**Steps to Reproduce:**

Here is the challenge: *Spot the mistake*. 

Spoiler: extra-args should be spelled as extra_args. 

**Results:**

The arguments are not added. 

It would be cool if invalid arguments would give some warning or fail it somewhere.
