### ISSUE TITLE
Scraping Canal´s metrics with Prometheus

### ISSUE THREAD

**Issue by sevenval-admins** [rancher/rke#2008]
**RKE version:**
RKE version: v0.3.2

**Docker version: (`docker version`,`docker info` preferred)**
```
-bash-4.2$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 72
  Running: 57
  Paused: 0
  Stopped: 15
 Images: 20
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.21.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.701GiB
 Name: mytestvm.local
 ID: USRU:TNXY:TIAS:ZP53:MCI4:4PTE:OH4F:ZKJI:6T3W:P7DB:3UA7:X634
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
-bash-4.2$ uname -r
3.10.0-957.21.3.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox - VMware

**cluster.yml file:**
```
nodes:
  - address: mytestvm.local
    user: rke
    role:
      - controlplane
      - worker
      - etcd
    port: 22
    labels:
      ingress: True
ignore_docker_version: False
ssh_key_path: /my/path/.ssh/id
ssh_agent_auth: false
private_registries:
  - url: my.registry.office.de
cluster_name: rke v1.16.2-rancher1-1
kubernetes_version: v1.16.2-rancher1-1

services:
    etcd:
      snapshot: true
      creation: 6h
      retention: 24h
    kube-api:
      service_cluster_ip_range: 10.13.0.0/16
      service_node_port_range: 30000-32767
      pod_security_policy: false
      extra_args:
        audit-log-path: "-"
        delete-collection-workers: 3
    kube-controller:
      cluster_cidr: 10.12.0.0/16
      service_cluster_ip_range: 10.13.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.13.0.10
      fail_swap_on: true
      extra_args:
        max-pods: 250
      extra_binds:
        - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
authentication:
    strategy: x509
    sans:
      - "my-master.local"
      - "mytestvm.local"
authorization:
    mode: rbac
addon_job_timeout: 80
network:
    plugin: canal
dns:
    provider: coredns
ingress:
    provider: nginx
    options:
      proxy-body-size: "1G"
      proxy-read-timeout: 600
    node_selector:
      ingress: True
```

**Steps to Reproduce:**
Hi and thank you very much in advance to everyone who will pay attention to this issue/feature request.
As [here](https://docs.projectcalico.org/maintenance/monitor-component-metrics) described, in order to be able to scrape Canal metrics with Prometheus, we have to set the Felix Parameter **PrometheusMetricsEnabled** on _true_. 
To do this, we have to set the Felix ENV variable **FELIX_PROMETHEUSMETRICSENABLED** on _true_ (as described [here](https://docs.projectcalico.org/reference/felix/configuration)).
I have tried to set this ENV by editing my Canal Pod:
`kubectl edit pod canal-a1bcd`

```
    - name: FELIX_LOGFILEPATH
      value: none
    - name: FELIX_LOGSEVERITYSYS
    - name: FELIX_LOGSEVERITYSCREEN
      value: Warning
    - name: FELIX_HEALTHENABLED
      value: "true" 
    - name: FELIX_PROMETHEUSMETRICSENABLED
      value: "true"
``` 
**Results:**
When I exit from the editing, I get a failure message:
```
error: pods "canal-a1bcd" is invalid
A copy of your changes has been stored to "/tmp/kubectl-edit-am5bj.yaml" 
error: Edit cancelled, no valid changes were saved.
```
In cluster.yml there is a Canal section, but it seems that is not possible to set extra arguments which could allow the scraping from Prometheus: https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/#canal-network-plug-in-options
Scraping Canal metrics with Prometheus would be a very useful feature, ist there any way to implement it?
