### ISSUE TITLE
rke is failing when running from a CIDR that matches or overlaps the docker bridge network

### ISSUE THREAD

**Issue by stearz** [rancher/rke#2018]
**RKE version:**
v1.0.4

**Docker version: (`docker version`,`docker info` preferred)**
19.03.5

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.138-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```
nodes:
  - address: 172.23.34.250
    internal_address: 172.23.34.250
    user: rancher
    role: [controlplane, worker, etcd]
  - address: 172.23.37.191
    internal_address: 172.23.37.191
    user: rancher
    role: [controlplane, worker, etcd]
  - address: 172.23.42.98
    internal_address: 172.23.42.98
    user: rancher
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
```

**Steps to Reproduce:**
Give the host you are running `rke` on an IP address in the 172.17.0.0/16 network and run `rke up --config ./<your-config>.yml`

**Results:**
rke fails with:
```
Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
```

**Comment by stearz** [comment]
It would be nice, if there was a way to set docker's `bip` in `/etc/docker/daemon.json` with rke like so:

```
{
  "bip": "192.168.1.1/24"
}
```

**Comment by stearz** [comment]
Just found out that it is possible to set the docker bip in RancherOS with a cloud-config like this:

```
#cloud-config
rancher:
  system_docker:
    extra_args: ['--bip=192.168.1.1/24'] 
```

So there is no critical need to enhance `rke`.
