### ISSUE TITLE
v1.0.4 - rke "cluster_name" doesn't change, still 'local'

### ISSUE THREAD

**Issue by ainiml** [rancher/rke#2020]
**RKE version:** 

```
rke version v1.0.4
```

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Debug Mode: false

Server:
 Containers: 37
  Running: 26
  Paused: 0
  Stopped: 11
 Images: 19
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.789GiB
 Name: dream.n7sa.com
 ID: M3N5:4PQC:XZAE:IL4L:BZMF:YFKP:57WB:I3PX:FYXG:GGV4:3QE2:LCVT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: naisanza
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.n7sa.com
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
4.15.0-76-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Dreamhost

**cluster.yml file:**

https://github.com/TheShellLand/antsable/blob/master/playbooks/roles/rancher/templates/k8s_rancher_with_no_external_tls.yaml:
```
---
# By default, the name of your cluster will be local
# Set different Cluster name
cluster_name: {{ LOCAL_CLUSTER_NAME }}

nodes:
  - address: {{ NODE_PUBLIC_ADDRESS }}
    internal_address: {{ NODE_INTERNAL_ADDRESS }}
    user: {{ NODE_USER }}
    role: [{{ node_role }}]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_agent_auth: true
```

**Steps to Reproduce:**
https://github.com/TheShellLand/antsable/blob/master/playbooks/rancher.yml
1. `cluster_name: dream`
2. `./ansible.sh playbooks/rancher.yml -l dream`

**Results:**
![image](https://user-images.githubusercontent.com/28725423/79091065-d5a16500-7d19-11ea-8ed2-054bf3da4df9.png)

related: https://github.com/rancher/rancher/issues/26610
