### ISSUE TITLE
Does kube-proxy not deploy in provisioned K8 cluster? 

### ISSUE THREAD

**Issue by MayankTahil** [rancher/rke#203]
**RKE version:** `rke version v0.0.9-dev`

**Docker version: (`docker version`,`docker info` preferred)** `Docker version 1.12.6, build 78d1802`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="RancherOS"
VERSION=v1.1.2
ID=rancheros
ID_LIKE=
VERSION_ID=v1.1.2
```
running 

```
4.9.69-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-Metal

**cluster.yml file:**

```yaml
---
auth:
  strategy: x509
  options:
    foo: bar

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS, use the network plugin config option:
# 'calico_cloud_provider: aws'
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

ssh_key_path: ./mgmt.key
ignore_docker_version: false
# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization
authorization:
  mode: rbac
  options:

nodes:
  - address: 192.168.10.119
    user: rancher
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0
```

**Steps to Reproduce:**

```
./rke_linux-amd64 up --config cluster-ros.yaml
```

**Results:**

no kube-proxy deployed when I check via kubectl :

```
bash-4.3# kubectl get pods --all-namespaces

NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-778977457c-vr27l              3/3       Running   0          7m
kube-system   kube-dns-autoscaler-5cb4f55974-2m8m6   1/1       Running   0          7m
kube-system   kube-flannel-kbnx4                     2/2       Running   0          7m
```

I am a bit confused, how is internal cluster load balancing being done in these deployments? I was expecting a kube-proxy container running to handle E-W load balancing. I know this is a single host but I have also tried the same set up with 3 hosts with same results. I feel like I'm missing something simple here.
