### ISSUE TITLE
Adding nodes & updating cluster fails

### ISSUE THREAD

**Issue by ColonelBundy** [rancher/rke#2035]
**RKE version:**
1.1.0

**Docker version: (`docker version`,`docker info` preferred)**
18.09.7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**cluster.yml file:**
```
nodes:
- address: 192.168.6.192
  port: 22
  role:
  - controlplane
  - worker
  - etcd
  user: xxx
  ssh_key_path: ./xxx.ppk
- address: 192.168.6.88
  port: 22
  role:
  - controlplane
  - worker
  - etcd
  user: xxx
  ssh_key_path: ./xxx.ppk
- address: 192.168.6.86
  port: 22
  role:
  - controlplane
  - worker
  - etcd
  user: xxx
  ssh_key_path: ./xxx.ppk

kubernetes_version: "v1.15.4-rancher1-1"
  
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```
**Steps to Reproduce:**
Create cluster with 1 node with an address set and an internal_address set, add two more nodes and remove internal_address of first node and update address with a new ip.

**Results:**
Error message from rke up
```
Failed to reconcile etcd plane: Etcd plane nodes are replaced. Stopping provisioning. Please restore your cluster from backup.
```
