### ISSUE TITLE
Please add an option to give additionalTrustedCAs to cluster.yaml

### ISSUE THREAD

**Issue by Boeller666** [rancher/rke#2038]
**RKE version: 1.1.0**

**Docker version: (`docker version`,`docker info` preferred)**
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-1062.9.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere/ESXi

**cluster.yml file:**
```yml
nodes:
  - address: 192.168.218.86
    user: rke
    role: [controlplane, etcd]
  - address: 192.168.218.87
    user: rke
    role: [controlplane, etcd]
  - address: 192.168.218.88
    user: rke
    role: [controlplane, etcd]
  - address: 192.168.218.89
    user: rke
    role: [worker]
  - address: 192.168.218.90
    user: rke
    role: [worker]
  - address: 192.168.218.91
    user: rke
    role: [worker]
  - address: 192.168.218.92
    user: rke
    role: [worker]
  - address: 192.168.218.93
    user: rke
    role: [worker]
  - address: 192.168.218.94
    user: rke
    role: [worker]
cluster_name: rancher
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
  kubelet:
    extra_binds:
      - /var/openebs/local:/var/openebs/local
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
```

**Steps to Reproduce:**
Try using a private registry with a SSL certificate from a self-signed Root CA for a deployment.

**Results:**
Message:  
Failed to pull image "my-registry.company.com/group/image:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://my-registry.company.com/v2/: x509: certificate signed by unknown authority

---

The only documentation found describes creating CSRs. But we only need to pass a root CA as trusted to Kubernetes.
