### ISSUE TITLE
ingress options cause error converting YAML to JSON

### ISSUE THREAD

**Issue by lwj5** [rancher/rke#2047]
**RKE version:**
1.1.1

**Docker version: (`docker version`,`docker info` preferred)**
CE 19.03.5

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

> NAME="CentOS Linux"
> VERSION="7 (Core)"
> 3.10.0-957.21.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```
ingress:
  options:
    compute-full-forwarded-for: true
    log-format-upstream: $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $http_x_forwarded_for $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id
    use-forwarded-headers: true
    use-proxy-protocol: true
```

**Steps to Reproduce:**
Add this line to ingress options
`log-format-upstream: $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $http_x_forwarded_for $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id`

causes

> INFO[0062] [addons] Executing deploy job rke-ingress-controller 
> WARN[0097] Failed to deploy addon execute job [rke-ingress-controller]: Failed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system 
> INFO[0097] [addons] Setting up user addons              
> INFO[0097] [addons] no user addons defined              
> INFO[0097] Finished building Kubernetes cluster successfully

Pod log
> namespace/ingress-nginx unchanged
> error: error parsing /etc/config/rke-ingress-controller.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key

**Results:**
Remove and it works, adding single quotes does nothing to resolve it.

gz#11537
