### ISSUE TITLE
Remove unneeded advertised port 4001 for etcd

### ISSUE THREAD

**Issue by dgiebert** [rancher/rke#2123]
**RKE version:**
v1.1.2

**Docker version: (`docker version`,`docker info` preferred)**
19.03.5

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.138-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
Snippet:
```
services:
    etcd:
      backup_config:
        interval_hours: 12
        retention: 6
        s3backupconfig:
          access_key: ""
          secret_key: ""
          bucket_name: ""
          region: ""
          folder: ""
          endpoint: ""
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 1001
      uid: 1001
```

**Results:**
docker inspect etcd:
```
                "/usr/local/bin/etcd",
                "--heartbeat-interval=500",
                "--initial-cluster-token=etcd-cluster-1",
                "--initial-cluster=etcd-master-1=https://10.44.0.1:2380,etcd-master-2=https://10.44.0.2:2380,etcd-master-3=https://10.44.0.3:2380",
                "--enable-v2=true",
                "--election-timeout=5000",
                "--peer-key-file=/etc/kubernetes/ssl/kube-etcd-10-44-0-3-key.pem",
                "--data-dir=/var/lib/rancher/etcd/",
                "--listen-client-urls=https://10.44.0.3:2379",
                "--trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
                "--peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
                "--peer-client-cert-auth=true",
                "--advertise-client-urls=https://10.44.0.3:2379,https://10.44.0.3:4001",
                "--key-file=/etc/kubernetes/ssl/kube-etcd-10-44-0-3-key.pem",
                "--peer-cert-file=/etc/kubernetes/ssl/kube-etcd-10-44-0-3.pem",
                "--client-cert-auth=true",
                "--cert-file=/etc/kubernetes/ssl/kube-etcd-10-44-0-3.pem",
                "--name=etcd-master-3",
                "--initial-advertise-peer-urls=https://10.44.0.3:2380",
                "--listen-peer-urls=https://10.44.0.3:2380",
                "--initial-cluster-state=new"
```

etcdctl list members:
```
6a8cc11a90803a5c, started, etcd-master-2, https://10.44.0.2:2380, https://10.44.0.2:2379,https://10.44.0.2:4001, false
bd66d95876b0dae8, started, etcd-master-3, https://10.44.0.3:2380, https://10.44.0.3:2379,https://10.44.0.3:4001, false
be8d96ff474a4b0f, started, etcd-master-1, https://10.44.0.1:2380, https://10.44.0.1:2379,https://10.44.0.1:4001, false
```

1. Netstat does not show port 4001 to be active
2. Curl on https://10.44.0.1:4001 fails
3. etcd commands throws a warning e.g. `etcdctl defrag --cluster` 
```
{"level":"warn","ts":"2020-06-16T09:33:15.996Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://10.44.0.1:4001","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.44.0.1:4001: connect: connection refused\""}
Failed to defragment etcd member[https://10.44.0.1:4001] (context deadline exceeded)
```
**Question:**
Where does this port come from or is this an error / misconfiguration  ?
