### ISSUE TITLE
RKE version command does not respect bastion config

### ISSUE THREAD

**Issue by yaron** [rancher/rke#2133]
**RKE version:**
1.1.2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
WSL
**cluster.yml file:**
```
ssh_agent_auth: true

nodes:
  - address: 172.1.15.2
    user: core
    role: [controlplane, etcd]
  - address: 172.1.15.4
    user: core
    role: [controlplane, etcd, worker]
  - address: 172.1.15.5
    user: core
    role: [controlplane, etcd, worker]
bastion_host:
  address: 81.201.23.12
  user: core
  port: 22
```
**Steps to Reproduce:**
Create a cluster with a bastion_host and run `rke version`.
**Results:**
```
INFO[0000] Running RKE version: v1.1.2
FATA[0021] Failed to get Kubernetes server version: Get https://172.1.15.5:6443/version?timeout=30s: dial tcp 172.1.15.5:6443: connect: connection refused 
```
