### ISSUE TITLE
Ingress-nginx 0.25.1-rancher1 couldn't startup properly with k8s v1.17

### ISSUE THREAD

**Issue by nickngch** [rancher/rke#2135]
**RKE version:**
1.1.12

**Docker version: (`docker version`,`docker info` preferred)**
```
client:
 Debug Mode: false

Server:
 Containers: 18
  Running: 6
  Paused: 0
  Stopped: 12
 Images: 15
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1051-aws
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.66GiB
 Name: ip-172-31-27-212
 ID: HYOR:GIYS:BT7J:WNM4:7MUD:3LVF:POBK:5JJC:GLOO:H6GA:E6B3:545M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
```
nodes:
  - address: x.x.x.x
    internal_address: 172.31.27.212
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: y.y.y.y
    internal_address: 172.31.25.30
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: z.z.z.z
    internal_address: 172.31.27.112
    user: ubuntu
    role: [controlplane,worker,etcd]
services:
  etcd:
    backup_config:
      interval_hours: 3
      retention: 12
system_images:
  ingress: rancher/nginx-ingress-controller:nginx-0.25.1-rancher1
```
**Steps to Reproduce:**
1. Specified the Nginx-ingress version under `system_images`
2. run `rke up --config cluster.yml` with rke 1.1.12 (default k8s version)

**Results:**
`nginx-ingress-controller`pod stuck in CrashLoopBackOff

Edit the ds  `kubectl get ds -n ingress-nginx -o yaml` and change `runAsUser` from 101 to 33 will fix the issue.

gz#10686
