### ISSUE TITLE
Expose kubelet, kube-scheduler, kube-controller-manager and etcd

### ISSUE THREAD

**Issue by jetersen** [rancher/rke#2142]
Consider exposing kubelet, kube-scheduler, kube-controller-manager and etcd, currently they are standalone containers instead of static pods.

Currently there is no visibility into the state from prometheus, when using prometheus-operator.

These default rules do not work:
KubeSchedulerDown, KubeControllerManagerDown, TargetDown (cannot see kubelet)

Using the prometheus-operator chart I curruntly have these values to workaround noisy alerts:
```yaml
defaultRules:
  rules:
# RKE, cluster in docker is still experimental 😭
    kubeScheduler: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
# End RKE 😭
```

Related to https://github.com/rancher/rancher/issues/21173
