### ISSUE TITLE
rke-ingress-controller-deploy-job fails with The Service "default-http-backend" is invalid

### ISSUE THREAD

**Issue by stefanfritsch** [rancher/rke#2146]
Hi,

when upgrading an rke-cli created cluster from 1.16.9 to 1.16.10 with rke 1.1.3 the `rke-ingress-controller-deploy-job` fails with

```
The Service "default-http-backend" is invalid:
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```
(full pod-log below).

The same applies to the rke-metrics-addon-deploy-job so I didn't open a separate issue:

```
The Service "metrics-server" is invalid:
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```

Thank you!

**RKE version:** v1.1.3

**Docker version: (`docker version`,`docker info` preferred)** 
```
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 18.04.4 LTS, 5.3.0-51-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

bare-metal

**cluster.yml file:**

```
nodes:
    - address: node0
      role: [controlplane,worker,etcd]
    - address: node1
      role: [controlplane,worker,etcd]
    - address: node2
      role: [controlplane,worker,etcd]

# Enable use of SSH agent to use SSH private keys with passphrase
# This requires the environment  configured pointing 
# to your SSH agent which has the private key added
ssh_agent_auth: true

cluster_name: mycluster

# Supported versions are on the releases page of rke
# https://github.com/rancher/rke/releases
kubernetes_version: v1.16.10-rancher2-2

network:
    plugin: weave

services:
  ##############################################################################
  ## kubelet
  ##############################################################################
  kubelet:
    ## Base domain for the cluster
    cluster_domain: something.local
    ## IP address for the DNS service endpoint
    cluster_dns_server: 10.10.10.10
    extra_args:
      volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    extra_binds:
      - /usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec  
  ##############################################################################
  ## kube-api
  ##############################################################################
  kube-api:
    ## IP range for any services created on Kubernetes
    ## This must match the service_cluster_ip_range in kube-controller
    service_cluster_ip_range: 10.10.0.0/16
    secrets_encryption_config:
      enabled: true
    pod_security_policy: true
  ##############################################################################
  ## kube-controller
  ##############################################################################
  kube-controller:
    ## IP range for any services created on Kubernetes
    ## This must match the service_cluster_ip_range in kube-api
    service_cluster_ip_range: 10.10.0.0/16
  ##############################################################################
  ## etcd
  ##############################################################################
  etcd:
    snapshot: true
    creation: 24h
    retention: 240h
```

**Steps to Reproduce:**

Upgrade the cluster from 1.16.9 to 1.16.10 with

```
./rke_linux-amd64 up
```

**Results:**

rke shows
```
WARN[0510] Failed to deploy addon execute job [rke-ingress-controller]: Failed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system
```

The logs of the rke-ingress-controller-deploy-job pods show:

```
namespace/ingress-nginx unchanged
configmap/nginx-configuration configured
configmap/tcp-services unchanged
configmap/udp-services unchanged
serviceaccount/nginx-ingress-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/nginx-ingress-clusterrole unchanged
role.rbac.authorization.k8s.io/nginx-ingress-role unchanged
rolebinding.rbac.authorization.k8s.io/nginx-ingress-role-nisa-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-clusterrole-nisa-binding unchanged
daemonset.apps/nginx-ingress-controller unchanged
deployment.apps/default-http-backend unchanged
The Service "default-http-backend" is invalid:
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```
