### ISSUE TITLE
Unable to determine if ./path/deployment.yaml is a file path or url, skipping 

### ISSUE THREAD

**Issue by steve-todorov** [rancher/rke#2151]
**RKE version:** 

v1.1.3

**Docker version: (`docker version`,`docker info` preferred)**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

`5.4.0-40-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

```
--- cluster.yaml
addons_include:
  - ./relative/path/to/default/loadbalancer-testing/20-deployment.yaml

--- ./relative/path/to/default/loadbalancer-testing/20-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Steps to Reproduce:**

Create a simple `cluster.yaml` and add an `addons_include` record pointing to a path relative to `cluster.yaml`.

**Results:**

```
WARN[0020] [addons] Unable to determine if ./relative/path/to/default/loadbalancer-testing/20-deployment.yaml is a file path or url, skipping 
```
