### ISSUE TITLE
Adding "extra_args:   cloud-provider: aws" fails kube controller deploy

### ISSUE THREAD

**Issue by nseyvet** [rancher/rke#216]
**RKE version:**
0.0.9-dev

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 16
 Running: 15
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1041-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-50-0-30-244
ID: PTSQ:YNOH:HXSG:E7BC:W5ZH:ZANT:CLN2:3FB6:PFLV:LBV2:MD42:3M4C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1041-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
```
---
authentication:
  strategy: x509
  options: {}

authorization:
  mode: none
  options: {}

# supported plugins are:
# flannel
# calico
# canal
network:
  plugin: flannel
  options:

nodes:
  - machine_name: ec2-34-242-164-192.eu-west-1.compute.amazonaws.com
    address: 50.0.30.74
    user: ubuntu
    role: [etcd,controlplane,worker]
    flannel_iface: eth0 
  - machine_name: ec2-54-171-118-159.eu-west-1.compute.amazonaws.com
    address: 50.0.30.71
    user: ubuntu
    role: [etcd,controlplane,worker]
    flannel_iface: eth0 
  - machine_name: ec2-54-194-94-59.eu-west-1.compute.amazonaws.com
    address: 50.0.30.244
    user: ubuntu
    role: [etcd,controlplane,worker]
    flannel_iface: eth0 
  - machine_name: ec2-54-154-209-13.eu-west-1.compute.amazonaws.com
    address: 50.0.30.98
    user: ubuntu
    role: [etcd,worker]
    flannel_iface: eth0 
  - machine_name: ec2-54-171-249-164.eu-west-1.compute.amazonaws.com
    address: 50.0.30.234
    user: ubuntu
    role: [etcd,worker]
    flannel_iface: eth0 

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.5-rancher1
    service_cluster_ip_range: 10.233.0.0/18
  kube-controller:
    image: rancher/k8s:v1.8.5-rancher1
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.5-rancher1
  kubelet:
    image: rancher/k8s:v1.8.5-rancher1
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args:
      fail-swap-on: FALSE
 #     cgroup-driver: systemd
  kubeproxy:
    image: rancher/k8s:v1.8.5-rancher1

# Ensure key is available
ssh_key_path: /home/nseyvet/.ssh/omega-common.pem
```
**Steps to Reproduce:**
We are trying RKE on AWS, and using dynamic volume provisioning,

Storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:  
  name: ebs-default-sc
  annotations:
      storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zones: eu-west-1
  iopsPerGB: "50"
```
Claim:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-claim
  namespace: default
spec:
  accessModes:     
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ebs-default-sc
```

The PVC remains "Pending" and I can see the following error:

```
ebs$ kubectl describe pvc ebs-claim
Name:          ebs-claim
Namespace:     default
StorageClass:  ebs-default-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"ebs-claim","namespace":"default"},"spec":{"accessModes":["ReadWr...
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  8s (x10 over 2m)  persistentvolume-controller  no volume plugin matched

```
Typically, this indicates that the kubernetes controller manager needs to be started with --cloud-provider=aws.

Question is, can the extra_args be used to add this such as: 

```
kube-controller:
   ...
  extra_args:
      cloud-provider: aws

```
?

**Results:**
