### ISSUE TITLE
can't resolve a domain end with '.cloud' in Pod's container

### ISSUE THREAD

**Issue by shellwalker** [rancher/rke#2162]
**RKE version:**
➜  ~ rke -version
rke version v1.1.3

**Docker version: (`docker version`,`docker info` preferred)**
➜  ~ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
➜  ~ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

➜  ~ uname -r
3.10.0-1127.8.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM ( Proxmox VE）

**cluster.yml file:**
➜  rke git:(master) ✗ cat cluster.yml
```
nodes:
- address: 192.168.10.121
  port: "22"
  role:
  - controlplane
  - etcd
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx
- address: 192.168.10.122
  port: "22"
  role:
  - controlplane
  - etcd
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx
- address: 192.168.10.123
  port: "22"
  role:
  - controlplane
  - etcd
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx
- address: 192.168.10.124
  port: "22"
  role:
  - worker
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx
- address: 192.168.10.125
  port: "22"
  role:
  - worker
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx
- address: 192.168.10.126
  port: "22"
  role:
  - worker
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx
- address: 192.168.10.127
  port: "22"
  role:
  - worker
  user: rancher
  labels:
    kube-dns: coredns
    kube-ingress: nginx

cluster_name: kubernetes

ignore_docker_version: true

kubernetes_version: "v1.18.3-rancher2-2"

ssh_key_path: /root/.ssh/id_rsa

# ssh_agent_auth: true

# addon_job_timeout: 30

# prefix_path:

private_registries:
  - url: registry.teset.cloud
    user: *
    password: *
    is_default: true

# bastion_host:

# system_images:

services:

  kube-api:
    audit_log:
      enabled: true

  etcd:
    snapshot: true
    backup_config:
      enabled: true
      interval_hours: 3
      retention: 24

  # kube-api:

  # kube-controller:

  kubelet:
    fail_swap_on: false
    extra_args:
      sync-frequency: "3s"
      serialize-image-pulls: "false"
      system-reserved: "cpu=0.25,memory=1024Mi"
      kube-reserved: "cpu=0.5,memory=2048Mi"
    extra_binds:
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
      - "/etc/iscsi:/etc/iscsi"
      - "/sbin/iscsiadm:/sbin/iscsiadm"
      - "/lib/modules:/lib/modules"

  kubeproxy:
    extra_args:
      proxy-mode: "ipvs"

  # scheduler:

# authentication:

authorization:
  mode: rbac

# cloud_provider:

network:
  plugin: calico

ingress:
  provider: nginx
  node_selector:
    kube-ingress: nginx
  options:
    enable-underscores-in-headers: "true"

dns:
  provider: coredns
  upstreamnameservers:
  - 192.168.10.100
  node_selector:
    kube-dns: coredns
```

**Steps to Reproduce:**
1. Setup a private DNS server (192.168.10.100)
2. config host/node's /etc/resolv.conf
```
➜  rke git:(master) ✗ cat /etc/resolv.conf
; Created by cloud-init on instance boot automatically, do not edit.
;
# Generated by NetworkManager
nameserver 192.168.10.100
nameserver 192.168.10.1
search host
```
```
➜  rke git:(master) ✗ nslookup test.com
Server:		192.168.10.100
Address:	192.168.10.100#53
Name:	test.com
Address: 192.168.10.100
➜  rke git:(master) ✗ nslookup test.cloud
Server:		192.168.10.100
Address:	192.168.10.100#53
Name:	test.cloud
Address: 192.168.10.100
```
3. deploy a spring boot container
4. exec command in the container
```
➜  ~ docker ps |grep backend
27f4feb8d52f        registry.test.cloud/test/backend-verify                "/bin/sh -c 'java $J…"   7 days ago          Up 7 days                               k8s_backend-verify_backend-verify-cdd9c75dc-zrz6x_sample_6eda2b8f-cb8b-467d-b0f6-f7d41cba5eb6_0
c94b5ab055b0        registry.test.cloud/rancher/pause:3.1                    "/pause"                 7 days ago          Up 7 days                               k8s_POD_backend-verify-cdd9c75dc-zrz6x_sample_6eda2b8f-cb8b-467d-b0f6-f7d41cba5eb6_0
➜  ~ docker exec -it 27f4feb8d52f nslookup test.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      test.com
Address 1: 192.168.10.100
➜  ~ docker exec -it 27f4feb8d52f nslookup test.cloud
nslookup: can't resolve '(null)': Name does not resolve

Name:      test.cloud
Address 1: 69.172.201.153
```

**Results:**
The result of `nslookup` is different between host and pod's container.
Can't get the right IP address of the domain end with `.cloud`.
