### ISSUE TITLE
Error from server (ServiceUnavailable): the server is currently unable to handle the request

### ISSUE THREAD

**Issue by vinothkumar1590** [rancher/rke#2181]
**RKE version:**
Server Version: version.Info{Major:"1", Minor:"14"

**Docker version: (`docker version`,`docker info` preferred)** 
Version:           18.09.2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
  VM-VMware
**cluster.yml file:**

```
nodes:
- address: 10.xx.xx.xx# NOTE - this is the master node for the rebuilt cluster, where all the configs are
  role:
  - controlplane
  - etcd
  hostname_override: "xxx"
  user: root
- address: 10.xx.xx,xx
  role:
  - controlplane
  - etcd
  hostname_override: "xxx"
  user: root
- address: 10.xx.xx.xx
  role:
  - controlplane
  - etcd
  hostname_override: "xxx"
  user: root
- address: 10.xxx.xx.xx
  role:
  - worker
  hostname_override: "xxx"
  user: root
- address: 10.xx.xx,xx
  role:
  - controlplane
  - etcd
  hostname_override: "xxx"
  user: root
- address: 10.xx.xx,xx
  role:
  - controlplane
  - etcd
  hostname_override: "xxx"
  user: root
- address: 10.xx.xx,xx
  role:
  - controlplane
  - etcd
  hostname_override: "xxx"
  user: root
etcd:
#    snapshot: true
#    retention: "24h"
#    creation: "4h0s"
    backup_config:
      interval_hours: 4
      retention: 6
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
ssh_key_path: /root/.ssh/id_rsa
#ssh_agent_auth: false
ssh_agent_auth: true
authorization:
  mode: rbac
  options: {}
ignore_docker_version: true
#kubernetes_version: "v1.12.4-rancher1-1"
private_registries:
  - url: docker.xxx.xxxx.com
    is_default: true
ingress:
  provider: "nginx"
  options:
    ssl-protocols: TLSv1.2
  node_selector:
    app: ingress
  extra_args: {}
```
