### ISSUE TITLE
Kubelet fails to detect broken network link to kube-apiserver, attempts to use closed socket

### ISSUE THREAD

**Issue by spirilis** [rancher/rke#2218]
**RKE version:**
v1.18.3

**Docker version: (`docker version`,`docker info` preferred)**
18.09.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.6 (Maipo) 3.10.0-957.12.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**cluster.yml file:**
```
  # 
  # Cluster Config
  # 
  answers: {}
  default_pod_security_policy_template_id: restricted-userswitch
  docker_root_dir: /var/lib/docker
  enable_cluster_alerting: false
  enable_cluster_monitoring: true
  enable_network_policy: true
  local_cluster_auth_endpoint:
    enabled: true
  name: intrak8s-test
  # 
  # Rancher Config
  # 
  rancher_kubernetes_engine_config:
    addon_job_timeout: 30
    authentication:
      strategy: x509|webhook
    authorization: {}
    bastion_host:
      ssh_agent_auth: false
    cloud_provider: {}
    ignore_docker_version: true
  # 
  # # Currently only nginx ingress provider is supported.
  # # To disable ingress controller, set `provider: none`
  # # To enable ingress on specific nodes, use the node_selector, eg:
  #    provider: nginx
  #    node_selector:
  #      app: ingress
  # 
    ingress:
      provider: nginx
    kubernetes_version: v1.18.3-rancher2-2
    monitoring:
      provider: metrics-server
      replicas: 1
  # 
  #   If you are using calico on AWS
  # 
  #    network:
  #      plugin: calico
  #      calico_network_provider:
  #        cloud_provider: aws
  # 
  # # To specify flannel interface
  # 
  #    network:
  #      plugin: flannel
  #      flannel_network_provider:
  #      iface: eth1
  # 
  # # To specify flannel interface for canal plugin
  # 
  #    network:
  #      plugin: canal
  #      canal_network_provider:
  #        iface: eth1
  # 
    network:
      mtu: 0
      options:
        flannel_backend_type: vxlan
      plugin: canal
    private_registries:
      - is_default: true
        url: <redacted>
        user: <redacted>
    restore:
      restore: false
  # 
  #    services:
  #      kube-api:
  #        service_cluster_ip_range: 10.43.0.0/16
  #      kube-controller:
  #        cluster_cidr: 10.42.0.0/16
  #        service_cluster_ip_range: 10.43.0.0/16
  #      kubelet:
  #        cluster_domain: cluster.local
  #        cluster_dns_server: 10.43.0.10
  # 
    services:
      etcd:
        backup_config:
          enabled: true
          interval_hours: 3
          retention: 32
          s3_backup_config:
            access_key: <redacted>
            bucket_name: <redacted>
            endpoint: <redacted>
          safe_timestamp: false
        creation: 12h
        extra_args:
          election-timeout: '5000'
          heartbeat-interval: '500'
        gid: 0
        retention: 72h
        snapshot: false
        uid: 0
      kube-api:
        always_pull_images: false
        pod_security_policy: true
        service_node_port_range: 30000-32767
      kube-controller: {}
      kubelet:
        fail_swap_on: false
        generate_serving_certificate: false
      kubeproxy: {}
      scheduler: {}
    ssh_agent_auth: false
    upgrade_strategy:
      drain: false
      max_unavailable_controlplane: '1'
      max_unavailable_worker: 10%
      node_drain_input:
        delete_local_data: false
        force: false
        grace_period: -1
        ignore_daemon_sets: true
        timeout: 120
  scheduled_cluster_scan:
    enabled: false
    scan_config:
      cis_scan_config:
        override_benchmark_version: rke-cis-1.4
        profile: permissive
    schedule_config:
      cron_schedule: 0 0 * * *
      retention: 24
```

**Symptom:**
This happens sporadically but the first event I notice is in "nginx-proxy" docker logs output:

`{"log":"2020/08/20 02:12:42 [error] 15#15: *49183 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: \"10.104.10.194:6443\", bytes from/to client:0/0, bytes from/to upstream:0/0\n","stream":"stderr","time":"2020-08-20T02:15:02.814726586Z"}`
`{"log":"2020/08/20 02:12:42 [warn] 15#15: *49183 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: \"10.104.10.194:6443\", bytes from/to client:0/0, bytes from/to upstream:0/0\n","stream":"stderr","time":"2020-08-20T02:15:04.790239955Z"}`

Shortly after this, Kubelet gets stuck - for hours and hours on end - with log messages like the following:
`{"log":"E0824 15:44:24.655186   21256 webhook.go:111] Failed to make webhook authenticator request: Post https://127.0.0.1:6443/apis/authentication.k8s.io/v1/tokenreviews: write tcp 127.0.0.1:36534-\u003e127.0.0.1:6443: use of closed network connection\n","stream":"stderr","time":"2020-08-24T15:44:24.655384691Z"}`
`{"log":"E0824 15:44:24.655243   21256 server.go:253] Unable to authenticate the request due to an error: Post https://127.0.0.1:6443/apis/authentication.k8s.io/v1/tokenreviews: write tcp 127.0.0.1:36534-\u003e127.0.0.1:6443: use of closed network connection\n","stream":"stderr","time":"2020-08-24T15:44:24.655419966Z"}`
`{"log":"E0824 15:44:30.780705   21256 webhook.go:111] Failed to make webhook authenticator request: Post https://127.0.0.1:6443/apis/authentication.k8s.io/v1/tokenreviews: write tcp 127.0.0.1:36534-\u003e127.0.0.1:6443: use of closed network connection\n","stream":"stderr","time":"2020-08-24T15:44:30.780953634Z"}`

My understanding is Kubelet access kube-apiserver via 127.0.0.1:6443, which points to nginx-proxy which then routes traffic to the "real" kube-apiserver, and if that connection drops for some unknown reason, kubelet never gets the memo and continues to try using the old socket.  This eventually causes "Kubelet stopped posting node status" to appear in the Rancher GUI and new processes can't start on that node.
