### ISSUE TITLE
`rke up` cannot mount volumes in v1.1.6 with virtualbox on windows

### ISSUE THREAD

**Issue by tsraza** [rancher/rke#2232]
Works in v1.1.4 but not v1.1.6

**RKE version:**

```
rke version v1.1.6
```

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      19.03.11
 API version:  1.40 (minimum version 1.12)
 Go version:   go1.13.10
 Git commit:   42e35e61f3
 Built:        Mon Jun  1 09:16:24 2020
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 19.03.11
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.138-rancher
Operating System: RancherOS v1.5.6
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.793GiB
Name: rke
ID: LYOB:AVMR:AHA5:XGXC:FWCY:ZU4P:73MB:DRLZ:2TWE:EQS2:7QP3:YUGV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

_Windows 10 / Boot2docker_

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

_VirtualBox_

**cluster.yml file:**

```yaml
nodes:
  - address: 192.168.99.100
    ssh_key_path: C:\xxxxx\id_rsa
    user: docker
    role:
      - controlplane
      - etcd
      - worker
ingress:
  provider: none
services:
  kube-api:
    extra_args:
      runtime-config: settings.k8s.io/v1alpha1=true
      enable-admission-plugins: "LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,Priority,PodPreset"
      authorization-mode: "Node,RBAC"
      oidc-issuer-url: https://dex.mydomain.net
      oidc-username-claim: email
      oidc-client-id: oauth2
      oidc-ca-file: /etc/ssl/certs.d/RootCA.crt
    extra_binds:
      - /etc/ssl/certs.d:/etc/ssl/certs.d
  kube-controller:
    extra_args:
      cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
      cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
  kubelet:
    extra_binds:
      - /etc/ssl/certs.d:/etc/ssl/certs.d
```

**Steps to Reproduce:**

```bash
here=$(dirname $(realpath $0))

docker-machine create \
  --virtualbox-hostonly-cidr "192.168.99.1/24" \
  --virtualbox-cpu-count 2 \
  --virtualbox-memory 8192 \
  --virtualbox-disk-size 40000 \
  --virtualbox-no-share \
  --virtualbox-boot2docker-url https://releases.rancher.com/os/latest/rancheros.iso \
  rke

eval $(docker-machine env rke --shell bash)
export DOCKER_TLS_VERIFY
export DOCKER_HOST
export DOCKER_CERT_PATH
export DOCKER_MACHINE_NAME
# tried with and without docker-compose path conversion
# export COMPOSE_CONVERT_WINDOWS_PATHS

export RKE_IP_ADDRESS=$(docker-machine ip rke)
export RKE_SSH_KEY_PATH="xxxxxx/id_rsa"
export KUBECONFIG="$here/kube_config_cluster.yml"

rm $here/kube_config_cluster.yml -f
rm $here/cluster.rkestate -f
rm $here/cluster_certs/* -f
envsubst < $here/template.yml > $here/cluster.yml
rke cert generate-csr --config $here/cluster.yml
rke up --config $here/cluster.yml
```

**Results:**

```
Running pre-create checks...
(rke) Boot2Docker URL was explicitly set to "https://releases.rancher.com/os/latest/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(rke) Boot2Docker URL was explicitly set to "https://releases.rancher.com/os/latest/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(rke) Downloading xxxxx\cache\boot2docker.iso from https://releases.rancher.com/os/latest/rancheros.iso...
(rke) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(rke) Creating VirtualBox VM...
(rke) Creating SSH key...
(rke) Starting the VM...
(rke) Check network to re-create if needed...
(rke) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(rke) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with rancheros...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: xxxxx\docker-machine.exe env rke
time="2020-09-08T17:46:12-10:00" level=info msg="Running RKE version: v1.1.6"
time="2020-09-08T17:46:12-10:00" level=info msg="Generating Kubernetes cluster CSR certificates"
time="2020-09-08T17:46:12-10:00" level=info msg="[certificates] Generating Kubernetes API server csr"
time="2020-09-08T17:46:13-10:00" level=info msg="[certificates] Generating Kube Controller csr"
time="2020-09-08T17:46:13-10:00" level=info msg="[certificates] Generating Kube Scheduler csr"
time="2020-09-08T17:46:14-10:00" level=info msg="[certificates] Generating Kube Proxy csr"
time="2020-09-08T17:46:14-10:00" level=info msg="[certificates] Generating Node csr and key"
time="2020-09-08T17:46:15-10:00" level=info msg="[certificates] Generating admin csr and kubeconfig"
time="2020-09-08T17:46:15-10:00" level=info msg="[certificates] Generating Kubernetes API server proxy client csr"
time="2020-09-08T17:46:16-10:00" level=info msg="[certificates] Generating etcd-192.168.99.100 csr and key"
time="2020-09-08T17:46:16-10:00" level=info msg="Successfully Deployed certificates at [xxxxx/cluster_certs]"
time="2020-09-08T17:46:17-10:00" level=info msg="Running RKE version: v1.1.6"
time="2020-09-08T17:46:17-10:00" level=info msg="Initiating Kubernetes cluster"
time="2020-09-08T17:46:17-10:00" level=info msg="[dialer] Setup tunnel for host [192.168.99.100]"
time="2020-09-08T17:46:17-10:00" level=info msg="Checking if container [cluster-state-deployer] is running on host [192.168.99.100], try #1"
time="2020-09-08T17:46:17-10:00" level=info msg="Pulling image [rancher/rke-tools:v0.1.64] on host [192.168.99.100], try #1"
time="2020-09-08T17:46:48-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:46:50-10:00" level=warning msg="Failed to create Docker container [cluster-state-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"
time="2020-09-08T17:46:51-10:00" level=warning msg="Failed to create Docker container [cluster-state-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"
time="2020-09-08T17:46:51-10:00" level=warning msg="Failed to create Docker container [cluster-state-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"
time="2020-09-08T17:46:51-10:00" level=info msg="[certificates] Generating CA kubernetes certificates"
time="2020-09-08T17:46:52-10:00" level=info msg="[certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates"
time="2020-09-08T17:46:53-10:00" level=info msg="[certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates"
time="2020-09-08T17:46:53-10:00" level=info msg="[certificates] Generating Kubernetes API server certificates"
time="2020-09-08T17:46:53-10:00" level=info msg="[certificates] Generating Service account token key"
time="2020-09-08T17:46:53-10:00" level=info msg="[certificates] Generating Kube Controller certificates"
time="2020-09-08T17:46:53-10:00" level=info msg="[certificates] Generating Kube Scheduler certificates"
time="2020-09-08T17:46:53-10:00" level=info msg="[certificates] Generating Kube Proxy certificates"
time="2020-09-08T17:46:54-10:00" level=info msg="[certificates] Generating Node certificate"
time="2020-09-08T17:46:54-10:00" level=info msg="[certificates] Generating admin certificates and kubeconfig"
time="2020-09-08T17:46:54-10:00" level=info msg="[certificates] Generating Kubernetes API server proxy client certificates"
time="2020-09-08T17:46:54-10:00" level=info msg="[certificates] Generating kube-etcd-192-168-99-100 certificate and key"
time="2020-09-08T17:46:54-10:00" level=info msg="Successfully Deployed state file at [xxxxxx/cluster.rkestate]"
time="2020-09-08T17:46:54-10:00" level=info msg="Building Kubernetes cluster"
time="2020-09-08T17:46:54-10:00" level=info msg="[dialer] Setup tunnel for host [192.168.99.100]"
time="2020-09-08T17:46:55-10:00" level=info msg="[network] Deploying port listener containers"
time="2020-09-08T17:46:55-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:46:56-10:00" level=info msg="Starting container [rke-etcd-port-listener] on host [192.168.99.100], try #1"
time="2020-09-08T17:46:58-10:00" level=info msg="[network] Successfully started [rke-etcd-port-listener] container on host [192.168.99.100]"
time="2020-09-08T17:46:58-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:47:00-10:00" level=info msg="Starting container [rke-cp-port-listener] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:02-10:00" level=info msg="[network] Successfully started [rke-cp-port-listener] container on host [192.168.99.100]"
time="2020-09-08T17:47:02-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:47:03-10:00" level=info msg="Starting container [rke-worker-port-listener] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:05-10:00" level=info msg="[network] Successfully started [rke-worker-port-listener] container on host [192.168.99.100]"
time="2020-09-08T17:47:05-10:00" level=info msg="[network] Port listener containers deployed successfully"
time="2020-09-08T17:47:05-10:00" level=info msg="[network] Running control plane -> etcd port checks"
time="2020-09-08T17:47:05-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:47:06-10:00" level=info msg="Starting container [rke-port-checker] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:07-10:00" level=info msg="[network] Successfully started [rke-port-checker] container on host [192.168.99.100]"
time="2020-09-08T17:47:07-10:00" level=info msg="Removing container [rke-port-checker] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:08-10:00" level=info msg="[network] Running control plane -> worker port checks"
time="2020-09-08T17:47:08-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:47:09-10:00" level=info msg="Starting container [rke-port-checker] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:11-10:00" level=info msg="[network] Successfully started [rke-port-checker] container on host [192.168.99.100]"
time="2020-09-08T17:47:11-10:00" level=info msg="Removing container [rke-port-checker] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:11-10:00" level=info msg="[network] Running workers -> control plane port checks"
time="2020-09-08T17:47:11-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:47:13-10:00" level=info msg="Starting container [rke-port-checker] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:14-10:00" level=info msg="[network] Successfully started [rke-port-checker] container on host [192.168.99.100]"
time="2020-09-08T17:47:14-10:00" level=info msg="Removing container [rke-port-checker] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:15-10:00" level=info msg="[network] Checking KubeAPI port Control Plane hosts"
time="2020-09-08T17:47:15-10:00" level=info msg="[network] Removing port listener containers"
time="2020-09-08T17:47:15-10:00" level=info msg="Removing container [rke-etcd-port-listener] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:16-10:00" level=info msg="[remove/rke-etcd-port-listener] Successfully removed container on host [192.168.99.100]"
time="2020-09-08T17:47:16-10:00" level=info msg="Removing container [rke-cp-port-listener] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:18-10:00" level=info msg="[remove/rke-cp-port-listener] Successfully removed container on host [192.168.99.100]"
time="2020-09-08T17:47:18-10:00" level=info msg="Removing container [rke-worker-port-listener] on host [192.168.99.100], try #1"
time="2020-09-08T17:47:19-10:00" level=info msg="[remove/rke-worker-port-listener] Successfully removed container on host [192.168.99.100]"
time="2020-09-08T17:47:19-10:00" level=info msg="[network] Port listener containers removed successfully"
time="2020-09-08T17:47:19-10:00" level=info msg="[certificates] Deploying kubernetes certificates to Cluster nodes"
time="2020-09-08T17:47:19-10:00" level=info msg="Checking if container [cert-deployer] is running on host [192.168.99.100], try #1"
time="2020-09-08T17:47:19-10:00" level=info msg="Image [rancher/rke-tools:v0.1.64] exists on host [192.168.99.100]"
time="2020-09-08T17:47:20-10:00" level=warning msg="Failed to create Docker container [cert-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"
time="2020-09-08T17:47:20-10:00" level=warning msg="Failed to create Docker container [cert-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"
time="2020-09-08T17:47:20-10:00" level=warning msg="Failed to create Docker container [cert-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path"
time="2020-09-08T17:47:20-10:00" level=fatal msg="[Failed to create Certificates deployer container on host [192.168.99.100]: Failed to create Docker container [cert-deployer] on host [192.168.99.100]: Error response from daemon: create \\/etc/kubernetes: \"\\\\/etc/kubernetes\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path]"
```

**Comment by veccsolutions** [comment]
Not just using Virtual Box, I just got the same thing with Windows pointed at 3 Debian VM's. Worked on 1.1.4, failed on 1.1.7. 

My cluster.yml is this
```
nodes:
- address: rancher1.redacted.org
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: redacted
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: c:/users/redacted/.ssh/linux_id
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher2.redacted.org
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: redacted
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: c:/users/redacted/.ssh/linux_id
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher3.redacted.org
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: redacted
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: c:/users/redacted/.ssh/linux_id
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    snapshot: true
    retention: 24h
    creation: 6h
network:
  plugin: flannel
```
