### ISSUE TITLE
kubernetes manifests get stored in /etc/kubernetes/ssl

### ISSUE THREAD

**Issue by sigurdblueface** [rancher/rke#2238]
**RKE version:** v1.1.7

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```
Client:
 Debug Mode: false

Server:
 Containers: 20
  Running: 15
  Paused: 0
  Stopped: 5
 Images: 15
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.904GiB
 Name: hvc-1
 ID: QMS2:6HCU:PTJ3:65HC:N6CQ:5QSL:IZXK:E7BO:JGZV:QGD2:TOTC:QEBM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://192.168.152.9:3128
 HTTPS Proxy: http://192.168.152.9:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
```
5.4.0-42-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**cluster.yml file:**
```
nodes:
  - address: <ip1>
    user: root
    role:
      - controlplane
      - etcd
      - worker
  - address: <ip2>
    user: root
    role:
      - controlplane
      - etcd
      - worker
  - address: <ip3>
    user: root
    role:
      - controlplane
      - etcd
      - worker
ignore_docker_version: true
# Cluster level SSH private key
# Used if no ssh information is set for the node
ssh_key_path: ~/.ssh/id_rsa
cluster_name: test_rke_cluster
kubernetes_version: v1.17.9-rancher1-1

network:
  plugin: flannel

# Specify DNS provider (coredns or kube-dns)
dns:
  provider: coredns
```
**Steps to Reproduce:**
 `rke up`
**Results:**

kubernetes manifests got stored in **/etc/kubernetes/ssl/** instead of just **/etc/kubernetes/**
why does it happen? Is there a workaroud for that behaviour?

```
root@hvc-1:/etc/kubernetes/ssl# ll *.yaml
-rw------- 1 root root 517 сен 15 12:18 kubecfg-kube-apiserver-proxy-client.yaml
-rw------- 1 root root 533 сен 15 12:18 kubecfg-kube-apiserver-requestheader-ca.yaml
-rw------- 1 root root 501 сен 15 12:18 kubecfg-kube-controller-manager.yaml
-rw------- 1 root root 445 сен 15 12:18 kubecfg-kube-node.yaml
-rw------- 1 root root 449 сен 15 12:18 kubecfg-kube-proxy.yaml
-rw------- 1 root root 465 сен 15 12:18 kubecfg-kube-scheduler.yaml
root@hvc-1:/etc/kubernetes/ssl#
```
