### ISSUE TITLE
Allow to specify custom parameters for CoreDNS autoscaler

### ISSUE THREAD

**Issue by BarthV** [rancher/rke#2247]
Hi !
I'm currently managing several clusters running many tainted dedicated nodes with very small cpu & ram. Each of these nodes are hosting very few pods.

So these nodes are not working "much" and are certainly not putting any pressure on my cluster nor on coredns.
But autoscaler still counts them as real servers and tries to adapt the number of coredns instances accordingly until reaching a demand much higher than the number of my "normal" untainted nodes. (which is sad and triggers some of my deployments alerts)

```
> kubectl get pods -n kube-system
NAME                                  READY   STATUS      RESTARTS   AGE
coredns-5f744cb5d8-2m92p              1/1     Running     2          95d
coredns-5f744cb5d8-db4f5              1/1     Running     0          41d
[...]
coredns-5f744cb5d8-pxjk8              1/1     Running     2          95d
coredns-5f744cb5d8-vhbwg              0/1     Pending     0          25h
coredns-autoscaler-65bfc8d47d-9c49p   1/1     Running     5          109d
```

As a cluster admin, I need to be able specifying custom `--default-params` options for the coredns-autoscaler.
Currently scaler configuration seems hardcoded and I can't see any way to tune it from rke `cluster.yml` file.

thanks a lot !

RKE autoscaler details in my current config :
```
Containers:
  autoscaler:
    Container ID:  docker://07a45cead2e9a113634ba3c55f6de1b82ddddf4fdbee88dc37cadf9c1cac8769
    Image:         rancher/cluster-proportional-autoscaler:1.7.1
    Image ID:      docker-pullable://rancher/cluster-proportional-autoscaler@sha256:1f5f92bcc7dde6673263ad716506586786a8cb7ecc24987d5a05bb9a907e0607
    Port:          <none>
    Host Port:     <none>
    Command:
      /cluster-proportional-autoscaler
      --namespace=kube-system
      --configmap=coredns-autoscaler
      --target=Deployment/coredns
      --default-params={"linear":{"coresPerReplica":128,"nodesPerReplica":4,"min":1,"preventSinglePointFailure":true}}
      --nodelabels=node-role.kubernetes.io/worker=true,beta.kubernetes.io/os=linux
      --logtostderr=true
      --v=2
```

Related issues :
- rancher/rke#2029

---
More infos from one of my cluster :

**RKE version:** v1.1.7
**Docker version:** 19.3.12
**Operating system and kernel:** Ubuntu 20.04 with 5.4.0 kernel
**Type/provider of hosts:** Bare-metal

**cluster.yml file:**
```yaml
cluster_name: foobar
kubernetes_version: v1.17.11-rancher1-1

authorization:
  mode: rbac

network:
  plugin: flannel
  options:
    flannel_backend_type: host-gw

dns:
  provider: coredns

ingress:
  provider: none

services:
  kubelet:
    extra_args:
      image-pull-progress-deadline: 420m
    extra_binds:
    - "/volumes:/volumes"

nodes:
  - [ ... ]
```

**Steps to Reproduce:**

**Results:**

**Comment by immanuelfodor** [comment]
I have 3 nodes with 4 cores each but only 2 CoreDNS replicas running based on the default config of `{"linear":{"coresPerReplica":128,"nodesPerReplica":4,"min":1,"preventSinglePointFailure":true}}` as shown above.

I'd like to have 3 replicas, each running on one node. It'd be great to be able to pass a custom config to the autoscaler as seen at https://github.com/kubernetes-sigs/cluster-proportional-autoscaler#linear-mode

**Comment by immanuelfodor** [comment]
Unstale

**Comment by lamroger** [comment]
Hey - is this supported?

I have 
```
rancher_kubernetes_engine_config:
  ...
  dns:
    linear_autoscaler_params:
      cores_per_replica: 256
      max: 4
      min: 2
      nodes_per_replica: 16
      prevent_single_point_failure: true
```

in my rancher config which does update the default params on the pod
```
      --default-params={"linear":{"coresPerReplica":256,"nodesPerReplica":16,"min":2,"max":4,"preventSinglePointFailure":true}}
```

but it doesn't update the configmap which is also loaded
```
 --configmap=coredns-autoscaler
```
