### ISSUE TITLE
Recurring RKE Backup Not Uploading to S3

### ISSUE THREAD

**Issue by oxr463** [rancher/rke#2320]
**RKE version:**

 v1.1.3

**Docker version: (`docker version`,`docker info` preferred)**

19.03.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

CentOS 7.8.2003 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

```yml
cluster_name: nonprod-mgmt
kubernetes_version: "v1.15.12-rancher2-3"
nodes:
  - address: node-cluster-etc1
    user: rancher
    role: [etcd]
  - address: node-cluster-etc2
    user: rancher
    role: [etcd]
  - address: node-cluster-etc3
    user: rancher
    role: [etcd]
  - address: node-cluster-etc4
    user: rancher
    role: [etcd]
  - address: node-cluster-etc5
    user: rancher
    role: [etcd]
  - address: node-cluster-ctl1
    user: rancher
    role: [controlplane]
  - address: node-cluster-ctl2
    user: rancher
    role: [controlplane]
  - address: node-cluster-ctl3
    user: rancher
    role: [controlplane]
  - address: node-cluster-wrk1
    user: rancher
    role: [worker]
  - address: node-cluster-wrk2
    user: rancher
    role: [worker]
  - address: node-cluster-wrk3
    user: rancher
    role: [worker]

ingress:
  provider: nginx
  options:
    enable-underscores-in-headers: true
    server-tokens: false
    use-forwarded-headers: true

network:
  plugin: canal
  options:
    mtu: 0

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 72h
    s3backupconfig:
      access_key: "[ . . . REDACTED . . . ]"
      secret_key: "[ . . . REDACTED . . . ]"
      bucket_name: "rancher-backups"
      region: "us-east-1"
      folder: "rancher"
      endpoint: "s3.us-east-1.amazonaws.com"
  kube-api:
    service_cluster_ip_range: 10.105.0.0/16
    service_node_port_range: 30000-32767
    pod_security_policy: false
  kube-controller:
    cluster_cidr: 10.104.0.0/16
    service_cluster_ip_range: 10.105.0.0/16
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.105.0.2
    fail_swap_on: true
```

**Steps to Reproduce:**

1. Configure recurring snapshots via the official docs, (See: https://rancher.com/docs/rke/latest/en/etcd-snapshots/recurring-snapshots/#configuring-the-snapshot-service-in-yaml).

**Results:**

The snapshots are never uploaded to S3. 

gz#12932
