### ISSUE TITLE
Failed to deploy job rke-network-plugin

### ISSUE THREAD

**Issue by pustovoytenko** [rancher/rke#2347]
**RKE version:**
`v1.2.3`

**Docker version:**
`19.03.13`

**Operating system and kernel:**
`CentOS-7`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`Bare-metal`

**cluster.yml file:**

```
cluster_name: xxxx
kubernetes_version: "v1.19.4-rancher1-1"
ssh_key_path: xxxx

nodes:
  - address: <FQDN>
    port: "22"
    user: xxxx
    role: [controlplane, worker, etcd]

services:
    etcd:
      snapshot: true
      creation: 6h
      retention: 24h

    kubelet:
      extra_args:
        root-dir: "custom-dir"
      extra_binds:
        - "custom-dir:custom-dir"
```

**Steps to Reproduce:**
`rke up`

**Results:**
```
kubectl logs rke-network-plugin-deploy-job-l4wrc -n kube-system

The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
The issue is kubectl from container `rke-network-plugin-deploy-job-*` tries to connect to kube-apiserver on localhost:8080, but that's disabled by default in the kube-apiserver options with the flag: --insecure-port=0.

**Workaround**
Add to cluster.yml file:
```
kube-api:
      extra_args:
        insecure-port: "8080"
        insecure-bind-address: "127.0.0.1"
```
