### ISSUE TITLE
FATA[0113] Failed to deploy addon execute job: Failed to get job complete status: <nil>

### ISSUE THREAD

**Issue by myselfghost** [rancher/rke#236]
**RKE version:** rke version v0.0.11-dev or  v0.0.12

**Docker version: (`docker version`,`docker info` preferred)** Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Linux docker-test4 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 

**cluster.yml file:**
```
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0
nodes:
  - address: 172.19.3.170
    user: app
    role: [etcd,controlplane]
  - address: 172.19.3.168
    user: app
    role: [worker]
  - address: 172.19.3.169
    user: app
    role: [worker]

services:
  etcd:
    image: hub.c.163.com/xiaopal/quay.io/coreos/etcd:v3.0.17 
  kube-api:
    image: rancher/k8s:v1.8.5-rancher4
  kube-controller:
    image: rancher/k8s:v1.8.5-rancher4
  scheduler:
    image: rancher/k8s:v1.8.5-rancher4
  kubelet:
    image: rancher/k8s:v1.8.5-rancher4
  kuberouter:
    image: rancher/k8s:v1.8.5-rancher4
```
**Steps to Reproduce:**

**Results:**
```
INFO[0088] [network] Setting up network plugin: flannel 
INFO[0088] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0088] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin 
INFO[0088] [addons] Executing deploy job..              
Failed to get job complete status: <nil>
FATA[0113] Failed to deploy addon execute job: Failed to get job complete status: <nil> 
```

docker logs kubelet  
```
W0116 06:58:15.920547   27626 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
E0116 06:58:15.920881   27626 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
