### ISSUE TITLE
ignore_docker_version is ignored

### ISSUE THREAD

**Issue by yankcrime** [rancher/rke#2378]
The `ignore_docker_version` option appears to be ignored.  However, passing `--ignore-docker-version` works as expected.

**RKE version:**

`rke version v1.2.3`

**Docker version: (`docker version`,`docker info` preferred)**

20.10.0 (CE)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 20.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VMware ESXi

**cluster.yml file:**

```yaml
cluster_name: vspherenetes
ssh_agent_auth: true
ignore_docker_version: true
kubernetes_version: "v1.19.4-rancher1-1"

nodes:
    - address: 192.168.1.92
      user: nick
      role:
        - controlplane
        - etcd
    - address: 192.168.1.12
      user: nick
      role:
        - worker
    - address: 192.168.1.27
      user: nick
      role:
        - worker
    - address: 192.168.1.96
      user: nick
      role:
        - worker
```

**Steps to Reproduce:**
`rke up`

**Results:**

```
FATA[0000] Unsupported Docker version found [20.10.0] on host [192.168.1.67], supported versions are [1.13.x 17.03.x 17.06.x 17.09.x 18.06.x 18.09.x 19.03.x]
zsh: exit 1     rke up
```

Retrying with the `--ignore-docker-version` set results in a successful cluster deployment.
