### ISSUE TITLE
fedora coreos 33 unable to ssh tunnel to nodes

### ISSUE THREAD

**Issue by forge3125** [rancher/rke#2388]
**RKE version:**
rke version v1.0.14

**Docker version: (`docker version`,`docker info` preferred)**
19.03.13

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Fedora CoreOS release 33

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```
nodes:
    - address: 10.208.28.186
      user: forgeadmin
      role:
        - etcd
        - controlplane
        - worker
    - address: 10.208.28.210
      user: core
      role: 
        - etcd 
        - controlplane 
        - worker
    - address: 10.208.28.224
      user: core
      role: 
        - etcd 
        - controlplane 
        - worker
    - address: 10.208.28.184
      user: core
      role:
        - etcd
        - controlplane
        - worker

cluster_name: kfc

network:
  plugin: calico
  options:
    calico_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    flannel_backend_type: vxlan
 
services:
  kube-controller:
    extra_args:
      flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
```

**Steps to Reproduce:**
rke up

**Results:**
./rke up
INFO[0000] Running RKE version: v1.0.14                 
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [certificates] Generating Kubernetes API server certificates 
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0000] [certificates] Generating kube-etcd-10-208-28-186 certificate and key 
INFO[0000] [certificates] Generating kube-etcd-10-208-28-210 certificate and key 
INFO[0000] [certificates] Generating kube-etcd-10-208-28-224 certificate and key 
INFO[0000] [certificates] Generating kube-etcd-10-208-28-184 certificate and key 
INFO[0000] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [10.208.28.224] 
INFO[0000] [dialer] Setup tunnel for host [10.208.28.184] 
INFO[0000] [dialer] Setup tunnel for host [10.208.28.186] 
INFO[0000] [dialer] Setup tunnel for host [10.208.28.210] 
WARN[0000] Failed to set up SSH tunneling for host [10.208.28.224]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.208.28.224:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
WARN[0000] Failed to set up SSH tunneling for host [10.208.28.210]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.208.28.210:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain 
WARN[0000] Failed to set up SSH tunneling for host [10.208.28.184]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.208.28.184:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
WARN[0001] Removing host [10.208.28.224] from node lists 
WARN[0001] Removing host [10.208.28.210] from node lists 
WARN[0001] Removing host [10.208.28.184] from node lists
