### ISSUE TITLE
Calico plugin fails with calicoct: "MountVolume.SetUp failed for volume "ippool-config" : configmap references non-existent config key: none-ippool"

### ISSUE THREAD

**Issue by nseyvet** [rancher/rke#240]
**RKE version:**
rke version v0.0.12-dev

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 30
 Running: 22
 Paused: 0
 Stopped: 8
Images: 21
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 177
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: aio-nise-k8s-master-00
ID: MOOG:XSLW:M7T3:GCMS:QSYC:MG5N:H73O:WUCT:XLGM:KEK6:N4DA:WADD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04, 4.4.0-104-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare.

**cluster.yml file:**

```
---
authentication:
  strategy: x509
  options: {}

authorization:
  mode: rbac
  options: {}

network:
  plugin: calico
  options: {}

nodes:
  - machine_name: aio-nise-k8s-master-00
    address: 10.0.8.30
    user: op5
    role: [etcd,controlplane,worker]
  - machine_name: aio-nise-k8s-master-01
    address: 10.0.8.31
    user: op5
    role: [etcd,controlplane,worker]
  - machine_name: aio-nise-k8s-master-02
    address: 10.0.8.32
    user: op5
    role: [etcd,controlplane,worker]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.5-rancher4
    service_cluster_ip_range: 10.233.0.0/18
  kube-controller:
    image: rancher/k8s:v1.8.5-rancher4
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.5-rancher4
  kubelet:
    image: rancher/k8s:v1.8.5-rancher4
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args:
      fail-swap-on: FALSE
  kubeproxy:
    image: rancher/k8s:v1.8.5-rancher4

# Ensure key is available
ssh_key_path: simple.pem

```
**Steps to Reproduce:**
rke up with above cluster..yml.

**Results:**
The calicoctl pod is failing with the following error:
`MountVolume.SetUp failed for volume "ippool-config" : configmap references non-existent config key: none-ippool
`
Seems similar to: https://github.com/rancher/rke/pull/199

Errors:
```
MountVolume.SetUp failed for volume "ippool-config" : configmap references non-existent config key: none-ippool
Unable to mount volumes for pod "calicoctl_kube-system(6766ace4-fb66-11e7-b46d-005056be3616)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"calicoctl". list of unattached/unmounted volumes=[ippool-config]
```
