### ISSUE TITLE
 Failed to copy file [/etc/kubernetes/.tmp/kube-ca.pem] from container

### ISSUE THREAD

**Issue by frankiezdh** [rancher/rke#247]
**RKE version:**
```bash
[vagrant@node1 ~]$ ./rke_linux-amd64 -v
rke version v0.0.12-dev
```
**Docker version: (`docker version`,`docker info` preferred)**
```bash
[vagrant@node1 ~]$ docker info                                                   
Containers: 2                                                                    
 Running: 0                                                                      
 Paused: 0                                                                       
 Stopped: 2                                                                      
Images: 2                                                                        
Server Version: 17.12.0-ce                                                       
Storage Driver: overlay2                                                         
 Backing Filesystem: xfs                                                         
 Supports d_type: true                                                           
 Native Overlay Diff: true                                                       
Logging Driver: json-file                                                        
Cgroup Driver: cgroupfs                                                          
Plugins:                                                                         
 Volume: local                                                                   
 Network: bridge host macvlan null overlay                                       
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog   
Swarm: inactive                                                                  
Runtimes: runc                                                                   
Default Runtime: runc                                                            
Init Binary: docker-init                                                         
containerd version: 89623f28b87a6004d4b785663257362d1658a729                     
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f                           
init version: 949e6fa                                                            
Security Options:                                                                
 seccomp                                                                         
  Profile: default                                                               
Kernel Version: 3.10.0-693.5.2.el7.x86_64                                        
Operating System: CentOS Linux 7 (Core)                                          
OSType: linux                                                                    
Architecture: x86_64                                                             
CPUs: 1                                                                          
Total Memory: 488.4MiB                                                           
Name: node1                                                                      
ID: MMMG:G2ME:MOXQ:YBS3:JELJ:ASUS:QKBL:I6BJ:M6YU:K36U:LMAV:XHDV                  
Docker Root Dir: /var/lib/docker                                                 
Debug Mode (client): false                                                       
Debug Mode (server): false                                                       
Registry: https://index.docker.io/v1/                                            
Labels:                                                                          
Experimental: false                                                              
Insecure Registries:                                                             
 127.0.0.0/8                                                                     
Registry Mirrors:                                                                
 https://f1spk3kz.mirror.aliyuncs.com/                                           
Live Restore Enabled: false                                                      
                                                                                 
WARNING: IPv4 forwarding is disabled                                             
WARNING: bridge-nf-call-iptables is disabled                                     
WARNING: bridge-nf-call-ip6tables is disabled                                    
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```bash
[vagrant@node1 ~]$ uname -r
3.10.0-693.5.2.el7.x86_64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**cluster.yml file:**
```yaml
---
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

enforce_docker_version: false
# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization
authorization:
  mode: rbac

nodes:
  - address: 1.1.1.1
    user: vagrant
    role: [controlplane, etcd]

  - address: 1.1.1.2
    user: vagrant
    role: [worker]

  - address: 1.1.1.3
    user: vagrant
    role: [worker]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 172.172.0.0/16
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 172.173.0.0/16
    service_cluster_ip_range: 172.172.0.0/16
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 223.5.5.5
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2


system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.0
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  service_sidekick_image: rancher/rke-service-sidekick:v0.1.0
  kubedns_image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0
```
**Steps to Reproduce:**

**Results:**
```bash
[vagrant@node1 ~]$ ./rke_linux-amd64 up  --config 1.yml.3
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [1.1.1.1]
WARN[0000] Unsupported Docker version found [17.12.0-ce], supported versions are [1.12.6 1.13.1 17.03.2]
INFO[0000] [dialer] Setup tunnel for host [1.1.1.2]
WARN[0000] Unsupported Docker version found [17.12.0-ce], supported versions are [1.12.6 1.13.1 17.03.2]
INFO[0000] [dialer] Setup tunnel for host [1.1.1.3]
WARN[0000] Unsupported Docker version found [17.12.0-ce], supported versions are [1.12.6 1.13.1 17.03.2]
INFO[0000] [certificates] Attempting to recover certificates from backup on host [1.1.1.1]
INFO[0000] [certificates] Checking image [alpine:latest] on host [1.1.1.1]
INFO[0000] [certificates] No pull necessary, image [alpine:latest] exists on host [1.1.1.1]
INFO[0000] [certificates] Successfully started [cert-fetcher] container on host [1.1.1.1]
FATA[0000] Failed to copy file [/etc/kubernetes/.tmp/kube-ca.pem] from container [cert-fetcher] on host [1.1.1.1]: Error response from daemon: Could not find the file /etc/kubernetes/.tmp/kube-ca.pem in container cert-fetcher
```
