### ISSUE TITLE
RKE 1.2.5 not compatible with kernel 4.18.0-240 (rhel8 or centos8)

### ISSUE THREAD

**Issue by lerminou** [rancher/rke#2474]
**RKE version:**
1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:19 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175

```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Redhat8.3 or centos 8.2
4.18.0-240.el8.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal VM with vsphere provider storage

**cluster.yml file:**
```
cluster_name: "nexus-cloud"
kubernetes_version: "v1.19.7-rancher1-1"
nodes:
  - hostname_override: "vm-01"
    address: "172.23.4.16"
    role:
      - controlplane
      - etcd
      - worker

  - hostname_override: "vm-02"
    address: "172.23.4.17"
    role:
      - controlplane
      - etcd
      - worker
```

**Steps to Reproduce:**
rke up

**Results:**
*The network is not working*
I tried all CNI in all modes (calico , flannel, canal) BGP or VXLAN
I followed all prerequisites: including kernel modules and firewall ports
the rke up finishes with success but nothing is working after that
pods in differents nodes cannot reach each other

It can be verified with:
`kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup kubernetes.default`
which returns timeout or no server

I tried to stop or reset iptables / firewalld / nftables but it changes nothing

When I launch `lsmod`, with the new kernel, nftables seems to be used, and iptables with the old one
and the module nf_conntrack_ipv4 is no more available in kernel .240 I saw a PR to accept that in the core rke but it's not working
![image](https://user-images.githubusercontent.com/3818051/109042881-faec5700-76d0-11eb-83ac-01ab77d0c170.png)

**Workaround**
downgrade the kernel package, reboot and reset the cluster
`yum install iptables-1.8.4-10.el8_2.1 kernel-4.18.0-193.6.3.el8_2`
