### ISSUE TITLE
Cluster CIDR for Rancher-managed Downstream Cluster Overwritten on ETCD Snapshot Restore via RKE Binary

### ISSUE THREAD

**Issue by oxr463** [rancher/rke#2480]
**RKE version:** 1.2.5

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.11.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.37GiB
 Name: catl0xlin10464
 ID: ESPE:GYO6:TUGV:UDPL:TK4T:GSEK:6UGT:CATP:JMMW:3VH7:V77Q:AL6C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://repo.corp.cox.com:5000/
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```

```
Linux catl0xlin10464 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**cluster.yml file:**

```
     addonJobTimeout: 45
      authentication:
        strategy: x509|webhook
      authorization:
        mode: rbac
      bastionHost: {}
      cloudProvider: {}
      clusterName: clusterName
      ignoreDockerVersion: true
      ingress:
        defaultBackend: true
        extraArgs:
          default-ssl-certificate: ingress-nginx/ingress-default-cert
          enable-ssl-passthrough: ""
        nodeSelector:
          ingress: "true"
        options:
          enable-underscores-in-headers: "true"
          server-tokens: "false"
        provider: nginx
      kubernetesVersion: v1.19.3-rancher1-2
      monitoring:
        provider: metrics-server
        replicas: 1
      network:
        options:
          flannel_backend_type: vxlan
        plugin: canal
      nodes:
        - address: 10.62.57.86
          role:
            - controlplane
            - etcd
            - worker
          port: 22
          user: user
          ssh_key_path: /home/user/.ssh/id_key
          hostnameOverride: "nodeHostname1"
        - address: 10.62.57.161
          role:
            - controlplane
            - etcd
            - worker
          port: 22
          user: user
          ssh_key_path: /home/user/.ssh/id_key
          hostnameOverride: "nodeHostname2"
        - address: 10.62.57.106
          role:
            - controlplane
            - etcd
            - worker
          port: 22
          user: user
          ssh_key_path: /home/user/.ssh/id_key
          hostnameOverride: "nodeHostname3"
      restore: {}
      services:
        etcd:
          backupConfig:
            enabled: true
            intervalHours: 1
            retention: 18
            s3BackupConfig:
              accessKey: <<redacted>>
              bucketName: etcd-snapshots
              endpoint: s3.us-east-1.amazonaws.com
              folder: etcd_backups/foo/bar
              region: us-east-1
              secretKey: <<redacted>>
          creation: 12h
          extraArgs:
            election-timeout: "5000"
            heartbeat-interval: "500"
          retention: 72h
          snapshot: false
        kubeApi:
          podSecurityPolicy: true
          serviceClusterIpRange: 192.168.0.0/16
          serviceNodePortRange: 30000-32767
        kubeController:
          clusterCidr: 30.10.0.0/16
          serviceClusterIpRange: 192.168.0.0/16
        kubelet:
          clusterDnsServer: 192.168.0.10
          clusterDomain: cluster.local
          extraArgs:
            eviction-hard: memory.available<8%
            max-pods: "250"
        kubeproxy: {}
        scheduler: {}
      upgradeStrategy:
        drain: false
        maxUnavailableControlplane: "1"
        maxUnavailableWorker: 10%
        nodeDrainInput:
          gracePeriod: -1
          ignoreDaemonSets: true
          timeout: 120
    scheduledClusterScan: {}
```

**Steps to Reproduce:**

1. Create a downstream cluster via the Rancher UI with the following settings:

```
clusterCidr: 30.10.0.0/16
serviceClusterIpRange: 192.168.0.0/16
```

2. Create an etcd snapshot of the downstream cluster via the Rancher UI.

3. Obtain a copy of the rkestate file by either:

  A) Use the rkestate file from the etcd snapshot (for RKE 1.1.4 and newer).

  B) Extracting the rkestate file from the kubelet: https://support.rancher.com/hc/en-us/articles/360042000731-How-to-recover-an-RKE-v0-2-x-v0-3-x-or-v1-x-x-cluster-after-restoration-with-an-incorrect-or-missing-rkestate-file

4. Run `rke etcd snapshot-restore` to recover the cluster.

**Results:**

Actual:

```
"kubeController": {
"image": "rancher/hyperkube:v1.19.3-rancher1",
"clusterCidr": "10.42.0.0/16",
"serviceClusterIpRange": "10.43.0.0/16"
},
```

Desired:

```
"kubeController": {
"image": "rancher/hyperkube:v1.19.3-rancher1",
"clusterCidr": "30.10.0.0/16",
"serviceClusterIpRange": "192.168.0.0/16"
},
```

[trace.txt](https://github.com/rancher/rke/files/6071164/trace.txt)

It works properly when specifying `kube-controller.cluster_cidr` in a regular `cluster.yml` with the RKE binary.

gz#14920
