### ISSUE TITLE
Can't upgrade claster to >=1.19

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [rancher/rke#2527]
**RKE version:** 1.2.7

**Docker version:** 19.03.13
<details>
<summary>docker version</summary>

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
</details>

<details>
<summary>docker info</summary>

```
Client:
 Debug Mode: false

Server:
 Containers: 25
  Running: 20
  Paused: 0
  Stopped: 5
 Images: 46
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-122-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 188.9GiB
 Name: master-3.prod-bm.kubecluster.vk.dreamhost.io
 ID: ODBD:JV4N:PSJN:WTR3:7J6Y:MWUI:WPOJ:355X:VU6I:RETF:656K:JOR6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
</details>

**Operating system and kernel:** Ubuntu 18.04

<details>
<summary>/etc/os-release</summary>

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
</details>
<details>
<summary>uname -r</summary>

```
4.15.0-122-generic
```
</details>

**Type/provider of hosts:**: Bare metal

**cluster.yml file:**
<details>
<summary>cluster.yml</summary>

```
nodes:
   - address: master-1
     user: root
     role: ["controlplane", "etcd"]
   - address: master-2
     user: root
     role: ["controlplane", "etcd"]
   - address: master-3
     user: root
     role: ["controlplane", "etcd"]
  
   - address: node-1
     user: root
     role: ["worker"]
   - address: node-2
     user: root
     role: ["worker"]
   - address: node-3
     user: root
     role: ["worker"]
   - address: node-4
     user: root
     role: ["worker"]

ssh_key_path: .clusters/conf/identity
ssh_agent_auth: false
ignore_docker_version: true
cluster_name: prod.kubecluster
kubernetes_version: v1.18.17-rancher1-1
addon_job_timeout: 300

# TBD: fetch these configs from external source to avoid conflicts
services:
  kube-api:
    service_cluster_ip_range: 10.255.32.0/20
    extra_args:
      event-ttl: 48h
      audit-policy-file: /var/lib/k8s_audit/audit-policy.yaml
      audit-webhook-config-file: /var/lib/k8s_audit/audit-webhook-kubeconfig.yaml
      audit-webhook-batch-max-wait: 5s
      audit-webhook-mode: batch
    extra_binds:
      - /var/lib/k8s_audit:/var/lib/k8s_audit
  kube-controller:
    cluster_cidr: 10.255.48.0/20
    service_cluster_ip_range: 10.255.32.0/20
  kubelet:
    cluster_domain: prod.cluster.local
    cluster_dns_server: 10.255.32.10
    extra_args:
      read-only-port: 10255
      max-pods: 250
    extra_binds:
      - "/opt/app/etc:/opt/app/etc"
  etcd:
    extra_args:
      heartbeat-interval: 1000
      election-timeout: 5000
      snapshot-count: 5000

network:
  plugin: canal

authentication:
  stretegy: x509
  sans:
  - "*.prod.kubecluster.domain.local"

authorization:
  mode: rbac

ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
    log-format-upstream: "$remote_addr - $remote_user [$time_local] \\\"$request\\\" $status
    $body_bytes_sent \\\"$http_referer\\\" \\\"$http_user_agent\\\" $request_length $request_time
    [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time
    $upstream_status $req_id $host"
    proxy-body-size: "101m"
    http-snippet: |
      server {
        listen 81;
        server_name localhost;
        access_log off;
        allow 127.0.0.1;
        deny all;
        location /nginx_status {
          stub_status;
        }
      }
  update_strategy:
    strategy: RollingUpdate
    rollingUpdate:
    maxUnavailable: 1
  extra_args:
    default-ssl-certificate: "ingress-nginx/default-star-ssl"
```
</details>

**Steps to Reproduce:**
Using `rke` upgrade cluster to kubernetes 1.19 or 1.20.

**Results:**
After upgrade pods `calico-kube-controllers-*` and `coredns-autoscaler-*` and `coredns-*` are stuck in ContainerCreating state. In `describe pod` we see that it lack some permissions or bind to wrong role:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "866ee7f18e1cf2ea182517157fec80e73073fe719b32fc8588925adb5802395f" network for pod "calico-kube-controllers-7fbff695b4-4svpn": networkPlugin cni failed to set up pod "calico-kube-controllers-7fbff695b4-4svpn_kube-system" network: error getting ClusterInformation: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "calico-node" not found, failed to clean up sandbox container "866ee7f18e1cf2ea182517157fec80e73073fe719b32fc8588925adb5802395f" network for pod "calico-kube-controllers-7fbff695b4-4svpn": networkPlugin cni failed to teardown pod "calico-kube-controllers-7fbff695b4-4svpn_kube-system" network: error getting ClusterInformation: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "calico-node" not found]
```

<details>
<summary>Log from rke-network-plugin-deploy-job:</summary>

```
kubectl -n kube-system logs job.batch/rke-network-plugin-deploy-job
configmap/canal-config configured
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org configured
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico unchanged
clusterrole.rbac.authorization.k8s.io/flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/canal-flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/canal-calico configured
daemonset.apps/canal configured
serviceaccount/canal unchanged
deployment.apps/calico-kube-controllers configured
serviceaccount/calico-kube-controllers unchanged
```
</summary>
</details>

We found that other people reported similar issue and were able to fix the issue manually with applying RBAC directly from calico: https://forums.rancher.com/t/canal-calico-rbac-issues-with-kubernetes-upgrade-to-v1-19-6-in-rancher-v2-5-5/19367
After downgrade to 1.18.x  coredns and calico-kube-controllers work again.
