### ISSUE TITLE
RKE for windwos10 find wrong docker engine version docker is 1.40 but get docker_engine/v1.24/info

### ISSUE THREAD

**Issue by phxism** [rancher/rke#2554]
I am not very good at rke ,but I use rke for windows to setup a k8s cluster in five centos7 OS.It has some problems
Docker Version in CentOS : Api-Version: 1.40
Error message

> "Failed to set up SSH tunneling for host [192.168.126.131]: Can't retrieve Docker Info: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: Failed to dial ssh using address [192.168.126.131:36925]: dial tcp 192.168.126.131:36925: connectex: No connection could be made because the target machine actively refused it."

there is not ssh issues  between my windows machine and centos visual machines.

Also I have configured firewalld to free 36925 by
```
sudo firewall-cmd --zone=public --add-port=36925/tcp --permanent
sudo firewall-cmd --zone=public --add-port=2375/tcp --permanent
 firewall-cmd --reload
```

I want to know why:
It says that **Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info:** but my docker is 1.40.
How to solve this problem? thanks

**RKE version:**
RKE version: v1.1.6
**Docker version: (`docker version`,`docker info` preferred)**
There are five VMware Centos7 installed same docker
`PS D:\cangda\rke> ssh root@k8s-master1 "curl -i -s --unix-socket /var/run/docker.sock -X GET http://localhost/containers/json"
HTTP/1.1 200 OK
Api-Version: 1.40
Content-Type: application/json
Docker-Experimental: false
Ostype: linux
Server: Docker/19.03.15 (linux)
Date: Tue, 01 Jun 2021 06:48:13 GMT
Content-Length: 3

[]
PS D:\cangda\rke> ssh root@k8s-master1 "docker version"
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:16:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
PS D:\cangda\rke> ssh root@k8s-master1 "docker info"
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc.)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 19.03.15
 Storage Driver: devicemapper
  Pool Name: docker-253:0-144801460-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 3.368GB
  Data Space Total: 107.4GB
  Data Space Available: 27.53GB
  Metadata Space Used: 20.23MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.127GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.170-RHEL7 (2020-03-24)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.25.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.934GiB
 Name: node3
 ID: LR67:NPKA:7C3L:GGVO:UC6I:ETHW:H6XU:CZJV:O35B:NKX5:X4B4:7SJK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.baison.net:9443
  127.0.0.0/8
 Registry Mirrors:
  https://k3e9zvnu.mirror.aliyuncs.com/
  https://docker.mirrors.ustc.edu.cn/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
PS D:\cangda\rke> ssh root@k8s-master2 "docker version|grep 'API'"
 API version:       1.40
  API version:      1.40 (minimum version 1.12)
PS D:\cangda\rke> ssh root@k8s-master3 "docker version|grep 'API'"
 API version:       1.40
  API version:      1.40 (minimum version 1.12)
PS D:\cangda\rke> ssh root@k8s-node1 "docker version|grep 'API'"
 API version:       1.40
  API version:      1.40 (minimum version 1.12)
PS D:\cangda\rke> ssh root@k8s-node2 "docker version|grep 'API'"
 API version:       1.40
  API version:      1.40 (minimum version 1.12)`
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`PS D:\cangda\rke> ssh root@k8s-master1 "uname -r"
3.10.0-1160.25.1.el7.x86_64`
`PS D:\cangda\rke> ssh root@k8s-master1 "cat /etc/os-release"
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"`
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware16
**cluster.yml file:**
```
nodes:
    - address: 192.168.126.131
      user: root
      role:
        - controlplane
        - etcd
        - worker
      port: 36925   
      labels:
        cluster_name: e3plus
        k8s-master: true
      hostname_override: k8s-master1
    
    - address: 192.168.126.132
      user: root
      role:
        - controlplane
        - etcd
        - worker
      port: 36925   
      labels:
        cluster_name: e3plus
        k8s-master: true
      hostname_override: k8s-master2
    
    - address: 192.168.126.133
      user: root
      role:
        - controlplane
        - etcd
        - worker
      port: 36925   
      labels:
        cluster_name: e3plus
        k8s-master: true
      hostname_override: k8s-master3
    
    - address: 192.168.126.129
      user: root
      role:
        - worker
      port: 36925   
      labels:
        cluster_name: e3plus
        node-monitor: true
        node-register: true
        k8s-node: true
      hostname_override: k8s-node1
    
    - address: 192.168.126.130
      user: root
      role:
        - worker
      port: 36925   
      labels:
        cluster_name: e3plus
        node-monitor: true
        node-register: true
        k8s-node: true
      hostname_override: k8s-node2
      ignore_docker_version: false
      ssh_key_path: C:\Users\root\.ssh\id_rsa_nopsw
      #omitted for brevity
```

**Steps to Reproduce:**
1.download rke1.1.6 for windows exe save to folder _D:\cangda\rke_
2.run command in powershell `PS D:\cangda\rke> ./rke_windows-amd64.exe up --config rancher-cluster-win.yml`
**Results:**
`PS D:\cangda\rke> ./rke_windows-amd64.exe up --config rancher-cluster-win.yml
time="2021-06-01T14:49:07+08:00" level=info msg="Running RKE version: v1.1.6"
time="2021-06-01T14:49:07+08:00" level=info msg="Initiating Kubernetes cluster"
time="2021-06-01T14:49:07+08:00" level=info msg="[certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates"
time="2021-06-01T14:49:07+08:00" level=info msg="[certificates] Generating Kubernetes API server certificates"
time="2021-06-01T14:49:07+08:00" level=info msg="[certificates] Generating admin certificates and kubeconfig"
time="2021-06-01T14:49:07+08:00" level=info msg="[certificates] Generating kube-etcd-192-168-126-131 certificate and key"
time="2021-06-01T14:49:07+08:00" level=info msg="[certificates] Generating kube-etcd-192-168-126-132 certificate and key"
time="2021-06-01T14:49:07+08:00" level=info msg="[certificates] Generating kube-etcd-192-168-126-133 certificate and key"
time="2021-06-01T14:49:08+08:00" level=info msg="Successfully Deployed state file at [./rancher-cluster-win.rkestate]"
time="2021-06-01T14:49:08+08:00" level=info msg="Building Kubernetes cluster"
time="2021-06-01T14:49:08+08:00" level=info msg="[dialer] Setup tunnel for host [192.168.126.131]"
time="2021-06-01T14:49:08+08:00" level=info msg="[dialer] Setup tunnel for host [192.168.126.132]"
time="2021-06-01T14:49:08+08:00" level=info msg="[dialer] Setup tunnel for host [192.168.126.129]"
time="2021-06-01T14:49:08+08:00" level=info msg="[dialer] Setup tunnel for host [192.168.126.133]"
time="2021-06-01T14:49:08+08:00" level=info msg="[dialer] Setup tunnel for host [192.168.126.130]"
time="2021-06-01T14:49:10+08:00" level=warning msg="Failed to set up SSH tunneling for host [192.168.126.131]: Can't retrieve Docker Info: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: Failed to dial ssh using address [192.168.126.131:36925]: dial tcp 192.168.126.131:36925: connectex: No connection could be made because the target machine actively refused it."
time="2021-06-01T14:49:10+08:00" level=warning msg="Failed to set up SSH tunneling for host [192.168.126.132]: Can't retrieve Docker Info: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: Failed to dial ssh using address [192.168.126.132:36925]: dial tcp 192.168.126.132:36925: connectex: No connection could be made because the target machine actively refused it."
time="2021-06-01T14:49:10+08:00" level=warning msg="Failed to set up SSH tunneling for host [192.168.126.129]: Can't retrieve Docker Info: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: Failed to dial ssh using address [192.168.126.129:36925]: dial tcp 192.168.126.129:36925: connectex: No connection could be made because the target machine actively refused it."
time="2021-06-01T14:49:10+08:00" level=warning msg="Failed to set up SSH tunneling for host [192.168.126.133]: Can't retrieve Docker Info: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: Failed to dial ssh using address [192.168.126.133:36925]: dial tcp 192.168.126.133:36925: connectex: No connection could be made because the target machine actively refused it."
time="2021-06-01T14:49:10+08:00" level=warning msg="Failed to set up SSH tunneling for host [192.168.126.130]: Can't retrieve Docker Info: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: Failed to dial ssh using address [192.168.126.130:36925]: dial tcp 192.168.126.130:36925: connectex: No connection could be made because the target machine actively refused it."
time="2021-06-01T14:49:10+08:00" level=warning msg="Removing host [192.168.126.131] from node lists"
time="2021-06-01T14:49:10+08:00" level=warning msg="Removing host [192.168.126.132] from node lists"
time="2021-06-01T14:49:10+08:00" level=warning msg="Removing host [192.168.126.129] from node lists"
time="2021-06-01T14:49:10+08:00" level=warning msg="Removing host [192.168.126.133] from node lists"
time="2021-06-01T14:49:10+08:00" level=warning msg="Removing host [192.168.126.130] from node lists"
time="2021-06-01T14:49:10+08:00" level=fatal msg="Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.126.131]"
PS D:\cangda\rke>`
