### ISSUE TITLE
passing featuregates attributes to the scheduler?

### ISSUE THREAD

**Issue by nseyvet** [rancher/rke#259]
**RKE version:**
rke version v0.0.9-dev

**Docker version: (`docker version`,`docker info` preferred)**
not relevant
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
not relevant
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**

```
---
authentication:
  strategy: x509
  options: {}

authorization:
  mode: rbac
  options: {}

network:
  plugin: flannel
  options: {}  

nodes:
  - machine_name: ec2-54
    address: 50.0.30.254
    user: ubuntu
    role: [etcd,controlplane,worker]
    flannel_iface: ens3 
  - machine_name: ec2-34
    address: 50.0.30.24
    user: ubuntu
    role: [etcd,controlplane,worker]
    flannel_iface: ens3 
  - machine_name: ec2-34
    address: 50.0.30.124
    user: ubuntu
    role: [etcd,controlplane,worker]
    flannel_iface: ens3 
  - machine_name: ec2-34
    address: 50.0.30.45
    user: ubuntu
    role: [etcd,worker]
    flannel_iface: ens3 
  - machine_name: ec2-52
    address: 50.0.30.219
    user: ubuntu
    role: [etcd,worker]
    flannel_iface: ens3 

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.9.1-rancher1-1
    service_cluster_ip_range: 10.233.0.0/18
  kube-controller:
    image: rancher/k8s:v1.9.1-rancher1-1
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.9.1-rancher1-1
    extra_args:
      feature-gates: PersistentLocalVolumes=true
  kubelet:
    image: rancher/k8s:v1.9.1-rancher1-1
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args:
      fail-swap-on: FALSE
 #     cgroup-driver: systemd
  kubeproxy:
    image: rancher/k8s:v1.9.1-rancher1-1
```

**Steps to Reproduce:**
Use above cluster.yml.

**Results:**
Kubernetes scheduler container fails to start with error:

```
docker logs -f scheduler
 '[' kube-scheduler == kubelet ']'
+ exec kube-scheduler --leader-elect=true --v=2 --address=0.0.0.0 --kubeconfig=/etc/kubernetes/ssl/kubecfg-scheduler.yaml --feature-gates=PersistentLocalVolumes=true
Error: unknown flag: --feature-gates
Usage:
  kube-scheduler [flags]

Flags:
      --address string                         The IP address to serve on (set to 0.0.0.0 for all interfaces)
      --algorithm-provider string              The scheduling algorithm provider to use, one of: ClusterAutoscalerProvider | DefaultProvider
      --alsologtostderr                        log to standard error as well as files
      --config string                          The path to the configuration file.
      --contention-profiling                   Enable lock contention profiling, if profiling is enabled
      --feature-gates mapStringBool            A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
APIListChunking=true|false (BETA - default=true)
APIResponseCompression=true|false (ALPHA - default=false)
Accelerators=true|false (ALPHA - default=false)
AdvancedAuditing=true|false (BETA - default=true)
AllAlpha=true|false (ALPHA - default=false)
AllowExtTrafficLocalEndpoints=true|false (default=true)
AppArmor=true|false (BETA - default=true)
BlockVolume=true|false (ALPHA - default=false)
CPUManager=true|false (ALPHA - default=false)
CSIPersistentVolume=true|false (ALPHA - default=false)
CustomPodDNS=true|false (ALPHA - default=false)
CustomResourceValidation=true|false (BETA - default=true)
DebugContainers=true|false (ALPHA - default=false)
DevicePlugins=true|false (ALPHA - default=false)
DynamicKubeletConfig=true|false (ALPHA - default=false)
EnableEquivalenceClassCache=true|false (ALPHA - default=false)
ExpandPersistentVolumes=true|false (ALPHA - default=false)
ExperimentalCriticalPodAnnotation=true|false (ALPHA - default=false)
ExperimentalHostUserNamespaceDefaulting=true|false (BETA - default=false)
HugePages=true|false (ALPHA - default=false)
Initializers=true|false (ALPHA - default=false)
KubeletConfigFile=true|false (ALPHA - default=false)
LocalStorageCapacityIsolation=true|false (ALPHA - default=false)
MountContainers=true|false (ALPHA - default=false)
MountPropagation=true|false (ALPHA - default=false)
PVCProtection=true|false (ALPHA - default=false)
PersistentLocalVolumes=true|false (ALPHA - default=false)
PodPriority=true|false (ALPHA - default=false)
ResourceLimitsPriorityFunction=true|false (ALPHA - default=false)
RotateKubeletClientCertificate=true|false (BETA - default=true)
RotateKubeletServerCertificate=true|false (ALPHA - default=false)
ServiceNodeExclusion=true|false (ALPHA - default=false)
StreamingProxyRedirects=true|false (BETA - default=true)
SupportIPVSProxyMode=true|false (BETA - default=false)
TaintBasedEvictions=true|false (ALPHA - default=false)
TaintNodesByCondition=true|false (ALPHA - default=false)
VolumeScheduling=true|false (ALPHA - default=false)
      --kube-api-burst int32                   Burst to use while talking with kubernetes apiserver (default 100)
      --kube-api-content-type string           Content type of requests sent to apiserver. (default "application/vnd.kubernetes.protobuf")
      --kube-api-qps float32                   QPS to use while talking with kubernetes apiserver (default 50)
      --kubeconfig string                      Path to kubeconfig file with authorization and master location information.
      --leader-elect                           Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
      --leader-elect-lease-duration duration   The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate. This is only applicable if leader election is enabled. (default 15s)
      --leader-elect-renew-deadline duration   The interval between attempts by the acting master to renew a leadership slot before it stops leading. This must be less than or equal to the lease duration. This is only applicable if leader election is enabled. (default 10s)
      --leader-elect-resource-lock endpoints   The type of resource object that is used for locking during leader election. Supported options are endpoints (default) and `configmaps`. (default "endpoints")
      --leader-elect-retry-period duration     The duration the clients should wait between attempting acquisition and renewal of a leadership. This is only applicable if leader election is enabled. (default 2s)
      --lock-object-name string                Define the name of the lock object. (default "kube-scheduler")
      --lock-object-namespace string           Define the namespace of the lock object. (default "kube-system")
      --log-backtrace-at traceLocation         when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                         If non-empty, write log files in this directory
      --log-flush-frequency duration           Maximum number of seconds between log flushes (default 5s)
      --logtostderr                            log to standard error instead of files (default true)
      --master string                          The address of the Kubernetes API server (overrides any value in kubeconfig)
      --policy-config-file string              File with scheduler policy configuration. This file is used if policy ConfigMap is not provided or --use-legacy-policy-config==true
      --policy-configmap string                Name of the ConfigMap object that contains scheduler's policy configuration. It must exist in the system namespace before scheduler initialization if --use-legacy-policy-config==false. The config must be provided as the value of an element in 'Data' map with the key='policy.cfg'
      --policy-configmap-namespace string      The namespace where policy ConfigMap is located. The system namespace will be used if this is not provided or is empty.
      --port int32                             The port that the scheduler's http service runs on (default 10251)
      --profiling                              Enable profiling via web interface host:port/debug/pprof/
      --scheduler-name string                  Name of the scheduler, used to select which pods will be processed by this scheduler, based on pod's "spec.SchedulerName". (default "default-scheduler")
      --stderrthreshold severity               logs at or above this threshold go to stderr (default 2)
      --use-legacy-policy-config               When set to true, scheduler will ignore policy ConfigMap and uses policy config file
  -v, --v Level                                log level for V logs (default 0)
      --version version[=true]                 Print version information and quit
      --vmodule moduleSpec                     comma-separated list of pattern=N settings for file-filtered logging
```

The scheduler expects an attribute in the following format: `--flag "string=bool"` 

How to do that from the cluster.yml?

**Comment by nseyvet** [comment]
OK. made a typo. The following works:

 ```
 scheduler:
    image: rancher/k8s:v1.9.1-rancher1-1
    extra_args:
      feature-gates: "PersistentLocalVolumes=true"
```
