### ISSUE TITLE
Rancher gui becomes unreacheable after rke up cluster upgrade

### ISSUE THREAD

**Issue by mleone87** [rancher/rke#2592]
**RKE version:**
v1.2.9

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed89195c
 Built:             Sun Feb 14 12:00:00 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed89195c
  Built:            Sun Feb 14 12:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit: 
```

```
Client:
 Debug Mode: false

Server:
 Containers: 57
  Running: 49
  Paused: 0
  Stopped: 8
 Images: 32
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.18-24.52-default
 Operating System: SUSE Linux Enterprise Server 15 SP2
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.45GiB
 Name: ip-10-202-64-63
 ID: CAOI:TZWD:OWZ3:IOYT:25NX:ORR7:XFPC:7N4U:4S3X:SOTZ:5KBF:SYBS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS EC2 instances

**cluster.yml file:**

```
nodes:
- address: node01
  port: "22"
  internal_address: *.*.*.*
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: node01
  user: ec2-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: **REDACTED**
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: node02
  port: "22"
  internal_address: *.*.*.*
  role:
  - worker
  - etcd
  - controlplane
  hostname_override: node02
  user: ec2-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: **REDACTED**
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: node03
  port: "22"
  internal_address: **REDACTED**
  role:
  - worker
  - etcd
  - controlplane
  hostname_override: node03
  user: ec2-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: **REDACTED**
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: shared-prd.pirelli.internal
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
ssh_key_path: **REDACTED**
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
kubernetes_version: "v1.19.12-rancher1-1"
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
cluster_name: **REDACTED**
cloud_provider:
  name: aws
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null
```

**Steps to Reproduce:**

1. download lateste rke binary
2. upgrade the cluster to lastest version supported by the rke bin and add cloud_provirde support
3. rancher guy stops working

**Results:**

![image](https://user-images.githubusercontent.com/807457/123670172-36dd2780-d83d-11eb-9566-d03dec545200.png)
