### ISSUE TITLE
Unable to mount folder to kubelet | extra_binds isn't working with RKE 1.2.9 

### ISSUE THREAD

**Issue by valexz** [rancher/rke#2604]
Any solutions or  compatible working versions ?
Same problem with other paths.

**RKE Version:**
```1.2.9```

**Docker version:**
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 21 Feb 2021 18:18:35 +0100
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Feb 21 17:18:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Operating system and kernel: **
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian/
```
```
kernel: 4.19.0-17-amd64
```

**Type/provider of hosts: **
Bare-metal

**cluster.yml file:**
```yaml
nodes:
   - address: ubi-k8s
     user: rancher
     role:
       - controlplane
       - etcd
       - worker
     ssh_key_path: /rancher/.ssh/id_rsa
     port: 2626
## If set to true, RKE will not fail when unsupported Docker version
# are found
ignore_docker_version: true


# In case the kubernetes_version and kubernetes image in
# system_images are defined, the system_images configuration
# will take precedence over kubernetes_version.
kubernetes_version: v1.20.8-rancher1-1

services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: "*"
        secret_key: "*"
        bucket_name: "*" 
        region: "*"
        #folder: "" # Optional - Available as of v0.3.0
        endpoint: "*"
        #snapshot: true
        #creation: "6h"
        #retention: "24h"
    kube-api:
      # IP range for any services created on Kubernetes
      # This must match the service_cluster_ip_range in kube-controller
      service_cluster_ip_range: 172.20.0.0/16
      # Expose a different port range for NodePort services
      service_node_port_range: 30000-32767    
      pod_security_policy: false
      # Add additional arguments to the kubernetes API server
      # This WILL OVERRIDE any existing defaults
    kube-controller:
      # CIDR pool used to assign IP addresses to pods in the cluster
      cluster_cidr: 10.20.0.0/16
      # IP range for any services created on Kubernetes
      # This must match the service_cluster_ip_range in kube-api
      service_cluster_ip_range: 172.20.0.0/16
    kubelet:
      extra_binds:
        - "/var/openebs/local:/var/openebs/local"
      # Base domain for the cluster
      cluster_domain: cluster.local
      # IP address for the DNS service endpoint
      cluster_dns_server: 172.20.0.10
      # Fail if swap is on
      fail_swap_on: false

authorization:
    mode: rbac
monitoring:
    provider: none


# Add-ons are deployed using kubernetes jobs. RKE will give
# up on trying to get the job status after this timeout in seconds..
addon_job_timeout: 60

# There are several network plug-ins that work, but we default
# to canal      
network:
    plugin: canal

# Specify DNS provider (coredns or kube-dns)
dns:
    provider: coredns

# Currently only nginx ingress provider is supported.
# To disable ingress controller, set `provider: none`
# `node_selector` controls ingress placement and is optional
ingress:
    provider: nginx
    options:
      http2-max-field-size: "8k" # Fix possible issue with big cert
      http2-max-header-size: "32k" #
    extra_args:
      enable-ssl-chain-completion: "false"
```

**Steps to Reproduce:**
Add  - "/var/openebs/local:/var/openebs/local" path to  ```extra_binds``` section of kubelet config part to ```config.yml``
run ```rke up```

**Results:**
docker inspect kubelet | grep openebs - shows nothing

**Comment by superseb** [comment]
I just tested using 1.2.9 and the following config:

```
services:
    kubelet:
      extra_binds:
        - "/var/openebs/local:/var/openebs/local"
```

And I see the bind added. I can only guess an indentation or formatting issue but for that I need the actual file that you are using. I assume as the bind is not added, its also not in the `cluster.rkestate` that is generated.
