### ISSUE TITLE
`rke etcd snapshot-recovery` fails when use with `--use-local-state` and state file is in hidden dir 

### ISSUE THREAD

**Issue by rlisewski** [rancher/rke#2605]
**RKE version:**
1.2.6
**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client: Docker Engine - Community
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3cb89e
 Built:             Thu Feb 25 07:05:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Thu Feb 25 07:03:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 19
  Running: 10
  Paused: 0
  Stopped: 9
 Images: 63
 Server Version: 20.10.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: master-3
 ID: ZN4Y:TJDS:KLFN:LLMK:S4WM:E6XM:6IG7:X6EF:ATON:UVEJ:FFYE:TVYK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
```
# uname -r
5.4.0-77-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack
**cluster.yml file:**
```
nodes:

  
   - address: <IP>
     user: ubuntu
     role: ["controlplane", "etcd"]
  
   - address: <IP>
     user: ubuntu
     role: ["controlplane", "etcd"]
  
   - address: <IP>
     user: ubuntu
     role: ["controlplane", "etcd"]
  

  
   - address: <IP>
     user: ubuntu
     role: ["worker"]
  
   - address: <IP>
     user: ubuntu
     role: ["worker"]
  
   - address: <IP>
     user: ubuntu
     role: ["worker"]
  

ssh_key_path: .clusters/<cluster_name>/conf/identity
ssh_agent_auth: false
ignore_docker_version: true
cluster_name: cluster_name.kubecluster
kubernetes_version: v1.20.4-rancher1-1

services:
  kube-api:
    service_cluster_ip_range: 10.255.64.0/20
  kube-controller:
    cluster_cidr: 10.255.80.0/20
    service_cluster_ip_range: 10.255.64.0/20
  kubelet:
    cluster_domain: domain.com
    cluster_dns_server: 10.255.64.10
    extra_args:
      read-only-port: 10255

  etcd:
    extra_args:
      heartbeat-interval: 1000
      election-timeout: 5000
      snapshot-count: 5000

network:
  plugin: canal

authentication:
  stretegy: x509 # currently only x509 is supported by rke
  sans:
  - "*.<domain>"

authorization:
  mode: rbac

ingress:
  provider: nginx


```
**Steps to Reproduce:**
1. Deploy cluster and move `rke.rkestate` to hidden directory
2. Create etcd backup
3. Restore backup with `--use-local-state` pointing to rke state file in hidden directory
**Results:**
```
rke etcd snapshot-restore --config ./clusters/cluster_name/conf/rke.yml --name 2021-07-13T11:23:21Z_etcd --use-local-state .clusters/cluster_name/conf/rke.rkestate 
INFO[0000] Running RKE version: v1.2.6                  
INFO[0000] Not checking if state file is included in snapshot file for [2021-07-13T11:23:21Z_etcd], using local state file [clusters/cluster_name/conf/rke.rkestate] 
FATA[0000] Can not find RKE state file: open <path_to>/clusters/cluster_name/conf/rke.rkestate: no such file or directory 

```
*[clusters/cluster-name/conf/rke.rkestate]* has no dot.
