### ISSUE TITLE
 Failed to start [cert-fetcher] container on host 

### ISSUE THREAD

**Issue by zhanhaibin** [rancher/rke#263]
**RKE version:**
rke version v0.0.12-dev
**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.0-105-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: master
ID: HIAT:GR3E:OPCM:CKUZ:OICO:NSQF:4K7G:74NC:GZVV:G5J6:4UF7:V6TJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://0sskao0e.mirror.aliyuncs.com
Live Restore Enabled: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

uname -r
4.4.0-105-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aliyun
**cluster.yml file:**
```
root@master:/srv/rke# cat clustersignle.yml
---
auth:
  strategy: x509
  options:
    foo: bar

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS or GCE, use the network plugin config option:
# 'calico_cloud_provider: aws'
# or
# 'calico_cloud_provider: gce'
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

ssh_key_path: /root/.ssh/id_rsa
enforce_docker_version: false
# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization
authorization:
  mode: rbac
  options:

nodes:
  - address: 47.104.162.134
    user: root
    role: [controlplane,worker, etcd]
    ssh_key_path: /root/.ssh/id_rsa

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {"fail-swap-on":"false"}
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2


system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  service_sidekick_image: rancher/rke-service-sidekick:v0.1.0
  kubedns_image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0

```
**Steps to Reproduce:**
./rke_linux-amd64 up --config clustersignle.yml
**Results:**

INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [47.104.162.134]
INFO[0003] [certificates] Attempting to recover certificates from backup on host [47.104.162.134]
INFO[0003] [certificates] Checking image [alpine:latest] on host [47.104.162.134]
INFO[0003] [certificates] No pull necessary, image [alpine:latest] exists on host [47.104.162.134]
INFO[0003] [certificates] Successfully started [cert-fetcher] container on host [47.104.162.134]
INFO[0006] [certificates] Certificate backup found on host [47.104.162.134]
INFO[0006] [reconcile] Reconciling cluster state
INFO[0006] [reconcile] This is newly generated cluster
INFO[0006] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0006] [certificates] Checking image [rancher/rke-cert-deployer:v0.1.1] on host [47.104.162.134]
INFO[0006] [certificates] No pull necessary, image [rancher/rke-cert-deployer:v0.1.1] exists on host [47.104.162.134]
INFO[0011] [certificates] Checking image [rancher/rke-cert-deployer:v0.1.1] on host [47.104.162.134]
INFO[0011] [certificates] No pull necessary, image [rancher/rke-cert-deployer:v0.1.1] exists on host [47.104.162.134]
INFO[0016] Successfully Deployed local admin kubeconfig at [./.kube_config_clustersignle.yml]
INFO[0016] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0016] [etcd] Building up Etcd Plane..
INFO[0016] [etcd] Checking image [quay.io/coreos/etcd:latest] on host [47.104.162.134]
INFO[0016] [etcd] No pull necessary, image [quay.io/coreos/etcd:latest] exists on host [47.104.162.134]
INFO[0016] [etcd] Successfully started [etcd] container on host [47.104.162.134]
INFO[0016] [etcd] Successfully started Etcd Plane..
INFO[0016] [controlplane] Building up Controller Plane..
INFO[0016] [remove/nginx-proxy] Checking if container is running on host [47.104.162.134]
INFO[0016] [remove/nginx-proxy] Container doesn't exist on host [47.104.162.134]
INFO[0016] [sidekick] Checking image [rancher/rke-service-sidekick:v0.1.0] on host [47.104.162.134]
INFO[0016] [sidekick] No pull necessary, image [rancher/rke-service-sidekick:v0.1.0] exists on host [47.104.162.134]
INFO[0016] [controlplane] Checking image [rancher/k8s:v1.8.3-rancher2] on host [47.104.162.134]
INFO[0016] [controlplane] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [47.104.162.134]
INFO[0017] [controlplane] Successfully started [kube-api] container on host [47.104.162.134]
INFO[0017] [healthcheck] Start Healthcheck on service [kube-api] on host [47.104.162.134]
INFO[0027] [healthcheck] service [kube-api] on host [47.104.162.134] is healthy
INFO[0027] [controlplane] Checking image [rancher/k8s:v1.8.3-rancher2] on host [47.104.162.134]
INFO[0027] [controlplane] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [47.104.162.134]
INFO[0027] [controlplane] Successfully started [kube-controller] container on host [47.104.162.134]
INFO[0027] [healthcheck] Start Healthcheck on service [kube-controller] on host [47.104.162.134]
INFO[0033] [healthcheck] service [kube-controller] on host [47.104.162.134] is healthy
INFO[0033] [controlplane] Checking image [rancher/k8s:v1.8.3-rancher2] on host [47.104.162.134]
INFO[0033] [controlplane] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [47.104.162.134]
INFO[0033] [controlplane] Successfully started [scheduler] container on host [47.104.162.134]
INFO[0033] [healthcheck] Start Healthcheck on service [scheduler] on host [47.104.162.134]
INFO[0038] [healthcheck] service [scheduler] on host [47.104.162.134] is healthy
INFO[0038] [controlplane] Successfully started Controller Plane..
INFO[0038] [authz] Creating rke-job-deployer ServiceAccount
INFO[0038] [authz] rke-job-deployer ServiceAccount created successfully
INFO[0038] [authz] Creating system:node ClusterRoleBinding
INFO[0038] [authz] system:node ClusterRoleBinding created successfully
INFO[0038] [certificates] Save kubernetes certificates as secrets
INFO[0062] [certificates] Successfully saved certificates as kubernetes secret [k8s-certs]
INFO[0062] [state] Saving cluster state to Kubernetes
INFO[0062] [state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state
INFO[0062] [worker] Building up Worker Plane..
INFO[0062] [sidekick] Sidekick container already created on host [47.104.162.134]
INFO[0062] [worker] Checking image [rancher/k8s:v1.8.3-rancher2] on host [47.104.162.134]
INFO[0062] [worker] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [47.104.162.134]
INFO[0062] [worker] Successfully started [kubelet] container on host [47.104.162.134]
INFO[0062] [healthcheck] Start Healthcheck on service [kubelet] on host [47.104.162.134]
INFO[0068] [healthcheck] service [kubelet] on host [47.104.162.134] is healthy
INFO[0068] [worker] Checking image [rancher/k8s:v1.8.3-rancher2] on host [47.104.162.134]
INFO[0068] [worker] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [47.104.162.134]
FATA[0068] [workerPlane] Failed to bring up Worker Plane: Failed to start [kube-proxy] container on host [47.104.162.134]: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:245: running exec setns process for init caused \\\"exit status 16\\\"\"\n"
