### ISSUE TITLE
Where does the cluster get DNS settings from on the host?

### ISSUE THREAD

**Issue by ajcollett** [rancher/rke#2641]
**RKE version:**
Latest for Rancher standalone docker container. 
Kubernetes: v1.20.9

**Docker version: (`docker version`,`docker info` preferred)**
```shell
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```shell
Client:
 Debug Mode: false

Server:
 Containers: 39
  Running: 27
  Paused: 0
  Stopped: 12
 Images: 17
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-80-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.42GiB
 Name: <snip>
 ID: D3ZD:U2FF:ZWFP:TJQS:FTEX:MXEM:XNHM:R42K:6FSL:TTZF:ONQR:MSWO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://<snip>/
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```
```
5.4.0-80-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**cluster.yml file:**
```yaml
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: cs2
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy: {}
    options: null
    reversecidrs: null
    stubdomains: null
    tolerations: null
    update_strategy: {}
    upstreamnameservers: null
  ignore_docker_version: true
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    provider: nginx
  kubernetes_version: v1.20.9-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  restore:
    restore: false
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
```

**Steps to Reproduce:**
I have setup a few different clusters to try and work out this issue. 

The main problem is that I need to reduce the number of DNS name servers, and the search string domains so as to get rid of the annoying log entries. 

I have replaced `/etc/resolv.conf` with a static file, and setup a new cluster after cleaning up the node, but the DNS config with-in the cluster still manages to get all the DNS name servers and search entries, as if it's talking to systemd-resolved. But, I am using CoreDNS, which the docs say should use `/etc/resolv.conf`. 

https://rancher.com/docs/rancher/v2.5/en/troubleshooting/dns/#check-upstream-nameservers-in-resolv-conf

That seems strange to me anyway, since on Ubuntu 20.04 the `/etc/resolv.conf` file is a stub, and doesn't have the correct DNS entries in it anyway. So it seems the cluster is pulling in the `/run/systemd/resolve/resolv.conf` file instead. Or getting the DNS settings some other way?

Sooooo, how do I get my cluster to stop using the network provided DNS and search entries? 

I have tried changing the docker DNS and dns-search daemon config, and the CoreDNS config to set the DNS. Nothing seems to override the network provided items. 

Do I need to fix this via systemd-resolved? Which seems to have no option to ignore interface DHCP provided DNS options. As I have many nodes, with varying hardware, it'll be tricky to setup networkd with DHCP off and static IP's / DNS.   

**Results:**
The annoying log entries. These end up hiding the actual issues and log entries I'd want to see. 

```shall
cattle-system | Warning | DNSConfigForming | cattle-node-agent-mrdv4 | Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: <snip> <snip> <snip> | a few seconds ago
-- | -- | -- | -- | -- | --
cattle-system | Warning | DNSConfigForming | cattle-cluster-agent-7b54ccfd5b-26l99 | Search Line limits were exceeded, some search paths have been omitted, the applied search line is: cattle-system.svc.cluster.local svc.cluster.local cluster.local <snip> <snip> <snip> | a few seconds ago
```

**Comment by superseb** [comment]
If it's not manually configured to the kubelet, it is determined by if systemd-resolved is running, if so, the actual `resolv.conf` is used. (see https://github.com/rancher/rke-tools/blob/master/entrypoint.sh#L55)

So depending on your machine requirements (if you need systemd-resolved or not), you need to fix it in systemd-resolved or disable it and the detection will just use `/etc/resolv.conf` from the host. Or manually pass a file via `--resolv-conf` to the kubelet.

**Comment by ajcollett** [comment]
@superseb Thanks for the info. So I guess there is something I don't understand about the setup, but that's not surprising, it's pretty complex. 

I run these K8s clusters via Rancher, so I usually just run the docker commands to get things up and running. Can you advise if there are flags I can pass the docker container to pass the `--resolv-conf` flag?

I might look into disabling resolved, but it seems there might be un-intended side effects of doing that.

**Comment by superseb** [comment]
You can override it using `extra_args` to the kubelet as described on https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/

**Comment by ajcollett** [comment]
@superseb Thank you for all your help here. 

This is the extra config I added to the rancher cluster yaml file:
```
    kubelet:
      extra_args:
        resolv-conf: /etc/resolv-kuber.conf
      extra_binds:
        - '/etc/resolv-kuber.conf:/etc/resolv-kuber.conf'
  ```

I'll refine that to something more sensible, but for a test, it worked great. 

Thanks again!
