### ISSUE TITLE
nginx-ingress of rke generated cluster not supporting the PROXY protocol

### ISSUE THREAD

**Issue by kagehisa** [rancher/rke#2666]
I'm following this [tutorial](https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/behind-proxy/prepare-nodes/) to setup a (for now) single node cluster for hosting Rancher. Since I wan't to upgrade to multi node setup at a later step I prepared a layer 4 load balancer as it is described [here](https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/infrastructure-tutorials/nginx/). The cluster generation with rke works and a curl request to the cluster node results in a 404 response from the default backend. 
If I direct the curl request to the load balancer I get a nginx 400 Bad Request error. After disabling the proxy protocol in the load balancer an curl request to the load balancer results in the desired 404 from the default backend. 
Is the nginx-ingress built without proxy support? Or is there a way through a rke config option to turn the proxy support on?

**RKE version:**
`v1.2.11`
**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:           20.10.6-ce
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        8728dd246c3a
 Built:             Thu Apr 15 12:00:00 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd246c3a
  Built:            Thu Apr 15 12:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit:
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release:
```
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

uname -r:
```
5.3.18-59.19-default
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
```
nodes:
  - address: l3vsrv103.pers.domain.de
    user: cowherder
    role:
      - controlplane
      - worker
      - etcd

services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6

# Cluster level SSH private key
# Used if no ssh information is set for the node
ssh_key_path: /home/cowherder/.ssh/rancher_admin_id_rsa

# Set the name of the Kubernetes cluster
cluster_name: adm_cluster

prefix_path: /opt/rke

ignore_docker_version: false

system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.15-rancher1
  alpine: rancher/rke-tools:v0.1.77
  nginx_proxy: rancher/rke-tools:v0.1.77
  cert_downloader: rancher/rke-tools:v0.1.77
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.77
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.15.10
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.15.10
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.15.10
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  coredns: rancher/mirrored-coredns-coredns:1.8.0
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.15.13
  kubernetes: rancher/hyperkube:v1.20.9-rancher1
  flannel: rancher/coreos-flannel:v0.13.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.17.2
  calico_cni: rancher/mirrored-calico-cni:v3.17.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.17.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  canal_node: rancher/mirrored-calico-node:v3.17.2
  canal_cni: rancher/mirrored-calico-cni:v3.17.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  canal_flannel: rancher/coreos-flannel:v0.13.0-rancher1
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.2
  ingress: rancher/nginx-ingress-controller:nginx-0.43.0-rancher3
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/mirrored-metrics-server:v0.4.1
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
```
**Steps to Reproduce:**
- Generate Cluster with the above cluster configuration file
- set up load balancer according to [rancher setup tutorial](https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/infrastructure-tutorials/nginx/)
- curl address of loadbalancer
- curl adress of single node cluster
- set `proxy_protocol off` in nginx.conf of load balancer
- reload nginx service on load balancer
- curl address of loadbalancer

**Results:**
- curl of the load balancer results in a `400 Bad Request`
- curl of the single node cluster results in  `default backend - 404`
- curl of the load balancer after disabling proxy_ptotocol results in  `default backend - 404`
