### ISSUE TITLE
unknown field "data" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta when using ingress.provider: nginx

### ISSUE THREAD

**Issue by izaac** [rancher/rke#2673]
**RKE version:**

`v1.3.0-rc17`

**Docker version:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 32
  Running: 12
  Paused: 0
  Stopped: 20
 Images: 14
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1038-aws
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.797GiB
 Name: ip-172-31-1-200
 ID: IVAS:2KOO:VFGG:PIMK:VVXO:6YPA:NJW2:SPXF:AXZI:OZTQ:5GT3:PYGU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`5.8.0-1038-aws`

```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Type/provider of hosts: AWS**

**cluster.yml file:**

```
ngress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
nodes:
  - address: <EXTERNAL>
    internal_address: <PRIVATE>
    user: ubuntu
    role: [etcd, controlplane,worker]
    hostname_override: izext1
  - address: <EXTERNAL>
    internal_address: <PRIVATE>
    user: ubuntu
    hostname_override: izext2
    role: [etcd, controlplane,worker]
  - address: <EXTERNAL>
    internal_address: <PRIVATE>
    user: ubuntu
    hostname_override: izext3
    role: [etcd, controlplane,worker]
services:
  etcd:
    backup_config:
      timeout: 30
      interval_hours: 1
      retention: 6
      safe_timestamp: true
      enabled: true
    snapshot: true
    creation: 1h
    retention: 24h
```

**Steps to Reproduce:**

Use the above cluster yaml and `rke --trace up --ssh-agent-auth`

**Results:**

```
INFO[0137] [addons] Executing deploy job rke-ingress-controller
DEBU[0137] Checking node list for node [izext1], try #1
TRAC[0137] template for [rke-ingress-controller] is: [
apiVersion: batch/v1
kind: Job
metadata:
  name: rke-ingress-controller-deploy-job
  namespace: kube-system
spec:
  backoffLimit: 10
  template:
    metadata:
       name: rke-deploy
    spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
        tolerations:
        - operator: Exists
        hostNetwork: true
        serviceAccountName: rke-job-deployer
        nodeName: izext1
        containers:
          - name: rke-ingress-controller-pod
            image: rancher/hyperkube:v1.21.4-rancher1
            command: [ "kubectl", "apply", "-f" , "/etc/config/rke-ingress-controller.yaml"]
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
        volumes:
          - name: config-volume
            configMap:
              # Provide the name of the ConfigMap containing the files you want
              # to add to the container
              name: rke-ingress-controller
              items:
                - key: rke-ingress-controller
                  path: rke-ingress-controller.yaml
        restartPolicy: Never]
DEBU[0137] [k8s] waiting for job rke-ingress-controller-deploy-job to complete..
FATA[0183] Failed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system

cat kube_config_cluster.yml > ~/.kube/config
kubectl get po -n kube-system

NAME                                       READY   STATUS      RESTARTS   AGE
calico-kube-controllers-6c977d77bc-tv8kb   1/1     Running     0          80s
canal-47sjq                                2/2     Running     0          80s
canal-bmppr                                2/2     Running     0          80s
canal-wk69j                                2/2     Running     0          80s
coredns-685d6d555d-94cgm                   1/1     Running     0          69s
coredns-685d6d555d-ct89v                   1/1     Running     0          71s
coredns-autoscaler-57fd5c9bd5-rwzgh        1/1     Running     0          71s
metrics-server-7bf4b68b78-q8wt5            1/1     Running     0          65s
rke-coredns-addon-deploy-job-t2smt         0/1     Completed   0          73s
rke-ingress-controller-deploy-job-4rr5z    0/1     Error       0          30s
rke-ingress-controller-deploy-job-9v9kq    0/1     Error       0          60s
rke-ingress-controller-deploy-job-nj9tn    0/1     Error       0          62s
rke-ingress-controller-deploy-job-swq94    0/1     Error       0          50s
rke-metrics-addon-deploy-job-5jz6g         0/1     Completed   0          68s
rke-network-plugin-deploy-job-8cmb9        0/1     Completed   0          84s


kubectl logs -n kube-system rke-ingress-controller-deploy-job-4rr5z

namespace/ingress-nginx unchanged
serviceaccount/nginx-ingress-serviceaccount unchanged
error: error validating "/etc/config/rke-ingress-controller.yaml": error validating data: ValidationError(ConfigMap.metadata): unknown field "data" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false
```
