### ISSUE TITLE
Disable NAT for flannel when backend_type is host-gw

### ISSUE THREAD

**Issue by vitalvas** [rancher/rke#2680]
**RKE version:**
v1.2.11

**Docker version: (`docker version`,`docker info` preferred)**
v20.10

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Is your feature request related to a problem? Please describe.**
There is a technical need to disable NAT in flannel when using it with host-gw.

**Describe the solution you'd like**
Disable via options in network settings. Example:
```
network:
  plugin: flannel
  options:
    flannel_backend_type: host-gw
    flannel_ipmasq: false
```
