### ISSUE TITLE
Nginx Ingress ocasionally coredumps

### ISSUE THREAD

**Issue by carloscarnero** [rancher/rke#2684]
With RKE version 1.3.0 I have upgraded four similar air-gapped clusters to Kubernetes 1.21.4 (up from 1.20.9.) The upgrade process went without any problems, but on one cluster (and only one) the nodes designated to the ingress controllers filled their disks in a rather quick fashion. The only practical difference of this cluster in relation to the others is that it has close to 120 Ingress objects.

The disks were filled because Nginx workers were dumping core as fast as they could. I observed exactly what's in kubernetes/ingress-nginx#6896 and kubernetes/ingress-nginx#7080, even though the version of the ingress controller is not the same.

I managed to (probably) fix the situation by scaling down Nginx's `DaemonSet` (using a dummy node selector), manually deleting the pods (which freed up disk space), and scaling back up the `DaemonSet`.

**RKE version:**

```console
$ rke --version
rke version v1.3.0
```

**Docker version: (`docker version`,`docker info` preferred)**

```console
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 33
  Running: 26
  Paused: 0
  Stopped: 7
 Images: 13
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.36.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 23.53GiB
 Name: d39e4c46.docker.example.com
 ID: 2NXM:ZKM4:G7PG:GZCY:NJXT:7IPU:6FVG:2IJP:BDSA:Z34N:2NFE:EQVM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -r
3.10.0-1160.36.2.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal (actually, manually created virtual machines under VMware with no automation of any kind.)

**cluster.yml file:**

```YAML
---
cluster_name: e0ac090c
kubernetes_version: v1.21.4-rancher1-1
nodes:
- address: 75290b87.docker.example.com
  user: dockeruser
  role:
  - controlplane
  - etcd
- address: 103da3b0.docker.example.com
  user: dockeruser
  role:
  - controlplane
  - etcd
- address: 7ff100c9.docker.example.com
  user: dockeruser
  role:
  - controlplane
  - etcd
- address: 73604fef.docker.example.com
  user: dockeruser
  role:
  - worker
  labels:
    example.com/node.ingress: true
- address: 9fe34fb3.docker.example.com
  user: dockeruser
  role:
  - worker
  labels:
    example.com/node.ingress: true
- address: d39e4c46.docker.example.com
  user: dockeruser
  role:
  - worker
  labels:
    example.com/node.ingress: true
- address: a3380fe2.docker.example.com
  user: dockeruser
  role:
  - worker
- address: a4828be3.docker.example.com
  user: dockeruser
  role:
  - worker
network:
  plugin: canal
  options:
    canal_flannel_backend_type: host-gw
dns:
  provider: coredns
  upstreamnameservers:
  - 8.8.8.8
ingress:
  provider: nginx
  node_selector:
    example.com/node.ingress: true
  options:
    disable-access-log: "true"
    disable-ipv6: "true"
    disable-ipv6-dns: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"
  extra_args:
    ingress-class: "nginx"
    report-node-internal-ip-address: "true"
    update-status: "true"
    update-status-on-shutdown: "true"
services:
  kubelet:
    extra_args:
      max-pods: "250"
      system-reserved: "cpu=500m,memory=1Gi,ephemeral-storage=1Gi"
      eviction-hard: "memory.available<1Gi,nodefs.available<5Gi"
      enforce-node-allocatable: "pods"
authentication:
  strategy: x509
  sans:
  - api.e0ac090c.example.com
addon_job_timeout: 120
private_registries:
- url: docker.example.com:5000
  user: someuser
  password: somepassword
  is_default: true
```
