### ISSUE TITLE
Secrets encryption config breaks on rke up

### ISSUE THREAD

**Issue by cmmarslender** [rancher/rke#2686]
**RKE version:**

1.3.0

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Mac & Linux both show the issue

**cluster.yml file:**

Relevant section in kube-api

```yaml
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
          - resources:
              - secrets
            providers:
              - aescbc:
                  keys:
                    - name: key1
                      secret: "......"
              - identity: { }
```

**Steps to Reproduce:**

Run rke up after setting secrets_encryption_config [per docs](https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/)

**Results:**

`FATA[0000] Failed to parse cluster file: unexpected type: *schema.GroupVersionKind`

removing the apiVersion line changes to this error instead:

`FATA[0000] Failed to parse cluster file: error decoding data: Object 'apiVersion' is missing...`

**Comment by superseb** [comment]
Does it work when you change `custom_config` to `customConfig`?

**Comment by cmmarslender** [comment]
It doesn't error any more, but I dont think its being loaded properly at that point - the yaml parsing annotation specifies `custom_config` as the key it needs https://github.com/rancher/rke/blob/54dc689ac040076881a5b4af50326d5d15efb2c6/types/rke_types.go#L991

**Comment by superseb** [comment]
Ok I can run some checks, so it doesnt use the custom configuration when it is used this way?

**Comment by cmmarslender** [comment]
Doesn't appear to load it otherwise.

I'm stepping through this with a go debugger, and the error is coming from here:
https://github.com/rancher/rke/blob/release/v1.3/cluster/encryption.go#L578

There is a commit that changed some stuff in this method that wasn't in 1.2.11 (the last version I used) but I'm not sure if its relevant yet https://github.com/rancher/rke/commit/d07658cf9b5a4b9a1891a5477b9919ecc121e1e6

**Comment by cmmarslender** [comment]
Tested the current version of PR #2690 last night and it all seemed to work correctly - encryption config is still set and the cluster upgraded fine, can read secrets, etc

**Comment by cmmarslender** [comment]
@superseb have you had a chance to take a look at the PR? I'd love to get a fix for this in a maintenance release if possible 😄

**Comment by yfoelling** [comment]
Any updates on this issue? 

We need a fix for this to be able to upgrade our Clusters.

**Comment by maxsokolovsky** [comment]
@superseb, is this already fixed by https://github.com/rancher/rke/pull/2701 then? I too built RKE from that commit and did not see the error with the above secret encryption configuration.

**Comment by superseb** [comment]
Yes this should be fixed by https://github.com/rancher/rke/pull/2701

**Comment by sowmyav27** [comment]
**Reproduced the issue using rke-1.3.2**
- cluster.yml has this section for secret encryption
```
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
          - resources:
              - secrets
            providers:
              - aescbc:
                  keys:
                    - name: key1
                      secret: "......"
              - identity: { }
```
- Error seen on rke up
```
INFO[0000] Running RKE version: v1.3.2                  
FATA[0000] Failed to parse cluster file: unexpected type: *schema.GroupVersionKind 
```

**Using rke 1.3.3-rc2**

- No error is seen with the cluster.yml ^^^ similar to one mentioned above. 
- Cluster comes up Active.
