### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by bmnizar** [rancher/rke#2696]
**RKE version:** rke version v1.2.12

**Docker version: (`docker version`,`docker info` preferred)**20.10.8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Centos 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Vmware

**cluster.yml file:**

nodes:
    - address: 192.168.198.135
      user: xp
      role:
        - controlplane
        - etcd
        - worker
      ssh_key_path: /home/xp/.ssh/id_rsa

**Steps to Reproduce:**
STEP1:ssh-keygen
STEP2: rke --debug up 

**Results:**

DEBU[0000] Checking if cluster version [1.20.10-rancher1-1] needs to have kube-api audit log enabled
DEBU[0000] Cluster version [1.20.10-rancher1-1] needs to have kube-api audit log enabled
DEBU[0000] Enabling kube-api audit log for cluster version [v1.20.10-rancher1-1]
DEBU[0000] Host: 192.168.198.135 has role: controlplane
DEBU[0000] Host: 192.168.198.135 has role: etcd
DEBU[0000] Host: 192.168.198.135 has role: worker
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.198.135]
DEBU[0000] Connecting to Docker API for host [192.168.198.135]
DEBU[0010] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
WARN[0010] Failed to set up SSH tunneling for host [192.168.198.135]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": Unable to access node with address [192.168.198.135:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
WARN[0010] Removing host [192.168.198.135] from node lists
FATA[0010] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.198.135]

**Comment by superseb** [comment]
Did you copy the SSH keys to the host? Did you successfully test using SSH on the command line (If so, how), what type of SSH key is generated? Is it passphrase protected or not?

**Comment by WillNilges** [comment]
Howdy,
My co-worker and I had the same problem for two separate installations:
Single-node cluster. SSH key installed in a user account
Triple-node cluster. One master, two workers. SSH key installed in a user account

Nothing I could think of worked to fix this issue:

- SSH directory file permissions
- docker permissions
- eks config
    - ssh key at absolute path
    - ssh key at relative path
    - internal address field not filled out
    - address not in quotes


**The thing that finally worked in both cases was to use an ed25519 SSH key, NOT an rsa key.**

**Comment by superseb** [comment]
What OS were you using? Some don't accept RSA by default anymore.

**Comment by WillNilges** [comment]
We're using Fedora 34. Using the `ssh -i` command itself worked fine.

**Comment by superseb** [comment]
@WillNilges What is in the log of sshd on the server when RKE attempts to login and fails? If it works manually, it sounds like a Golang library (version) issue or something.

**Comment by WillNilges** [comment]
https://www.reddit.com/r/Fedora/comments/jhxbdh/no_ssh_public_key_auth_after_upgrade_to_fedora_33/

Figured it out. It's a Fedora issue, not an RKE issue. The sshd service was giving my co-worker these logs:

```
Sep 29 14:48:59 rke-master sshd[1242159]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Sep 29 14:48:59 rke-master sshd[1242159]: Connection closed by authenticating user ezerai 10.10.1.254 port 55553 [preauth]
Sep 29 14:48:59 rke-master sshd[1242161]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Sep 29 14:48:59 rke-master sshd[1242161]: Connection closed by authenticating user ezerai 10.10.1.254 port 55556 [preauth]
Sep 29 14:48:59 rke-master sshd[1242163]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Sep 29 14:48:59 rke-master sshd[1242163]: Connection closed by authenticating user ezerai 10.10.1.254 port 55559 [preauth]
Sep 29 14:50:36 rke-master sshd[1243327]: Accepted password for ezerai from 10.10.1.254 port 50273 ssh2
Sep 29 14:50:36 rke-master sshd[1243327]: pam_unix(sshd:session): session opened for user ezerai(uid=1000) by (uid=0)
Sep 29 14:50:36 rke-master sshd[1243408]: Accepted password for ezerai from 10.10.1.254 port 50456 ssh2
Sep 29 14:50:36 rke-master sshd[1243408]: pam_unix(sshd:session): session opened for user ezerai(uid=1000) by (uid=0)
Sep 29 14:53:01 rke-master sshd[1245369]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Sep 29 14:53:01 rke-master sshd[1245369]: Connection closed by authenticating user ezerai 10.10.1.254 port 54073 [preauth]
Sep 29 14:53:01 rke-master sshd[1245371]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Sep 29 14:53:01 rke-master sshd[1245371]: Connection closed by authenticating user ezerai 10.10.1.254 port 56509 [preauth]
Sep 29 14:53:02 rke-master sshd[1245373]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Sep 29 14:53:02 rke-master sshd[1245373]: Connection closed by authenticating user ezerai 10.10.1.254 port 56512 [preauth]
```

He's currently in the process of replacing his keys. Though, because he's on Windows, there's some wackyness with the way that keys are being handled. He's got an ed25519 key, and that's the one his rke config is pointed to, but for some reason, as you can see, it's defaulting to the RSA key still. I told him to yeet the key out of his SSH directory so there's no way it'll be used. Will keep you posted.

**Comment by bmnizar** [comment]
So what's the solution?
I have tried with ed25519 in vain with this config:
nodes:
- address: 192.168.198.136
user:root
role:
- controlplane
- etcd
- worker
ssh_key_path: /home/xp/.ssh/id_ed25519

This is blocking for us to continue with Rancher.

**Comment by bmnizar** [comment]
@WillNilges What was your workaround to make it work?

**Comment by WillNilges** [comment]
> @WillNilges What was your workaround to make it work?

Can you post your complete ignition config? I think there are several places where keys are mentioned,  and you have to be sure that they're all correct.

Also post logs from your `rke up` attempt and your nodes' `sshd` service, if you have them. I'm pretty sure all we had to do was confirm we were using the new keys, and that they were correctly installed in the node user accounts.

**I see that you're trying to set up with `root`. That could be problematic.** I used a normal user account, but if you must, check your `sshd` configs to make sure that authentication with the root account is allowed.

**Comment by bmnizar** [comment]
cluster.yml
```
# If you intended to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: localhost
  port: "22"
  internal_address: 1.0.2.5
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: "yes"
  user: xp
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/xp/.ssh/id_ed25519
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.16-rancher1
  alpine: rancher/rke-tools:v0.1.78
  nginx_proxy: rancher/rke-tools:v0.1.78
  cert_downloader: rancher/rke-tools:v0.1.78
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.78
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.17.4
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.17.4
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.17.4
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  coredns: rancher/mirrored-coredns-coredns:1.8.4
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.18.0
  kubernetes: rancher/hyperkube:v1.21.6-rancher1
  flannel: rancher/mirrored-coreos-flannel:v0.14.0
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.19.2
  calico_cni: rancher/mirrored-calico-cni:v3.19.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.19.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.19.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  canal_node: rancher/mirrored-calico-node:v3.19.2
  canal_cni: rancher/mirrored-calico-cni:v3.19.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.19.2
  canal_flannel: rancher/mirrored-coreos-flannel:v0.14.0
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.4.1
  ingress: rancher/nginx-ingress-controller:nginx-0.49.3-rancher1
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1
  metrics_server: rancher/mirrored-metrics-server:v0.5.0
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: /home/xp/.ssh/id_ed25519
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null

```

rke up
![image](https://user-images.githubusercontent.com/10269818/140305542-72406260-e69f-4d36-9020-f07bd52dca36.png)
