### ISSUE TITLE
Calico node installed in cluster after upgrade. 

### ISSUE THREAD

**Issue by matsch01** [rancher/rke#2699]
**RKE version:**
1.2.11

**Docker version: (`docker version`,`docker info` preferred)**
19.03.11

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
On Prem

We upgraded our cluster to use Kubernetes v1.20.9. After the upgrade there was a Daemon set for docker/calico-node installed. 

The calico-node Daemon Set did not exist before the upgrade. calico-node in turn created a black route that exactly matched the PodCidr used for our pod ip addresses. This effectively killed all cross node communications.

```
)~ ip ro ls
blackhole 192.168.223.64/26 proto bird
```

Also, docker/calico-node was not installed in another cluster that was upgraded to the same version.

Can anyone explain why the docker/calico-node Daemon Set was installed?  And any insight into why it created the blackhole is also appreciated.

UPDATE
Ultimately we had to rebuild the cluster. When we rebuilt the cluster it did not contain the calico-node Daemon Set and our pod ips followed the cluster cidr 10.42.0.0/16. 

Any insight into why the calico-node Daemon Set was installed and why the podCidr  was 192.168.0.0/16 versus 10.42.0.0/16 (per the rke documentation) would be very helpful.

I know the IPPool cidr is 192.168.0.0/16 and that it likely came from this, but why did it not use it when we rebuilt the cluster.

**Comment by superseb** [comment]
Please share previous RKE version, previous k8s version, `cluster.yml` used, how did you upgrade, possibly the log from `rke up`

**Comment by matsch01** [comment]
Previous rke: v1.0.4
Previous k8s: v1.17.2-rancher1-2

Original cluster.yaml:
```
nodes:
  - address: 172.16.11.131
    internal_address: 172.16.11.131
    user: root
    role: [controlplane,etcd]
  - address: 172.16.11.132
    internal_address: 172.16.11.132
    user: root
    role: [controlplane,etcd]
  - address: 172.16.11.133
    internal_address: 172.16.11.133
    user: root
    role: [controlplane,etcd]
  - address: 172.16.11.135
    internal_address: 172.16.11.135
    user: root
    role: [worker]
  - address: 172.16.11.136
    internal_address: 172.16.11.136
    user: root
    role: [worker]
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ingress:
  provider: nginx
  options:
    use-proxy-protocol: "true"

cluster_name: uat
```

I don't have the rke up logs unfortunately.
