### ISSUE TITLE
RKE fails on CoreOS hosts due to read-only filesystem

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#270]
**RKE version:**

```
v0.0.12-dev
```

**Docker version: (`docker version`,`docker info` preferred)** 

```
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Fri Jan  5 11:07:59 2018
 OS/Arch:      linux/amd64
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
4.14.11-coreos
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Azure

**cluster.yml file:**

```
---
nodes:
- address: 10.18.160.23
  role:
  - worker
  user: kubelabadmin
- address: 10.18.160.20
  role:
  - worker
  user: kubelabadmin
- address: 10.18.160.21
  role:
  - worker
  user: kubelabadmin
- address: 10.18.160.27
  role:
  - worker
  user: kubelabadmin
- address: 10.18.160.25
  role:
  - worker
  user: kubelabadmin
- address: 10.18.160.19
  role:
  - controlplane
  - etcd
  user: kubelabadmin
- address: 10.18.160.22
  role:
  - controlplane
  - etcd
  user: kubelabadmin
- address: 10.18.160.17
  role:
  - controlplane
  - etcd
  user: kubelabadmin
- address: 10.18.160.26
  role:
  - controlplane
  - etcd
  user: kubelabadmin
- address: 10.18.160.24
  role:
  - controlplane
  - etcd
  user: kubelabadmin
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.9.1-rancher1-1
    service_cluster_ip_range: 10.233.0.0/18
    admission-control: NamespaceAutoProvision
  kube-controller:
    image: rancher/k8s:v1.9.1-rancher1-1
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.9.1-rancher1-1
  kubelet:
    image: rancher/k8s:v1.9.1-rancher1-1
    cluster_domain: kubelab.vpc.starbucks.net
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    cluster_dns_server: 10.233.0.3
  kubeproxy:
    image: rancher/k8s:v1.9.1-rancher1-1
network:
  plugin: flannel
auth:
  strategy: x509
ssh_key_path: "~/.ssh/kubernetes"
```

**Steps to Reproduce:**

* Bootstrap with rke v0.0.10-dev or above.
* Run on CoreOS nodes.

**Results:**

```
FATA[0133] [workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [10.18.160.22]: Error response from daemon: mkdir /usr/libexec/kubernetes: read-only file system 
```

`/usr` is a [read-only mounted filesystem](https://coreos.com/os/docs/latest/sdk-disk-partitions.html)

Why did this break?
Because of [this commit adding support for Flexvolume plugins](https://github.com/rancher/rke/commit/2242cda0f7d7ad221f9dbe6e1bc336b8ec92f122)
