### ISSUE TITLE
Kubelet - The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused)

### ISSUE THREAD

**Issue by qdupuy** [rancher/rke#2703]
Hello,

**RKE version:**

rke version v1.3.0

**Docker version: (`docker version`,`docker info` preferred)**

Docker version 20.10.8, build 3967b7d

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

20.04.3 LTS (Focal Fossa)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

```
- address: x
  port: "22"
  internal_address: x
  role:
  - worker
  hostname_override: x
  user: x
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./keys/id_rsa_x
  ssh_cert: ""
  ssh_cert_path: ""
  labels:
    scaleway/network: rpnv2
    scaleway/host-type: pro-6-m
    x/scope: public
    x/monitoring: "true"
    x/gitlab: "true"
    node.longhorn.io/create-default-disk: "true"
  taints: []
```

```
bastion_host:
  address: "10.99.0.99"
  port: "22"
  user: "quentin"
  ssh_key: ""
  ssh_key_path: "~/.ssh/id_ed25519"
  ssh_cert: ""
  ssh_cert_path: "~/.ssh/id_ed25519.pub"
```

system image : 

```
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.15-rancher1
  alpine: rancher/rke-tools:v0.1.75
  nginx_proxy: rancher/rke-tools:v0.1.75
  cert_downloader: rancher/rke-tools:v0.1.75
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.75
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.15.10
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.15.10
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.15.10
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  coredns: rancher/mirrored-coredns-coredns:1.8.0
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.15.13
  kubernetes: rancher/hyperkube:v1.20.9-rancher1-1
  flannel: rancher/coreos-flannel:v0.13.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.17.2
  calico_cni: rancher/mirrored-calico-cni:v3.17.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.17.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  canal_node: rancher/mirrored-calico-node:v3.17.2
  canal_cni: rancher/mirrored-calico-cni:v3.17.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  canal_flannel: rancher/coreos-flannel:v0.13.0-rancher1
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.2
  ingress: rancher/nginx-ingress-controller:nginx-0.43.0-rancher3
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/mirrored-metrics-server:v0.4.1
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
```
**Steps to Reproduce:**

Adding a worker node

**Results:**

I try to integrate a worker on my cluster with the same versions as docker and I get the following error :

```
ERRO[0295] Failed to upgrade hosts: x with error [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [x]: Get "http://localhost:10248/healthz": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log:     /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:299 +0x6e] 

```

The error indicates a connection problem on ssh but the configuration is identical on each server same for my ssh's config file
