### ISSUE TITLE
ingress-nginx race condition in admission controller starting with rke 1.3.0

### ISSUE THREAD

**Issue by horihel** [rancher/rke#2705]
Since RKE 1.3.0 ingress-nginx has validating webhooks enabled. Unfortunately, they're currently suffering a race condition when you create many ingresses at once (as helm usually does with bigger applications).

See here: https://github.com/kubernetes/ingress-nginx/issues/6245

This affects our development infrastructure and CI pipelines and will keep us on 1.2.x until fixed or worked around.

Currently the only reliable fix is deleting the admission hooks after installing rke, but I'm uncertain if they reappear during reconciliation or updates. Ideally I'd prefer to be able to disable them in cluster.yml (or the underlying bug being fixed).

**RKE version:**
1.3.1

**Docker version: (`docker version`,`docker info` preferred)**
20.10.7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```sh
dev@se-dev:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
dev@se-dev:~$ uname -r
5.4.0-84-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM/Bare Metal

**cluster.yml file:**
```yaml
cluster_name: se
nodes:
  - address: node1
    user: dev
    role:
      - controlplane
      - etcd
      - worker
services:
  kubelet:
    extra_binds:
      - "/data:/data"
      - "/mnt/pv:/mnt/pv"
```

**Steps to Reproduce:**
* install rke 1.3.0+
* install a helm chart that generates about 20 ingresses
* try a few times, see about 25% failure rate

**Results:**
See https://github.com/kubernetes/ingress-nginx/issues/6245 for details
