### ISSUE TITLE
rke - nginx controller metrics

### ISSUE THREAD

**Issue by qdupuy** [rancher/rke#2710]
Hello,

Is it possible to specify the activation of nginx controller metrics via the rke configuration file? 

The rke documentation does not say anything about this :( And on the ingress nginx configmap I don't see what I'm interested in.

I would like to permanently implement my configuration to capture nginx metrics from my configuration file.

Here is what I want to implement on the rke configuration file:

https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/ 

rke version v1.3.1
kubernetes version v1.20.9

**Comment by superseb** [comment]
Annotations are currently not configurable by RKE configuration, but you can do it using add-ons I think: https://rancher.com/docs/rke/latest/en/config-options/add-ons/user-defined-add-ons/

**Comment by qdupuy** [comment]
I don't think it would work because I'm going to overwrite the nginx ingress

**Comment by jcwimer** [comment]
When I deploy with RKE 1.2.12 the annotations for the nginx daemonset are there

```
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
```

With 1.2.14 and 1.3.2 those annotations are gone. Why did this change?
