### ISSUE TITLE
unknow option - ReplicaSet/calico-kube-controllers

### ISSUE THREAD

**Issue by qdupuy** [rancher/rke#2711]
Hello,

Since adding a node on my cluster worker, I have this problem on ReplicaSet/calico-kube-controllers :

```
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  10m (x2323 over 23h)  kubelet  Liveness probe failed: unknown shorthand flag: 'l' in -l
unknown shorthand flag: 'l' in -l
Usage of check-status:
  -f, --file string   File to read with status information (default "/status/status.json")
  -r, --ready         Check readiness
  -v, --version       Display version
  Warning  BackOff  60s (x4714 over 22h)  kubelet  Back-off restarting failed container
```

I see that the instructions for liveness are present whereas before this was not present.

How can I correct the problem from the rke configuration file?

rke version v1.3.1
kubernetes version v1.20.9

**Comment by superseb** [comment]
Please share your `cluster.yml`, is this an upgrade or new cluster?

**Comment by qdupuy** [comment]
I upgraded my cluster with a new worker

Here is my config file :

```
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: x
  port: "22"
  internal_address: x
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: x
  user: x
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./keys/id_rsa_x
  ssh_cert: ""
  ssh_cert_path: ""
  labels:
    scaleway/network: rpnv2
    scaleway/host-type: pro-7-s
    x/scope: public
    x/nfs: "true"
    node.longhorn.io/create-default-disk: "true"
    # node.longhorn.io/default-disks-config: '[
    #       { 
    #           "path":"/var/lib/longhorn",
    #           "allowScheduling":true,
    #           "storageReserved":10485760,
    #           "tags":[
    #               "ssd",
    #               "fast"
    #           ]
    #       }
    #   ]'
  taints: []
- address: x
  port: "22"
  internal_address: x
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: x
  user: x
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./keys/id_rsa_x
  ssh_cert: ""
  ssh_cert_path: ""
  labels:
    scaleway/network: rpnv2
    scaleway/host-type: pro-7-s
    x/scope: public
    x/nfs: "true"
    node.longhorn.io/create-default-disk: "true"
  taints: []
- address: x
  port: "22"
  internal_address: x
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: x
  user: x
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./keys/id_rsa_x
  ssh_cert: ""
  ssh_cert_path: ""
  labels:
    scaleway/network: rpnv2
    scaleway/host-type: pro-7-s
    x/scope: public
    x/nfs: "true"
    node.longhorn.io/create-default-disk: "true"
  taints: []
- address: x
  port: "22"
  internal_address: x
  role:
  - worker
  hostname_override: x
  user: x
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ./keys/id_rsa_x
  ssh_cert: ""
  ssh_cert_path: ""
  labels:
    scaleway/network: rpnv2
    scaleway/host-type: pro-6-m
    x/scope: public
    x/monitoring: "true"
    x/gitlab: "true"
    node.longhorn.io/create-default-disk: "true"
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config:
      enabled: true     # enables recurring etcd snapshots
      interval_hours: 2 # time increment between snapshots
      retention: 31     # time in days before snapshot purge
      s3backupconfig:
        access_key: x
        secret_key: x
        bucket_name: backup-etcd
        region: "fr-par"
        folder: "etcd-x" # Optional - Available as of v0.3.0
        endpoint: x
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: 
      cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
      cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: true
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options:
    canal_iface: netk8s01
    canal_flannel_backend_type: vxlan
    canal_autoscaler_priority_class_name: system-cluster-critical
    canal_priority_class_name: system-cluster-critical
  mtu: 9000
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.15-rancher1
  alpine: rancher/rke-tools:v0.1.75
  nginx_proxy: rancher/rke-tools:v0.1.75
  cert_downloader: rancher/rke-tools:v0.1.75
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.75
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.15.10
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.15.10
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.15.10
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  coredns: rancher/mirrored-coredns-coredns:1.8.0
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.15.13
  kubernetes: rancher/hyperkube:v1.20.9-rancher1-1
  flannel: rancher/coreos-flannel:v0.13.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.17.2
  calico_cni: rancher/mirrored-calico-cni:v3.17.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.17.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  canal_node: rancher/mirrored-calico-node:v3.17.2
  canal_cni: rancher/mirrored-calico-cni:v3.17.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  canal_flannel: rancher/coreos-flannel:v0.13.0-rancher1
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.2
  ingress: rancher/nginx-ingress-controller:nginx-0.43.0-rancher3
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/mirrored-metrics-server:v0.4.1
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: true
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: "10.99.0.99"
  port: "22"
  user: "quentin"
  ssh_key: ""
  ssh_key_path: "~/.ssh/id_ed25519"
  ssh_cert: ""
  ssh_cert_path: "~/.ssh/id_ed25519.pub"
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null
```
