### ISSUE TITLE
canal-config ConfigMap CIDR value

### ISSUE THREAD

**Issue by remche** [rancher/rke#2718]
~After an upgrade on our test cluster from Ubuntu 16.04 to Ubuntu 18.04, the kubernetes service is unavailable, causing calico-kube-controllers, metrics-server and cattler-cluster-agent to fail.~

Turns out it has probably nothing see with OS upgrade. The cancl-config ConfigMap was changed, probably by an RKE upgrade.

We are still using iptables, and br_netfilter is loaded.

Oddly enough, we got the wrong cidr in iptables : 

```
ACCEPT     all  --  anywhere             10.244.0.0/16       
ACCEPT     all  --  10.244.0.0/16        anywhere  
```

Trying to manually add 10.42.0.0/16 did not solve the issue. Any clue on this issue ?

**RKE version:**

1.3.1
K8s v1.19.15

**Docker version: (`docker version`,`docker info` preferred)**

20.10.7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 18.04.6 LTS
4.15.0-159-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere

**cluster.yml file:**
```yaml
nodes:
    - address: xxx
      role:
        - controlplane
        - etcd
      hostname_override: rke-test-master-01
      user: user
    - address: xxx
      role:
        - worker
      hostname_override: rke-test-worker-01
      user: user
    - address: xxx
      role:
        - worker
      hostname_override: rke-test-worker-02
      user: user
upgrade_strategy:
    drain: true
    node_drain_input:
        force: false
services:
    kubelet:
        fail_swap_on: true
ssh_agent_auth: true
ssh_key_path: ~/.ssh/id_rsa
ignore_docker_version: false
kubernetes_version: v1.19.15-rancher1-2
ingress:
    provider: none
cluster_name: rke-test
addon_job_timeout: 0
```

I

**Results:**

**Comment by remche** [comment]
Turns out that canal-config ConfigMap was referencing wrong cidr : 

```yaml
  net-conf.json: |
    {
      "Network": "10.42.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
```

I wonder what caused that change :question:
