### ISSUE TITLE
Failed to create Docker container [kube-apiserver] .. Cannot connect to .. unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by audacioustux** [rancher/rke#2723]
I'm trying to setup a rke cluster on lxc (2 container). it's failling to connect to docker.socket at some point. tried out complete docker system prune, but no luck

**RKE version:**
`v1.3.1`
**Docker version:**
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Operating system and kernel:**
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
# uname -r
5.4.0-88-generic

```
**Type/provider of hosts:**
LXC
**cluster.yml file:**
```
nodes:
- address: 192.168.31.201
  port: "22"
  internal_address: 192.168.31.201
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: machine-1
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_ed25519
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.31.202
  port: "22"
  internal_address: 192.168.31.202
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: machine-2
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_ed25519
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: calico
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.16-rancher1
  alpine: rancher/rke-tools:v0.1.78
  nginx_proxy: rancher/rke-tools:v0.1.78
  cert_downloader: rancher/rke-tools:v0.1.78
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.78
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.17.4
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.17.4
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.17.4
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  coredns: rancher/mirrored-coredns-coredns:1.8.4
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.18.0
  kubernetes: rancher/hyperkube:v1.21.5-rancher1
  flannel: rancher/mirrored-coreos-flannel:v0.14.0
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.19.2
  calico_cni: rancher/mirrored-calico-cni:v3.19.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.19.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.19.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  canal_node: rancher/mirrored-calico-node:v3.19.2
  canal_cni: rancher/mirrored-calico-cni:v3.19.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.19.2
  canal_flannel: rancher/mirrored-coreos-flannel:v0.14.0
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.4.1
  ingress: rancher/nginx-ingress-controller:nginx-0.48.1-rancher1
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: rancher/mirrored-jettech-kube-webhook-certgen:v1.5.1
  metrics_server: rancher/mirrored-metrics-server:v0.5.0
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: ~/.ssh/id_ed25519
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null
ssh_agent_auth: true
```

**Steps to Reproduce:**
lxc profiles:
```
config:
  user.network-config: |
    version: 2
    ethernets:
        eth0:
            addresses:
            - 192.168.31.201/32
            nameservers:
                addresses:
                - 8.8.8.8
                search: []
            routes:
            -   to: 0.0.0.0/0
                via: 169.254.0.1
                on-link: true
devices:
  eth0:
    ipv4.address: 192.168.31.201
    nictype: routed
    parent: wlx18a6f70e038e
    type: nic
name: machine_1
used_by:
- /1.0/instances/machine-1
```
* same for profile machine-2  
`lxc launch ubuntu:20.04 machine-1 --profile default --profile machine_1`  
in both container: `curl https://releases.rancher.com/install-docker/20.10.sh | sh`  

**Results:**
```
...
...
INFO[0233] Image [rancher/rke-tools:v0.1.78] exists on host [192.168.31.201]
INFO[0233] Image [rancher/rke-tools:v0.1.78] exists on host [192.168.31.202]
INFO[0242] Image [rancher/hyperkube:v1.21.5-rancher1] exists on host [192.168.31.201]
INFO[0243] Image [rancher/hyperkube:v1.21.5-rancher1] exists on host [192.168.31.202]
WARN[0292] Failed to create Docker container [kube-apiserver] on host [192.168.31.201]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
WARN[0292] Failed to create Docker container [kube-apiserver] on host [192.168.31.201]: Error response from daemon: Conflict. The container name "/kube-apiserver" is already in use by container "5fb4fcd3751d24096265830d9099160026e920985ce4ccc17efd59222c9adb2e". You have to remove (or rename) that container to be able to reuse that name.
WARN[0292] Failed to create Docker container [kube-apiserver] on host [192.168.31.201]: Error response from daemon: Conflict. The container name "/kube-apiserver" is already in use by container "5fb4fcd3751d24096265830d9099160026e920985ce4ccc17efd59222c9adb2e". You have to remove (or rename) that container to be able to reuse that name.
WARN[0293] Failed to create Docker container [kube-apiserver] on host [192.168.31.202]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
WARN[0293] Failed to create Docker container [kube-apiserver] on host [192.168.31.202]: Error response from daemon: Conflict. The container name "/kube-apiserver" is already in use by container "d5ff9660b33e00923b4e1894c4d71b5664f8198b8fc32d6dd1c57dbef6fbcdae". You have to remove (or rename) that container to be able to reuse that name.
WARN[0293] Failed to create Docker container [kube-apiserver] on host [192.168.31.202]: Error response from daemon: Conflict. The container name "/kube-apiserver" is already in use by container "d5ff9660b33e00923b4e1894c4d71b5664f8198b8fc32d6dd1c57dbef6fbcdae". You have to remove (or rename) that container to be able to reuse that name.
FATA[0293] [controlPlane] Failed to bring up Control Plane: [Failed to create [kube-apiserver] container on host [192.168.31.201]: Failed to create Docker container [kube-apiserver] on host [192.168.31.201]: Error response from daemon: Conflict. The container name "/kube-apiserver" is already in use by container "5fb4fcd3751d24096265830d9099160026e920985ce4ccc17efd59222c9adb2e". You have to remove (or rename) that container to be able to reuse that name.]
```

```
root@machine-2:~# docker ps -a
CONTAINER ID   IMAGE                                           COMMAND                  CREATED          STATUS          PORTS     NAMES
d5ff9660b33e   rancher/hyperkube:v1.21.5-rancher1              "/opt/rke-tools/entr…"   21 minutes ago   Created                   kube-apiserver
5c5035a2abde   rancher/rke-tools:v0.1.78                       "/bin/bash"              21 minutes ago   Created                   service-sidekick
762797818f08   rancher/rke-tools:v0.1.78                       "/docker-entrypoint.…"   22 minutes ago   Up 22 minutes             etcd-rolling-snapshots
a5ab9295c565   rancher/mirrored-coreos-etcd:v3.4.16-rancher1   "/usr/local/bin/etcd…"   22 minutes ago   Up 22 minutes             etcd
```
