### ISSUE TITLE
SELinux label on processes changes based on location & labels of docker data-root

### ISSUE THREAD

**Issue by wbrefvem** [rancher/rke#2739]
**RKE version:** 1.2.9

**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 64
  Running: 36
  Paused: 0
  Stopped: 28
 Images: 20
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.19.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.51GiB
 Name: devgorilla-vm1
 ID: 7XZJ:6723:KPSZ:JSY5:KHZD:TRLJ:P3YZ:VXTV:TPWA:N37D:DRXR:VGXO
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
$ uname -r
3.10.0-1127.19.1.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Azure

**cluster.yml file:**

```
cluster_name: gorilla-dev
kubernetes_version: v1.20.8-rancher1-1

nodes:
  - address: [removed]
    internal_address: [removed]
    user: [removed]
    role: [controlplane, worker, etcd]
    ssh_key_path: ~/.ssh/id_rsa
  - address: [removed]
    internal_address: [removed]
    user: [removed]
    role: [controlplane, worker, etcd]
    ssh_key_path: ~/.ssh/id_rsa
  - address: [removed]
    internal_address: [removed]
    user: [removed]
    role: [controlplane, worker, etcd]
    ssh_key_path: ~/.ssh/id_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
  kubelet:
    extra_args:
      feature-gates: "TTLAfterFinished=true"

network:
  plugin: canal

ingress:
  provider: none
```

**Steps to Reproduce:**

1. Set `data-root` in docker `daemon.json` on each to node to a non-default value.
2. Run `rke up`
3. Run `ps fauxZ` on one or more nodes to inspect SELinux labels on container processes.
4. Run `ls -alZ /path/to/docker/data/root` to inspect SELinux file labels.

**Results:**

Container processes have `container_runtime_t` label instead of expected `spc_t` label.

Docker data root directories and files have `system_u:object_r:default_t:s0` label.
