### ISSUE TITLE
rke up does not update webhook authentication server url

### ISSUE THREAD

**Issue by nneul** [rancher/rke#2743]
**RKE version:**
v1.3.2 

**Docker version: (`docker version`,`docker info` preferred)**

```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 20.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal

**cluster.yml file:**
NA except for the webhook config

```
authentication:
  strategy: x509|webhook
  sans:
  - "cluster1.domain"
  webhook:
    config_file: |-
        apiVersion: v1
        kind: Config
        clusters:
          - name: srv-dev-hook
            cluster:
              certificate-authority: /etc/ssl/certs/ca-certificates.crt
              server: https://server/path/hook.pl
        users:
          - name: my-api-server
            user:
              token: test-token
        current-context: auth-webhook
        contexts:
        - context:
            cluster: srv-dev-hook
            user: my-api-server
          name: auth-webhook
    cache_timeout: 60s
```

**Steps to Reproduce:**

Set up a cluster with working web hooks for auth, everything happy.

Change the URL for server: entry in cluster.yml. Issue rke up. No errors applying configuration, but api server continues to talk to old URL. 

**Results:**

Can't change url/config with rke up.

**Workaround:**

Reconfigure with empty webhook config (comment entirely in the cluster.yml), rke up, uncomment in config issue rke up again.
