### ISSUE TITLE
RKE uploads etcd snapshot to S3 from all etcd nodes

### ISSUE THREAD

**Issue by gabbler97** [rancher/rke#2755]
**RKE version:**
v1.3.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 20.10.10, build b485636

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.04 LTS
5.4.0-90-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**cluster.yml file:**
```
nodes:
    - address: 10.10.10.2
      user: rancher
      role:
        - controlplane
        - etcd
        - worker
      hostname_override: master1
      taints:
        - key: CriticalAddonsOnly
          value: True
          effect: NoExecute
    - address: 10.10.10.3
      user: rancher
      role:
        - controlplane
        - etcd
        - worker
      hostname_override: master2
      taints:
        - key: CriticalAddonsOnly
          value: True
          effect: NoExecute
    - address: 10.10.10.4
      user: rancher
      role:
        - controlplane
        - etcd
        - worker
      hostname_override: master3
      taints:
        - key: CriticalAddonsOnly
          value: True
          effect: NoExecute
    - address: 10.10.10.5
      user: rancher
      role:
        - worker
      hostname_override: worker1
    - address: 10.10.10.6
      user: rancher
      role:
        - worker
      hostname_override: worker2
    - address: 10.10.10.7
      user: rancher
      role:
        - worker
      hostname_override: worker3

cluster_name: local
kubernetes_version: v1.21.6-rancher1-1
addon_job_timeout: 60
services:
  etcd:
    backup_config:
      enabled: true
      interval_hours: 1
      retention: 14
      s3backupconfig:
        access_key: "notimportant"
        secret_key: "notimportant"
        bucket_name: "etcbackups"
        region: ""
        folder: "" # Optional - Available as of v0.3.0
        endpoint: "10.10.10.10"
        custom_ca: |-
          -----BEGIN CERTIFICATE-----
          SOMESLEFSIGNEDCERT
          LIKETHISNOTINBASE64
          -----END CERTIFICATE-----
```

**Steps to Reproduce:**
Bring up the cluster with this config, create a minio with docker, create self-signed cert for that.

**Results:**
When I'm backing up the cluster manually everything works fine. (sudo rke etcd snapshot-save)
The backup is created and uploaded to the bucket. (rke_etcd_snapshot_2021-11-25T08:41:35Z.zip)
When the backup is created automatically every etcd node uploads its own backup to the bucket.
(2021-11-25T08:27:24Z_etcd.zip)
(2021-11-25T08:27:14Z_etcd.zip)
(2021-11-25T08:27:04Z_etcd.zip)
The following error also appears in the logs on the etcd-rolling-snapshots container:
level=warning msg="Couldn't parse backup" error="parsing time \"rke\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"rke\" as \"2006\"" name="rke_etcd_snapshot_2021-11-24T22:28:36Z.zip"
