### ISSUE TITLE
Add load balancer option to K8s ingress controller

### ISSUE THREAD

**Issue by jgallucci32** [rancher/rke#2759]
**Is your feature request related to a problem? Please describe.**
By default, RKE deploys the NGINX ingress controller on all schedulable nodes. The ingress controller is configured as a `HostPort` and requires an external load balancer to be configured. Clusters running in a supported environment have the option of automatically creating a cloud load balancer. This provides an externally-accessible IP address that sends traffic to the correct port on your cluster nodes.

Configuring the nginx ingress controller with no network mode will make it run on the overlay network (for example, if you want to expose the nginx ingress controller using a LoadBalancer):
```yaml
ingress:
  provider: nginx
  network_mode: none
```
To expose the ingress controller using a cloud load balancer you must create a service of `type:LoadBalancer` and configure it to point to the ingress controller.
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: ingress-nginx
  type: LoadBalancer
```
This results in the ingress controller being accessible from a cloud load balancer which applications can use.

**Describe the solution you'd like**
Add the option `network_mode: loadBalancer` to the RKE cluster configuration which automatically creates the Service for exposing the ingress controller through a cloud load balancer.

**Describe alternatives you've considered**
This can be setup manually after the cluster has been deployed.

**Additional context**
https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

**Comment by jgallucci32** [comment]
Bump

**Comment by mddamato** [comment]
Possible workaround. Add the following to your cluster.yml:

```
ingress:
  provider: nginx
  network_mode: none

addons: |-
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx-external
    namespace: ingress-nginx
  spec:
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
    sessionAffinity: None
    type: LoadBalancer
```

then `rke up` again. 

I have also confirmed this working in downstream clusters by editing the cluster config via yaml in UI

Cluster Management -> Edit Config (for cluster) -> Edit as YAML

then in the spec modify to 

```
rancher_kubernetes_engine_config:
  addons: |-
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: ingress-nginx-external
      namespace: ingress-nginx
    spec:
      ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
      selector:
        app: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
      sessionAffinity: None
      type: LoadBalancer
  ingress:
    network_mode: none

```
