### ISSUE TITLE
Feature request - cluster.yml option to add files to /etc/kubernetes/ on plane hosts or way to add additional cert file

### ISSUE THREAD

**Issue by nneul** [rancher/rke#2775]
I am using web hook authentication, part of that is using a custom cert for the backend service to be able to mutually authenticate the backend. To do this now, I'm manually copying that cert into /etc/kubernetes/ssl on each control plane node so that it can be available to the kube-apiserver when referenced from the webhook authentication config.

It would be nice if there were one of two options:

A) ability to provide a cert inline (or referencing a file on the rke-invoking side) in the cluster.yml
B) ability to provide a file/dir path in cluster.yml which would ask rke 'copy these files into /etc/kubernetes/

I could do this with 'custom-certs' now, but that seems a touch heavy handed when I just want to add an additional cert

**RKE version:**
1.3.2

**Docker version: (`docker version`,`docker info` preferred)**
na

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal

**cluster.yml file:**

```
authentication:
  strategy: x509|webhook
  sans:
  - "whatever.domain"
  webhook:
    config_file: |-
        apiVersion: v1
        kind: Config
        clusters:
          - name: something-hook
            cluster:
              certificate-authority: /etc/kubernetes/ssl/my-internal-mutual-auth-for-that-someurl.crt
              server: https://someurl/auth
        users:
          - name: my-api-server
            user:
              token: test-token
        current-context: auth-webhook
        contexts:
        - context:
            cluster: something-hook
            user: my-api-server
          name: auth-webhook
    cache_timeout: 25s
```
