### ISSUE TITLE
v1.22.4-rancher1-1 cannot be deployed on Fedora CoreOS with SELinux

### ISSUE THREAD

**Issue by debackerl** [rancher/rke#2792]
**RKE version:**

RKE 1.3.3 as included by Terraform Provider 1.3.0.

**Docker version: (`docker version`,`docker info` preferred)**

```
Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.5
  Git commit:       b0f5bc3
  Built:            Fri Jul 16 00:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.3
  GitCommit:        
 runc:
  Version:          1.0.0-rc95
  GitCommit:        4c62ef789fd7a2963bf61ffbf421ce9646063648
 docker-init:
  Version:          0.19.0
  GitCommit:   
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME=Fedora
VERSION="34.20210725.3.0 (CoreOS)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora CoreOS 34.20210725.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='34.20210725.3.0'
DEFAULT_HOSTNAME=localhost
```

rpm-ostree status

```
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 34.20210725.3.0 (2021-08-09T21:47:26Z)
                BaseCommit: 8f45ac7421e77b4335a37fe40f3fcf4ce4762ce9fd987130e113e35b79d5d6dd
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
             LocalPackages: rancher-selinux-0.2-1.el8.noarch
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Baremetal

**cluster.yml file:**

```
# https://rancher.com/docs/rke/latest/en/example-yamls/

network:
  # WARNING: the CNI cannot be modified after cluster creation

  # RKE's flannel container images are have their privileged flag set to false
  # which makes it uncompatible with SELinux under Fedora CoreOS 

  # RKE's calico seems to put SELinux in permissive mode on controller nodes

  plugin: calico
  options:
    # https://github.com/rancher/rke/issues/1744
    # https://github.com/rancher/rke/pull/1929/files
    # https://github.com/rancher/rancher/issues/29593
    # must also set flex-volume-plugin-dir as extra-arg to kube-controller
    calico_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds

    # not sure if line below makes sense
    flannel_backend_type: vxlan

  # plugin: none

services:
  kube-api:
    audit_log:
      # https://rancher.com/docs/rke/latest/en/config-options/audit-log/
      enabled: false
  
  kube-controller:
    #cluster_cidr: 10.42.0.0/16
    extra_args:
      # https://github.com/rancher/rke/issues/1744
      flex-volume-plugin-dir: "/opt/kubernetes/kubelet-plugins/volume/exec/"

  kubelet:
    cluster_domain: cluster.local
    #extra_args:
      # to see hierarchy of cgroups on a node: systemd-cgls
      # this has to match the docker service
      # cgroup-driver: "systemd"
      # cgroup-root: "/"

upgrade_strategy:
  # https://rancher.com/docs/rke/latest/en/upgrades/configuring-strategy/

  # Try to evict Pods before stopping a worker.
  drain: true

  node_drain_input:
    # --force, Continue even if there are pods not managed by a ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet.
    force: true
    # --ignore-daemonsets, Ignore DaemonSet-managed pods (avoid their deletion?).
    ignore_daemonsets: true
    # --delete-emptydir-data, Continue even if there are pods using emptyDir.
    delete_local_data: true
    # --grace-period, Period of time in seconds given to each pod to terminate gracefully.
    # If negative, the default value specified in the pod will be used.
    grace_period: -1
    # --timeout, The length of time (in seconds) to wait before giving up, zero means infinite
    timeout: 120

  # Doc: This number can be configured as a percentage or as an integer. When defined as a percentage,
  # the batch size is rounded down to the nearest node, with a minimum of one node per batch.
  max_unavailable_worker: 1

  # warning: not sure if this is compatible with stateful-load because all replicas
  # maybe be in the 'unlucky' 20%
  #max_unavailable_worker: 20%

  max_unavailable_controlplane: 1

addons_include: []
  # using Terraform RKE Provider 1.2.3, the kube-flannel container has privileged: false
  # this prevents it from running on Fedora CoreOS with SELinux enabled

  # - "artifacts/config-files/rke-addons-flannel.yaml"

ingress:
  # we install the Ingress Controller ourselves via an Helm Chart
  provider: none
```

**Steps to Reproduce:**

Deploy Fedora CoreOS nodes using:

```
variant: fcos
version: 1.4.0

boot_device:
  luks:
    # enabling root partition encryption requires the partition to be moved to RAM during setup,
    # it works with 2GiB of RAM, not sure about 1GiB
    tpm2: false
    # a single PIN provider will be required to unlock LUKS' passphrase
    # this allows all but one Tang server to be down
    threshold: 1
    tang:
      # Tang as PIN provider
      # Tang's protocol does not required TLS for safety
      # Free TCP ports: http://ports.my-addr.com/tcp_port_list-udp_port_list_search_by_number.php?filter=on&protocol=TCP&ports_list=7900-8200
      - url: http://XXX:7950
        # obtain thumbprint from Tang's server by running: jose jwk thp -i $DBDIR/$SIG.jwk
        # validate by doing, curl http://XXX:7950/adv/XXX
        # we specify the thumbprint to avoid man-in-the-middle attacks where an attacker would impersonate the Tang server
        # and return his own keys
        thumbprint: XXX
      - url: http://XXX:7951
        thumbprint: XXX

storage:
  files:
    # by default, FCOS uses journald logging driver
    - path: /etc/sysconfig/docker
      overwrite: true
      contents:
        inline: |
          # Modify these options if you want to change the way the docker daemon runs
          OPTIONS="--selinux-enabled \
            --live-restore \
            --default-ulimit nofile=65536:65536 \
            --init-path /usr/libexec/docker/docker-init \
            --userland-proxy-path /usr/libexec/docker/docker-proxy \
          "

    - path: /etc/docker/daemon.json
      contents:
        inline: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }

    # https://docs.rke2.io/known_issues/#networkmanager
    # you can later validate that an interface is unmanaged by running: "nmcli dev status"
    - path: /etc/NetworkManager/conf.d/rke-cni.conf
      mode: 0644
      contents:
        inline: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:flannel*

    - path: /etc/ssh/sshd_config.d/60-rke.conf
      mode: 0644
      contents:
        inline: |
          PermitTunnel yes
          AllowTcpForwarding yes

    # https://docs.fedoraproject.org/en-US/fedora-coreos/auto-updates/
    - path: /etc/zincati/config.d/51-rollout-wariness.toml
      contents:
        inline: |
          [identity]
          rollout_wariness = 0.5

    - path: /etc/zincati/config.d/55-updates-strategy.toml
      contents:
        inline: |
          [updates]
          strategy = "fleet_lock"
          [updates.fleet_lock]
          # ClusterIP for fleetlock or airlock
          base_url = "http://10.43.0.10/"

    - path: /etc/sysctl.d/20-silence-audit.conf
      mode: 0644
      contents:
        inline: |
          # Raise console message logging level from DEBUG (7) to WARNING (4)
          # to hide audit messages from the interactive console
          kernel.printk = 4

    - path: /etc/sysctl.d/90-sysrq.conf
      contents:
        inline: |
          # requirement for KeyDB
          vm.overcommit_memory = 1
          # recommended by Zalando to reduce chance of OOM with PostgreSQL
          # starts flushing after 64MiB, blocks I/O after 128MiB
          # https://archive.fosdem.org/2020/schedule/event/postgresql_postgresql_on_k8s_at_zalando_two_years_in_production/attachments/slides/3883/export/events/attachments/postgresql_postgresql_on_k8s_at_zalando_two_years_in_production/slides/3883/PostgreSQL_on_K8s_at_Zalando_Two_years_in_production.pdf
          vm.dirty_background_bytes = 67108864
          vm.dirty_bytes = 134217728

systemd:
  units:
    # RKE will create containers with "--restart=always", but docker has to be started on reboot
    - name: docker.service
      enabled: true

    # https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/
    # https://github.com/coreos/fedora-coreos-tracker/issues/681
    - name: rpm-ostree-install-rke.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer additional rpms
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive https://github.com/rancher/rancher-selinux/releases/download/v0.2.production.1/rancher-selinux-0.2-1.el8.noarch.rpm
        ExecStart=/bin/touch /var/lib/%N.stamp
        [Install]
        WantedBy=multi-user.target

kernel_arguments:
  should_exist:
    # requirement for KeyDB, to be validated
    # see https://unix.stackexchange.com/questions/99154/disable-transparent-hugepages
    - transparent_hugepage=never
    # auto mitigation to CPU vulnerabilities, but keep SMT on since our server is not multi-tenant
    - mitigations=auto

passwd:
  users:
    - name: rke
      groups:
        - docker
      ssh_authorized_keys:
        - "ssh-ed25519 XXX rke"
```

Deploy for the first time RKE through Terraform using kubernetes_version = "v1.22.4-rancher1-1"

**Results:**

```
Failed running cluster err:[etcd] Failed to bring up Etcd Plane: Container [etcd-fix-perm] exited with non-zero exit code [1] on host [x.x.x.x]: stdout: , stderr: chmod: /var/lib/rancher/etcd/: Permission denied
```

Before I disabled the Audit Log, I got a similar error but for a different file:

```
Failed running cluster err:[file-deploy] Failed to deploy file [/etc/kubernetes/audit-policy.yaml] on node [x.x.x.x]: Container [file-deployer] exited with non-zero exit code [1] on host [x.x.x.x]: stdout: , stderr: mv: can't create '/etc/kubernetes/audit-policy.yaml': Permission denied
```

If I first deploy using kubernetes_version = "v1.21.7-rancher1-1" and then upgrade the cluster using kubernetes_version = "v1.22.4-rancher1-1", it works great. So problem is with clean install only, not upgrade.
