### ISSUE TITLE
Networking issues that don't auto-resolve after node reboot

### ISSUE THREAD

**Issue by gboor** [rancher/rke#2805]
**RKE version:**
1.3.2

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:23 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 78
  Running: 42
  Paused: 0
  Stopped: 36
 Images: 38
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-9-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.36GiB
 Name: sadc-1
 ID: FAKV:S5QP:DPPQ:FSLF:X67G:DEWX:U22G:L4BK:XOKU:IS6P:SCXG:SVE2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
5.10.0-9-amd64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**cluster.yml file:**
```
cluster_name: sadc-cluster
ssh_agent_auth: true
nodes:
  - address: 172.28.1.3
    internal_address: 192.168.10.11
    user: rke
    hostname_override: master
    role:
      - controlplane
      - etcd
      - worker
  - address: 172.28.1.4
    internal_address: 192.168.10.12
    user: rke
    hostname_override: worker1
    role:
      - controlplane
      - etcd
      - worker
  - address: 172.28.1.5
    internal_address: 192.168.10.13
    user: rke
    hostname_override: worker2
    role:
      - controlplane
      - etcd
      - worker

ingress:
  provider: none
```

**Steps to Reproduce:**
Create a cluster using `rke up`, then reboot one of the nodes.

**Results:**
I first thought there was an issue with DNS resolution, as some pods kept crashlooping not being able to resolve backend addresses, but it turns out it's networking related.

After rebooting a node, the node comes back online and all the pods appear to be deployed on it correctly, however, I cannot reach any of the pods on that node from any pod on another node. It simply won't resolve. For services that span multiple nodes, this means that some percentage of calls doesn't resolve at all.

If I `rke remove` and then bring it back up, everything works just fine. This only happens when a node reboots.

I have no special firewall settings on the nodes; policy is ACCEPT on INPUT and OUTPUT. All other rules are created automatically by Docker and Canal.

There are no errors in Canal pods, or CoreDNS pods.

Edit: just for completion: I switched out iptables-nft for iptables-legacy following some recommendation in a much older ticket that seemed vaguely related.
