### ISSUE TITLE
[metrics-server] If generate_serving_certificate is True then do not add --kubelet-insecure-tls

### ISSUE THREAD

**Issue by iridian-ks** [rancher/rke#2846]
**RKE version:**

RKE Version: v1.19.10-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**

```
[root@ulvaqdik8sc01 opt]#  docker info
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 15
  Paused: 0
  Stopped: 4
 Images: 15
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.24.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.62GiB
 Name: ulvaqdik8sc01
 ID: SBKA:4PEW:J4S2:5RMF:V4QU:4GQZ:VD73:GQPP:E5EY:222G:KG6E:GBJ2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled

```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Architecture | amd64
Docker Version | 19.3.15
Kernel Version | 3.10.0-1160.24.1.el7.x86_64
Kubelet Version | v1.19.10
Kube Proxy Version | v1.19.10
Operating System Image | CentOS Linux 7 (Core)
Operating System | linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VMWare

**cluster.yml file:**

```

Version: v3
clusters:
  di-lva-qa:
    answers: {}
    dockerRootDir: /var/lib/docker
    enableNetworkPolicy: false
    fleetWorkspaceName: fleet-default
    localClusterAuthEndpoint:
      enabled: true
    rancherKubernetesEngineConfig:
      addonJobTimeout: 45
      authentication:
        strategy: x509|webhook
      authorization: {}
      bastionHost: {}
      cloudProvider: {}
      dns:
        linearAutoscalerParams:
          coresPerReplica: 128
          min: 1
          nodesPerReplica: 4
          preventSinglePointFailure: true
        nodelocal:
          updateStrategy:
            rollingUpdate:
              maxUnavailable: 0
        updateStrategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 0
      ignoreDockerVersion: false
      ingress:
        defaultBackend: false
        provider: none
      kubernetesVersion: v1.19.10-rancher1-1
      monitoring:
        provider: metrics-server
        replicas: 1
      network:
        options:
          flannel_backend_type: vxlan
        plugin: canal
      restore: {}
      services:
        etcd:
          backupConfig:
            enabled: true
            intervalHours: 12
            retention: 6
            timeout: 300
          creation: 12h
          extraArgs:
            election-timeout: "5000"
            heartbeat-interval: "500"
          retention: 72h
          snapshot: false
        kubeApi:
          secretsEncryptionConfig:
            enabled: true
          serviceNodePortRange: 30000-32767
        kubeController:
          extraArgs:
            cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
            cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
        kubelet:
          generateServingCertificate: true
        kubeproxy: {}
        scheduler: {}
      upgradeStrategy:
        drain: true
        maxUnavailableControlplane: "1"
        maxUnavailableWorker: 33%
        nodeDrainInput:
          deleteLocalData: true
          force: true
          gracePeriod: -1
          ignoreDaemonSets: true
          timeout: 300
    scheduledClusterScan:
      enabled: true
      scanConfig:
        cisScanConfig:
          overrideBenchmarkVersion: rke-cis-1.5
          profile: permissive
      scheduleConfig:
        cronSchedule: 0 0 * * *
        retention: 24
​
```

**Steps to Reproduce:**

Do an RKE install. Set `generate_serving_certificate` and `monitoring` to True.

**Results:**

metrics-server is installed and is unnecessarily using the `--kubelet-insecure-tls` flag. The certs on kubelet are signed by the kube-ca, whose cert can be found in /run/kubernetes/service-account/ca.crt.
