### ISSUE TITLE
Error with kubelet - failed to get cgroup stats for docker.service

### ISSUE THREAD

**Issue by asettouf** [rancher/rke#2859]
**RKE version:** 
v1.3.5

**Docker version: (`docker version`,`docker info` preferred)** 
Docker version 20.10.10, build b485636

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 

Debian GNU/Linux 11 (bullseye)
```
$ uname -r
5.10.0-9-amd64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**

```
cluster_name: REDACTED
ssh_agent_auth: true
nodes:
  - address: REDACTED
    internal_address: REDACTED
    user: REDACTED
    hostname_override: REDACTED
    role:
      - controlplane
      - etcd
      - worker
  - address: REDACTED
    internal_address: REDACTED
    user: REDACTED
    hostname_override: REDACTED
    role:
      - controlplane
      - etcd
      - worker
  - address: REDACTED
    internal_address: REDACTED
    user: REDACTED
    hostname_override: REDACTED
    role:
      - controlplane
      - etcd
      - worker

ingress:
  provider: none

network:
  plugin: weave
```

**Steps to Reproduce:**

Run a RKE cluster following the documentation. Log onto the master. Check the `kubelet` logs (e.g. `docker logs kubelet`), notice:

```
{"log":"E0304 08:25:21.790039 1254022 summary_sys_containers.go:82] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:21.790228872Z"}
{"log":"E0304 08:25:27.053568 1254022 summary_sys_containers.go:47] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:27.053717473Z"}
{"log":"E0304 08:25:36.782447 1254022 summary_sys_containers.go:82] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:36.782667215Z"}
{"log":"E0304 08:25:37.088424 1254022 summary_sys_containers.go:47] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:37.088597744Z"}
{"log":"I0304 08:25:44.387285 1254022 container_manager_linux.go:510] \"Discovered runtime cgroup name\" cgroupName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:44.387486807Z"}
{"log":"E0304 08:25:47.113253 1254022 summary_sys_containers.go:47] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:47.113331873Z"}
{"log":"E0304 08:25:51.775447 1254022 summary_sys_containers.go:82] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:51.775623277Z"}
{"log":"E0304 08:25:57.132109 1254022 summary_sys_containers.go:47] \"Failed to get system container stats\" err=\"failed to get cgroup stats for \\\"/../docker.service\\\": failed to get container info for \\\"/../docker.service\\\": unknown container \\\"/../docker.service\\\"\" containerName=\"/../docker.service\"\n","stream":"stderr","time":"2022-03-04T08:25:57.132211897Z"}
``` 

**Results:**
It's expected to have no errors in this log. Possibly linked to this issue: https://github.com/kubernetes/kubeadm/issues/2077

Of course as `kubelet` runs on `docker` with RKE, it's quite impossible to apply the suggested workarounds that rely on `systemd`

**Comment by AntsInMyEy3sJohnson** [comment]
Same issue here, except it occurs on all nodes (three-node cluster, one as master+worker+etcd, the other two being only worker nodes).

* RKE version: 1.3.7
* Docker version: 20.10.12
* OS: Fedora Server 33
* `uname -r` --> `5.14.18-100.fc33.x86_64`
* Provider of hosts: bare-metal

```
# Docker logs on master node
$ docker logs kubelet
# ...
E0305 14:04:57.220501   44783 summary_sys_containers.go:82] "Failed to get system container stats" err="failed to get cgroup stats for \"/../docker.service\": failed to get container info for \"/../docker.service\": unknown container \"/../docker.service\"" containerName="/../docker.service"
E0305 14:05:04.343207   44783 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/../docker.service\": failed to get container info for \"/../docker.service\": unknown container \"/../docker.service\"" containerName="/../docker.service"
# ...
```

Full `cluster.yml`:

```
nodes:
- address: 192.168.8.119
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: kube-1
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.8.150
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: kube-2
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.8.120
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: kube-3
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: flannel
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.5.0
  alpine: rancher/rke-tools:v0.1.78
  nginx_proxy: rancher/rke-tools:v0.1.78
  cert_downloader: rancher/rke-tools:v0.1.78
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.78
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.17.4
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.17.4
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.17.4
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  coredns: rancher/mirrored-coredns-coredns:1.8.6
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.5
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.21.1
  kubernetes: rancher/hyperkube:v1.22.6-rancher1
  flannel: rancher/mirrored-coreos-flannel:v0.15.1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.21.1
  calico_cni: rancher/mirrored-calico-cni:v3.21.1
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.21.1
  calico_ctl: rancher/mirrored-calico-ctl:v3.21.1
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.21.1
  canal_node: rancher/mirrored-calico-node:v3.21.1
  canal_cni: rancher/mirrored-calico-cni:v3.21.1
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.21.1
  canal_flannel: rancher/mirrored-coreos-flannel:v0.15.1
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.21.1
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.5
  ingress: rancher/nginx-ingress-controller:nginx-1.1.0-rancher1
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1
  metrics_server: rancher/mirrored-metrics-server:v0.5.1
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
  default_ingress_class: null
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null
```

Is this a configuration problem or a bug somewhere in RKE?
