### ISSUE TITLE
Enhancement: Allow specifying ssh_cert and ssh_cert_path globally, instead of per node.

### ISSUE THREAD

**Issue by Laikulo** [rancher/rke#2863]
**RKE version:** 1.3.7

**Docker version: (`docker version`,`docker info` preferred)**  
N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**  
N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** N/A

**cluster.yml file:** N/A

**Steps to Reproduce:** N/A

**Results:** N/A

Currently, it is not possible to specify `ssh_cert` or `ssh_cert_path` at the top level of `cluster.yml`, as can be done for `ssh_key` and `ssh_key_path`. This leads to repetition in `cluster.yml` if all machines are to be accessed with the same certificate.

This request is to add a top-level `ssh_cert` and `ssh_cert_path` that behave the same as `ssh_key` and `ssh_key_path`, in that they provide a default for nodes, but can be overridden per-node.

Because it may be desirable to connect to a node with a key only, it may be prudent to consider explicit nulls or empty strings on individual nodes as requesting no cert.

Something like this might make sense:
```yaml
nodes:
  - address: 192.0.2.1
  - address: 192.0.2.2
  - address: 192.0.2.3
  # This node does not use a cert
  - address: 192.0.2.11
    ssh_key_path: ./weird-node-key
    ssh_cert: ~
  - address: 192.0.2.22
    ssh_key_path: ./strange-node-key
    ssh_cert_path: ./strange-node-key-cert.pub

ssh_key_path: ./ssh-key
ssh_cert_path: ./ssh-key-cert.pub
```

Whereas now, this is specified as:
```yaml
nodes:
  - address: 192.0.2.1
    ssh_key_path: ./ssh-key
    ssh_cert_path: ./ssh-key-cert.pub
  - address: 192.0.2.2
    ssh_key_path: ./ssh-key
    ssh_cert_path: ./ssh-key-cert.pub
  - address: 192.0.2.3
    ssh_key_path: ./ssh-key
    ssh_cert_path: ./ssh-key-cert.pub
  # This node does not use a cert
  - address: 192.0.2.11
    ssh_key_path: ./weird-node-key
    ssh_cert: ~
  - address: 192.0.2.22
    ssh_key_path: ./strange-node-key
    ssh_cert_path: ./strange-node-key-cert.pub
```
