### ISSUE TITLE
Health Endpoint not Available for NGINX Ingress Controller

### ISSUE THREAD

**Issue by Volkimd** [rancher/rke#2891]
**RKE version:** v1.3.7
**Docker version: (`docker version`,`docker info` preferred)** 

```
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 

5.4.0-104-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**: VMWare

**cluster.yml file:** Rancher provisioned
```
answers: {}
default_pod_security_policy_template_id: unrestricted
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: test2
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ignore_proxy_env_vars: false
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy: {}
    options: null
    reversecidrs: null
    stubdomains: null
    tolerations: null
    update_strategy: {}
    upstreamnameservers: null
  enable_cri_dockerd: false
  ignore_docker_version: true
  ingress:
    default_backend: false
    default_ingress_class: true
    http_port: 0
    https_port: 0
    provider: nginx
  kubernetes_version: v1.22.7-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  restore:
    restore: false
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: true
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
```

**Steps to Reproduce:**

Simply build a RKE Cluster. Check NGINX Health port

`curl <worker node>::10254/healthz`

**Results:**

`Connection Refused`

For most of ingress dependent implementation a health endpoint is needed but It seems that in current version the Ingress Controller Daemonset comes up without hostPort. If hostNetwork: true is added health endpoint is available. 

This problem exists only with k8s version higher 1.20
On 1.20 Clusters this port and. endpoint is reachable

**Comment by mghlaiel** [comment]
I'm running into the same issue with the same config using `rke v1.3.8` to create a cluster on EC2

**Comment by bashofmann** [comment]
As a workaround, you could expose the port through a nodeport service:

```
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: ingress-nginx-health
spec:
  type: NodePort
  selector:
    app: ingress-nginx
  ports:
    - port: 10254
      targetPort: 10254
      nodePort: 30007
```

Also, this only affects RKE1. With RKE2 the port is still accessible, also with K8s versions >= 1.21:

```
$ curl https://get.rke2.io | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19421  100 19421    0     0   105k      0 --:--:-- --:--:-- --:--:--  105k
[INFO]  finding release for channel stable
[INFO]  using v1.22.8+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.22.8+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.22.8+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local

$ systemctl start rke2-server

$ curl localhost:10254/healthz
ok
```
