### ISSUE TITLE
etcd snapshots fail to send to s3 when IMDSv2 enabled

### ISSUE THREAD

**Issue by cernst-mx** [rancher/rke#2959]
RKE version:  v1.3.1

Docker version: 20.10.12

Operating system and kernel: Ubuntu 18.04.06 (5.4.0-1068-aws)

Type/provider of hosts: AWS EC2 with IMDSv2 enabled

cluster.yml file (relevant section):
```
services:
  etcd:
    backup_config: 
      enabled: true
      interval_hours: 12
      retention: 10
      s3backupconfig:
        bucket_name: <valid s3 bucket>
        folder: <valid folder in bucket>
        endpoint: "s3.amazonaws.com"
        region: <valid AWS region>
```

Steps to Reproduce:
1) Create a cluster with EC2 nodes with IMDSv2 enabled.
2) Enable s3backupconfig as above.
3) Ensure node has appropriate access to s3 bucket via IAM instance role.
4) Create and etcd snapshot.
5) Snapshot will be created locally, but fail to upload to s3.

Results:
Logs for snapshot container show "`failed to set s3 server: failed to check s3 bucket: <bucket name> err:401`"

After a little research, in appears that v6 of minio-go s3utils used by rke-tools simply doesn't support IMDSv2.  In order to properly support IMDSv2, minio-go >= v7.0.13 is required.
