### ISSUE TITLE
Question: configure network plugin cpu limit

### ISSUE THREAD

**Issue by belfhi** [rancher/rke#2973]
I have a cluser that is giving me CPU throttling
alterts for the pods in the flannel daemonset.
How do I increase / set the limits?
I presume it would happen in the `network` section of the cluster YAML?

```
network:
  plugin: "flannel"
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
```
Is there a way to configure this with RKE while the cluster is running or should I manually 
edit the daemonset with increased values and lose the config when I upgrade the k8s version
later on?

**Comment by carlosrodfern** [comment]
We are needing the same feature. Flannel is being cpu bandwidth throttled significantly in our system. We would like to increase the cpu limit of the flannel daemonset pods in the RKE yaml itself.

**Comment by carlosrodfern** [comment]
The cpu limit are hard-coded here: https://github.com/rancher/rke/blob/release/v1.4/data/data.json
```
        - --ip-masq
        - --kube-subnet-mgr
        {{- if .FlannelInterface}}
        - --iface={{.FlannelInterface}}
        {{end}}
        resources:
          requests:
            cpu: \"100m\"
            memory: \"50Mi\"
          limits:
            cpu: \"100m\"
            memory: \"50Mi\"
        securityContext:
          privileged: false
          capabilities:
             add: [\"NET_ADMIN\"]
        env:
        - name: POD_NAME
          valueFrom:
```
It may be a matter of making it an option and use it in this go-template. I noticed the newer versions of flannel listed in the data.json does increase the cpu limit to 300m.
