### ISSUE TITLE
[RKE] Ignore/Remove user-addons after initially providing them

### ISSUE THREAD

**Issue by Moep90** [rancher/rke#2976]
When we initially setup our RKE-Cluster we had to provide our addons via local files.

Nowdays we provide them elsewhere.
In the meantime we had updated the addons via something like helm-chart directly while not updating the cluster)

This leaves the files provided in `addons_include:` obsolet. Therefore we removed the whole section (while thinking this will dont harm anything.

# Applying an RKE upgrade
After removing the `addons_include:` section we found out that RKE removes all resources from the cluster which are not in `addons_include:` anymore.
Therfore please provide me with a solution how I can get RID of the `addons_include:` section....

**RKE version:**
```
$ rke --version
rke version v1.3.12
```
**Docker version: (`docker version`,`docker info` preferred)**

```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$  cat cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -r
5.10.0-15-amd64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
* VMware 7.x VM

**cluster.yml file:**
```yaml
cluster_name: k8s-nodes-cluster
ssh_key_path: /home/myuser/.ssh/id_rsa
kubernetes_version: "v1.21.13-rancher1-1"

nodes:
  - address: 1.2.3.50
    user: myuser
    role: [controlplane,worker,etcd]
    port: 10022
  - address: 1.2.3.51
    user: myuser
    role: [controlplane,worker,etcd]
    port: 10022
  - address: 1.2.3.52
    user: myuser
    role: [controlplane,worker,etcd]
    port: 10022
  - address: 1.2.3.53
    user: myuser
    role: [worker]
    port: 10022
  - address: 1.2.3.54
    user: myuser
    role: [worker]
    port: 10022
  - address: 1.2.3.55
    user: myuser
    role: [worker]
    port: 10022
  - address: 1.2.3.56
    user: myuser
    role: [worker]
    port: 10022
  - address: 1.2.3.57
    user: myuser
    role: [worker]
    port: 10022
authentication:
    strategy: x509
    sans:
      - "k8s-nodes-cluster"
      - "k8s-node-01.example.com"
      - "1.2.3.50"
      - "k8s-node-02.example.com"
      - "1.2.3.51"
      - "k8s-node-03.example.com"
      - "1.2.3.52"
      - "k8s-node-04.example.com"
      - "1.2.3.53"
      - "k8s-node-05.example.com"
      - "1.2.3.54"
      - "k8s-node-06.example.com"
      - "1.2.3.55"
      - "k8s-node-07.example.com"
      - "1.2.3.56"
      - "k8s-node-08.example.com"
      - "1.2.3.57"
services:
  kubelet:
    extra_args:
      # Should not be exceeded: https://github.com/rancher/rke/issues/1298
      max-pods: 250
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
  kube-api:
[...]


# Specify DNS provider (coredns or kube-dns)
dns:
  provider: coredns


# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: none

# Add-ons are deployed using kubernetes jobs. RKE will give
# up on trying to get the job status after this timeout in seconds..
addon_job_timeout: 120

addons: ""
addons_include:
  - /home/myuser/k8s-addon-rook/common.yaml
  - /home/myuser/k8s-addon-rook/operator.yaml
  - /home/myuser/k8s-addon-rook/toolbox.yaml
  - /home/myuser/k8s-addon-rook/cluster.yaml
  - /home/myuser/k8s-addon-rook/csi/rbd/storageclass.yaml
  - /home/myuser/k8s-addon-rook/csi/rbd/snapshotclass.yaml

```
**Steps to Reproduce:**
```
$ rke up --config rancher-cluster.yml --update-only
```
**Results:**

**Comment by Moep90** [comment]
Any advise?

**Comment by Moep90** [comment]
@jiaqiluo do you have an idea how I can tackle this?

**Comment by Moep90** [comment]
Still waiting for any kind of Feedback

**Comment by Moep90** [comment]
Hey guys, thanks for the apprechiated feedback so far.

I figured a (hacky) way out now....

1. comment the `addons:` and/or `addons_include:` section within the rke config file `rancher-cluster.yml` in my case
2. kubectl edit cm both `rke-user-addon`and `rke-user-includes-addons`and remove the relevant sections, in my case I just had `""` left so for example it looked like `rke-user-addon: ""`
3. patch your full-cluster-state `k get -n kube-system configmap full-cluster-state -o yaml > rkestate.yml`
4. remove the `addons`and `addons_include` sections from `rkestate.yml`
5. `kubectl apply -n kube-system -f rkestate.yml` 
6. run `rke up --config rancher-cluster.yml`

I tested this deploying this
```yaml
addons: |-
   ---
   apiVersion: v1
   kind: Pod
   metadata:
     name: addons-nginx
     namespace: default
   spec:
     containers:
     - name: my-nginx
       image: nginx
       ports:
       - containerPort: 80
addons_include:
 - ./addons_include.yml
```

And after doing 1 to 6 it looked like this
```yaml
#addons: |-
#    ---
#    apiVersion: v1
#    kind: Pod
#    metadata:
#      name: addons-nginx
#      namespace: default
#    spec:
#      containers:
#      - name: my-nginx
#        image: nginx
#        ports:
#        - containerPort: 80
#addons_include:
#  - ./addons_include.yml
```

this again at the end resulted in this
```
[...]
INFO[0055] [addons] Setting up user addons              
INFO[0055] [addons] Removing user addons                
INFO[0071] [addons] User addons removed successfully    
INFO[0086] [addons] no user addons defined              
INFO[0086] Finished building Kubernetes cluster successfully 

$ kubectl get po -n default
NAME                       READY   STATUS    RESTARTS   AGE
addons-include-nginx       1/1     Running   0          60m
addons-nginx               1/1     Running   0          60m
```

.... which was the expected outcome..
