### ISSUE TITLE
Add support for iface-regex options in flannel/canal

### ISSUE THREAD

**Issue by germanoeich** [rancher/rke#2996]
flanneld has support for the `iface-regex` option, but this is not available in the rancher network config options. This forces operators to either modify the DaemonSet manually, which is very fragile, or enforce a consistent interface name across all nodes within the cluster, which may not always be feasible and is error prone.

This has been asked multiple times:
https://github.com/rancher/rke/issues/2577 - Marked as stale and closed
https://github.com/rancher/rancher/issues/17180 - Opened since 2018

Can I get a confirmation on if you plan to support this and/or if you would accept PRs relating to this?

**Comment by steve-todorov** [comment]
Yes! YES PLEASE!!!! 

I have a custom bash script which starts `rke` and then does a very nasty patch to fix some issues:

```
  echo "Patch flannel deployment to add iface-regex so it uses the correct interfaces for flannel external traffic"  > /dev/null
  IFACE1_REGEX="192\.0\.0\.*"
  IFACE2_REGEX="192\.8\.1\.*"
  (kubectl get daemonsets.apps --namespace=kube-system canal -o yaml | yq e '(.spec.template.spec.containers.[] | select(.name == "kube-flannel")).command |= ["/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface-regex='$IFACE1_REGEX'", "--iface-regex='$IFACE2_REGEX'"]' - | kubectl apply -f -)
```

It would make my life so much, much, MUCH easier if there was an option you could put in the `services` section that would ... maybe something like:

```yaml
network:
  plugin: canal
  options:
    flannel_backend_type: vxlan
    flannel_iface: flannel.1
    flannel_iface_regex: [ "192\.0\.0\.*", "192\.8\.1\.*", ... ]
```
