### ISSUE TITLE
RKE - Add support for provisioning 1.25 clusters

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#3034]
TODOs:

- [x] bump Go packages to the lastest for 1.25.2 or newer  
- [x] bring in and test the updated KDM and maker sure provisioning and upgrading to 1.25 cluster succeeds 
- [x] add the support for PSA. See the below for details

--- 

# Design 

RKE will provide two pre-defined `AdmissionConfiguration`s: `privileged` and `restricted`.
To use the `AdmissionConfiguration`, RKE will provide a new field in the cluster configuration:  `service.kube-api.pod_security_admission_configuration`. 

Example:
```
# cluster.yml 
nodes:
  - address: xxx.xxx.xx.xx
    internal_address: xxx.xxx.xx.xx
    user: ubuntu
    role: [controlplane,worker,etcd] 
rotate_encryption_key: false
kubernetes_version: v1.25.2-rancher1-1
services:
  kube-api:
    pod_security_admission: privileged
```

RKE also supports using customized configuration vai `kube-api.admission_configuration`. The extra argument will be used if both are set.
```
# cluster.yml 
services:
  kube-api:
    admission_configuration:
      apiVersion: apiserver.config.k8s.io/v1
      kind: AdmissionConfiguration
      plugins:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1
          kind: PodSecurityConfiguration
          defaults:
            enforce: "privileged"
            enforce-version: "latest"
            ...
          exemptions:
            usernames: []
            runtimeClasses: []
            namespaces: []
```

## Scenario: Create a new cluster whose k8s version is >= 1.25:

- If PSP is set in the cluster.yml file, RKE will exit with the error message: "Pod Security Policy is removed since 1.25, please disable pod_security_policy and try again" 
- If `service.kube-api.pod_security_admission_configuration` is set, RKE will check if its value is valid:
	- If the value is not `privileged` or `restricted`, RKE will exit with the error message: "Invalid setting for pod_security_admission, supported values are 'privileged' and 'restricted'"  
	- If the value is valid, RKE will create a file for the chosen configuration, and pass its path to the flag `admission-control-config-file` on  the `kube-apiserver` binary 
- If the exra_args is set, RKE will pass its value to the flag `admission-control-config-file` on the `kube-apiserver` binary
- If both the `service.kube-api.pod_security_admission_configuration`  and the exra_args are set,  RKE will use the value from the exra_args.

## Scenario: Create a new cluster whose k8s version is <= 1.24:
- if PSP is set in the cluster.yml file, RKE will behave the same as it is today for PSP 
- if PSA-related fields are set, RKE will behave the same as it does for cluster >= 1.25 

Note: RKE 1.4 will support k8s >= 1.23; therefore we do not need to worry whether the Pod Security Admission is enabled or not because it is enabled by default since k8s 1.22

## Scenario: Upgrade a cluster from  <=1.24  to >=1.25:
RKE will behave the same as it does for creating a new  >= 1.25 cluster.
Additionally,  if resources of the kind `PodSecurityPolicy` are detected in the cluster, RKE will show a warning message in logs "Warning: the PodSecurityPolicy resources left in the cluster will be lost after upgrading" 

## Scenario: Edit a cluster whose k8s version is >= 1.25:
RKE will behave the same as it does for creating a new  >= 1.25 cluster.

Here is the YAML file of the pre-defined AdmissionConfiguration:  `privileged` and `restricted`  
```
# restricted
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "restricted"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: [kube-system, cattle-system, fleet-system]
```

```
# privileged
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "privileged"
      enforce-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: []
```
