### ISSUE TITLE
IP_AUTODETECTION_METHOD can't be change from cluster.yml and cluster not working with new network cards

### ISSUE THREAD

**Issue by XDavidT** [rancher/rke#3044]
**Issue:** After adding network cards to some of the nodes, and running `rke up --update-only` the calico daemon-set configure the wrong interface. 
The issue is one of the env variables configured automatically: 
```
            - name: IP_AUTODETECTION_METHOD
              value: cidr=10.200.10.102/16
```
which suppose to have another segment: `10.200.10.0/24`
After I tried to edit the Daemon set manually - it's rolled back to the original one.
1. Is any other service controlling the Daemon set? How it's rolling back to old values after editing?
2. How to configure it right to have the new segment? Is there an option to add configuration for that under the 'cluster.yml'?

**Steps to Reproduce:**
1. Have a cluster working
2. add new network cards for some of the nodes
3. running `rke up --update-only` and watch daemon set
4. Watch the calico pod events
**Results:**

> Events:
>   Type     Reason     Age                   From               Message
>   ----     ------     ----                  ----               -------
>   Normal   Scheduled  23m                   default-scheduler  Successfully assigned calico-system/calico-node-bkmt6 to b10
>   Normal   Pulled     23m                   kubelet            Container image "docker.io/calico/pod2daemon-flexvol:v3.18.1" already present on machine
>   Normal   Created    23m                   kubelet            Created container flexvol-driver
>   Normal   Started    23m                   kubelet            Started container flexvol-driver
>   Normal   Started    23m                   kubelet            Started container install-cni
>   Normal   Created    23m                   kubelet            Created container install-cni
>   Normal   Pulled     23m                   kubelet            Container image "docker.io/calico/cni:v3.18.1" already present on machine
>   Normal   Killing    22m                   kubelet            Container calico-node failed liveness probe, will be restarted
>   Normal   Created    22m (x2 over 23m)     kubelet            Created container calico-node
>   Normal   Started    22m (x2 over 23m)     kubelet            Started container calico-node
>   Warning  Unhealthy  22m (x4 over 23m)     kubelet            Liveness probe failed: Get "http://localhost:9099/liveness": dial tcp 127.0.0.1:9099: connect: connection refused
>   Normal   Pulled     18m (x7 over 23m)     kubelet            Container image "docker.io/calico/node:v3.18.1" already present on machine
>   Warning  Unhealthy  8m12s (x60 over 23m)  kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
>   Warning  BackOff    3m11s (x76 over 20m)  kubelet            Back-off restarting failed container
> 

**RKE version:** v1.3.14

**Docker version: (`docker version`,`docker info` preferred)** 
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:17 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 nvidia:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**cluster.yml file:**
```
cluster_name: cnvrg
nodes:
  - address: 10.200.10.101
    internal_address: 10.200.10.101
    hostname_override: b1
    user: rancher
    role:
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: turing
      gpus: 2xTRTX
      jobs: gen
      ngpus: "2"
  - address: 10.200.10.102
    internal_address: 10.200.10.102
    hostname_override: b2
    user: rancher
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      cnvrg: cnvrg-controlplane
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: pascal
      gpugen: pascal
      jobs: gen
      ngpus: "2"
  - address: 10.200.10.103
    internal_address: 10.200.10.103
    hostname_override: b3
    user: rancher
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      cnvrg: cnvrg-controlplane
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: pascal
      gpugen: pascal
      jobs: gen
      ngpus: "2"
      gpu_type: titan_xp
  - address: 10.200.10.104
    internal_address: 10.200.10.104
    hostname_override: b4
    user: rancher
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      cnvrg: cnvrg-controlplane
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: pascal
      gpugen: pascal
      jobs: gen
      ngpus: "2"
  - address: 10.200.10.105
    internal_address: 10.200.10.105
    hostname_override: b5
    user: rancher
    role:
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: pascal
      gpugen: pascal
      jobs: gen
      ngpus: "2"
      suspend: ""
  - address: 10.200.10.106
    internal_address: 10.200.10.106
    hostname_override: b6
    user: rancher
    role:
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: pascal
      gpugen: pascal
      jobs: gen
      ngpus: "2"
      gpus: ""
  - address: 10.200.10.108
    internal_address: 10.200.10.108
    hostname_override: b8
    user: rancher
    role:
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      accelerator: nvidia
      cicd: "1"
      cuda: "11"
      gpu_gen: turing
      ngpus: "8"
      gpus: V100
  - address: 10.200.10.109
    internal_address: 10.200.10.109
    hostname_override: b9
    user: rancher
    role:
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      accelerator: nvidia
      cicd: "1"
      cuda: "11"
      gpu_gen: turing
      gpus: 2080ti
      ngpus: "2"
  - address: 10.200.10.110
    internal_address: 10.200.10.110
    hostname_override: b10
    user: rancher
    role:
      - worker
    ssh_key_path: ~/id_rsa
    labels:
      accelerator: nvidia
      cicd: "1"
      cnvrg-general-purpose: "true"
      cuda: "11"
      gpu_gen: turing
      gpus: 2xTRTX
      jobs: gen
      ngpus: "8"

services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 30000-32767
    pod_security_policy: false #
    always_pull_images: false #
    secrets_encryption_config: #
      enabled: false
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false

network:
  plugin: none
ingress: 
  provider: none
dns:
  provider: coredns
  node_selector:
    cnvrg: cnvrg-controlplane

monitoring:
  node_selector:
    cnvrg: cnvrg-controlplane

```
