### ISSUE TITLE
Unable to build 3 node cluster with 3 etcd/cp roles

### ISSUE THREAD

**Issue by impsik** [rancher/rke#3072]
**RKE version:**
`rke version v1.3.14 also rke version v1.3.15`
**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Kernel: 5.4.0-90-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM
**cluster.yml file:**
```
kubernetes_version: v1.24.4-rancher1-1
nodes:

  - address: 192.168.122.34
    user: user
    role: [controlplane,etcd,worker]
  - address: 192.168.122.35
    user: user
    role: [controlplane,etcd,worker]
  - address: 192.168.122.36
    user: user
    role: [controlplane,etcd,worker]

cluster_name: testing
services:
  etcd:
    snapshot: true
    creation: 2h
    retention: 24h
    extra_args:
      enable-v2: "true"
    kubelet:
      fail_swap_on: false
      extra_args:
        max-pods: 250
        cloud-provider: "external"
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
```
**Steps to Reproduce:**
Clean 3 VMs, docker installed etc. Use above cluster.yml.
**Results:**
```
WARN[0344] [etcd] host [192.168.122.34] failed to check etcd health: failed to get /health for host [192.168.122.34]: Get "https://192.168.122.34:2379/health": net/http: TLS handshake timeout 
WARN[0624] [etcd] host [192.168.122.35] failed to check etcd health: failed to get /health for host [192.168.122.35]: Get "https://192.168.122.35:2379/health": net/http: TLS handshake timeout 
WARN[0904] [etcd] host [192.168.122.36] failed to check etcd health: failed to get /health for host [192.168.122.36]: Get "https://192.168.122.36:2379/health": net/http: TLS handshake timeout 
FATA[0904] [etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [192.168.122.34,192.168.122.35,192.168.122.36] failed to report healthy. Check etcd container logs on each host for more information
```
`{"level":"warn","ts":"2022-10-16T08:12:52.591Z","caller":"embed/config_logging.go:160","msg":"rejected connection","remote-addr":"192.168.122.1:36568","server-name":"","ip-addresses":["192.168.122.34","192.168.122.35","192.168.122.36","127.0.0.1","10.43.0.1"],"dns-names":["localhost","kubernetes","kubernetes.default","kubernetes.default.svc","kubernetes.default.svc.cluster.local"],"error":"tls: \"192.168.122.1\" does not match any of DNSNames [\"localhost\" \"kubernetes\" \"kubernetes.default\" \"kubernetes.default.svc\" \"kubernetes.default.svc.cluster.local\"] (lookup kubernetes.default.svc.cluster.local on 127.0.0.53:53: server misbehaving)"}`

When i have only one VM with controlplane,etcd,worker roles then cluster is built up.
In docs Rancher has similar cluster.yml: [LINK](https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-rke/)
