### ISSUE TITLE
Unable to run rke up with AWS EC2 nodes

### ISSUE THREAD

**Issue by bkonick** [rancher/rke#3091]
I am able to run the same `rke up` command with the same `cluster.yml` on RKE 1.2 without issues. Using RKE 1.3, there is always a failure.

**RKE version:**

1.3.15

**Docker version: (`docker version`,`docker info` preferred)** 

`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:57 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:16:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

`docker info`
```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 26
  Running: 22
  Paused: 0
  Stopped: 4
 Images: 18
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.209-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.02GiB
 Name: rancher-controller-REDACTED
 ID: 4DG5:P642:PSTG:UAZJ:4Q4Q:J3CZ:6DQX:HL6S:EL7T:BW5Q:OU53:HXIT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

`cat /etc/os-release`
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

`uname -r`
```
5.4.209-1.el7.elrepo.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS EC2 m6i.xlarge

**cluster.yml file:**

```yaml
addon_job_timeout: 0
addons: ""
addons_include: []
authentication:
  sans:
  - api.rancher.REDACTED
  strategy: x509
  webhook: null
authorization:
  mode: ""
  options: {}
bastion_host:
  address: ""
  ignore_proxy_env_vars: false
  port: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ssh_key: ""
  ssh_key_path: ""
  user: ""
cloud_provider:
  name: aws
cluster_name: rancher
dns: null
enable_cri_dockerd: false
ignore_docker_version: false
ingress:
  default_backend: true
  default_http_backend_priority_class_name: ""
  default_ingress_class: null
  dns_policy: ""
  extra_args: {}
  extra_envs: []
  extra_volume_mounts: []
  extra_volumes: []
  http_port: 80
  https_port: 443
  network_mode: hostNetwork
  nginx_ingress_controller_priority_class_name: ""
  node_selector: {}
  options:
    use-forwarded-headers: "true"
  provider: nginx
  tolerations: []
  update_strategy: null
kubernetes_version: v1.20.12-rancher1-1
monitoring:
  metrics_server_priority_class_name: ""
  node_selector: {}
  options: {}
  provider: ""
  replicas: null
  tolerations: []
  update_strategy: null
network:
  mtu: 0
  node_selector: {}
  options: {}
  plugin: ""
  tolerations: []
  update_strategy: null
nodes:
- address: x.x.x.215
  docker_socket: ""
  hostname_override: ""
  internal_address: x.x.x.215
  labels: {}
  nodeName: rancher-controller-i-******.REDACTED
  port: ""
  role:
  - controlplane
  - worker
  - etcd
  ssh_agent_auth: true
  ssh_cert: ""
  ssh_cert_path: ""
  ssh_key: ""
  ssh_key_path: ""
  taints: []
  user: centos
- address: x.x.x.5
  docker_socket: ""
  hostname_override: ""
  internal_address: x.x.x.5
  labels: {}
  nodeName: rancher-controller-i-******.REDACTED
  port: ""
  role:
  - controlplane
  - worker
  - etcd
  ssh_agent_auth: true
  ssh_cert: ""
  ssh_cert_path: ""
  ssh_key: ""
  ssh_key_path: ""
  taints: []
  user: centos
- address: x.x.x.66
  docker_socket: ""
  hostname_override: ""
  internal_address: x.x.x.66
  labels: {}
  nodeName: rancher-controller-i-******.REDACTED
  port: ""
  role:
  - controlplane
  - worker
  - etcd
  ssh_agent_auth: true
  ssh_cert: ""
  ssh_cert_path: ""
  ssh_key: ""
  ssh_key_path: ""
  taints: []
  user: centos
- address: x.x.x.75
  docker_socket: ""
  hostname_override: ""
  internal_address: x.x.x.75
  labels: {}
  nodeName: rancher-controller-i-******.REDACTED
  port: ""
  role:
  - controlplane
  - worker
  - etcd
  ssh_agent_auth: true
  ssh_cert: ""
  ssh_cert_path: ""
  ssh_key: ""
  ssh_key_path: ""
  taints: []
  user: centos
- address: x.x.x.32
  docker_socket: ""
  hostname_override: ""
  internal_address: x.x.x.32
  labels: {}
  nodeName: rancher-controller-i-******.REDACTED
  port: ""
  role:
  - controlplane
  - worker
  - etcd
  ssh_agent_auth: true
  ssh_cert: ""
  ssh_cert_path: ""
  ssh_key: ""
  ssh_key_path: ""
  taints: []
  user: centos
prefix_path: ""
private_registries: []
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
services:
  etcd:
    backup_config:
      enabled: true
      interval_hours: 2
      retention: 96
      s3backupconfig:
        access_key: ""
        bucket_name: REDACTED
        custom_ca: ""
        endpoint: s3.amazonaws.com
        folder: rancher/etcd
        region: us-east-1
        secret_key: ""
      safe_timestamp: false
      timeout: 300
    ca_cert: ""
    cert: ""
    creation: 12h
    external_urls: []
    extra_args:
      election-timeout: "5000"
      heartbeat-interval: "500"
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    gid: 0
    image: rancher/mirrored-coreos-etcd:v3.4.15-rancher1
    key: ""
    path: ""
    retention: 72h
    snapshot: true
    uid: 0
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kube-api:
    admission_configuration: null
    always_pull_images: false
    audit_log:
      configuration:
        format: json
        max_age: 14
        max_backup: 14
        max_size: 250
        path: /var/log/kube-audit/audit-log.json
        policy:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          metadata:
            creationTimestamp: null
          rules:
          - level: RequestResponse
            resources:
            - resources:
              - pods
      enabled: true
    event_rate_limit: null
    extra_args:
      service-account-issuer: kubernetes/serviceaccount
      service-account-signing-key-file: /etc/kubernetes/ssl/kube-service-account-token-key.pem
    extra_args_array: {}
    extra_binds: []
    extra_env:
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_AUDITLOG_CONFIG_CHECKSUM=d36bdce4fae1b3566d8138f67f5d9ebc
    image: rancher/hyperkube:v1.20.12-rancher1
    pod_security_policy: false
    secrets_encryption_config:
      custom_config: null
      enabled: true
    service_cluster_ip_range: 10.10.0.0/16
    service_node_port_range: 30000-32767
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kube-controller:
    cluster_cidr: 10.8.0.0/16
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env:
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    image: rancher/hyperkube:v1.20.12-rancher1
    service_cluster_ip_range: 10.10.0.0/16
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    cluster_dns_server: 10.10.10.10
    cluster_domain: k8s.REDACTED
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    fail_swap_on: false
    generate_serving_certificate: false
    image: rancher/hyperkube:v1.20.12-rancher1
    infra_container_image: rancher/mirrored-pause:3.2
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kubeproxy:
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    image: rancher/hyperkube:v1.20.12-rancher1
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  scheduler:
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    image: rancher/hyperkube:v1.20.12-rancher1
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
ssh_agent_auth: true
ssh_cert_path: ""
ssh_key_path: ""
system_images:
  aci_cni_deploy_container: ""
  aci_controller_container: ""
  aci_gbp_server_container: ""
  aci_host_container: ""
  aci_mcast_container: ""
  aci_opflex_container: ""
  aci_opflex_server_container: ""
  aci_ovs_container: ""
  alpine: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  calico_flexvol: ""
  calico_node: ""
  canal_cni: ""
  canal_controllers: ""
  canal_flannel: ""
  canal_flexvol: ""
  canal_node: ""
  cert_downloader: ""
  coredns: ""
  coredns_autoscaler: ""
  dnsmasq: ""
  etcd: ""
  flannel: ""
  flannel_cni: ""
  ingress: ""
  ingress_backend: ""
  ingress_webhook: ""
  kubedns: ""
  kubedns_autoscaler: ""
  kubedns_sidecar: ""
  kubernetes: ""
  kubernetes_services_sidecar: ""
  metrics_server: ""
  nginx_proxy: ""
  nodelocal: ""
  pod_infra_container: ""
  weave_cni: ""
  weave_node: ""
  windows_pod_infra_container: ""
upgrade_strategy:
  drain: true
  max_unavailable_controlplane: "1"
  max_unavailable_worker: 10%
  node_drain_input:
    delete_local_data: true
    force: true
    grace_period: 120
    ignore_daemonsets: false
    timeout: 0
win_prefix_path: ""
```

**Steps to Reproduce:**

- Run `rke up` with RKE 1.3.15

**Results:**

```
...SNIP...
ERRO[0166] Failed to upgrade hosts: x.x.x.215 with error [[controlplane] Error getting node x.x.x.215:  "x.x.x.215" not found]
FATA[0166] [controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node x.x.x.215:  "x.x.x.215" not found]]
```
