### ISSUE TITLE
Request to specify custome kubelet flags in cluster.yaml

### ISSUE THREAD

**Issue by MayankTahil** [rancher/rke#310]
What's the recommended way to add flags to kubelet in an already deployed k8 cluster?
Not quite sure how to follow [these directions]( https://rook.github.io/docs/rook/master/flexvolume.html) given I can't see where in cluster.yaml file I can add additional flags.

**RKE version:**

Next

**Docker version: (`docker version`,`docker info` preferred)**

17.03.x-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

RancherOS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Baremetal

**cluster.yml file:**

```
---
auth:
  strategy: x509
  options:
    foo: bar

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS, use the network plugin config option:
# 'calico_cloud_provider: aws'
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

ssh_key_path: ./mgmt.key
ignore_docker_version: false
# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization
authorization:
  mode: rbac
  options:

nodes:
  - address: 192.168.10.116
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.117
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.118
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    **flags: 
     - --volume-plugin-dir=/var/lib/kubelet/volumeplugins**
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0
```

**Steps to Reproduce:**

N/A

**Results:**

N/A
