### ISSUE TITLE
enforce_docker_version has no effect

### ISSUE THREAD

**Issue by stefanvangastel** [rancher/rke#311]
**RKE version:**
`rke version v0.1.1-rc1`

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
Version:      17.09.0-ce
API version:  1.32
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:42:45 2017
OS/Arch:      linux/amd64
 
Server:
Version:      17.09.0-ce
API version:  1.32 (minimum version 1.12)
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:41:24 2017
OS/Arch:      linux/amd64
Experimental: false
--------------------------------------
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
apparmor
seccomp
  Profile: default
Kernel Version: 4.13.0-16-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.856GiB
Name: ubuntu
ID: GN6H:6OHL:NCSZ:WDCT:BS2O:3X3A:OEQW:UWYX:EMGV:LHGP:OTHV:M4CY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
 
WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 17.10

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack VM

**cluster.yml file:**
```
---
network:
  plugin: flannel
  options:
    flannel_image: my.private.registry/docker/rke/flannel:v0.9.1
    flannel_cni_image: my.private.registry/docker/rke/flannel-cni:v0.2.0
 
enforce_docker_version: false
 
nodes:
  - address: 10.x.x.8
    user: user
    ssh_key_path: /home/users/myuser/key.pem
    role: [controlplane,etcd]
  - address: 10.x.x.14
    user: user
    ssh_key_path: /home/users/myuser/key.pem
    role: [worker]
  - address: 10.x.x.20
    user: user
    ssh_key_path: /home/users/myuser/key.pem
    role: [worker]
  - address: 10.x.x.24
    user: user
    ssh_key_path: /home/users/myuser/key.pem
    role: [worker]
 
services:
  etcd:
    image: my.private.registry/docker/rke/etcd:latest
  kube-api:
    image: my.private.registry/docker/rke/rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: my.private.registry/docker/rke/rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: my.private.registry/docker/rke/rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: my.private.registry/docker/rke/rancher/k8s:v1.8.3-rancher2
    infra_container_image: my.private.registry/docker/rke/pause-amd64:3.0
  kubeproxy:
    image: my.private.registry/docker/rke/rancher/k8s:v1.8.3-rancher2
 
system_images:
  alpine: my.private.registry/docker/rke/alpine:latest
  nginx_proxy: my.private.registry/docker/rke/rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: my.private.registry/docker/rke/rancher/rke-cert-deployer:v0.1.1
  service_sidekick_image: my.private.registry/docker/rke/rancher/rke-service-sidekick:v0.1.0
  kubedns_image: my.private.registry/docker/rke/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: my.private.registry/docker/rke/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: my.private.registry/docker/rke/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: my.private.registry/docker/rke/cluster-proportional-autoscaler-amd64:1.0.0
```

**Steps to Reproduce:**
Run `cluster.yml`

**Results:**
Docker version is **not** ignored:

```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [10.x.x.8]
FATA[0000] Failed to set up SSH tunneling for Etcd host [10.x.x.8]: Unsupported Docker version found [17.09.0-ce], supported versions are [1.12.6 1.13.1 17.03.2]
```
