### ISSUE TITLE
Success in Approving Certificate but Fail in Issuing Certificate using kubectl certificate

### ISSUE THREAD

**Issue by nizarakbarm** [rancher/rke#3156]
**RKE version:** v1.4.2

**Docker version:** 20.10.23

**Operating system and kernel:** Ubuntu 22.04 kernel 5.15.0-25-generic

**Type/provider of hosts:** vm at opennebula

**cluster.yml file:**
```
nodes:
- address: ip
  role: [controlplane, worker, etcd]
  user: findnull
  hostname_override: node1
- address: ip2
  role: [controlplane, worker, etcd]
  user: findnull
  hostname_override: node2
- address: ip3
  role: [controlplane, worker, etcd]
  user: findnull
  hostname_override: node3

cluster_name: rke

ignore_docker_version: false
kubernetes_version: v1.23.12-rancher1-1

services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
    snapshot: true
    creation: 6h
    retention: 24h

kube-api:
  service_cluster_ip_range: 10.43.0.0/16
  service_node_port_range: 30000-32767
  pod_security_policy: false

kube-controller:
  cluster_cidr: 10.42.0.0/16
  service_cluster_ip_range: 10.43.0.0/16
  extra_args:
    cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
    cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem

kubelet:
  #cluster_domain: cluster.local
  #cluster_dns_server: 10.43.0.10
  fail_sawp_on: false
  generate_serving_certificate: false
  #extra_args:
    #max-pods: 150

network:
  plugin: canal
  options:
    canal_iface: eth1
    cannal_flannel_backend_type: vxlan
    flannel_iface: eth1
  mtu: 0
  canal_network_provider:
    iface: eth1
  flannel_network_provider:
    iface: eth1
  node_selector: {}
  update_strategy: null


dns:
  provider: coredns

authentication:
  strategy: x509

authorization:
  mode: rbac

ingress:
  provider: nginx
  options:
    user-forwarded-headers: "true"
```

**Steps to Reproduce:**
create key:
```
openssl genrsa -out apicall.key
```
create crs:
```
openssl req -new -key apicall.key -out apicall.csr -subj "/CN=apicall/O=system:authenticated/O=system:master/"
```
get crs in base64:
```
cat apicall.csr | base64 | tr -d '\n'
```
create CertificateSigningRequest:
```
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: apicall
spec:
  groups:
  - system:authenticated
  request: [fill with result of base64 encoding of csr]
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000
  usages:
  - digital signature
  - key encipherment
  - client auth
```
apply configuration to kubernetes:
```
kubectl apply -f apicall-csr.yaml
```
approve certificate:
```
kubectl certificate approve apicall
```

**Results:**
![gambar](https://user-images.githubusercontent.com/12729998/216029615-735050e8-5a1e-4c4c-ba3f-f1fc6a9fdfea.png)

And the certificate is not created too:
![gambar](https://user-images.githubusercontent.com/12729998/216029879-3b30b50b-e185-4559-8b01-98cddd5b0346.png)

I try to apply this csr to non rke k8s and it is success, but when using rke the certificate is not issued.
