### ISSUE TITLE
rke1.4.4 upgrade calico to 3.24.1 rbac missing permissions

### ISSUE THREAD

**Issue by yangzinan** [rancher/rke#3221]
After the upgrade, ClusterRole calico-node is missing the following content causing install_cni not to start

```
    - apiGroups: [""]
      resources:
        - serviceaccounts/token
      resourceNames:
        - calico-node
      verbs:
        - create
 ```
ipamconfigs Missing creation permission

```
    - apiGroups: ["crd.projectcalico.org"]
      resources:
        - ipamconfigs
      verbs:
        - get
        - create
```
I now use addons to remedy this problem
I don't know if direct installation will also have this problem
