### ISSUE TITLE
Host [x.x.x.x] is not able to connect to the following ports: [y.y.y.y:2379, y.y.y.y:2380]. Please check network policies and firewall rules

### ISSUE THREAD

**Issue by mshahmalaki** [rancher/rke#3223]
**RKE version: v1.4.4**

**Docker version: 20.10.24**

**Operating system and kernel: ubuntu 20.04.6**

**Type/provider of hosts: VMware Virtual Machines**

**cluster.yml file:**

```
nodes:
- address: 172.16.10.101
  internal_address: 192.168.250.101
  role: 
    - controlplane
    - etcd
    - worker
  hostname_override: rke01
  user: ubuntu

- address: 172.16.10.102
  internal_address: 192.168.250.102
  role: 
    - controlplane
    - etcd
    - worker
  hostname_override: rke02
  user: ubuntu

- address: 172.16.10.103
  internal_address: 192.168.250.103
  role: 
    - controlplane
    - etcd
    - worker
  hostname_override: rke03
  user: ubuntu

- address: 172.16.10.104
  internal_address: 192.168.250.104
  role: 
    - controlplane
    - etcd
    - worker
  hostname_override: rke04
  user: ubuntu

- address: 172.16.10.105
  internal_address: 192.168.250.105
  role: 
    - controlplane
    - etcd
    - worker
  hostname_override: rke05
  user: ubuntu

ssh_key_path: ~/.ssh/id_rsa

private_registries:
  - url: 172.16.10.5:8080
    is_default: true

kubernetes_version: v1.25.6-rancher4-1 

cluster_name: "cluster.local"

network:
  plugin: canal

addon_job_timeout: 60
```

**Steps to Reproduce:**

```bash
rke up
```

**Results:**

```
FATA[0125] [[network] Host [172.16.10.101] is not able to connect to the following ports: [192.168.250.101:2379, 192.168.250.101:2380, 192.168.250.102:2379, 192.168.250.102:2380, 192.168.250.103:2379, 192.168.250.103:2380, 192.168.250.104:2379, 192.168.250.104:2380, 192.168.250.105:2380, 192.168.250.105:2379]. Please check network policies and firewall rules] 
```

there is no firewall active rule for this hosts. ufw is inactive on them.
