### ISSUE TITLE
RKE upgrade fails due to kubelet can not restart, because umount blocking - Ubuntu only

### ISSUE THREAD

**Issue by mr-anderson86** [rancher/rke#3235]
**RKE version:** Trying to upgrade from `v1.3.12` to `v1.4.5`

**Docker version: (`docker version`,`docker info` preferred)**
`docker info`
```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 214
  Running: 100
  Paused: 0
  Stopped: 114
 Images: 54
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-1022-aws
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.03GiB
 Name: node1
 ID: JNGZ:DS36:ZH77:JH7J:RCET:3TFP:RTYS:32FE:G6V6:MYMB:53GL:NHGD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```bash
uname -r
5.13.0-1022-aws

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**cluster.yml file:**
In RKE `v1.3.12`:
```yaml
nodes:
- address: 10.111.22.123
  user: myuser
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: node1
  labels:
    myuser-cluster: true
    node-myuser-Application: true
    node-myuser-Query: true
- address: 10.111.22.124
  user: myuser
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: node2
  labels:
    myuser-cluster: true
    node-myuser-Application: true
    node-myuser-Query: true
- address: 10.111.22.125
  user: myuser
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: node3
  labels:
    myuser-cluster: true
    node-myuser-Build: true
ssh_key_path: /home/myuser/myuser-L2023.2.0.156/id_rsa
cluster_name: rke-cluster
kubernetes_version: v1.23.7-rancher1-1
ignore_docker_version: False
addon_job_timeout: 60
ssh_agent_auth: False

authorization:
  mode: rbac

system_images:
  calico_node: rancher/mirrored-calico-node:v3.22.1

dns:
  provider: coredns

network:
  plugin: calico
  mtu: 1500
  options:
    calico_autoscaler_priority_class_name: system-cluster-critical # Available as of RKE v1.2.6+
    calico_priority_class_name: system-cluster-critical # Available as of RKE v1.2.6+

ingress:
  provider: none

monitoring:
  provider: none

services:
  etcd:
    uid: 52034
    gid: 52034
    backup_config:
      enabled: true
      interval_hours: 12
      retention: 6
    extra_args:
      quota-backend-bytes: 4294967296
      auto-compaction-retention: 240
  kube-api:
    secrets_encryption_config:
      enabled: True
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 30000-32767
    always_pull_images: false
    pod_security_policy: false
    audit_log:
      enabled: true
    event_rate_limit:
      enabled: true
    extra_args:
      insecure-port: "0"
      anonymous-auth: "false"
      kubelet-preferred-address-types: "InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP"
      audit-log-path: /var/log/kube-audit/audit-log.json
      audit-log-maxage: 30
      audit-log-maxbackup: 5
      audit-log-maxsize: 100
      audit-log-format: json
      delete-collection-workers: 3
      v: 1
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
    extra_args:
      node-monitor-period: 5s
      node-monitor-grace-period: 20s
      node-startup-grace-period: 30s
      pod-eviction-timeout: 1m
      node-cidr-mask-size: 24
      feature-gates: RotateKubeletServerCertificate=true
      v: 1
      bind-address: 127.0.0.1
      address: 127.0.0.1

  kubeproxy:
    extra_args:
      proxy-mode: ipvs
      metrics-bind-address: 0.0.0.0:10249
      kube-api-burst: 20
      kube-api-qps: 10
      v: 1
    extra_binds:
      - "/lib/modules:/lib/modules:ro"
  scheduler:
    extra_args:
      v: 1
      bind-address: 127.0.0.1
      address: 127.0.0.1

  controllerManager:
    extra_args:
      node-monitor-grace-period: 20s
      node-monitor-period: 2s
      pod-eviction-timeout: 30s
      node-cidr-mask-size: 21

  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    fail_swap_on: False
    # Generate per node serving certificate
    generate-serving-certificate: true
    extra_args:
      protect-kernel-defaults: true
      tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
      docker-root:
      feature-gates: RotateKubeletServerCertificate=true
      root-dir: /var/lib/kubelet
      pod-manifest-path: /etc/kubernetes/manifests
      max-pods: 1100
      read-only-port: 0
      sync-frequency: 3s
      max-open-files: 2000000
      kube-api-burst: 30
      kube-api-qps: 15
      serialize-image-pulls: false
      registry-burst: 10
      registry-qps: 0
      cgroups-per-qos: true
      cgroup-driver: cgroupsfs
      enforce-node-allocatable: pods
      system-reserved: ephemeral-storage=1Gi,cpu=270m,memory=3751Mi
      kube-reserved: ephemeral-storage=1Gi,cpu=180m,memory=1072Mi
      eviction-hard: memory.available<300Mi,imagefs.available<15%,nodefs.available<10%,nodefs.inodesFree<5%
      # eviction-soft: memory.available<500Mi
      # system-reserved-cgroup: /kubelet
      # runtime-reserved-cgroup: /kubelet
      # kube-reserved-cgroup: /kubesystem
      # kubelet-cgroups: /systemd/system.slice
      # runtime-cgroups: /systemd/system.slice
      # eviction-soft-grace-period: memory.available=1m30s
      eviction-max-pod-grace-period: 30
      eviction-pressure-transition-period: 30s
      node-status-update-frequency: 10s
      global-housekeeping-interval: 1m0s
      housekeeping-interval: 10s
      runtime-request-timeout: 2m0s
      volume-stats-agg-period: 1m0s
      v: 1
    extra_binds:
      - "/opt/myuser/grafana/grafana-myuser:/opt/myuser/grafana/grafana-myuser"
      - "/opt/myuser/prometheus:/opt/myuser/prometheus"
      - "/opt/myuser/alertmanager:/opt/myuser/alertmanager"
      - "/opt/myuser/grafana:/opt/myuser/grafana"
      - "/var/log/myuser:/var/log/myuser"
      - "/var/log:/var/log"
      # - "/etc/iscsi:/etc/iscsi"
      # - "/sbin/iscsiadm:/sbin/iscsiadm"
      - '/lib/modules:/lib/modules:ro'

addons:
  "apiVersion: policy/v1beta1\nkind: PodSecurityPolicy\nmetadata:\n  name: restricted\n\
    spec:\n  requiredDropCapabilities:\n  - NET_RAW\n  privileged: false\n  allowPrivilegeEscalation:\
    \ false\n  defaultAllowPrivilegeEscalation: false\n  fsGroup:\n    rule: RunAsAny\n\
    \  runAsUser:\n    rule: MustRunAsNonRoot\n  seLinux:\n    rule: RunAsAny\n  supplementalGroups:\n\
    \    rule: RunAsAny\n  volumes:\n  - emptyDir\n  - secret\n  - persistentVolumeClaim\n\
    \  - downwardAPI\n  - configMap\n  - projected\n---\napiVersion: networking.k8s.io/v1\n\
    kind: NetworkPolicy\nmetadata:\n  name: default-allow-all\nspec:\n  podSelector:\
    \ {}\n  ingress:\n  - {}\n  egress:\n  - {}\n  policyTypes:\n  - Ingress\n  - Egress\n\
    ---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: default\nautomountServiceAccountToken:\
    \ false\n"
```
And right before the RKE upgrade we remove all of the `PodSecurityPolicy` stuff since it's not existing in k8s `v1.25`

**Steps to Reproduce:**
1. I've launched RKE `v1.3.12` with k8s `v1.23.7` (over 3 nodes)
2. Installed on it rook-ceph Helm chart (v1.7.8)
3. Trying to upgrade to RKE `v1.4.5` (k8s `v1.25.9`)

**Results:**
* Each time some of the nodes (each times different node, or nodes, or even all of them) are in "NotReady" status since the kubelet container is stuck on umount commands.
* Sometimes I see this: 
```bash
[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [10.111.22.124]: Get \"http://localhost:10248/healthz\": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: + umount /var/lib/docker/overlay2/8e95a7d0bd83abeb8e52bdfd450fc2e8a167fa1ca9d314807620a480f3ec0100/merged/var/lib/kubelet/pods/b49460a3-5c18-4020-8764-a20c6bc3f149/volumes/kubernetes.io~csi/pvc-fc0ea6b5-3cab-470c-88ac-4fd273fa6e0b/mount]
```
* The only WA is to reboot all of the nodes (via AWS) and then they are all up and running.
Please refer to this issue: https://github.com/rancher/rke/issues/2425

How can I overcome this issue without rebooting each time?
Just note: it's not happening on any other OS (like `Amazon Linux` or `RedHat` or `CentOS` etc...), only on `Ubuntu`, from 18.04 to 22.04
Thanks in advance.
