### ISSUE TITLE
"kubectl get no" mis-reports new rke cluster state

### ISSUE THREAD

**Issue by alanbchristie** [rancher/rke#3246]
**RKE version:**
```
v1.2.7
```

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 14
  Running: 8
  Paused: 0
  Stopped: 6
 Images: 18
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.36.2.el7.x86_64
 Operating System: Scientific Linux 7.9 (Nitrogen)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.638GiB
 Name: rke-etcd-2.novalocal
 ID: MJTT:YP4G:BCTQ:S53T:XEF7:AY5T:4F7X:G476:QFTN:OD5C:HO4T:VEUQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://dockerhub.stfc.ac.uk/
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
3.10.0-1160.36.2.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
Bare-metal/OpenStack
```

**cluster.yml file:**
```
---
cluster_name: rancher-xchem
kubernetes_version: v1.19.9-rancher1-1

nodes:

  # etcd

- address: 192.168.253.47
  user: wmu55374
  ssh_key_path: /home/wmu55374/.ssh/stfc-abc-1
  role:
  - etcd

  # control plane

- address: 130.246.215.43
  user: wmu55374
  ssh_key_path: /home/wmu55374/.ssh/stfc-abc-1
  role:
  - controlplane
- address: 192.168.253.166
  user: wmu55374
  ssh_key_path: /home/wmu55374/.ssh/stfc-abc-1
  role:
  - controlplane

 # workers

- address: 192.168.253.64
  user: wmu55374
  ssh_key_path: /home/wmu55374/.ssh/stfc-abc-1
  role:
  - worker
- address: 192.168.253.36
  user: wmu55374
  ssh_key_path: /home/wmu55374/.ssh/stfc-abc-1
  role:
  - worker

services:
  etcd:
    backup_config:
      enabled: true
      interval_hours: 6
      retention: 28
      s3backupconfig:
        **[S3 Configuration is sensitive and has been redacted]**
```

**Steps to Reproduce:**
- I started with a cluster that had 3 **etcd** nodes (`192.168.253.47`, `192.168.253.14`, `192.168.253.30`).
- `14` and `30` experienced catastrophic failure and are now non-functional
- The remaining **etcd** node was repaired and made functional
- I removed the non-functional **etcd** nodes from `cluster.yml` (`14` and `30`)
- I re-ran `rke up`
- All is reported successfully

**Results:**
Cluster _appears_ to be operating successfully **BUT** `kubectl` mis-reports the node presence of the cluster. The two non-functional (and removed) **etcd** nodes are still reported...

```
$ kubectl get no
NAME              STATUS     ROLES          AGE      VERSION
xxx.xxx.xxx.43    Ready      controlplane   2y361d   v1.19.9
192.168.253.14    NotReady   etcd           2y361d   v1.19.9
192.168.253.166   Ready      controlplane   49m      v1.19.9
192.168.253.30    NotReady   etcd           2y361d   v1.19.9
192.168.253.36    Ready      worker         2y30d    v1.19.9
192.168.253.47    Ready      etcd           2y361d   v1.19.9
192.168.253.64    Ready      worker         2y333d   v1.19.9
```

> The IP Address `xxx.xxx.xxx.43` is public and has been redacted.

**Why are nodes `14` and `30` still reported by `kubectl`?**

Incidentally: -

- All nodes have since been _rebooted_ to see if that helps (it does not)
- The `kube-apiserver` container (on the control plane nodes) has the `Entrypoint` argument `--etcd-servers=https://192.168.253.47:2379` (which is correct for the new cluster state) 

I raise the issue because I'm reluctant to commission new **etcd** nodes until I understand why `kubectl` is _out of sync_ with the current cluster state.

**Comment by alanbchristie** [comment]
Is this a `kubernetes` anomaly? Do I just have to do this?

- `kubectl delete no/192.168.253.14 no/192.168.253.30`

**Comment by alanbchristie** [comment]
Interestingly, Rancher on the RKE cluster also complains (but I guess this is because it's using kubectl and getting the same response)...

<img width="1182" alt="Screenshot 2023-05-15 at 14 34 36" src="https://github.com/rancher/rke/assets/29806285/0e1fb729-fbd8-4f88-83ac-111a6995fda5">

**Comment by alanbchristie** [comment]
I'm going to try and resolve the situation by running appropriate `kubectl delete no` commands in the hope that this is a kubernetes-centric issue that RKE has not cleaned up properly, and that doing so will not disturb the existing nodes.

**Comment by alanbchristie** [comment]
So I just removed the nodes with...

```
kubectl drain 192.168.253.14 --ignore-daemonsets --delete-local-data
kubectl delete node 192.168.253.14
kubectl drain 192.168.253.30 --ignore-daemonsets --delete-local-data
kubectl delete node 192.168.253.30
```

> The second `drain` did not return to the command-line so I just hit `CTRL-C` to continue. As the broken nodes don't actually exist this kubectl command is probably unnecessary.

Then the cluster looks OK to kubectl: -

```
kubectl get no
NAME              STATUS   ROLES          AGE      VERSION
130.246.215.43    Ready    controlplane   2y364d   v1.19.9
192.168.253.166   Ready    controlplane   3d22h    v1.19.9
192.168.253.36    Ready    worker         2y34d    v1.19.9
192.168.253.47    Ready    etcd           2y364d   v1.19.9
192.168.253.64    Ready    worker         2y336d   v1.19.9
```

I then return to **RKE**, add two new replacement nodes to the `cluster.yml` and then run `rke up`. After a few minutes my new etcd nodes appear to be ready...

```
kubectl get no
NAME              STATUS   ROLES          AGE      VERSION
130.246.215.43    Ready    controlplane   2y364d   v1.19.9
192.168.253.101   Ready    etcd           85s      v1.19.9
192.168.253.166   Ready    controlplane   3d22h    v1.19.9
192.168.253.201   Ready    etcd           78s      v1.19.9
192.168.253.36    Ready    worker         2y34d    v1.19.9
192.168.253.47    Ready    etcd           2y364d   v1.19.9
192.168.253.64    Ready    worker         2y336d   v1.19.9
```

**Comment by alanbchristie** [comment]
Quite why RKE didn't remove the etcd nodes from the kubernetes stand-point is still a mystery. Maybe someone who understands RKE can comment but, for now, my problem is fixed, and I've moved on...

**Comment by HectorB-2020** [comment]
I won't be able to explain but can confirm that we've seen this behaviour when we started creating `cluster.yml` with FQDN addresses. 
```yaml
nodes:
- address: srv211.dept.company.net
```
Soon we realized that FQDNs were inconvenient to deal with and decided to use their short versions instead.
```yaml
nodes:
- address: srv211.dept.company.net
  hostname_override: "srv211"
```
After running `rke up` we got both versions of the same hosts in `k get no`. Thankfully that was a testing cluster so `rke remove` followed by `rke up` fixed everything.
```
rke --version
rke version v1.4.6
```
