### ISSUE TITLE
 FATA[0000] Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE

### ISSUE THREAD

**Issue by GlitchTQ** [rancher/rke#3247]
rke version v1.4.5 from git hub releases

Docker version 20.10.9

opensuse:leap:15.2

VmWare

**cluster.yaml file:**
``` yaml
nodes:
  - address: 10.10.10.1
    internal_address: 10.10.10.1
    user: root
    ssh_key_path: ~/.ssh/id_rsa
    role: [controlplane, worker, etcd]
  - address: 10.10.10.2
    internal_address: 10.10.10.2
    user: root
    ssh_key_path: ~/.ssh/id_rsa
    role: [controlplane, worker, etcd]
  - address: 10.10.10.2
    internal_address: 10.10.10.2
    user: root
    ssh_key_path: ~/.ssh/id_rsa
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# network:
#   plugin: calico

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

# enable_cri_dockerd: true
cluster_name: local
# kubernetes_version: v1.21.14-rancher1-1
kubernetes_version: v1.23.16-rancher2-2
```

**Steps to Reproduce:**
rke -d up --config rancher-cluster.yml

**Results:**
`FATA[0000] Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE`

I want to update rke k8s cluster to v1.23 version, how can i avoid this error?

**Comment by alanbchristie** [comment]
I had a similar issue and wonder whether your issue is caused by Pod Security Admissions (PSA) support that may have been added in RKE v1.4.4? Have a look at the **Workaround** suggestion in https://github.com/rancher/rancher/issues/41292#issuecomment-1528181762.

I suspect that starting with a pre-1.4.4 RKE that supports your existing kubernetes version will help.

_I'm not a contributor/developer of RKE, just a user who encountered a similar issue last week_

**Comment by jiaqiluo** [comment]
waiting for the next RC 

---

### Root cause
  
When RKE initializes the cluster, it sets the default value to the field `spec.Services.KubeAPI.PodSecurityConfiguration` when no value is provided in the cluster.yml file (see [code](https://github.com/rancher/rke/blob/5d360491203a3c1511aa6d12c496679dea05ba37/cluster/defaults.go#L398-L400)) **regardless of the cluster's Kubernetes version**.

But later on, when RKE validates the cluster's configuration before starting the upgrading, it expects to see the abovementioned field to be set only for clusters whose k8s version is **at least 1.23** (see [code](https://github.com/rancher/rke/blob/5d360491203a3c1511aa6d12c496679dea05ba37/cluster/validation.go#L691-L703)). Therefore the following error is returned: 
```
FATA[0000] Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE
```

To reproduce the bug, we can use RKE CLI v1.4.5 to provision a cluster with k8s version 1.22.17-rancher1-2, although the version is not officially supported by RKE CLI v1.4.5. 

```
// cluster.yaml
nodes:
  - address: xxx
    internal_address: xxx
    user: ubuntu
    role: [controlplane,worker,etcd]
kubernetes_version: v1.22.17-rancher1-2
```


### What was fixed, or what changes have occurred
  

Check the cluster k8s version and set the default PodSecurityConfiguration value only if the cluster's k8s version is at least 1.23


### Areas or cases that should be tested

**cluster provisioning**
Follow the same steps to provision a cluster with k8s version `1.22.17-rancher1-2` using the RKE RC. The cluster is provisioned successfully. Also, if we ssh into the node to check the file `/etc/kubernetes/admission.yaml`, we can see that the default PodSecurity Configuration is not in the file, which is expected. 

**cluster upgrading**
First, reproduce the bug using RKE v1.4.5, then upgrade the cluster (i.e., run `rke up` again) using the RKE RC; we should see the cluster is upgraded successfully. 
  
### What areas could experience regressions?

- cluster provisioning
- cluster upgrading 
  
### Are the repro steps accurate/minimal?

Yes
