### ISSUE TITLE
NFS Volume not mounting

### ISSUE THREAD

**Issue by techBeck03** [rancher/rke#3252]
**RKE version:**
`1.4.1`

**Docker version: (`docker version`,`docker info` preferred)**

```sh
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:04 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```ini
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

`vsphere`

**cluster.yml file:**

This was deployed using the rancher/rke terraform provider

```yaml
nodes:
- address: 172.16.91.37
  port: \"\"
  internal_address: \"\"
  role:
  - controlplane
  - etcd
  hostname_override: \"\"
  user: ubuntu
  docker_socket: \"\"
  ssh_key: |-
    <redacted>
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  labels: {}
  taints: []
- address: 172.16.91.35
  port: \"\"
  internal_address: \"\"
  role:
  - worker
  hostname_override: \"\"
  user: ubuntu
  docker_socket: \"\"
  ssh_key: |-
    <redacted>
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  labels: {}
  taints: []
- address: 172.16.91.36
  port: \"\"
  internal_address: \"\"
  role:
  - worker
  hostname_override: \"\"
  user: ubuntu
  docker_socket: \"\"
  ssh_key: |-
   <redacted>
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  labels: {}
  taints: []
- address: 172.16.91.34
  port: \"\"
  internal_address: \"\"
  role:
  - worker
  hostname_override: \"\"
  user: ubuntu
  docker_socket: \"\"
  ssh_key: |-
    <redacted>
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  labels: {}
  taints: []
- address: 172.16.91.39
  port: \"\"
  internal_address: \"\"
  role:
  - worker
  hostname_override: \"\"
  user: ubuntu
  docker_socket: \"\"
  ssh_key: |-
    <redacted>
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  labels: {}
  taints: []
- address: 172.16.91.40
  port: \"\"
  internal_address: \"\"
  role:
  - worker
  hostname_override: \"\"
  user: ubuntu
  docker_socket: \"\"
  ssh_key: |-
    <redacted>
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  labels: {}
  taints: []
services:
  etcd:
    image: \"\"
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: \"\"
    cert: \"\"
    key: \"\"
    path: \"\"
    uid: 0
    gid: 0
    snapshot: null
    retention: \"\"
    creation: \"\"
    backup_config: null
  kube-api:
    image: \"\"
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: \"\"
    service_node_port_range: \"\"
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: \"\"
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: \"\"
    service_cluster_ip_range: \"\"
  scheduler:
    image: \"\"
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: \"\"
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: \"\"
    infra_container_image: \"\"
    cluster_dns_server: \"\"
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: \"\"
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: calico
  options:
    calico_cloud_provider: none
    calico_flex_volume_plugin_dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: \"\"
  sans: []
  webhook: null
addons: \"\"
addons_include:
- https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
system_images:
  etcd: \"\"
  alpine: \"\"
  nginx_proxy: \"\"
  cert_downloader: \"\"
  kubernetes_services_sidecar: \"\"
  kubedns: \"\"
  dnsmasq: \"\"
  kubedns_sidecar: \"\"
  kubedns_autoscaler: \"\"
  coredns: \"\"
  coredns_autoscaler: \"\"
  nodelocal: \"\"
  kubernetes: \"\"
  flannel: \"\"
  flannel_cni: \"\"
  calico_node: \"\"
  calico_cni: \"\"
  calico_controllers: \"\"
  calico_ctl: \"\"
  calico_flexvol: \"\"
  canal_node: \"\"
  canal_cni: \"\"
  canal_controllers: \"\"
  canal_flannel: \"\"
  canal_flexvol: \"\"
  weave_node: \"\"
  weave_cni: \"\"
  pod_infra_container: \"\"
  ingress: \"\"
  ingress_backend: \"\"
  ingress_webhook: \"\"
  metrics_server: \"\"
  windows_pod_infra_container: \"\"
  aci_cni_deploy_container: \"\"
  aci_host_container: \"\"
  aci_opflex_container: \"\"
  aci_mcast_container: \"\"
  aci_ovs_container: \"\"
  aci_controller_container: \"\"
  aci_gbp_server_container: \"\"
  aci_opflex_server_container: \"\"
ssh_key_path: \"\"
ssh_cert_path: \"\"
ssh_agent_auth: false
authorization:
  mode: \"\"
  options: {}
ignore_docker_version: false
enable_cri_dockerd: true
kubernetes_version: v1.24.10-rancher4-1
private_registries: []
ingress:
  provider: none
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: \"\"
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 80
  https_port: 443
  network_mode: hostPort
  tolerations: []
  default_backend: true
  default_http_backend_priority_class_name: \"\"
  nginx_ingress_controller_priority_class_name: \"\"
  default_ingress_class: null
cluster_name: \"\"
cloud_provider:
  name: \"\"
prefix_path: \"\"
win_prefix_path: \"\"
addon_job_timeout: 0
bastion_host:
  address: \"\"
  port: \"\"
  user: \"\"
  ssh_key: \"\"
  ssh_key_path: \"\"
  ssh_cert: \"\"
  ssh_cert_path: \"\"
  ignore_proxy_env_vars: false
monitoring:
  provider: \"\"
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: \"\"
restore:
  restore: false
  snapshot_name: \"\"
rotate_encryption_key: false
dns: null
upgrade_strategy:
  max_unavailable_worker: 20%
  max_unavailable_controlplane: \"1\"
  drain: true
  node_drain_input:
    force: false
    ignore_daemonsets: false
    delete_local_data: false
    grace_period: 0
    timeout: 0

```

This was deployed using the rke terraform provider so i don't have the cluster.yml file and it's empty in the terraform state

**Steps to Reproduce:**

Within a kubernetes deployment i'm trying to mount an nfs volume

```yaml
spec:
      containers:
         ...
        volumeMounts:
        - mountPath: /app/dist/web/assets/img
          name: assets
      volumes:
      - name: assets
        nfs: 
          path: /tools/img
          server: infra-chx.auslab.cisco.com
```

**Results:**

I receive the following error in the pod description

```sh
Mounting command: mount
Mounting arguments: -t nfs infra-chx.auslab.cisco.com:/tools/img /var/lib/kubelet/pods/0b686b4b-c646-4151-b9b9-461cc7da071e/volumes/kubernetes.io~nfs/assets
Output: Running in chroot, ignoring command 'start'
Running in chroot, ignoring command 'start'
Running in chroot, ignoring command 'start'
Running in chroot, ignoring command 'start'
mount.nfs: mounting infra-chx.auslab.cisco.com:/tools/img failed, reason given by server: No such file or directory
```

This same syntax is working on a non-RKE cluster running K8s version `1.21.11`.  The NFS server is reachable from the cluster nodes and i've manually mounted that same share+path from a different workstation within the same network as the nodes.  Any help is much appreciated.
