### ISSUE TITLE
cri-dockerd needs IPv6 dual stack flag enabled when more than 1 CIDR is configured

### ISSUE THREAD

**Issue by superseb** [rancher/rke#3271]
**RKE version:**
v1.4.6

**Docker version: (`docker version`,`docker info` preferred)**
Tested with 23.0.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 22.04, `5.19.0-1025-aws`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**cluster.yml file:**
```
services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
  kube-controller:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
    cluster_cidr: 10.42.0.0/16,fd01::/64

network:
  plugin: calico
```

**Steps to Reproduce:**
Run `rke up`, deploy pod(s) and check `.status.podIPs`

**Results:**
It will only show IPv4 address, not the IPv6 address.


After looking at the `cri-dockerd` flags, I found this flag which needs to be enabled to make it work. After running with a custom `rke-tools` with this flag added, the IPv6 connectivity worked.

```
      --ipv6-dual-stack                         Enable IPv6 dual stack support                                                                                                                                                                                                                                                
```

**Comment by terraboops** [comment]
@superseb - I'd like to take this on, I've been investigating this issue for our RKE clusters and I think I can have a fix for it in the next few days.

**Comment by superseb** [comment]
@terramauthe thanks for the help! I opened 2 PRs for the issue as linked above, if you are able to test it if it resolves the issue for your cluster(s), that would be great. If not or if you come up with a better solution, let me know.

**Comment by terraboops** [comment]
> @terramauthe thanks for the help! I opened 2 PRs for the issue as linked above, if you are able to test it if it resolves the issue for your cluster(s), that would be great. If not or if you come up with a better solution, let me know.

Great! Thanks! I should be able to take a look tomorrow at testing and PR feedback.

**Comment by superseb** [comment]
You should be able to test it using RKE CLI built from the PR, you need to build the `rke-tools` image and make it available (publicly or locally) and then override the `rke-tools` image in the configuration (probably only `kubernetes_services_sidecar` but automation changes them all when I test):

```
system_images:                   
  alpine: your_name/rke-tools:ipv6
  nginx_proxy: your_name/rke-tools:ipv6
  cert_downloader: your_name/rke-tools:ipv6
  kubernetes_services_sidecar: your_name/rke-tools:ipv6
```

**Comment by terraboops** [comment]
> probably only `kubernetes_services_sidecar` but automation changes them all when I test

This is super helpful! Thank you! I thought it was only the alpine image based on [this](https://github.com/rancher/rke/blob/582da9d299d76a8e8bf04fdd344d1c0a9857db41/util/util.go#L156). I'll override them all when I test it out tomorrow or the next day.

**Comment by terraboops** [comment]
Hi @superseb, sorry for the inconvenience, but it's looking like I won't be able to test this until early next week.

By the way, once it's tested and merged - approximately how long before we'd see this upstream? I'm currently working on a temporary workaround for our clusters to enable the dualstack flag, but it might be wasted effort if the upstream fix will be out shortly. We deploy our clusters using the Terraform provider, so I suppose we'd also need to wait for that to be released.

No worries if you're unsure, I just figured I'd ask in case you had a rough idea. Thanks!

**Comment by superseb** [comment]
No problem, any testing that could be done is helpful. Unfortunately I don't have the information on when it will be released.

**Comment by terraboops** [comment]
I tried testing this out yesterday and ran into issues building `rke` locally. It is failing on the `integration` task.

I followed the instructions here:
https://github.com/rancher/rke#building

Can I just run `make build`? Any tips on building locally from a fresh clone would be appreciated.

**Comment by superseb** [comment]
`make build` is fine, it will get you just the Linux binary. If you need cross compiled binaries, you can set an environment variable (`CROSS=1 make build`).

**Comment by terraboops** [comment]
Hi @superseb! Sorry it took so long, I had some other work take priority from this.

I was able to test this out and it does resolve the issue!

I also did some investigations into the `rke` Terraform provider, it includes `rke` as a Go module and calls `RancherUp` through code, so once this is released and the imported version in the provider is bumped, we can resolve our issues in production using your changes.

https://github.com/rancher/terraform-provider-rke/blob/master/go.mod#L9

Thanks a lot for this fix! Let me know if you want any more information.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.8-head 01127d8
Rancher cluster type: HA
RKE1 version: v1.5.0-rc8

----------

### Testing: ###
Tested this issue with the following:
1. Create ec2 instance with ipv6 primary address
2. Create tg and nlb and route53 with ipv6 enabled
3. I used rke1 v1.5.0-rc8 to do rke up --config cluster.yml
The contents of cluster.yml
```
# set path to ssh private key so we can ssh into each node for provisioning. If aws ec2 should point to your aws public key
ssh_key_path: tim.pem

# kubernetes_version is not required can leave blank or comment out and will use latest
kubernetes_version:

# list of nodes including internal addresses is strongly recommended. user must be set to ubuntu for example for ubuntu ec2 instances for ssh access.
# if your AWS AMI is not ubuntu like centos, rocky linux, etc the username is usually (but not always) ec2-user
# role must be defined - here we specify all three roles per each node. However technically minimums just are: etcd 3 nodes, controlplane 2 nodes, worker 2 nodes for minimal fault tolerance
nodes:
  - address: 3.149.253.178
    internal_address: 172.31.12.234
    user: ubuntu
    role: [etcd, controlplane, worker]

services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
  kube-controller:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
    cluster_cidr: 10.42.0.0/16,fd01::/64

network:
  plugin: calico
```
4. The k8s cluster came up successfully
time="2023-10-09T11:50:57-04:00" level=info msg="[ingress] ingress controller nginx deployed successfully"
time="2023-10-09T11:50:57-04:00" level=info msg="[addons] Setting up user addons"
time="2023-10-09T11:50:57-04:00" level=info msg="[addons] no user addons defined"
time="2023-10-09T11:50:57-04:00" level=info msg="Finished building Kubernetes cluster successfully"
5. Run the following to command to create an nginx deployment
`kubectl create deployment nginx --image=nginx --replicas=1`
6. Run the following command to get  the ip addresses of newly created deployment
```
kubectl get pod nginx-77b4fdf86c-rqdct -o go-template --template="{{range .status.podIPs}}{{.ip}}{{println}}`n{{end}}" --kubeconfig .\kube_config_cluster.yml
```

**Result**
IPv6 dual stack is now being supported correctly and the flag is getting passed. Both IPv4 and IPv6 addresses are showing.
![image](https://github.com/rancher/rke/assets/108360907/24f7f8b3-9494-488c-9b16-9497415073ca)
