### ISSUE TITLE
Minor issue: Update `metrics-server` manifest with correct `nodeAffinity`

### ISSUE THREAD

**Issue by HectorB-2020** [rancher/rke#3289]
**RKE version:**
rke version v1.4.6

K8s version reported by `k get no`
VERSION: v1.26.4

**Docker version:**
Docker is not installed on controlling node.
Docker on VM where k8s is to run:
```
Server:
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Kernel where `rke` and `kubectl` are run: `5.10.152`

VMs with Docker and k8s
  Kernel:`3.10.0-1160.el7.x86_64`
  OS: CentOS 7.9

**Type/provider of hosts:**
On-prem QEMU/KVM on kernel  `5.10.152`

**Steps to Reproduce:**
```bash
rke config
rke up
k rollout restart deployment metrics-server
```

**Results:**
```
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
```
Output of `k get deploy metrics-server -o yaml` indeed shows this 
```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows
              - key: node-role.kubernetes.io/worker
                operator: Exists
```
So please replace `beta.kubernetes.io/os` with `kubernetes.io/os` as advised in the warning or switch to up-to-date manifest in `rke` tool.
