### ISSUE TITLE
K8 Cluster created taking time to get Stabilized

### ISSUE THREAD

**Issue by hemanthavs** [rancher/rke#329]
**RKE version:** 
``` 
rke version v0.1.1-rc2
```

**Docker version: (`docker version`,`docker info` preferred)**

```
Containers: 31
 Running: 10
 Paused: 0
 Stopped: 21
Images: 10
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 121
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.73 GiB
Name: host3-deleteplz-dev-dal12
ID: 4GQZ:JT4C:KWPH:T6HM:G5JC:TZ5X:SEKC:RKEV:RS7B:4ICV:G3MJ:VZTO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# uname -r
4.4.0-112-generic

# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

```
Softlayer VM
```

**cluster.yml file:**

```
auth:
  options:
    foo: bar
  strategy: x509
authorization:
  mode: rbac
  options: null
enforce_docker_version: true
kubernetes_version: v1.8.7-rancher1-1
network:
  options: null
  plugin: flannel
nodes:
- address: 169.48.240.217
  role:
  - controlplane
  - etcd
  - worker
  user: root
- address: 169.48.238.59
  role:
  - controlplane
  - etcd
  - worker
  user: root
- address: 169.48.240.218
  role:
  - controlplane
  - etcd
  - worker
  user: root
services:
  etcd: null
  kube-api:
    extra_args:
      v: 4
    pod_security_policy: false
    service_cluster_ip_range: 10.233.0.0/18
  kube-controller:
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  kubelet:
    cluster_dns_server: 10.233.0.3
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy: null
  scheduler: null
ssh_key_path: /opt/ibm/cb/jiraportal/mount/csastate/deleteplz-dev-20180207-211400/privatekey
system_images:
  alpine: alpine:latest
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  etcd: rancher/etcd:v3.0.17
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.5
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubernetes: rancher/k8s:v1.8.7-rancher1-1
  kubernetes_services_sidecar: rancher/rke-service-sidekick:v0.1.0
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
```

**Steps to Reproduce:**

-> rke up
-> Occasionally K8 Cluster taking around 1 hour to get stabilized

```
NAMESPACE       NAME                                    READY     STATUS              RESTARTS   AGE       IP               NODE
ingress-nginx   default-http-backend-66b447d9cf-mzvtf   1/1       Running             0          40m       10.233.65.2      169.48.238.59
ingress-nginx   nginx-ingress-controller-b95gz          1/1       Running             4          40m       169.48.238.59    169.48.238.59
ingress-nginx   nginx-ingress-controller-p22q9          1/1       Running             0          40m       169.48.240.217   169.48.240.217
ingress-nginx   nginx-ingress-controller-zs2mj          1/1       Running             12         40m       169.48.240.218   169.48.240.218
kube-system     kube-dns-6f7666d48c-llfn7               3/3       Running             0          42m       10.233.66.2      169.48.240.217
kube-system     kube-dns-autoscaler-54fd4c549b-vfkq8    0/1       ContainerCreating   0          42m       <none>           169.48.240.218
kube-system     kube-flannel-8w8lf                      2/2       Running             3          42m       169.48.238.59    169.48.238.59
kube-system     kube-flannel-g996f                      1/2       CrashLoopBackOff    11         42m       169.48.240.218   169.48.240.218
kube-system     kube-flannel-rd6s9                      2/2       Running             2          42m       169.48.240.217   169.48.240.217

``` 

This environment get stabilized after an hour.. during that time pod kube-flannel-g996f  restarted 11 times and   nginx-ingress-controller-zs2mj restarted 12 times

is it an expected behaviour that sometimes cluster takes an hours to get stabilized?

**Results:**
