### ISSUE TITLE
Incorrect images list for RKE

### ISSUE THREAD

**Issue by HectorB-2020** [rancher/rke#3294]
**RKE version:**
rke version v1.4.7

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           20.10.16

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16

```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.04 LTS

**cluster.yml file:**
```yaml
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.5.4
  alpine: rancher/rke-tools:v0.1.88
  nginx_proxy: rancher/rke-tools:v0.1.88
  cert_downloader: rancher/rke-tools:v0.1.88
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.88
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.21.1
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.21.1
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.21.1
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.5
  coredns: rancher/mirrored-coredns-coredns:1.9.3
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.5
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.21.1
  kubernetes: rancher/hyperkube:v1.24.15-rancher1
  flannel: rancher/mirrored-coreos-flannel:v0.15.1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.22.5
  calico_cni: rancher/calico-cni:v3.22.5-rancher1
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.22.5
  calico_ctl: rancher/mirrored-calico-ctl:v3.22.5
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.22.5
  canal_node: rancher/mirrored-calico-node:v3.22.5
  canal_cni: rancher/calico-cni:v3.22.5-rancher1
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.22.5
  canal_flannel: rancher/mirrored-flannelcni-flannel:v0.17.0
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.22.5
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.7
  ingress: rancher/nginx-ingress-controller:nginx-1.5.1-rancher2
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1
  metrics_server: rancher/mirrored-metrics-server:v0.6.2
  windows_pod_infra_container: rancher/mirrored-pause:3.7
  aci_cni_deploy_container: noiro/cnideploy:5.2.7.1.81c2369
  aci_host_container: noiro/aci-containers-host:5.2.7.1.81c2369
  aci_opflex_container: noiro/opflex:5.2.7.1.81c2369
  aci_mcast_container: noiro/opflex:5.2.7.1.81c2369
  aci_ovs_container: noiro/openvswitch:5.2.7.1.81c2369
  aci_controller_container: noiro/aci-containers-controller:5.2.7.1.81c2369
  aci_gbp_server_container: noiro/gbp-server:5.2.7.1.81c2369
  aci_opflex_server_container: noiro/opflex-server:5.2.7.1.81c2369
```
**Steps to Reproduce:**
docker pull noiro/gbp-server:5.2.7.1.81c2369

**Results:**
```
noiro/gbp-server:5.2.7.1.81c2369
 Error response from daemon: manifest for noiro/gbp-server:5.2.7.1.81c2369 not found: manifest unknown: manifest unknown

noiro/opflex-server:5.2.7.1.81c2369
Error response from daemon: manifest for noiro/opflex-server:5.2.7.1.81c2369 not found: manifest unknown: manifest unknown
```
---
Seems like this is a repetition of  previous issue
* rancher/rke#3030

Seems like they don't have such tags indeed: https://hub.docker.com/r/noiro/gbp-server/tags
The newest is [5.2.3.6.1d150da](https://hub.docker.com/layers/noiro/gbp-server/5.2.3.6.1d150da/images/sha256-7df3e51ce743b1e894a8895e879a5de5eba41d9c6a97c9c7894a5d69d339eefc?context=explore)
