### ISSUE TITLE
`rke config` generates inconsistent `cluster.yml`

### ISSUE THREAD

**Issue by HectorB-2020** [rancher/rke#3295]
**RKE version:**
1.4.7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.04 LTS

**Steps to Reproduce:**
1. Run `rke config`, provide answers.
2. Give k8s version as one of answers, e.g. `v1.24.15-rancher1`.
3. Try running `rke up`.
4. Watch error like
    rke [controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host couldn't init admission plugin PodSecurity

**Explanation:**
When `rke config` seeks for responses, it puts k8s version only into `system_images`:
```yaml
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.5.4
  ...
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.5
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.21.1
  kubernetes: rancher/hyperkube:v1.24.15-rancher1     ## <----
  flannel: rancher/mirrored-coreos-flannel:v0.15.1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  ...
```
Parameter `kubernetes_version` is left empty after `rke config`:
`kubernetes_version: ""`

Thanks to old issue rancher/rke#3134 I found a mitigation - we needed to explicitly define
`kubernetes_version: "v1.24.15-rancher1"`

Funny thing, before playing with `rke` and `cluster.yml` I had perused all documentation which said that information defined in `system_images` prevails. I certainly had seen empty `kubernetes_version: ""` but never though it made any sense for my configuration.

So bottom line, it would be nice to have ready-to-use `cluster.yml` after providing answers to `rke config` which include k8s version.

----

BTW, I hope you'll also be able to look into other issue with `system_images`:
* https://github.com/rancher/rke/issues/3294

**Comment by HectorB-2020** [comment]
I wonder if this is relevant. The following command explicitly specifies version `1.24.15` but its logs say that it believes that version `1.26.6` was chosen.
```bash
rke config --system-images -v v1.24.15-rancher1
```
`level=info msg="Generating images list for version [v1.26.6-rancher1-1]`

**Comment by HectorB-2020** [comment]
And I guess something related was discussed in https://github.com/rancher/rke/issues/2532#issuecomment-832896860

**Comment by jiaqiluo** [comment]
> I wonder if this is relevant. The following command explicitly specifies version `1.24.15` but its logs say that it believes that version `1.26.6` was chosen.
> 
> ```shell
> rke config --system-images -v v1.24.15-rancher1
> ```
> 
> `level=info msg="Generating images list for version [v1.26.6-rancher1-1]`

 @HectorB-2020, in this case, the default version, which is v1.26.6-rancher1-1,  will be used. 
https://github.com/rancher/rke/blob/5a8cacb962809382906100bcb8e797e9c8144f68/cmd/config.go#L296-L310

To check the default version, run `rke config -l`
```
> rke config -l   
v1.26.6-rancher1-1

>  rke -v       
rke version v1.4.7
```

**Comment by HectorB-2020** [comment]
@jiaqiluo I hope you can help a bit more.
There are two places where Kubernetes version is specified in `cluster.yml`.
```yaml
kubernetes_version: "v1.24.15-rancher1"
...
system_images:
  kubernetes: rancher/hyperkube:v1.24.15-rancher1
```
Both places expect k8s version without the tailing digit, don't they? Am I right?
Yet `rke config -l` lists k8s versions with the last digits. This is confusing.
So I wonder how these two places relate to each other in the configuration.
