### ISSUE TITLE
Problem with pod to pod communication (7 nodes & calico)

### ISSUE THREAD

**Issue by bleleve** [rancher/rke#330]
Hi there,

I have a network problem with my fresh k8s cluster setup.

The heapster service which is currently running on worker 3 is not accessible by the dashboard on worker 4. I have executed `curl http://10.74.252.2:8082/metrics` on all cluster nodes, all return me a timeout except master 2 and worker 3...

The random side disturbs me, I can not understand why but I guess a calico conf problem.

Any help is welcome ;)

Thanks !

**RKE version:**
110c9f3 Alena Prokharchyk <alena@rancher.com> on 03/02/2018 at 18:00

**Docker version: (`docker version`,`docker info` preferred)**
`docker info`
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.13.16-coreos-r1
Operating System: Container Linux by CoreOS 1520.9.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.8 GiB

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`cat /etc/os-release`
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.9.0
VERSION_ID=1520.9.0
BUILD_ID=2017-11-30-1105
PRETTY_NAME="Container Linux by CoreOS 1520.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

`uname -r`
4.13.16-coreos-r1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**cluster.yml file:**
```
nodes:
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.13
    role: [controlplane, etcd]
    hostname_override: master-1
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: master
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.6
    role: [controlplane, etcd]
    hostname_override: master-3
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: master
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.8
    role: [controlplane, etcd]
    hostname_override: master-2
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: master
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.10
    role: [worker]
    hostname_override: worker-2
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: worker
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.4
    role: [worker]
    hostname_override: worker-1
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: worker
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.5
    role: [worker]
    hostname_override: worker-4
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: worker
  - address: XXX.XXX.XXX.XXX
    internal_address: 192.168.0.11
    role: [worker]
    hostname_override: worker-3
    user: core
    docker_socket: /var/run/docker.sock
    ssh_key_path: ********************
    labels:
      role: worker
services:
  etcd:
    image: quay.io/coreos/etcd:v3.0.17
  kube-api:
    image: rancher/k8s:v1.8.5-rancher4
    service_cluster_ip_range: 10.74.0.0/17
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.8.5-rancher4
    cluster_cidr: 10.74.128.0/17
    service_cluster_ip_range: 10.74.0.0/17
  scheduler:
    image: rancher/k8s:v1.8.5-rancher4
  kubelet:
    image: rancher/k8s:v1.8.5-rancher4
    cluster_domain: k8s.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    cluster_dns_server: 10.74.127.254
  kubeproxy:
    image: rancher/k8s:v1.8.5-rancher4
network:
  plugin: calico
authentication:
  strategy: x509
ssh_key_path: ********************
authorization:
  mode: rbac
ignore_docker_version: false
private_registries:
  - url: registry.local
    user: ********************
    password: ********************
ingress:
  type: nginx
  options:
    server-tokens: false
    proxy‑read‑timeout: 3600
    proxy‑send‑timeout: 3600
  node_selector:
    role: worker
```

**Steps to Reproduce:**
Deploy Heapster Cluster Addon (standalone - https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring)
Deploy Dashboard Cluster Addon (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dashboard)

**Results:**
Metric client health check failed: an error on the server ("Error: 'dial tcp 10.74.252.2:8082: getsockopt: connection timed out'\nTrying to reach: 'http://10.74.252.2:8082/healthz'") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.
