### ISSUE TITLE
RKE Cluster DNS/Network Issue in Air-Gap Environment

### ISSUE THREAD

**Issue by GuillaumeDorschner** [rancher/rke#3347]
I am encountering a problem with my RKE setup, which I believe is related to DNS or network configurations. Here's an outline of the problem:

**RKE version:**
```
rke version v1.4.7
```

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:32 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:32 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```
nodes:
  - address: 192.168.137.65
    hostname_override: master
    user: k8s
    role: [controlplane, etcd]
  - address: 192.168.137.62
    hostname_override: worker1
    user: k8s
    role: [worker]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

network:
  plugin: calico

ingress:
  provider: nginx
  network_mode: none

addons: |-
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx-external
    namespace: ingress-nginx
  spec:
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
    sessionAffinity: None
    type: LoadBalancer
```

My cluster needs to operate in an Air-Gap environment, so I must resolve this issue. I Air-Gap in a VLAN, maybe that the problem ?

**Cluster Creation Output Failed**:

```bash
# Output when isolated within VLAN
➜  rke-setup ./rke up --config cluster.yml
...
FATA[0117] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
➜  rke-setup
```

I don't know how to fix this. I would appreciate some advice or help in resolving this issue.
