### ISSUE TITLE
RKE Installed master nodes etcd cluster not working properly 

### ISSUE THREAD

**Issue by syswe** [rancher/rke#3358]
**RKE version:** v1.4.8

**Docker version: (`docker version`,`docker info` preferred)** 20.10.x

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** oel 8

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Proxmox

**cluster.yml file:** default only added nodes

```

nodes:
- address: "10.10.25.33"
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []

- address: "10.10.25.34"
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []

- address: "10.10.25.35"
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []

- address: "10.10.25.36"
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
...
services:
  etcd:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
 ...
 
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.5.6
  alpine: rancher/rke-tools:v0.1.89
  nginx_proxy: rancher/rke-tools:v0.1.89
  cert_downloader: rancher/rke-tools:v0.1.89
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.89
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.22.20
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.22.20
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.22.20
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.6
  coredns: rancher/mirrored-coredns-coredns:1.9.4
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.6
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.22.20
  kubernetes: rancher/hyperkube:v1.26.7-rancher1
  flannel: rancher/mirrored-flannel-flannel:v0.21.4
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher8
  calico_node: rancher/mirrored-calico-node:v3.25.0
  calico_cni: rancher/calico-cni:v3.25.0-rancher1
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.25.0
  calico_ctl: rancher/mirrored-calico-ctl:v3.25.0
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.25.0
  canal_node: rancher/mirrored-calico-node:v3.25.0
  canal_cni: rancher/calico-cni:v3.25.0-rancher1
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.25.0
  canal_flannel: rancher/mirrored-flannel-flannel:v0.21.4
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.25.0
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.7
  ingress: rancher/nginx-ingress-controller:nginx-1.7.0-rancher1
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
  metrics_server: rancher/mirrored-metrics-server:v0.6.3
  windows_pod_infra_container: rancher/mirrored-pause:3.7
  aci_cni_deploy_container: noiro/cnideploy:5.2.7.1.81c2369
  aci_host_container: noiro/aci-containers-host:5.2.7.1.81c2369
  aci_opflex_container: noiro/opflex:5.2.7.1.81c2369
  aci_mcast_container: noiro/opflex:5.2.7.1.81c2369
  aci_ovs_container: noiro/openvswitch:5.2.7.1.81c2369
  aci_controller_container: noiro/aci-containers-controller:5.2.7.1.81c2369
  aci_gbp_server_container: noiro/gbp-server:5.2.7.1.81c2369
  aci_opflex_server_container: noiro/opflex-server:5.2.7.1.81c2369
  ```

**Steps to Reproduce:** 3 master 7 worker node 

**Results:** Etcd on masters not work properly 

WARN[0289] [etcd] host [10.10.25.33] failed to check etcd health: failed to get /health for host [10.10.25.33]: Get "https://10.10.25.33:2379/health": net/http: TLS handshake timeout

on my main master master1 (10.10.25.33) not contact self etcd container. always getting these errors: 
```

...
{"level":"warn","ts":"2023-09-08T09:30:50.671Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.672Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.751Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.751Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.771Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.771Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.851Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-08T09:30:50.851Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
...
```

1 ms 1000 logs ? service not working. 

error logs while restarting 
``` 
{"level":"info","ts":"2023-09-04T12:04:49.217Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"23c07694d16b9dd2 [logterm: 1, index: 3] sent MsgPreVote request to bb7ee9e106a7a21 at term 1"}
{"level":"info","ts":"2023-09-04T12:04:49.217Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"23c07694d16b9dd2 [logterm: 1, index: 3] sent MsgPreVote request to c686f889ae0cee2f at term 1"}
{"level":"error","ts":"2023-09-04T12:04:49.217Z","caller":"rafthttp/util.go:99","msg":"request sent was ignored due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-cluster-id":"695bd40f65521893","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.checkPostResponse\n\tgo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/util.go:99\ngo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*pipeline).post\n\tgo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/pipeline.go:163\ngo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*pipeline).handle\n\tgo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/pipeline.go:100"}
{"level":"error","ts":"2023-09-04T12:04:49.218Z","caller":"rafthttp/util.go:99","msg":"request sent was ignored due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-cluster-id":"695bd40f65521893","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.checkPostResponse\n\tgo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/util.go:99\ngo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*pipeline).post\n\tgo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/pipeline.go:163\ngo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*pipeline).handle\n\tgo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/pipeline.go:100"}
{"level":"warn","ts":"2023-09-04T12:04:49.218Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-04T12:04:49.218Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"bb7ee9e106a7a21","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-04T12:04:49.241Z","caller":"etcdserver/server.go:2083","msg":"failed to publish local member to cluster through raft","local-member-id":"23c07694d16b9dd2","local-member-attributes":"{Name:etcd-10.10.25.33 ClientURLs:[https://10.10.25.33:2379]}","request-path":"/0/members/23c07694d16b9dd2/attributes","publish-timeout":"15s","error":"etcdserver: request timed out"}
{"level":"warn","ts":"2023-09-04T12:04:49.261Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
{"level":"warn","ts":"2023-09-04T12:04:49.279Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"c686f889ae0cee2f","remote-peer-cluster-id":"4e1726eb2b1c530b","local-member-id":"23c07694d16b9dd2","local-member-cluster-id":"695bd40f65521893","error":"cluster ID mismatch"}
``` 

my firewall rules have configurated with no problems for access all k8s ports. etcd keep working successfully for only my master2 master3 nodes (25.34, 25.35). 

etcd container image: etcd: rancher/mirrored-coreos-etcd:v3.5.6
  kubernetes: rancher/hyperkube:v1.26.7-rancher1

my master2 master3 nodes etcdctl lists with no problem: 
bb7ee9e106a7a21, started, etcd-10.10.25.34, https://10.10.25.34:2380/, https://10.10.25.34:2379/, false
c686f889ae0cee2f, started, etcd-10.10.25.35, https://10.10.25.35:2380/, https://10.10.25.35:2379/, false

on my master1 has ran etcdctl commands: 
![image](https://github.com/rancher/rke/assets/32529331/eb6efb56-3acb-4777-9d3f-106cad464884)

I've ran too much "rke up" and still not working for master1 cannot join etcd cluster. How can I fix that problem ?
