### ISSUE TITLE
FATA[0315] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck

### ISSUE THREAD

**Issue by linjungz** [rancher/rke#337]
**RKE version:**
rke version v0.1.1

**Docker version: (`docker version`,`docker info` preferred)**
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

$ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: lju73
ID: PCHX:IQGU:IJFT:4GCW:VKSO:URIR:P2RV:GJV2:AAWE:UDBS:TAYA:NAP7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

$ uname -r
4.4.0-31-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**cluster.yml file:**
$ cat cluster.yml
```
auth:
  strategy: x509
  options:
    foo: bar
# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS, use the network plugin config option:
# 'cloud_provider: aws'
network:
  plugin: flannel
  options:
    flannel_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/flannel:v0.9.1
    flannel_cni_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/flannel-cni:v0.2.0


nodes:
  - address: 192.168.219.73
    user: linjungz
    role: [controlplane, etcd, worker]

services:
  etcd:
    image: rancher/etcd:v2.3.7-13
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2


system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: googlecontainer/cluster-proportional-autoscaler-amd64:1.0.0

# all addon manifests MUST specify a namespace
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-nginx
      namespace: default
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
```
**Steps to Reproduce:**
./rke up

**Results:**
```
INFO[0045] [etcd] Building up Etcd Plane..
INFO[0057] [etcd] Successfully pulled image [rancher/etcd:v2.3.7-13] on host [192.168.219.73]
INFO[0057] [etcd] Successfully started [etcd] container on host [192.168.219.73]
INFO[0057] [etcd] Successfully started Etcd Plane..
INFO[0057] [controlplane] Building up Controller Plane..
INFO[0059] [sidekick] Successfully pulled image [rancher/rke-service-sidekick:v0.1.0] on host [192.168.219.73]
INFO[0264] [controlplane] Successfully pulled image [rancher/k8s:v1.8.3-rancher2] on host [192.168.219.73]
INFO[0264] [controlplane] Successfully started [kube-api] container on host [192.168.219.73]
INFO[0264] [healthcheck] Start Healthcheck on service [kube-api] on host [192.168.219.73]
FATA[0315] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: service [kube-api] is not healthy response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}
```
