### ISSUE TITLE
Cannot specify `ingress: none` as per README

### ISSUE THREAD

**Issue by nlowe** [rancher/rke#341]
**RKE version:**

```bash
rke version v0.1.1
```

**Docker version: (`docker version`,`docker info` preferred)**

<details>
<summary>Docker Info</summary>

```bash
Containers: 12
 Running: 5
 Paused: 0
 Stopped: 7
Images: 12
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.796GiB
Name: worker-01
ID: VVPC:YIXB:IP2R:AOLL:4MFJ:GY7J:2I23:6PBE:PTGL:WQ4L:ACA5:V5HX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

<details>
<summary>/etc/os-release</summary>

```bash
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

</details>

`uname -r`: `4.4.0-112-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

```yaml
---
nodes:
  - address: master-01.k8s.mydomain.net
    user: user
    role: [controlplane, etcd]
  - address: master-02.k8s.mydomain.net
    user: user
    role: [controlplane, etcd]
  - address: master-03.k8s.mydomain.net
    user: user
    role: [controlplane, etcd]
  - address: worker-01.k8s.mydomain.net
    user: user
    role: [worker]
  - address: worker-02.k8s.mydomain.net
    user: user
    role: [worker]
ignore_docker_version: true
ingress: none
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
```

**Steps to Reproduce:**

1. `./rke up`

**Results:**

```bash
FATA[0000] Failed to parse cluster file: yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `none` into v3.IngressConfig
```

I want to use a different ingress controller. The `README` states that I should be able to specify `ingress: none` to disable the deployment of the `nginx` ingress controller:

> RKE will deploy Nginx controller by default, user can disable this by specifying `none` to `ingress` option in the cluster configuration...

Is this supposed to be specified elsewhere?
