### ISSUE TITLE
Can not set DeleteEmptyDirData to true, even with delete_local_data: true in node_drain_input

### ISSUE THREAD

**Issue by leqduyvp** [rancher/rke#3412]
**RKE version: 1.3.23**

**Steps to Reproduce:**
Set the `upgrade_strategy` as below:
```yaml
upgrade_strategy:
  max_unavailable_worker: 1
  max_unavailable_controlplane: 1
  drain: true
  node_drain_input:
    force: false
    ignore_daemonsets: true
    delete_local_data: true
```

**Results:**
Log of drain command param
`Parameters provided to drain command: "Force: false, IgnoreAllDaemonSets: true, DeleteEmptyDirData: false, Timeout: 2m0s, GracePeriodSeconds: -1"`

---
It's weird that if I add `grace_period` and `timeout` config as below, DeleteEmptyDirData is set to true as expected:
```yaml
upgrade_strategy:
  max_unavailable_worker: 1
  max_unavailable_controlplane: 1
  drain: true
  node_drain_input:
    force: false
    ignore_daemonsets: true
    delete_local_data: true
    grace_period: -1
    timeout: 1200
```
**Results:**
Log of drain command param
`Parameters provided to drain command: "Force: false, IgnoreAllDaemonSets: true, DeleteEmptyDirData: true, Timeout: 20m0s, GracePeriodSeconds: -1"`

**Comment by jiaqiluo** [comment]
Cause
 
In the declaration of the type `NodeDrainInput` ([here](https://github.com/rancher/rke/blob/dbf3a46c7cc2e56f5a62d3a22c0bc1aca40b0da6/types/rke_types.go#L1062-L1076)), the name of the same field is different in the YAML format v.s. JSON format:
- ignore_daemonsets v.s. ignoreDaemonSets
- delete_local_data v.s. deleteLocalData
- grace_period v.s gracePeriod

In the [function parseNodeDrainInput](https://github.com/rancher/rke/blob/release/v1.5/cluster/cluster.go#L647),  RKE uses `ghodssyaml.Unmarshal` and `ghodssyaml.Marshal` to covert the user's config into the `NodeDrainInput` object. those two functions internally use ` json.Marshal` and ` json.Unmarshal` to do the convention.  However because the names of the same field are different, those values are dropped in the final output. This is also why there is [ inline comment](https://github.com/rancher/rke/blob/dbf3a46c7cc2e56f5a62d3a22c0bc1aca40b0da6/cluster/cluster.go#L690) about  `ghodssyaml.Marshal` is losing the user-provided value for GracePeriod.

**Comment by jiaqiluo** [comment]
this issue can be validated in RKE [v1.5.7-rc3](https://github.com/rancher/rke/releases/tag/v1.5.7-rc3)

For validating the fix, please check [the testing section in the PR](https://github.com/rancher/rke/pull/3511)

**Comment by Josh-Diamond** [comment]
Ticket #3412 - Test Results - ✅ 
---

Verified with RKE `v1.5.7-rc3` and k8s `v1.27.11-rancher1-1 => v1.28.7-rancher1-1`:
1. Using RKE `v1.5.7-rc3`, provision a k8s `v1.27.11-rancher1-1` cluster with the following configurations set in the `cluster.yml` for the `upgrade_strategy`:
```yaml
upgrade_strategy:
  max_unavailable_worker: 1
  max_unavailable_controlplane: 1
  drain: true
  node_drain_input:
    force: false
    ignore_daemonsets: true
    delete_local_data: true
```
2. Once cluster is `active`, upgrade the k8s version to `v1.28.7-rancher1-1`
3. Verified - the following log is seen when upgrading the cluster; as expected
```log
INFO[0051] [controlplane] Processing controlplane hosts for upgrade 1 at a time
INFO[0051] [controlplane] Parameters provided to drain command: "Force: false, IgnoreAllDaemonSets: true, DeleteEmptyDirData: true, Timeout: 2m0s, GracePeriodSeconds: -1"
```
