### ISSUE TITLE
Ingress Controller Not Deployed

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#342]
**RKE version:**
rke version 6ea9ff0 (latest master)

**Docker version: (`docker version`,`docker info` preferred)**
```
Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:19:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.14.16-coreos
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure Private Cloud

**cluster.yml file:**
```
---
nodes:
- address: 10.18.160.30
  hostname_override: sandboxworker-0
  internal_address: 10.18.160.30
  role:
  - worker
  user: sandboxadmin
- address: 10.18.160.31
  hostname_override: sandboxworker-1
  internal_address: 10.18.160.31
  role:
  - worker
  user: sandboxadmin
- address: 10.18.160.32
  hostname_override: sandboxmaster-0
  internal_address: 10.18.160.32
  role:
  - controlplane
  - etcd
  user: sandboxadmin
- address: 10.18.160.34
  hostname_override: sandboxmaster-1
  internal_address: 10.18.160.34
  role:
  - controlplane
  - etcd
  user: sandboxadmin
- address: 10.18.160.33
  hostname_override: sandboxmaster-2
  internal_address: 10.18.160.33
  role:
  - controlplane
  - etcd
  user: sandboxadmin
kubernetes_version: v1.9.2-rancher1-2
network:
  plugin: flannel
auth:
  strategy: x509
authorization:
  mode: rbac
services:
  etcd:
  kube-api:
    service_cluster_ip_range: 10.233.0.0/18
    extra_args:
      cloud-config: "/etc/kubernetes/azure.conf"
      v: 4
  kube-controller:
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
    extra_args:
      cloud-config: "/etc/kubernetes/azure.conf"
  scheduler:
  kubelet:
    cluster_domain: kubelab.vpc.starbucks.net
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args:
      cloud-config: "/etc/kubernetes/azure.conf"
  kubeproxy:
ssh_key_path: "~/.ssh/kubernetes"
ignore_docker_version: true
ingress:
  provider: nginx

system_images:
  etcd: quay.io/coreos/etcd:latest
  kubernetes: rancher/k8s:v1.9.2-rancher1-2
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  kubernetes_services_sidecar: rancher/rke-service-sidekick:v0.1.0
  kubedns: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.1.2-r2
```

**Steps to Reproduce:**
```rke up```

**Results:**
No ingress controller deployed...
This could be due to the job deployment error:
```
...
INFO[0046] [worker] Successfully started Worker Plane.. 
INFO[0046] [sync] Syncing nodes Labels and Taints       
INFO[0049] [sync] Successfully synced nodes Labels and Taints 
INFO[0049] [network] Setting up network plugin: flannel 
INFO[0049] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0050] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin 
INFO[0050] [addons] Executing deploy job..              
INFO[0050] [addons] Setting up KubeDNS                  
INFO[0050] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0050] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-kubedns-addon 
INFO[0050] [addons] Executing deploy job..              
FATA[0076] Failed to deploy addon execute job: Failed to get job complete status: <nil> 
Failed to get job complete status: <nil>
```

```
$ kubectl get nodes
NAME              STATUS    ROLES         AGE       VERSION
sandboxmaster-0   Ready     etcd,master   13m       v1.9.2-rancher1
sandboxmaster-1   Ready     etcd,master   13m       v1.9.2-rancher1
sandboxmaster-2   Ready     etcd,master   13m       v1.9.2-rancher1
sandboxworker-0   Ready     worker        13m       v1.9.2-rancher1
sandboxworker-1   Ready     worker        13m       v1.9.2-rancher1
```

```
kubectl get all --all-namespaces
NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   ds/kube-flannel   5         5         5         5            5           <none>          12m

NAMESPACE     NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns              1         1         1            1           2m
kube-system   deploy/kube-dns-autoscaler   1         1         1            1           2m

NAMESPACE     NAME                                DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-6bc5c78657              1         1         1         2m
kube-system   rs/kube-dns-autoscaler-7b795dc5cf   1         1         1         2m

NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   ds/kube-flannel   5         5         5         5            5           <none>          12m

NAMESPACE     NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns              1         1         1            1           2m
kube-system   deploy/kube-dns-autoscaler   1         1         1            1           2m

NAMESPACE     NAME                                DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-6bc5c78657              1         1         1         2m
kube-system   rs/kube-dns-autoscaler-7b795dc5cf   1         1         1         2m

NAMESPACE     NAME                                 DESIRED   SUCCESSFUL   AGE
kube-system   jobs/rke-kubedns-addon-deploy-job    1         1            3m
kube-system   jobs/rke-network-plugin-deploy-job   1         1            13m

NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE
kube-system   po/kube-dns-6bc5c78657-fx8k4              3/3       Running   0          2m
kube-system   po/kube-dns-autoscaler-7b795dc5cf-8g7ng   1/1       Running   0          2m
kube-system   po/kube-flannel-8dqqs                     2/2       Running   1          12m
kube-system   po/kube-flannel-nzzf8                     2/2       Running   0          11m
kube-system   po/kube-flannel-qj6b6                     2/2       Running   0          12m
kube-system   po/kube-flannel-x466v                     2/2       Running   0          11m
kube-system   po/kube-flannel-z5rzs                     2/2       Running   1          12m

NAMESPACE     NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP         13m
kube-system   svc/kube-dns     ClusterIP   10.233.0.3   <none>        53/UDP,53/TCP   2m
```
