### ISSUE TITLE
RKE v1.4.2 | Docker v24.0.7 | Terraform v1.6.3 | failed to check etcd health

### ISSUE THREAD

**Issue by vasudeva78** [rancher/rke#3428]
**RKE version: 1.4.2**

**Docker version: 24.0.7**

**Operating system and kernel**
```
[aj_docker@vmi1462281 ~]$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
[aj_docker@vmi1462281 ~]$ 

```

**Type/provider of hosts: Contabo**

**contabo server_1  network config**
```
[aj_docker@vmi1462281 ~]$ nmcli
eth0: connected to System eth0
        "Red Hat Virtio"
        ethernet (virtio_net), 00:50:56:4C:78:6B, hw, mtu 1500
        ip4 default, ip6 default
        inet4 158.220.84.100/20
        route4 158.220.80.0/20 metric 100
        route4 default via 158.220.80.1 metric 100
        route4 158.220.80.0/20 via 158.220.80.1 metric 0
        inet6 fe80::250:56ff:fe4c:786b/64
        inet6 2a02:c204:2146:2281::1/64
        route6 2a02:c204:2146:2281::/64 metric 100
        route6 default via fe80::1 metric 100
        route6 fe80::/64 metric 1024

docker0: connected (externally) to docker0
        "docker0"
        bridge, 02:42:C0:5A:16:FF, sw, mtu 1500
        inet4 172.17.0.1/16
        route4 172.17.0.0/16 metric 0
        inet6 fe80::42:c0ff:fe5a:16ff/64
        route6 fe80::/64 metric 256

eth1: connected to System eth1
        "Red Hat Virtio"
        ethernet (virtio_net), 16:7B:66:78:60:90, hw, mtu 1500
        inet4 10.0.0.2/22
        route4 10.0.0.0/22 metric 101
        inet6 fe80::147b:66ff:fe78:6090/64
        route6 fe80::/64 metric 256

lo: connected (externally) to lo
        "lo"
        loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536
        inet4 127.0.0.1/8
        inet6 ::1/128
        route6 ::1/128 metric 256

Use "nmcli device show" to get complete information about known devices and
"nmcli connection show" to get an overview on active connection profiles.

Consult nmcli(1) and nmcli-examples(7) manual pages for complete usage details.
[aj_docker@vmi1462281 ~]$ 
```

**contabo server_1  firewall config**
```
[aj_docker@vmi1462281 ~]$ sudo firewall-cmd --zone=public --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 2379/tcp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
[aj_docker@vmi1462281 ~]$ 

```

**contabo server_2  network config**
```
aj_docker@vmi1462282 ~]$ nmcli
eth0: connected to System eth0
        "Red Hat Virtio"
        ethernet (virtio_net), 00:50:56:4C:78:6D, hw, mtu 1500
        ip4 default, ip6 default
        inet4 158.220.84.102/20
        route4 158.220.80.0/20 metric 100
        route4 default via 158.220.80.1 metric 100
        route4 158.220.80.0/20 via 158.220.80.1 metric 0
        inet6 fe80::250:56ff:fe4c:786d/64
        inet6 2a02:c204:2146:2282::1/64
        route6 2a02:c204:2146:2282::/64 metric 100
        route6 default via fe80::1 metric 100
        route6 fe80::/64 metric 1024

docker0: connected (externally) to docker0
        "docker0"
        bridge, 02:42:12:1B:C3:9A, sw, mtu 1500
        inet4 172.17.0.1/16
        route4 172.17.0.0/16 metric 0
        inet6 fe80::42:12ff:fe1b:c39a/64
        route6 fe80::/64 metric 256

eth1: connected to System eth1
        "Red Hat Virtio"
        ethernet (virtio_net), 66:F7:1C:A7:E0:8A, hw, mtu 1500
        inet4 10.0.0.1/22
        route4 10.0.0.0/22 metric 101
        inet6 fe80::64f7:1cff:fea7:e08a/64
        route6 fe80::/64 metric 256

lo: connected (externally) to lo
        "lo"
        loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536
        inet4 127.0.0.1/8
        inet6 ::1/128
        route6 ::1/128 metric 256

Use "nmcli device show" to get complete information about known devices and
"nmcli connection show" to get an overview on active connection profiles.

Consult nmcli(1) and nmcli-examples(7) manual pages for complete usage details.
[aj_docker@vmi1462282 ~]$ 

```

**contabo server_2  firewall config**
```
[aj_docker@vmi1462282 ~]$ sudo firewall-cmd --zone=public --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 2379/tcp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
[aj_docker@vmi1462282 ~]$ 

```

**terraform main.tf**
```
terraform {
  required_providers {
    rke = {
      source  = "rancher/rke"
      version = "1.4.2"

    }
  }
}

provider "rke" {
  debug    = true
  log_file = "./rke_debug.log"
}

resource rke_cluster "my-first-cluster" {
  cluster_name = "my-first-k8s-cluster"
  cluster_yaml = file("./cluster.yml")

  # If set to true, RKE will not fail when unsupported Docker version are found
  ignore_docker_version = true

  # Keep using Docker as the default container runtime
  enable_cri_dockerd = true
}

###############################################################################
# If you need kubeconfig.yml for using kubectl, please uncomment follows.
###############################################################################
resource "local_file" "kube_cluster_yaml" {
  filename = "./kube_config_cluster.yml"
  content  = rke_cluster.my-first-cluster.kube_config_yaml
}
```

**cluster.yml**
```
nodes:
  - address: 158.220.84.100
    internal_address: 10.0.0.2
    nodeName: server_1
    user: aj_docker
    role:
      - controlplane
      - etcd
    ssh_key_path: /home/aj/.ssh/id_rsa

  - address: 158.220.84.102
    internal_address: 10.0.0.1
    nodeName: server_2
    user: aj_docker
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: /home/aj/.ssh/id_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
```

**rke_debug.yml: https://pastebin.com/ms12K731**

**docker ps -a:**
```
[aj_docker@vmi1462281 ~]$ docker ps -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED       STATUS                   PORTS     NAMES
a3204889a408   rancher/rke-tools:v0.1.89             "/docker-entrypoint.…"   5 hours ago   Up 5 hours                         etcd-rolling-snapshots
4263f68a947f   rancher/mirrored-coreos-etcd:v3.5.6   "/usr/local/bin/etcd…"   5 hours ago   Up 5 hours                         etcd
d74f46d6a1dc   rancher/rke-tools:v0.1.89             "/docker-entrypoint.…"   5 hours ago   Exited (0) 5 hours ago             cluster-state-deployer
[aj_docker@vmi1462281 ~]$ 
```

**docker logs 426 : https://pastebin.com/sWdLPzW6**

Help please !!!
