### ISSUE TITLE
 failed to check etcd health: failed to get /health for host .. remote error: tls: bad certificate 

### ISSUE THREAD

**Issue by david-nano** [rancher/rke#3457]
**RKE version:** v1.5.0-rc8

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 9
  Paused: 0
  Stopped: 8
 Images: 10
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-166-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.697GiB
 Name: eng-k8s-1.domain-di.local
 ID: 67f5bcca-8865-46c2-a167-7d108e2a862f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  cubinary.dc.local:8083
  cubinary.dc.local:8084
  cubinary.dc.local:8082
  127.0.0.0/8
 Registry Mirrors:
  http://cubinary.dc.local:8084/
 Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```
# If you intended to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
kubernetes_version: v1.24.17-rancher1-1
upgrade_strategy:
  max_unavailable_worker: 10%
  max_unavailable_controlplane: 1
nodes:
- address: 10.*00.10.123
  port: "22"
  role:
  - controlplane
  - etcd
  hostname_override: eng-k8s-1
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: 10.*00.10.124
  port: "22"
  role:
  - controlplane
  hostname_override: eng-k8s-2
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: 10.*00.10.125
  port: "22"
  role:
  - controlplane
  - etcd
  hostname_override: eng-k8s-3
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: 10.*00.10.127
  port: "22"
  internal_address: ""
  role:
    - worker
  hostname_override: eng-k8s-worker1
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: 10.*00.10.128
  port: "22"
  role:
  - worker
  hostname_override: eng-k8s-worker2
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: 10.*00.10.129
  port: "22"
  role:
  - worker
  hostname_override: eng-k8s-worker3
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: eng-k8s-gworker1.domain-di.local
  port: "22"
  role:
    - worker
  hostname_override: eng-k8s-gworker1
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: eng-k8s-gworker2.domain-di.local
  port: "22"
  role:
    - worker
  hostname_override: eng-k8s-gworker2
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: eng-k8s-gworker3.domain-di.local
  port: "22"
  role:
    - worker
  hostname_override: eng-k8s-gworker3
  user: dcdevops
  docker_socket: /var/run/docker.sock
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  taints: []
- address: r2d6-linux.domain-di.local
  port: "22"
  role:
    - worker
  hostname_override: r2d6
  user: dcdevops
  ssh_key_path: ~/.ssh/id_rsa
  labels:
    gitlab-runner-generic: true
  taints:
    - key: "gitlab-runner-generic"
      effect: NoSchedule
      value: true
services:
  etcd:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args:
      cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
      cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: calico
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
private_registries: []
ingress:
  provider: none
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
  default_ingress_class: null
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null
```

**Steps to Reproduce:**
I got a running cluster a more than a year.
I've wanted to do some changes, so I've got back into my RKE folder, run `rke up` before doing any change, and got some issues with etcd.
Found that control plane number 2 has restarted etc, so I've removed etcd from worker 2, but I still have the same result when doing `rke up`

**Results:**
```
INFO[0044] [etcd] Successfully started etcd plane.. Checking etcd cluster health 
WARN[0145] [etcd] host [10.*00.10.123] failed to check etcd health: failed to get /health for host [10.*00.10.123]: Get "https://10.*00.10.123:2379/health": remote error: tls: bad certificate 
WARN[0246] [etcd] host [10.*00.10.125] failed to check etcd health: failed to get /health for host [10.*00.10.125]: Get "https://10.*00.10.125:2379/health": remote error: tls: bad certificate 
FATA[0246] [etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [10.*00.10.123,10.*00.10.125] failed to report healthy. Check etcd container logs on each host for more information 
```
