### ISSUE TITLE
v1.5.1 rke up on existing cluster fails: for v1.26.11-rancher2-1 [cluster upgrade]

### ISSUE THREAD

**Issue by Vox1984** [rancher/rke#3467]
**RKE version: v1.5.1**

**Rancher version: 2.7.9**

**Docker version:  20.10.23**

**Operating system and kernel: "Debian GNU/Linux 10 (buster)" | 4.19.0-25-cloud-amd64**

**Type/provider of hosts: openstack**

**cluster.yml**:

```
nodes:
- address: rancher-worker-01
  port: "22"
  internal_address: "10.50.2.31"
  role:
  - worker
  hostname_override: rancher-worker-01"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher-worker-02
  port: "22"
  internal_address: "10.50.2.32"
  role:
  - worker
  hostname_override: rancher-worker-02"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher-worker-03
  port: "22"
  internal_address: "10.50.2.33"
  role:
  - worker
  hostname_override: rancher-worker-03"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher-master-01
  port: "22"
  internal_address: "10.50.2.21"
  role:
  - controlplane
  - etcd
  hostname_override: rancher-master-01"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher-master-02
  port: "22"
  internal_address: "10.50.2.22"
  role:
  - controlplane
  - etcd
  hostname_override: rancher-master-02"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: rancher-master-03
  port: "22"
  internal_address: "10.50.2.23"
  role:
  - controlplane
  - etcd
  hostname_override: rancher-master-03"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 52034
    gid: 52034
    snapshot: null
    retention: ""
    creation: ""
    backup_config:
      interval_hours: 3
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config:
      enabled: true
    audit_log:
      enabled: true
      configuration:
        max_age: 6
        max_backup: 6
        max_size: 110
        path: /var/log/kube-audit/audit-log.json
        format: json
        policy:
          apiVersion: audit.k8s.io/v1 # This is required.
          kind: Policy
          omitStages:
            - "RequestReceived"
          rules:
            # Log pod changes at RequestResponse level
            - level: RequestResponse
              resources:
              - group: ""
                # Resource "pods" doesn't match requests to any subresource of pods,
                # which is consistent with the RBAC policy.
                resources: ["pods"]
            # Log "pods/log", "pods/status" at Metadata level
            - level: Metadata
              resources:
              - group: ""
                resources: ["pods/log", "pods/status"]

            # Don't log requests to a configmap called "controller-leader"
            - level: None
              resources:
              - group: ""
                resources: ["configmaps"]
                resourceNames: ["controller-leader"]

            # Don't log watch requests by the "system:kube-proxy" on endpoints or services
            - level: None
              users: ["system:kube-proxy"]
              verbs: ["watch"]
              resources:
              - group: "" # core API group
                resources: ["endpoints", "services"]

            # Don't log authenticated requests to certain non-resource URL paths.
            - level: None
              userGroups: ["system:authenticated"]
              nonResourceURLs:
              - "/api*" # Wildcard matching.
              - "/version"

            # Log the request body of configmap changes in kube-system.
            - level: Request
              resources:
              - group: "" # core API group
                resources: ["configmaps"]
              # This rule only applies to resources in the "kube-system" namespace.
              # The empty string "" can be used to select non-namespaced resources.
              namespaces: ["kube-system"]

            # Log configmap and secret changes in all other namespaces at the Metadata level.
            - level: Metadata
              resources:
              - group: "" # core API group
                resources: ["secrets", "configmaps"]

            # Log all other resources in core and extensions at the Request level.
            - level: Request
              resources:
              - group: "" # core API group
              - group: "extensions" # Version of group should NOT be included.

            # A catch-all rule to log all other requests at the Metadata level.
            - level: Metadata
              # Long-running requests like watches that fall under this rule will not
              # generate an audit event in RequestReceived.
              omitStages:
                - "RequestReceived"
    admission_configuration: null
    event_rate_limit:
      enabled: true
  kube-controller:
    image: ""
    extra_args:
      feature-gates: "RotateKubeletServerCertificate=true"
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args:
      profiling: 'false'
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args:
      anonymous-auth: 'false'
      event-qps: '0'
      feature-gates: "RotateKubeletServerCertificate=true"
      protect-kernel-defaults: "true"
      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: true
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons_include: []
ssh_key_path: /home/rke/.ssh/id_ecdsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: "v1.26.11-rancher2-1"
enable_network_policy: true
#default_pod_security_policy_template_id: "restricted"
private_registries: []
ingress:
  provider: ""
  options:
    proxy-body-size: 10m
    use-proxy-protocol: "true"
    server-tokens: "false"
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
cluster_name: rancher"
cloud_provider:
    name: openstack
    openstackCloudProvider:
      global:
        username: "xxxx"
        password: "xxxxxxxxxxx"
        auth-url: "https://hostname.some.com:5000/v3"
        tenant-id: "yyyyyyyyyyy"
        domain-name: "some.com"
      load_balancer:
        subnet-id: "aaa-bbb-ccc"
      block_storage:
        ignore-volume-az: true
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
restore:
  restore: false
  snapshot_name: ""
dns: null
```

**Steps to Reproduce:**
I have running rke1 cluster with 3 master and 3 worker nodes, v1.5.1, kubernetes version v1.25.16 without issues.
I am trying to upgrade kubernetes version with same rke, v1.5.1 to version v1.26.11:
`rke up --config /usr/local/bin/cluster.yml >> /var/log/rancher/install.log`

**Results:**
It fails upgrade, giving me error:

```
time="2024-01-09T17:22:41+01:00" level=info msg="[worker] Successfully updated [kubelet] container on host [rancher-master-01]"
time="2024-01-09T17:22:41+01:00" level=info msg="Removing container [old-kubelet] on host [rancher-master-01], try #1"
time="2024-01-09T17:22:41+01:00" level=info msg="[healthcheck] Start Healthcheck on service [kubelet] on host [rancher-master-01]"
time="2024-01-09T17:23:32+01:00" level=error msg="Failed to upgrade hosts: rancher-master-01 with error [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [rancher-master-01]: Get \"http://localhost:10248/healthz\": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: time=\"2024-01-09T16:23:22Z\" level=info msg=\"Start cri-dockerd grpc backend\"]"
time="2024-01-09T17:23:32+01:00" level=fatal msg="[controlPlane] Failed to upgrade Control Plane: [[Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [rancher-master-01]: Get \"http://localhost:10248/healthz\": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: time=\"2024-01-09T16:23:22Z\" level=info msg=\"Start cri-dockerd grpc backend\"]]"
```
The master node: rancher-master-01 is now in cordoned state, Not Ready, Scheduling Disabled.
after inspection, with `docker ps` there is no kubelet container running on rancher-master-01
