### ISSUE TITLE
Can't register a node from a new template on a downstream cluster

### ISSUE THREAD

**Issue by yoav-miles-se** [rancher/rke#3487]
**RKE version:** 1.4.10

**Docker version: (`docker version`,`docker info` preferred)**
* RKE cluster (Kubernetes v1.24.17-rancher1-1):
```
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 59
  Running: 30
  Paused: 0
  Stopped: 29
 Images: 33
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-72-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: rancher-worker-01
 ID: 213d65e2-7ecd-449b-a058-d3af29c01de6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
* Downstream cluster (Kubernetes v1.26.8):
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 3
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 94.38GiB
 Name: qa-v7-worker2
 ID: 5690602d-2c07-4c7f-98eb-5c10bf973ebd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=vmwarevsphere
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://<redacted>/
 Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
* RKE cluster (Kubernetes v1.24.17-rancher1-1):
`5.15.0-72-generic`
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* Downstream cluster (Kubernetes v1.26.8):
`5.15.0-91-generic`
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
On-premise vSphere: virtual machines on VMware ESX

**cluster.yml file:**
```
nodes:
- address: 10.171.30.241
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: my-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.171.30.242
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: my-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.171.30.243
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: my-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.171.30.244
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: my-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.171.30.245
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: my-user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: my-company.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
ssh_key_path: /path/to/ssh/key
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: v1.24.17-rancher1-1
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
restore:
  restore: false
  snapshot_name: ""
dns: null
```

**Steps to Reproduce:**
Add a new node template and pool in Terraform and apply them:
```
resource "rancher2_node_template" "ubuntu22-v1-node-template" {
  name                = "ubuntu22-node-template-${var.cluster_name}"
  cloud_credential_id = rancher2_cloud_credential.vcenter.id
  vsphere_config {
    vcenter                   = var.vcenter_ip
    datacenter                = var.datacenter
    pool                      = var.pool
    datastore                 = var.datastore
    folder                    = var.folder
    cpu_count                 = 24
    memory_size               = 98304
    disk_size                 = 102400
    creation_type             = "template"
    clone_from                = var.vm_template_ubuntu22
    network                   = var.network
    cloud_config              = templatefile(var.cloud_config_path_ubuntu22, {
      USERNAME = var.domain_user,
      PASSWORD = var.domain_password
    })
  }
  engine_install_url = "https://releases.rancher.com/install-docker/23.0.sh"
}

resource "rancher2_node_pool" "kube_worker_v7_node_pool" {
  cluster_id       = rancher2_cluster.rancher_cluster.id
  name             = "kube-workers-v7-${var.cluster_name}"
  hostname_prefix  = "${var.nodes_prefix}-v7-worker"
  node_template_id = rancher2_node_template.ubuntu22-v1-node-template.id
  quantity         = 1
  control_plane    = false
  etcd             = false
  worker           = true
}
```

**Results:**
Expected: A new node is created
Actual: A new node is created, but is stuck on the final step: "Waiting to register with Kubernetes"

My current worker nodes are based on an Ubuntu 18.04.6 template and I want to replace them with a new template based on Ubuntu 22.04.3. After Rancher is done provisioning a new machine it tries to register in to the cluster and I get the following message in Rancher's logs on the RKE cluster:
```
$ kubectl -n cattle-system logs svc/rancher
...
[ERROR] error syncing 'c-kk7ws/m-rj7nh': handler rke-worker-upgrader: getNodePlan error for node [m-rj7nh]: failed to find plan for 10.171.30.19, requeuing
...
```
These are the containers Rancher has created on the new machine:
```
$ sudo docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                      PORTS     NAMES
03396ef12367   rancher/hyperkube:v1.26.8-rancher1   "sh -c 'mkdir -p /va…"   58 seconds ago   Exited (1) 57 seconds ago             rke-log-linker-kubelet
4d5e92ccfdbe   rancher/hyperkube:v1.26.8-rancher1   "sh -c 'mkdir -p /va…"   58 seconds ago   Exited (1) 57 seconds ago             rke-log-linker-kube-proxy
907d25ca14ee   rancher/hyperkube:v1.26.8-rancher1   "/opt/rke-tools/entr…"   15 hours ago     Created                               kubelet
e85c80f88240   rancher/hyperkube:v1.26.8-rancher1   "/opt/rke-tools/entr…"   16 hours ago     Created                               kube-proxy
a43ec802b8a4   rancher/rke-tools:v0.1.90            "nginx-proxy CP_HOST…"   16 hours ago     Up 14 hours                           nginx-proxy
a7c001575f9d   rancher/rancher-agent:v2.7.9         "run.sh --no-registe…"   16 hours ago     Exited (0) 14 hours ago               share-mnt
7039436059f5   rancher/rke-tools:v0.1.90            "/bin/bash"              16 hours ago     Exited (0) 14 hours ago               service-sidekick
5c501278e129   rancher/rancher-agent:v2.7.9         "run.sh --server htt…"   16 hours ago     Up 14 hours                           lucid_beaver
```
When I try to manually start the kubelet container I get:
```
$ sudo docker start kubelet
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/rke-tools/entrypoint.sh": permission denied: unknown
Error: failed to start containers: kubelet
```
This left me baffled - the entrypoint script is executable and this was the only error I could find. The rancher-agent containers are running, so there is no issue with Docker itself. There is no fancy stuff in Docker's configuration either:
```
$ sudo cat /etc/docker/daemon.json
{
  "bip": "172.17.0.1/16",
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "5"
  },
  "mtu": 8950,
  "default-network-opts": {
    "bridge": {
      "com.docker.network.bridge.mtu": "8950"
    }
  },
  "registry-mirrors" : ["https://<redacted>"]
}
```
Clearly I'm doing something wrong because the Ubuntu 18.04.6 nodes can be provisioned, but I can't seem to find the issue by myself. The configurations of the Ubuntu 18.04.6 and 22.04.3 are both the same except for the OS and Docker versions.

I'm not sure if I opened the issue in right project, but maybe you have an idea on how to further investigate the startup error of the kubelet container?
The same image (`rancher/hyperkube:v1.26.8-rancher1`) runs with no issues on the Ubuntu 18.04.6 nodes.
The docker --debug flag didn't provide any more info unfortunately.

Thank you!

**Comment by yoav-miles-se** [comment]
Never mind, the fault was that I mounted `/var/lib/docker` with the `noexec` option...

Now I have another problem where the kubelet container can't reserve ephemeral-storage, but it's not likely that it's related to RKE so I'm closing this. Sorry to bother.
```
{"ts":1706181759804.5632,"caller":"app/server.go:659","msg":"--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /","v":0}
{"ts":1706181759804.6077,"caller":"cli/run.go:74","msg":"command failed","err":"failed to run Kubelet: cannot reserve \"ephemeral-storage\\\"\" resource"}
```

**Comment by yoav-miles-se** [comment]
If anyone wonders - the second error was actually because of a misconfigured /var/lib/kubelet/config.yaml (didn't quote the keys).
This is a working config.yaml for example:
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
readOnlyPort: 10255
logging:
  format: json
  sanitization: false
systemReserved:
  "cpu": "0.25"
  "memory": "500Mi"
kubeReserved:
  "cpu": "0.25"
  "memory": "500Mi"
  "ephemeral-storage": "500Mi"
evictionHard:
  "memory.available": "150Mi"
  "imagefs.available": "3%"
  "imagefs.inodesFree": "3%"
  "nodefs.available": "3%"
  "nodefs.inodesFree": "3%"
evictionMinimumReclaim:
  "nodefs.available": "400Mi"
  "imagefs.available": "400Mi"
```
