### ISSUE TITLE
kubectl exec and logs not working.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#36]
rke version v0.0.3-dev

Steps to reproduce the problem:
Create a cluster using hosts from Digitial Ocean provider.
Create user pods.
kubectl exec and logs do not work.

```
Sangeethas-MBP:~ sangeethahariharan1$ kubectl exec -it k8testnew-0fbtw  bash
Error from server: error dialing backend: dial tcp: lookup sangee-now-rke-5 on 67.207.67.2:53: no such host
Sangeethas-MBP:~ sangeethahariharan1$ kubectl logs k8testnew-0qrpx
Error from server: Get https://sangee-now-rke-5:10250/containerLogs/default/k8testnew-0qrpx/testcontainer: dial tcp: lookup sangee-now-rke-5 on 67.207.67.2:53: no such host
```

**Comment by galal-hussein** [comment]
@sangeethah In DO hostnames are not resolvable so kubeapi will not be able to reach the node by hostname, it will cause exec/logs to fail, to solve this you can just specify the following extra arguments for kubeapi service:
```
extra_args:
  kubelet-preferred-address-types: "InternalIP,ExternalIP,Hostname"
```

**Comment by sangeethah** [comment]
rke version v0.0.4-dev

Steps to reproduce the problem:

used the following  extra_args for kube-api service:
```
extra_args:
  kubelet-preferred-address-types: "InternalIP,ExternalIP,Hostname"
```

Create a cluster using hosts from Digitial Ocean provider.
Create user pods.
kubectl exec and logs works.

**Comment by sangeethah** [comment]
Reopening this issue  to support the case where when the advertised_hostname provided is not resolvable there should be no need for user to manually override the default order for kube-api service by providing kubelet-preferred-address-types

**Comment by sangeethah** [comment]
rke version v0.0.6-dev

Following configurations works fine:
Able to create K8s cluster successfully.
Able to deploy pods.
Able to launch dashboard addon.
Able to exec/log to containers.

1. Specify host , internal_address and hostname_override.
In this case hostname_override is not resolvable:
 nodes:
  - address: ec2-<ip>.us-east-2.compute.amazonaws.com
    internal_address: <ip>
    hostname_override: mynode1
    user: ubuntu
    role: [controlplane]

nodes get registered with the "hostname_override" value.

There was no extra parameters that were set for  kubeapi service:

```
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
```
