### ISSUE TITLE
worker node label lost after node reboot [v1.5.10]

### ISSUE THREAD

**Issue by Vox1984** [rancher/rke#3614]
**RKE version:**
v1.5.10  

**Docker version: (`docker version`,`docker info` preferred)**
24.0.9
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 11 (bullseye)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
openstack
**cluster.yml file:**
```
- address: yy-xx-rancher-accept-worker-03
  port: "22"
  internal_address: "10.X0.X.33"
  role:
  - worker
  hostname_override: "yy-xx-rancher-accept-worker-03"
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rke/.ssh/id_ecdsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
```
**Steps to Reproduce:**
Reboot worker node: yy-xx-rancher-accept-worker-03
**Results:**
Node label: node-role.kubernetes.io/worker: "true" is gone from yy-xx-rancher-accept-worker-03.
Happens always.
For kubectl get nodes:
```
NAME                             STATUS   ROLES               AGE    VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION          CONTAINER-RUNTIME

yy-xx-rancher-accept-worker-03   Ready    <none>              10m    v1.28.10   XX.XX.XX.XX    <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-30-cloud-amd64   docker://24.0.9
```
To make worker node usable, it is needed to add the label manually,
or run rke up --config cluster.yml --update-only
