### ISSUE TITLE
Rename "ip" to "host" and make "advertised_hostname" optional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#41]
host config parameter requirements:

advertised_hostname: Optional - If provided ,  name should be resolvable
host:  Required - can be ip of fqdn that is fully resolvable externally
advertise_address: Optional - Internally resolvable ips

Default resolution order ( in kube api):
advertised_hostname
advertise_address
host

This can be altered by configuring the following in kube api:
```
  extra_args:
      kubelet-preferred-address-types: "InternalIP,ExternalIP,Hostname"
```

This will allow for hostname resolution to not take effect and hence allow for providing "advertised_hostname" to be non resolvable names.

**Comment by sangeethah** [comment]
rke version v0.0.6-dev

Following configurations  works fine:
Able to create K8s cluster successfully.
Able to deploy pods.
Able to launch dashboard addon.
Able to exec/log to containers.


1. Specify only address for host:
```
nodes:
  - address: ec2-<ip>.us-east-2.compute.amazonaws.com
    user: ubuntu
    role: [controlplane]
```

In this case , nodes get registered with the "address".

2. Specify host , internal_address and hostname_override. 
In my case hostname_override is not resolvable:

```
 nodes:
  - address: ec2-<ip>.us-east-2.compute.amazonaws.com
    internal_address: <ip>
    hostname_override: mynode1
    user: ubuntu
    role: [controlplane]
```

In this case , nodes get registered with the "hostname_override" value.
