### ISSUE TITLE
Unable to perform `rke up` with ssh_key_path field

### ISSUE THREAD

**Issue by kujenga** [rancher/rke#441]
**RKE version:**

` v0.1.3-rc4`

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 16.04

17.4.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**cluster.yml file:**

```yaml
nodes:
  - address: 10.0.1.10
    user: ubuntu
    role: [controlplane]
    ssh_key_path: ~/.ssh/my-key.pem
  - address: 10.0.1.11
    user: ubuntu
    role: [worker]
    ssh_key_path: ~/.ssh/my-key.pem
  - address: 10.0.1.12
    user: ubuntu
    role: [etcd]
    ssh_key_path: ~/.ssh/my-key.pem
```

**Steps to Reproduce:**

run `rke up --config path/to/cluster.yaml`

**Results:**

The ssh key is not found, with these error logs for each of the hosts:

```
INFO[0000] [dialer] Setup tunnel for host [10.0.1.10]  
WARN[0000] Failed to set up SSH tunneling for host [10.0.1.10]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [10.0.1.10:22]: Error configuring SSH: ssh: no key found 
```

The key at `~/.ssh/my-key.pem` does exist, and making the paths to them absolute does not help things. Adding the literal `ssh_key` field to the cluster.yml does work.

Looking through the code a bit, it appears the the following function may be swallowing an error of some kind:
https://github.com/rancher/rke/blob/486cea84646d1608a3548d61d7caa385308f7a8b/hosts/tunnel.go#L123-L129

Still though, I'm not able to get that field working.
