### ISSUE TITLE
i had I the similar problem,

### ISSUE THREAD

**Issue by saiJPlus** [rancher/rke#483]
**RKE version:**
rke version v0.1.5-rc2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware
**cluster.yml file:**
```
---
auth:
  strategy: x509
  options:
    foo: bar
network:
  plugin: flannel
  options:
    flannel_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/flannel
    flannel_cni_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/flannel-cni
nodes:
  - address: 192.168.61.136
    user: lsj
    role: [controlplane, etcd]
    ssh_key_path: /home/lsj/.ssh/id_rsa
  - address: 192.168.61.137
    user: lsj
    role: [worker]
    ssh_key_path: /home/lsj/.ssh/id_rsa
services:
  etcd:
      image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/pause-amd64:3.0
    command: --fail-swap-on=false
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: registry.cn-shenzhen.aliyuncs.com/rancher_cn/cluster-proportional-autoscaler-amd64:1.0.0
# all addon manifests MUST specify a namespace
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-nginx
      namespace: default
    spec:
      containers:
      - name: my-nginx
        image: nginx
      ports:
        - containerPort: 80
```

**Steps to Reproduce:**

**Results:**
 at first,i run rke,but it report some mistake:
FATA[1382] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [192.168.61.136]. Response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}
then, i try to use ./rke remove,./rke up ,new problem occured:
FATA[0069] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [192.168.61.136]. Response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}
