### ISSUE TITLE
Docker Daemon: Invalid Mount Config

### ISSUE THREAD

**Issue by rossedman** [rancher/rke#489]
**RKE version:** 1.5

**Docker version: (`docker version`,`docker info` preferred)** 17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** CoreOS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Azure

**cluster.yml file:**
```
#
# this file was autogenerated, do not edit manually
# template generated from: snd.yaml.j2
#
nodes:
  # control plane
  - address: 172.28.2.6
    user: rancher
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube-ctl0
  - address: 172.28.2.5
    user: rancher
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube-ctl1

  # general compute
  - address: 172.28.2.9
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-gpc0
  - address: 172.28.2.12
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-gpc1
  - address: 172.28.2.13
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-gpc2
  - address: 172.28.2.14
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-gpc3
  - address: 172.28.2.10
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-gpc4
  - address: 172.28.2.11
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-gpc5

  # load balancers
  - address: 172.28.2.7
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-lbe0
  - address: 172.28.2.8
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube-lbe1

services:
  kube-api:
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0

kubernetes_version: v1.8.9-rancher1-2

ssh_key_path: ~/.ssh/nozomi_rsa

ignore_docker_version: true

network:
  plugin: flannel

ingress:
  provider: none

addons_include:
  - ./rke/addons/helm-crd.yaml
  - ./rke/addons/ingress.yaml
  - ./rke/addons/cert-manager.yaml
  - ./rke/addons/tsp-base.yaml
```

**Steps to Reproduce:**

Ran RKE remove and then reprovisioned. This error occurs and cannot be resolved. This was on a cluster that I previously setup with RKE that had nothing running on it. Sustained frequest NodeLost errors and lost half the cluster multiple times. Have not had problems provisioning clusters until now.

**Results:**

```
Failed to create [kubelet] container on host [172.28.2.6]: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate" 
```
