### ISSUE TITLE
Directory /sys/fs/cgroup/cpuacct,cpu missing on RHEL 7.3 with Kubernetes v1.9.5-rancher1-{1,2}

### ISSUE THREAD

**Issue by frankhinek** [rancher/rke#498]
**NOTE**: This issue was not resolved by the latest `rancher/k8s:v1.9.5-rancher2` image.

#### **Docker version:**
<details>
<summary>docker version</summary>

```bash
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
</details>
<details>
<summary>docker info</summary>

```bash
Containers: 18
 Running: 10
 Paused: 0
 Stopped: 8
Images: 11
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702 GiB
Name: HIC005233
ID: JONT:5UKZ:YNVQ:4BPH:3D2J:J66E:EAIS:M5EW:UQDK:2GYO:PSGK:R7JC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
</details>

#### **Operating system and kernel:**

<details>
<summary>cat /etc/os-release</summary>

```bash
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
```
</details>

<details>
<summary>uname -r</summary>

```bash
3.10.0-514.el7.x86_64
```
</details>

#### **Type/provider of hosts:**
Virtual machines running on VMware vSphere cluster

#### **cluster.yml file:**
<details>
<summary>cluster-A.yml</summary>

```yaml
nodes:
- address: 10.224.88.38
  hostname_override: control01
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.86
  hostname_override: control02
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.30
  hostname_override: control03
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.81
  hostname_override: worker01
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

- address: 10.224.88.85
  hostname_override: worker02
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

- address: 10.224.88.178
  hostname_override: worker03
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

services:
  etcd:
    image: rancher/coreos-etcd:v3.0.17
  kube-api:
    image: rancher/k8s:v1.9.5-rancher1-1
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.9.5-rancher1-1
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: rancher/k8s:v1.9.5-rancher1-1
  kubelet:
    image: rancher/k8s:v1.9.5-rancher1-1
    cluster_domain: cluster.local
    infra_container_image: rancher/pause-amd64:3.0
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    extra_args: {"feature-gates": "DevicePlugins=true"}  # for k8s 1.8+
  kubeproxy:
    image: rancher/k8s:v1.9.5-rancher1-1

network:
  plugin: canal
authentication:
  strategy: x509
ssh_agent_auth: true
authorization:
  mode: rbac
ignore_docker_version: false
kubernetes_version: v1.9.5-rancher1-1
cluster_name: kube01
ingress:
  provider: none
```
</details>

<details>
<summary>cluster-B.yml</summary>

```yaml
nodes:
- address: 10.224.88.38
  hostname_override: control01
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.86
  hostname_override: control02
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.30
  hostname_override: control03
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.81
  hostname_override: worker01
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

- address: 10.224.88.85
  hostname_override: worker02
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

- address: 10.224.88.178
  hostname_override: worker03
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

services:
  etcd:
    image: rancher/coreos-etcd:v3.0.17
  kube-api:
    image: rancher/k8s:v1.9.5-rancher1-2
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.9.5-rancher1-2
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: rancher/k8s:v1.9.5-rancher1-2
  kubelet:
    image: rancher/k8s:v1.9.5-rancher1-2
    cluster_domain: cluster.local
    infra_container_image: rancher/pause-amd64:3.0
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    extra_args: {"feature-gates": "DevicePlugins=true"}  # for k8s 1.8+
  kubeproxy:
    image: rancher/k8s:v1.9.5-rancher1-2

network:
  plugin: canal
authentication:
  strategy: x509
ssh_agent_auth: true
authorization:
  mode: rbac
ignore_docker_version: false
cluster_name: kube01
ingress:
  provider: none
```
</details>

#### **Steps to Reproduce:**
1. Build 6 virtual machines running RHEL 7.3 and install Docker 17.03.2
2. Run `rke up --config cluster-A.yml` (using the `A` version of the RKE included above)
3. Observe `ImageGCFailed` events in the output of `kubectl describe node <node>` and errors in the `kubelet` container logs on all 6 nodes.

#### **Results:**
When the cluster is built with `cluster-A.yml` which uses the `rancher/k8s:v1.9.5-rancher1-1` image for the kube control plane containers the result is the following event repeated endlessly on all 6 nodes (e.g., output of `kubectl describe node control02`):
```bash
Events:
  Type     Reason                   Age                From               Message
  ----     ------                   ----               ----               -------
  Warning  ImageGCFailed            1m (x10 over 46m)  kubelet, worker01  failed to get imageFs info: unable to find data for container /
```

Examining `docker logs kubelet` on the control02 node reveals thousands of entries like the following:
```bash
W0412 00:30:48.091180   25810 container.go:507] Failed to update stats for container "%s": %s/kubepods/burstableopen /sys/fs/cgroup/cpuacct,cpu/kubepods/burstable/cpuacct.stat: no such file or directory, continuing to push stats
W0412 00:30:53.977747   25810 container.go:507] Failed to update stats for container "%s": %s/kubepods/besteffortopen /sys/fs/cgroup/cpuacct,cpu/kubepods/besteffort/cpuacct.stat: no such file or directory, continuing to push stats
E0412 00:30:54.520934   25810 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
```

I confirmed the `cpuacct,cpu` directory was missing from `/sys/fs/cgroup`:

<details>
<summary>ls -l /sys/fs/cgroup/</summary>

```bash
drwxr-xr-x. 6 root root  0 Apr 11 22:41 blkio
lrwxrwxrwx. 1 root root 11 Apr 11 22:41 cpu -> cpu,cpuacct
lrwxrwxrwx. 1 root root 11 Apr 11 22:41 cpuacct -> cpu,cpuacct
drwxr-xr-x. 6 root root  0 Apr 11 22:41 cpu,cpuacct
drwxr-xr-x. 4 root root  0 Apr 11 22:41 cpuset
drwxr-xr-x. 6 root root  0 Apr 11 23:09 devices
drwxr-xr-x. 4 root root  0 Apr 11 22:41 freezer
drwxr-xr-x. 4 root root  0 Apr 11 22:41 hugetlb
drwxr-xr-x. 6 root root  0 Apr 11 22:41 memory
lrwxrwxrwx. 1 root root 16 Apr 11 22:41 net_cls -> net_cls,net_prio
drwxr-xr-x. 4 root root  0 Apr 11 22:41 net_cls,net_prio
lrwxrwxrwx. 1 root root 16 Apr 11 22:41 net_prio -> net_cls,net_prio
drwxr-xr-x. 3 root root 60 Apr 11 23:36 net_prio,net_cls
drwxr-xr-x. 4 root root  0 Apr 11 22:41 perf_event
drwxr-xr-x. 4 root root  0 Apr 11 22:41 pids
drwxr-xr-x. 6 root root  0 Apr 11 22:41 systemd
```
</details>

&nbsp;

Working with @superseb on Slack I learned that this caused by the same issue that was reported for Docker 1.12.6 and K8s 1.10.1: https://github.com/rancher/rancher/issues/12587

With his guidance I was able to manually edit the `/usr/bin/entry.sh` in the kubelet container with changes identical to [this fix](https://github.com/rancher/kubernetes-package/commit/6db52cdbccbc71f3a62afcbeda69c26a7bf44c23) that was applied to produce the `rancher/k8s:v1.10.0-rancher1-2` image.  After restarting the `kubelet` container this resolved the issue such that there were no further errors logged by the kubelet container nor `ImageGCFailed` warnings in the `kubectl describe node <node>` output.

A few hours later the `rancher/k8s:v1.9.5-rancher2` image was pushed with [this fix](https://github.com/rancher/kubernetes-package/commit/6db52cdbccbc71f3a62afcbeda69c26a7bf44c23) by @moelsayed , which added the following to the entry.sh script:
```bash
    [ -d /sys/fs/cgroup/cpuacct,cpu ] && rm -rf  /sys/fs/cgroup/cpuacct,cpu
    ln -s /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct,cpu 2>/dev/null || true
```

I reset all of my VMs to a previous snapshot so that they were clean (prior to any RKE run) and ran `rke up --config cluster-B.yml`.  Instead of resulting in a symlink from `/sys/fs/cgroup/cpuacct,cpu` to `/sys/fs/cgroup/cpu,cpuacct` as you'd expect, listing the contents of `/sys/fs/cgroup` reveals that there is instead a `cpuacct,cpu` directory:

<details>
<summary>ls -l /sys/fs/cgroup/</summary>

```bash
drwxr-xr-x. 6 root root  0 Apr 12 00:57 blkio
lrwxrwxrwx. 1 root root 11 Apr 12 00:57 cpu -> cpu,cpuacct
lrwxrwxrwx. 1 root root 11 Apr 12 00:57 cpuacct -> cpu,cpuacct
drwxr-xr-x. 3 root root 60 Apr 12 01:06 cpuacct,cpu
drwxr-xr-x. 6 root root  0 Apr 12 00:57 cpu,cpuacct
drwxr-xr-x. 4 root root  0 Apr 12 00:57 cpuset
drwxr-xr-x. 6 root root  0 Apr 12 00:57 devices
drwxr-xr-x. 4 root root  0 Apr 12 00:57 freezer
drwxr-xr-x. 4 root root  0 Apr 12 00:57 hugetlb
drwxr-xr-x. 6 root root  0 Apr 12 00:57 memory
lrwxrwxrwx. 1 root root 16 Apr 12 00:57 net_cls -> net_cls,net_prio
drwxr-xr-x. 4 root root  0 Apr 12 00:57 net_cls,net_prio
lrwxrwxrwx. 1 root root 16 Apr 12 00:57 net_prio -> net_cls,net_prio
drwxr-xr-x. 3 root root 60 Apr 12 01:06 net_prio,net_cls
drwxr-xr-x. 4 root root  0 Apr 12 00:57 perf_event
drwxr-xr-x. 4 root root  0 Apr 12 00:57 pids
drwxr-xr-x. 6 root root  0 Apr 12 00:57 systemd
```
</details>

&nbsp;

Listing the contents of the `/sys/fs/cgroup/cpuacct,cpu` directory reveals that a `kubepods` directory was created and that data was subsequently written to sub-directories:

```bash
/sys/fs/cgroup/cpuacct,cpu/
└── kubepods
    ├── besteffort
    │   ├── podede00c88-3ded-11e8-9cf4-005056a65aba
    │   └── podf103b3b8-3ded-11e8-9cf4-005056a65aba
    └── burstable
        └── podefb46a45-3ded-11e8-9cf4-005056a65aba

6 directories, 0 files
```

Listing the contents of the `/sys/fs/cgroup/cpu,cpuacct` directory reveals that under the `kubepods` directory exists all of the stats:
```bash
/sys/fs/cgroup/cpu,cpuacct/kubepods/
├── besteffort
│   ├── cgroup.clone_children
│   ├── cgroup.event_control
│   ├── cgroup.procs
│   ├── cpuacct.stat
│   ├── cpuacct.usage
│   ├── cpuacct.usage_percpu
│   ├── cpu.cfs_period_us
│   ├── cpu.cfs_quota_us
│   ├── cpu.rt_period_us
│   ├── cpu.rt_runtime_us
│   ├── cpu.shares
│   ├── cpu.stat
│   ├── notify_on_release
│   └── tasks
├── burstable
│   ├── cgroup.clone_children
│   ├── cgroup.event_control
│   ├── cgroup.procs
│   ├── cpuacct.stat
│   ├── cpuacct.usage
│   ├── cpuacct.usage_percpu
│   ├── cpu.cfs_period_us
│   ├── cpu.cfs_quota_us
│   ├── cpu.rt_period_us
│   ├── cpu.rt_runtime_us
│   ├── cpu.shares
│   ├── cpu.stat
│   ├── notify_on_release
│   ├── podefb46a45-3ded-11e8-9cf4-005056a65aba
│   │   ├── cgroup.clone_children
│   │   ├── cgroup.event_control
│   │   ├── cgroup.procs
│   │   ├── cpuacct.stat
│   │   ├── cpuacct.usage
│   │   ├── cpuacct.usage_percpu
│   │   ├── cpu.cfs_period_us
│   │   ├── cpu.cfs_quota_us
│   │   ├── cpu.rt_period_us
│   │   ├── cpu.rt_runtime_us
│   │   ├── cpu.shares
│   │   ├── cpu.stat
│   │   ├── notify_on_release
│   │   └── tasks
│   └── tasks
├── cgroup.clone_children
├── cgroup.event_control
├── cgroup.procs
├── cpuacct.stat
├── cpuacct.usage
├── cpuacct.usage_percpu
├── cpu.cfs_period_us
├── cpu.cfs_quota_us
├── cpu.rt_period_us
├── cpu.rt_runtime_us
├── cpu.shares
├── cpu.stat
├── notify_on_release
└── tasks
```
