### ISSUE TITLE
Rancher Server Cannot Access Through Load Balancer

### ISSUE THREAD

**Issue by rossedman** [rancher/rke#508]
**RKE version:** v0.1.5

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 4.14.19-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Azure

**cluster.yml file:** 

```
nodes:
  # control plane
  - address: 172.28.2.4
    user: rancher
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube0-ctl0
  - address: 172.28.2.5
    user: rancher
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube0-ctl1
  - address: 172.28.2.6
    user: rancher
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube0-ctl2

  # general compute
  - address: 172.28.2.12
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-gpc1
  - address: 172.28.2.10
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-gpc0
  - address: 172.28.2.9
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-gpc3
  - address: 172.28.2.8
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-gpc2
  - address: 172.28.2.11
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-gpc5
  - address: 172.28.2.7
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-gpc4

  # load balancers
  - address: 172.28.2.13
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-lbe0
  - address: 172.28.2.15
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-lbe1
  - address: 172.28.2.14
    user: rancher
    role: ["worker"]
    hostname_override: am660-kube0-lbe2

authentication:
  sans:
  - <LOAD BALANCER IP>
  - <LOAD BALANCER DNS ENTRY>

services:
  kube-api:
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0

kubernetes_version: v1.8.9-rancher1-2

ssh_key_path: ~/.ssh/nozomi_rsa

network:
  plugin: flannel

ingress:
  provider: none

addons_include:
  - ./rke/addons/helm-crd.yaml

```

**Steps to Reproduce:**

```
> kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Results:**

Cannot contact using Rancher Server provided credentials. Can use generated kube credentials from RKE and can insert Load Balancer DNS entry and it works. However, when importing cluster to Rancher Server the above errors happens. When digging into the `v3` API the `apiEndpoint` is set to `https://10.233.0.1:443` which is find for when in the cluster but doesn't work when distributing credentials.

I'm not sure how the `cattle-system` reverse-proxy (not even sure if thats what it is) layer works. What can I do to provide it the actual apiServer endpoint?

**Comment by HighwayofLife** [comment]
I don't know the *right* answer yet as I don't go through Rancher Server, but looking up the kubeapi arguments, this parameter stood out:

* `--advertise-address ip`
  * The IP address on which to advertise the apiserver to members of the cluster. This address must be reachable by the rest of the cluster. If blank, the `--bind-address` will be used. If `--bind-address` is unspecified, the host's default interface will be used.

This could be represented in `extra_args` like so... however, I don't know if this will solve the problem you're encountering. 

```
services:
  kube-api:
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
      advertise-address: <kube-api-load-balancer-ip>
```
