### ISSUE TITLE
Should be allowed to create a k8s cluster by specifying only image parameter for all the service containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#53]
Should be allowed to create a k8s cluster by specifying only image parameter for all the service containers.

**Comment by sangeethah** [comment]
rke version v0.0.6-dev

Able to create K8s cluster successfully by using only the following parameters in services section of cluster.yml
```
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
```
