### ISSUE TITLE
Kubelet Hyperkube image missing mkfs.xfs

### ISSUE THREAD

**Issue by frankhinek** [rancher/rke#538]
#### **Docker version:**
<details>
<summary>docker version</summary>

```bash
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
</details>
<details>
<summary>docker info</summary>

```bash
Containers: 18
 Running: 10
 Paused: 0
 Stopped: 8
Images: 11
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702 GiB
Name: HIC005233
ID: JONT:5UKZ:YNVQ:4BPH:3D2J:J66E:EAIS:M5EW:UQDK:2GYO:PSGK:R7JC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
</details>

#### **Operating system and kernel:**

<details>
<summary>cat /etc/os-release</summary>

```bash
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
```
</details>

<details>
<summary>uname -r</summary>

```bash
3.10.0-514.el7.x86_64
```
</details>

#### **Type/provider of hosts:**
Virtual machines running on VMware vSphere cluster

#### **cluster.yml file:**
<details>
<summary>cluster.yml</summary>

```yaml
nodes:
- address: 10.224.88.38
  hostname_override: control01
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.86
  hostname_override: control02
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.30
  hostname_override: control03
  role:
  - controlplane
  - etcd
  user: frank

- address: 10.224.88.81
  hostname_override: worker01
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

- address: 10.224.88.85
  hostname_override: worker02
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

- address: 10.224.88.178
  hostname_override: worker03
  role:
  - worker
  user: frank
  labels:
    node-role.rook.io/storage: true
    node-role.rook.io/rgw: true

services:
  etcd:
    image: rancher/coreos-etcd:v3.0.17
  kube-api:
    image: rancher/k8s:v1.9.5-rancher1-1
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.9.5-rancher1-1
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: rancher/k8s:v1.9.5-rancher1-1
  kubelet:
    image: rancher/k8s:v1.9.5-rancher1-1
    cluster_domain: cluster.local
    infra_container_image: rancher/pause-amd64:3.0
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    extra_args: {"feature-gates": "DevicePlugins=true"}  # for k8s 1.8+
  kubeproxy:
    image: rancher/k8s:v1.9.5-rancher1-1

network:
  plugin: canal
authentication:
  strategy: x509
ssh_agent_auth: true
authorization:
  mode: rbac
ignore_docker_version: false
kubernetes_version: v1.9.5-rancher1-1
cluster_name: kube01
ingress:
  provider: none
```
</details>

**Steps to Reproduce:**
1. Build a Kubernetes cluster using RKE
2. Deploy Rook v0.7.1
3. Create a storage pool with an XFS formatted block storage
4. Create a deployment with a PVC that references the new block storageClass

**Results:**

Mounting the persistent volume will fail and the logs from the kubelet are:
```bash
9023028 +0000 UTC m=+102005.944639480 (durationBeforeRetry 2s). Error: "MountVolume.SetUp failed for volume \"pvc-b8ba310f-44d7-11e8-84dc-005056a620ef\" (UniqueName: \"flexvolume-rook.io/rook/b8c592c6-44d7-11e8-8145-005056a65aba-pvc-b8ba310f-44d7-11e8-84dc-005056a620ef\") pod \"wordpress-mysql-646d96544d-g5hk8\" (UID: \"b8c592c6-44d7-11e8-8145-005056a65aba\") : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd0 [xfs] to /var/lib/kubelet/plugins/rook.io/rook/mounts/pvc-b8ba310f-44d7-11e8-84dc-005056a620ef, error executable file not found in $PATH"
```

The root cause is `error executable file not found in $PATH`.  I launched a shell on the kubelet container and confirmed that the `mkfs.xfs` binary is missing:

```bash
# ls /sbin/mkfs*
/sbin/mkfs
/sbin/mkfs.bfs
/sbin/mkfs.cramfs
/sbin/mkfs.ext2
/sbin/mkfs.ext3
/sbin/mkfs.ext4
/sbin/mkfs.ext4dev
/sbin/mkfs.minix
```

If the kubelet image is based on Ubuntu, it would require the `xfsprogs` package (e.g., `apt-get install xfsprogs`).

I would be happy to submit a PR for this but with the recent changes to the RKE repos I'm not sure which Dockerfile requires the additional package.
