### ISSUE TITLE
 Path /var/lib/kubelet is mounted on / but it is not a shared mount

### ISSUE THREAD

**Issue by joesonw** [rancher/rke#541]
**RKE version:**
  v0.1.6-rc2
**Docker version: (`docker version`,`docker info` preferred)**
```
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 * Server:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```
 * Client:
macOS Sierra 10.12.6

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aliyun KVM
**cluster.yml file:**
```
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 172.16.10.178
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: k8s-1
  user: docker
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: "" 
  labels: {}
- address: 172.16.10.179
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: k8s-2
  user: docker
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: "" 
  labels: {}
- address: 172.16.10.180
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: k8s-3
  user: docker 
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: "" 
  labels: {}
services:
  etcd:
    image: rancher/coreos-etcd:v3.1.12
    extra_args: {}
    extra_binds: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
  kube-api:
    image: rancher/hyperkube:v1.10.1
    extra_args:
      admission-control: NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    extra_binds: []
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/hyperkube:v1.10.1
    extra_args: {}
    extra_binds: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: rancher/hyperkube:v1.10.1
    extra_args: {}
    extra_binds: []
  kubelet:
    image: rancher/hyperkube:v1.10.1
    extra_args: {}
    extra_binds: []
    cluster_domain: cluster.local
    infra_container_image: rancher/pause-amd64:3.1
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: rancher/hyperkube:v1.10.1
    extra_args: {}
    extra_binds: []
network:
  plugin: calico
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  canal_node: ""
  canal_cni: ""
  canal_flannel: ""
  wave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
  dashboard: ""
  heapster: ""
  grafana: ""
  influxdb: ""
  tiller: ""
ssh_key_path: /Users/Joesonw/funlearnworld/chinaworld/devops/k8s_cluster_private_key
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
  cloud_config: {}
prefix_path: ""
```
**Steps to Reproduce:**
spin up a few machiens

set them up with following:
```
yum install docker -y

systemctl enable docker && systemctl start docker

cat <<EOF >> /root/.ssh/authorized_keys
ssh-rsa xxxxx
EOF


## BELOW FOR https://github.com/rancher/rke/issues/93#issuecomment-350808467 

cat <<EOF >> /etc/ssh/sshd_config
AllowTcpForwarding yes
PermitTunnel yes
EOF

systemctl restart sshd

sed -i s_MountFlags=slave_MountFlags=shared_g /etc/systemd/system/multi-user.target.wants/docker.service 

systemctl daemon-reload && systemctl restart docker

groupadd docker

useradd -g docker docker

mkdir -p /home/docker/.ssh

chmod 700 /home/docker/.ssh

touch /home/docker/.ssh/authorized_keys

chmod 644 /home/docker/.ssh/authorized_keys

chown docker:docker -R /home/docker/.ssh

cat <<EOF > /home/docker/.ssh/authorized_keys
ssh-rsa xxxxx
EOF

## ABOVE FOR  https://github.com/rancher/rke/issues/93#issuecomment-350808467

yum install -y kubelet
```
rke up
**Results:**
```
Failed to bring up Worker Plane: Failed to start [kubelet] container on host [172.16.10.178]: Error response from daemon: linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount. 
```
