### ISSUE TITLE
kubectl exec fails with "error: unable to upgrade connection: Unauthorized"

### ISSUE THREAD

**Issue by ericlanderson** [rancher/rke#552]
**RKE version:** 
v0.1.6-rc2 and v0.1.6-rc3

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
/etc/os-release:
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

uname -r:
4.14.32-coreos
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```
---
ignore_docker_version: true

kubernetes_version: v1.10.1

nodes:
  - address: 10.10.0.80
    user: core
    role: [controlplane,etcd]
  - address: 10.10.0.81
    user: core
    role: [controlplane,etcd]
  - address: 10.10.0.82
    user: core
    role: [controlplane,etcd]
  - address: 10.10.0.83
    user: core
    role: [worker]
  - address: 10.10.0.84
    user: core
    role: [worker]
  - address: 10.10.0.85
    user: core
    role: [worker]
  - address: 10.10.0.86
    user: core
    role: [worker]
  - address: 10.10.0.87
    user: core
    role: [worker]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
  kube-controller:
  scheduler:
  kubelet:
  kubeproxy:
```
**Steps to Reproduce:**
```
$ kubectl get pods
NAME                                        READY     STATUS    RESTARTS   AGE
wordpress-fpm-7794448b5f-fbbst              1/1       Running   1          15d
wordpress-mysql-7d8c94c9bb-jd8fr            1/1       Running   3          13d
wordpress-nginx-f985ff994-6tw25             1/1       Running   2          15d

$ kubectl exec -it wordpress-nginx-f985ff994-6tw25 -- bash
error: unable to upgrade connection: Unauthorized
```
**Results:**

This used to work for me on this cluster. This cluster has been up for some time and I recently upgraded to K8s 1.8.10 using rke v0.1.6-rc2. After that upgrade, "kubectl exec" stopped working. I have since upgraded to 1.10.1 and still receive the same error. I also reran the upgrade using rke v0.1.6-rc3. To perform the upgrades, I update the "kubernetes_version: " in the cluster config and then just run "rke up". 

I understand this error has something to do with the certificates between the apiserver and the kubelet. Could those client certificates get removed some how during upgrades?
