### ISSUE TITLE
rke for Windows fails to run

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rke#564]
**RKE version:**
v.0.1.6

**Docker version: (`docker version`,`docker info` preferred)**
```sh
docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: linuxkit-00155d34a401
ID: FWIR:EIFZ:EHEP:TF73:VKMA:QHG5:6CV4:DZAP:AX7D:N7O3:T4BR:SKSU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 35
 System Time: 2018-05-02T03:40:14.8544Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 10

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**cluster.yml file:**
```yaml
# default k8s version: v1.8.9-rancher1-1
# default network plugin: flannel
nodes:
  - address: 168.62.60.216
    user: jvb
    role: [worker]
    ssh_key_path: "/home/jvb/.ssh/id_rsa"
  - address: 168.62.60.204
    user: jvb
    role: [controlplane]
    ssh_key_path: "/home/jvb/.ssh/id_rsa"
  - address: 168.62.58.233
    user: jvb
    role: [etcd]
    ssh_key_path: "/home/jvb/.ssh/id_rsa"

ingress:
  provider: nginx
  extra_args:
    enable-ssl-passthrough: ""

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"      # Enable ssl-passthrough to backend.
  spec:
    rules:
    - host: <FQDN>  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 443
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:master
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
cloud_provider:
  name: azure
  cloud_config:
    aadClientId: **********
    aadClientSecret: ********
    location: "eastus"
    resourceGroup: "rancher-group"
    subnetName: "rancher-group-subnet"
    subscriptionId: ********
    vnetName: "rancher-group-network"
    tenantId: *****
```

**Steps to Reproduce:**
1. Rename the rke binary to rke.exe 
2. Unblock the binary
3. Run .\rke.exe

**Results:**
```powershell
C:\Users\jason\Downloads> .\rke.exe
Program 'rke.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
+ .\rke.exe
+ ~~~~~~~~~.
At line:1 char:1
+ .\rke.exe
+ ~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

Oddly this (and the Linux version both run in Ubuntu on Windows, but is not useful as dockerd doesn't work there.)

```sh

jvb@vblaptop:/mnt/c/Users/jason/Downloads$ ./rke.exe
NAME:
   rke - Rancher Kubernetes Engine, Running kubernetes cluster in the cloud

USAGE:
   rke.exe [global options] command [command options] [arguments...]

VERSION:
   v0.1.6

AUTHOR(S):
   Rancher Labs, Inc.

COMMANDS:
     up       Bring the cluster up
     remove   Teardown the cluster and clean cluster nodes
     version  Show cluster Kubernetes version
     config   Setup cluster configuration
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d    Debug logging
   --help, -h     show help
   --version, -v  print the version

jvb@vblaptop:/mnt/c/Users/jason/Downloads$ ./rke_linux-amd64
NAME:
   rke - Rancher Kubernetes Engine, Running kubernetes cluster in the cloud

USAGE:
   rke_linux-amd64 [global options] command [command options] [arguments...]

VERSION:
   v0.1.6

AUTHOR(S):
   Rancher Labs, Inc.

COMMANDS:
     up       Bring the cluster up
     remove   Teardown the cluster and clean cluster nodes
     version  Show cluster Kubernetes version
     config   Setup cluster configuration
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d    Debug logging
   --help, -h     show help
   --version, -v  print the version

jvb@vblaptop:/mnt/c/Users/jason/Downloads$

```
