### ISSUE TITLE
Mark release candidates as GitHub pre-release (non production)

### ISSUE THREAD

**Issue by superseb** [rancher/rke#581]
If we set each release candidate as pre-release in GitHub we:

- Can use `https://github.com/rancher/rke/releases/latest` as link for documentation to point to latest production ready release.
- Marking the release as pre-release makes the user aware of non production use.

**Comment by deniseschannon** [comment]
@cloudnautique is this possible with our drone builds?

**Comment by cloudnautique** [comment]
You can do pre-release. Right now we only publish on tag events for branch master. We would need an alternate event situation to publish pre-releases.

**Comment by superseb** [comment]
We can test:

```
    when:
        event: tag
        status: success
        ref: refs/tags/*rc*
```
