### ISSUE TITLE
Enable addons upgrades

### ISSUE THREAD

**Issue by moelsayed** [rancher/rke#584]
Currently, during upgrade, we only upgrade core components only. We don't upgrade any of the addons.  We need to support that.

**Comment by sangeethah** [comment]
Tested with rke version v0.1.8-rc5

Deployed cluster with following yml:

```
addon_job_timeout: 60
addons: |-
  ---
  apiVersion: v1
  kind: Service
  metadata:
   name: k8test2
   labels:
     k8s-app: k8test2-service
  spec:
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP
     name: http
   selector:
     k8s-app: k8test2-service
  ---
  apiVersion: v1
  kind: ReplicationController
  metadata:
   name: k8testrc2
  spec:
   replicas: 2
   selector:
     k8s-app: k8test2-service
   template:
     metadata:
       labels:
         k8s-app: k8test2-service
     spec:
       terminationGracePeriodSeconds: 60
       containers:
       - name: testcontainer
         image: nginx
         ports:
         - containerPort: 80
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
   name: ingress198
   annotations:
     http.port: "9198"
  spec:
   rules:
   -  http:
       paths:
       - path: /name.html
         backend:
           serviceName: test123
           servicePort: 80
```
Add on service/rc and ingress get created as expected.

But when I change the image name from RC and rerun the ```rke up``` command , I see the image change reflected in the RC. But pods dont get recreated.
