### ISSUE TITLE
Pre-Pull Pause images to be able to use private registries with basic auth

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#588]
Using private registries with basic auth in rke should allow kubelet to use the pause image, one solution is to pre pull the image with docker credentials like we do in kubernetes images. also using ImagePullSecret will be necessary to be added to the templates

https://github.com/rancher/rancher/issues/13339

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/13339

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/13
rke version v0.1.10-rc2

* Created private registry and tagged/pushed system images (`rke config --system-images`)
* Created cluster in Rancher, with edited yaml to include private registry
```
private_registries:
- url: <registry url>
  user: <password>
  password: <password>
  is_default: true
```
* The created cluster comes up successfully and is using images from the private registry
* Deployed workload w/ ingress (nginx:latest) - functions propertly
