### ISSUE TITLE
K8 Cluster created with weave don't have CNI loopback driver

### ISSUE THREAD

**Issue by YoranSys** [rancher/rke#596]
**RKE version:**

`   v0.1.6`

**Docker version: (`docker version`,`docker info` preferred)**

```
Containers: 1741
 Running: 10
 Paused: 0
 Stopped: 1731
Images: 6
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.801 GiB
Name: k8si-1
ID: OCLT:VTKY:MWLA:XF6D:GD72:YHVC:UOXA:G5KP:ZDSZ:YL2R:VVHR:RLCK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
```

Kernel : `4.9.0-6-amd64`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`
Bare-metal`

**cluster.yml file:**

```yaml
---

network:
  plugin: weave


services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
    extra_args:
      cluster-name: "cluster01"

ingress:
  provider: nginx
  node_selector:
    app: ingress
      
nodes:
  - address: 10.55.10.120
    hostname_override: k8si-1
    user: ansibleadm
    role: [controlplane,etcd]
    label:
    - app: ingress

  - address: 10.55.10.121
    hostname_override: k8si-2
    user: ansibleadm
    role: [controlplane,etcd]        
    label:
    - app: ingress

  - address: 10.55.10.122
    hostname_override: k8si-3
    user: ansibleadm    
    role: [controlplane,etcd]
    label:
    - app: ingress

  - address: 10.55.10.123
    hostname_override: k8sc-4
    user: ansibleadm
    role: [worker]
    

  - address: 10.55.10.124
    hostname_override: k8sc-5
    user: ansibleadm
    role: [worker]

```

**Steps to Reproduce:**

1.  Install debian 9
2.  Install docker 17.03 from rancher script : `curl -fsSL https://releases.rancher.com/install-docker/17.03.sh -o get-docker.sh && sudo sh get-docker.sh`
3.  Use weave at CNI driver in cluster.yml and deploy: `rke up --config my_config.yml `

**Results:**

-   The deployment will fail :

```
INFO[0299] [addons] Deploying rke-user-includes-addons  
INFO[0299] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0299] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-user-includes-addons 
INFO[0299] [addons] Executing deploy job..              
ERRO[0325] Failed to get job complete status: <nil>     
FATA[0325] Failed to deploy addon execute job: Failed to get job complete status: <nil> 
```

- After rerun the `rke up` the deployment seem ok but some pod will be unavailable : 

```
$ kubectl --namespace=kube-system get all
NAME                                           READY     STATUS              RESTARTS   AGE
po/kube-dns-7dfdc4897f-p9tzp                   0/3       ContainerCreating   0          49m
po/kube-dns-autoscaler-6c4b786f5-zvjwl         0/1       ContainerCreating   0          49m
po/rke-user-includes-addons-deploy-job-4g879   1/1       Running             0          3s
po/weave-net-2n76g                             2/2       Running             0          49m
po/weave-net-98frz                             2/2       Running             0          49m
po/weave-net-ctn86                             2/2       Running             0          49m
po/weave-net-f4lw4                             2/2       Running             0          49m
po/weave-net-h55ck                             2/2       Running             0          49m
po/weave-net-qpt8h                             2/2       Running             0          49m
po/weave-net-vc6cx                             2/2       Running             0          49m

NAME           CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
svc/kube-dns   10.43.0.10   <none>        53/UDP,53/TCP   49m

NAME                                       DESIRED   SUCCESSFUL   AGE
jobs/rke-ingress-controller-deploy-job     1         1            49m
jobs/rke-kubedns-addon-deploy-job          1         1            49m
jobs/rke-network-plugin-deploy-job         1         1            49m
jobs/rke-user-includes-addons-deploy-job   1         0            49m

NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns              1         1         1            0           49m
deploy/kube-dns-autoscaler   1         1         1            0           49m

NAME                               DESIRED   CURRENT   READY     AGE
rs/kube-dns-7dfdc4897f             1         1         0         49m
rs/kube-dns-autoscaler-6c4b786f5   1         1         0         49m
```

- The result of `kubectl describe` seem explicit : 
```
NetworkPlugin cni failed to set up pod "kube-dns-autoscaler-6c4b786f5-zvjwl_kube-system" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
```

```bash
$  kubectl  --namespace=kube-system describe po/kube-dns-autoscaler-6c4b786f5-zvjwl
Name:		kube-dns-autoscaler-6c4b786f5-zvjwl
Namespace:	kube-system
Node:		k8sc-7/10.0.10.126
Start Time:	Wed, 09 May 2018 16:00:14 +0200
Labels:		k8s-app=kube-dns-autoscaler
		pod-template-hash=270634291
Annotations:	<none>
Status:		Pending
IP:		
Controlled By:	ReplicaSet/kube-dns-autoscaler-6c4b786f5
Containers:
  autoscaler:
    Container ID:	
    Image:		rancher/cluster-proportional-autoscaler-amd64:1.0.0
    Image ID:		
    Port:		<none>
    Command:
      /cluster-proportional-autoscaler
      --namespace=kube-system
      --configmap=kube-dns-autoscaler
      --target=Deployment/kube-dns
      --default-params={"linear":{"coresPerReplica":128,"nodesPerReplica":4,"min":1}}
      --logtostderr=true
      --v=2
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Requests:
      cpu:		20m
      memory:		10Mi
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-autoscaler-token-rgh5m (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  kube-dns-autoscaler-token-rgh5m:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	kube-dns-autoscaler-token-rgh5m
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.kubernetes.io/not-ready:NoExecute for 300s
		node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  51m		50m		6	default-scheduler			Warning		FailedScheduling	0/7 nodes are available: 7 node(s) were not ready.
  50m		50m		1	default-scheduler			Normal		Scheduled		Successfully assigned kube-dns-autoscaler-6c4b786f5-zvjwl to k8sc-7
  50m		50m		1	kubelet, k8sc-7				Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "kube-dns-autoscaler-token-rgh5m" 
  50m		25m		1391	kubelet, k8sc-7				Warning		FailedCreatePodSandBox	Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-autoscaler-6c4b786f5-zvjwl_kube-system" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
  50m		30s		2786	kubelet, k8sc-7				Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created.
```

-On my host I don't have any cni loopback driver: 

```bash
$ ls -alh /opt/loopback/bin /opt/cni/bin
ls: cannot access '/opt/loopback/bin': No such file or directory
/opt/cni/bin:
total 9.8M
drwxr-xr-x 2 root root 4.0K May  9 13:59 .
drwxr-xr-x 3 root root 4.0K May  9 13:59 ..
lrwxrwxrwx 1 root root   18 May  9 13:59 weave-ipam -> weave-plugin-2.1.2
lrwxrwxrwx 1 root root   18 May  9 13:59 weave-net -> weave-plugin-2.1.2
-rwxr-xr-x 1 root root 9.8M May  9 13:59 weave-plugin-2.1.2

```
