### ISSUE TITLE
Example cluster config files are very confusing

### ISSUE THREAD

**Issue by bobdis** [rancher/rke#597]
cluster.yml documentation is extremely poor, or I am looking in the wrong place

The installation guide at https://rancher.com/docs/rancher/v2.x/en/installation/server-installation/ha-server-install says that you should use this RKE template yml:

https://github.com/rancher/rancher/blob/master/rke-templates/3-node-certificate.yml

Which isn't great, because you might decide to terminate ssl at the switch rather than use certs, and there are no examples given in https://github.com/rancher/rancher/tree/master/rke-templates without certs.

So I just _guessed_ which lines need removing, but then I thought, hmm... where is the documentation for all these settings?

Which brought me to this file:
https://github.com/rancher/rke/blob/master/cluster.yml

Which looks completely different to the 3-node-certificate.yml file

For example, compare these 2 example files in:

1. the addons sections

the cluster.yml has an nginx addon but also these includes:

```
addons_include:
    - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-operator.yaml
    - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-cluster.yaml
```

(btw, I think it would be a bad idea to include something in my yml file that could be updated in github by a PR, so this is not a good example to copy from, but I digress...)

The interesting thing is there is no mention of addons for cattle in the cluster.yml, whereas the 3-node-certificate.yml referred to from the rancher 2.x guide has loads:

```
addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
   apiVersion: v1
   kind: Secret
   metadata:
     name: cattle-keys-ingress
    namespace: cattle-system
   type: Opaque
   data:
    tls.crt: <BASE64_CRT>  # ssl cert for ingress. If selfsigned, must be signed by same CA as cattle server
    tls.key: <BASE64_KEY>  # ssl key for ingress. If selfsigned, must be signed by same CA as cattle server
  ---
   apiVersion: v1
   kind: Secret
   metadata:
    name: cattle-keys-server
    namespace: cattle-system
   type: Opaque
   data:
    cert.pem: <BASE64_CRT>    # ssl cert for cattle server.
    key.pem: <BASE64_KEY>     # ssl key for cattle server.
    cacerts.pem: <BASE64_CA>  # CA cert used to sign cattle server cert and key
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host:  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
     tls: 
     - secretName: cattle-keys-ingress
      hosts:
      - <FQDN>      # FQDN to access cattle server

  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:master
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server

```

Thing is, I'm a brand new user - I have no idea if I need all this cattle stuff specified or not, but _I guess_ I do? because its in the version 2.x example cluster.yml. Hmm, but if so, why isn't it in the other example yml file? maybe its Rancher 2.0 specific. If only it was documented somewhere...

2. the services/images sections in the cluster.yml example:

```
services:
  etcd:
    # ...
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
    # add additional arguments to the kubernetes component
    # Note that this WILL OVERRIDE existing defaults
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
      # Increase number of delete workers
      delete-collection-workers: 3
      # Set the level of log output to debug-level
      v: 4
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    # Optionally define additional volume binds to a service
    extra_binds:
      - "/host/dev:/dev"
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
  kubeproxy:

system_images:
  etcd: rancher/etcd:v3.0.17
  kubernetes: rancher/hyperkube:v1.10.1
  alpine: rancher/rke-tools:v0.1.4
  nginx_proxy: rancher/rke-tools:v0.1.4
  cert_downloader: rancher/rke-tools:v0.1.4
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.4
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  flannel: rancher/coreos-flannel:v0.9.1
  flannel_cni: rancher/coreos-flannel-cni:v0.2.0
```

vs 

_nothing at all_ in the 3-node-certificate.yml

vs, a 3rd option, from a "minimal" example from https://rancher.com/an-introduction-to-rke, which again looks different (and doesn't seem minimal if you don't need to specify services):

```
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
```

There's just so little consistency in the examples, and I can't find any proper documentation.

I guess I'll run `rke config` and go from there, but I hate that approach.

*I'd much prefer to start with an very filled out (and mostly commented out) single configuration file with most of the common options and LOTS and LOTS and LOTS of comments about what each section/line does (and what options there are for a given setting) as opposed to having to _guess_. It is _not_ obvious.*

As a new user experience, the config documentation (if you can call it that) is really poor. 

I notice that someone has actually already completed a PR to improve the comments in the config file. 
Unfortunately, it's nowhere near enough.
