### ISSUE TITLE
SELinux relabeling of /var/lib is not allowed: "operation not supported"

### ISSUE THREAD

**Issue by rossedman** [rancher/rke#598]
**RKE version:**

1.7-rc1

**Docker version: (`docker version`,`docker info` preferred)**

1.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**cluster.yml file:**
```
#
# this file was autogenerated, do not edit manually
# template generated from: rke.yaml.j2
#

nodes:
  # control plane
  - address: 172.28.2.6
    user: core
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube0-ctl0
  - address: 172.28.2.5
    user: core
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube0-ctl1
  - address: 172.28.2.7
    user: core
    role: ["controlplane", "etcd"]
    hostname_override: am660-kube0-ctl2

  # general compute
  - address: 172.28.2.16
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-gpc1
  - address: 172.28.2.10
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-gpc0
  - address: 172.28.2.18
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-gpc3
  - address: 172.28.2.14
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-gpc2
  - address: 172.28.2.11
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-gpc5
  - address: 172.28.2.12
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-gpc4

  # load balancers
  - address: 172.28.2.15
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-lbe0
  - address: 172.28.2.17
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-lbe1
  - address: 172.28.2.13
    user: core
    role: ["worker"]
    hostname_override: am660-kube0-lbe2


authentication:
  sans:
  - $IP_ADDRESS

services:
  kube-api:
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
  kube-controller:
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args:
      cadvisor-port: 4194
      read-only-port: 10255

kubernetes_version: v1.9.5

ssh_key_path: ~/.ssh/id_rsa

cluster_name: kubernetes

network:
  plugin: flannel

ingress:
  provider: none

bastion_host:
  address: some.bastion.host.com
  user: core
  port: 22
  ssh_key_path: ~/.ssh/id_rsa
```

**Steps to Reproduce:**

Currently trying to stand up a cluster, and tear down a cluster and am receiving this error with 1.7rc1. Tested with bastion configuration and without. Also appears that `kubernetes_version` is no longer honored. RKE is trying to deploy 1.10 even though I overrode it.

**Results:**
