### ISSUE TITLE
Add S3 for etcd backup/restore

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#616]
Currently etcd backup/restore uses local disk for backup storage, it will be a nice enhancement to etcd backup to save and restore backups from Amazon S3 buckets to both the regular backups and onetime backups, for example:
cluster.yml
```
services:
  etcd:
    backup: true
    s3: true
    s3_bucket_name: "etcd-backup"
```
and for one time backup:
```
./rke etcd backup --name snapshot --config cluster.yml --s3 --s3-bucket-name "etcd-backup"
```

**Comment by curx** [comment]
or on others, like minio ?

**Comment by techcto** [comment]
I +1 this to s3

It would also be nice to have a feature to control etcd backup size. On my test server, it is growing rapidly. Are there any better ways to control it's size?  

I see this page:  https://coreos.com/etcd/docs/latest/op-guide/maintenance.html

**Comment by iwilltry42** [comment]
Hi there,
I created two PRs in https://github.com/rancher/rke/pull/968 and https://github.com/rancher/rke-tools/pull/27 to solve this.
This is my first contribution to a larger project, so I hope I didn't do too much wrong... happy about reviews :)

**Comment by mitchellmaler** [comment]
Will this support other S3 providers and not just AWS? We have a local minio cluster that runs with path based buckets. Would be nice to be able to specify the URL and bucket (path) with auth token, etc.

**Comment by guangbochen** [comment]
Addressed in https://github.com/rancher/rke/pull/1036.

**Comment by soumyalj** [comment]
Tested with rke version v0.2.0-rc5.  Backup restore using S3 is functional
1. Create a cluster using RKE CLI specifying S3 configuration in the cluster.yml file
```
auth:
  strategy: x509
nodes:
  - address: a.b.cd
    user: root
    role: [etcd,controlplane,worker]
  - address: e.f.g.h
    user: root
    role: [etcd,controlplane,worker]
  - address: i.j.k.l
    user: root
    role: [etcd,controlplane,worker]
services:
  etcd:
    snapshot: true
    backup_config:
      s3BackupConfig:
        access_key: "efgh"
        secret_key: "abcd"
        bucket_name: "testbucket2"
        endpoint: s3.amazonaws.com
```

2. Create few pods.
3. Create a one time backup using the command: 
```
./rke_darwin-amd64 etcd snapshot-save --name testsnapshot1 --s3 --bucket-name testbucket2 --access-key abcde --secret-key fgjuk --s3-endpoint s3.amazonaws.com --config testbkprestorenew.yml

``` 
Snapshot "testsnapshot1" was created in S3

4. Restore also succeeded on a healthy and broken cluster. Command used for restore below:
```
./rke_darwin-amd64 etcd snapshot-restore --name testsnapshot1 --s3 --bucket-name testbucket2 --access-key abcde --secret-key fgjuk --s3-endpoint s3.amazonaws.com --config testbkprestorenew.yml


```
