### ISSUE TITLE
rke snapshot-restore brings 502 Bad Gateway

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rke#637]
Hi,
here is my steps:
1. installing rke with HA version: 1 nginx, 3 etcd, 3 controplane, 3 worker (`./rke_linux-amd64 up --config rancher-cluster.yml` (https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/)
2. creating deployment with a few replicas(for test purposes)
3. creating etcd backup `./rke_linux-amd64 etcd snapshot-save --name snapshot --config rancher-cluster.yml`
4. removing my cluster in order to test the restore of etcd `./rke_linux-amd64 remove --config rancher-cluster.yml` and then removing all containers and images from hosts separately: 
```./cleanup.sh ; docker stop `docker ps |awk '{print $1}' |paste -sd' '` ; docker rm `docker ps -a |awk '{print $1}' |paste -sd' '` ; docker rmi `docker images |awk '{print $3}' |paste -sd' '` ; service docker stop && rm -rf /var/lib/docker/ ; umount -l -f /var/lib/rancher/volumes/ ; umount -l -f /var/lib/rancher ; rm -rf /var/lib/rancher ; umount -l -f /var/lib/kubelet ; service docker start && docker ps```
I've downloaded the./cleanup.sh script from @superseb repo (https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d)
4. installing the rke with the same way/config as I've described in the 1st step
5. coping the saved snapshot to all etcd hosts in the `/opt/rke/etcd-snapshots/` directory
6. restoring from snapshot `./rke_linux-amd64 etcd snapshot-restore --name snapshot --config rancher-cluster.yml `
7. get 502 Bad Gateway :(
also the pods aren't recreated after delete

```
kubectl get po --all-namespaces --show-all
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
cattle-system   cattle-84f9cd8589-j7nl2                   1/1       Running     0          4h
cattle-system   cattle-cluster-agent-7657c8c794-rw9k4     1/1       Running     0          4h
cattle-system   cattle-node-agent-2mvhd                   1/1       Running     0          4h
cattle-system   cattle-node-agent-bp872                   1/1       Running     0          4h
cattle-system   cattle-node-agent-flvkt                   1/1       Running     0          4h
default         ubuntutest-94846979c-85g4b                1/1       Running     0          4h
default         ubuntutest-94846979c-bgbp9                1/1       Running     0          4h
default         ubuntutest-94846979c-hsr58                1/1       Running     0          4h
default         ubuntutest-94846979c-vshb5                1/1       Running     0          4h
ingress-nginx   default-http-backend-564b9b6c5b-7qbtm     1/1       Running     0          4h
ingress-nginx   nginx-ingress-controller-cm7ht            1/1       Running     0          4h
ingress-nginx   nginx-ingress-controller-cwhg8            1/1       Running     0          4h
ingress-nginx   nginx-ingress-controller-g5877            1/1       Running     0          4h
kube-system     canal-mcl6t                               3/3       Running     1          4h
kube-system     canal-nknjq                               3/3       Running     0          4h
kube-system     canal-ntl9w                               3/3       Running     0          4h
kube-system     kube-dns-5ccb66df65-j6q5f                 3/3       Running     0          4h
kube-system     kube-dns-autoscaler-6c4b786f5-87l85       1/1       Running     0          4h
kube-system     rke-ingress-controller-deploy-job-ctjgb   0/1       Completed   0          4h
kube-system     rke-kubedns-addon-deploy-job-f85zk        0/1       Completed   0          4h
kube-system     rke-network-plugin-deploy-job-6sjqx       0/1       Completed   0          4h
kube-system     rke-user-addon-deploy-job-v5xpk           0/1       Completed   0          4h
```

**Comment by Lssikkes** [comment]
I'm seeing the same thing, using rke v0.1.7.
Cluster nginx will not show "default backend - 404" on a wrong domain, but 502 Bad Gateway after a snapshot restore.

**Comment by harutyundermenjyan** [comment]
seem the issue doesn't resolved,
now the web interface doesn't reachable at all after etcd restore.

**Comment by harutyundermenjyan** [comment]
@galal-hussein any update?

**Comment by harutyundermenjyan** [comment]
```
kubectl get po --all-namespaces
NAMESPACE       NAME                                      READY     STATUS             RESTARTS   AGE
cattle-system   cattle-84f9cd8589-wmrzk                   1/1       Running            0          19h
cattle-system   cattle-cluster-agent-556bdc4698-z55zp     1/1       Running            3          19h
cattle-system   cattle-node-agent-2lhnq                   0/1       Error              6          19h
cattle-system   cattle-node-agent-c9g62                   0/1       CrashLoopBackOff   6          19h
cattle-system   cattle-node-agent-v65j2                   0/1       CrashLoopBackOff   6          19h
default         ubuntutest-94846979c-fndnm                1/1       Running            0          5m
default         ubuntutest-94846979c-s4wb4                1/1       Running            0          19h
default         ubuntutest-94846979c-v28cj                1/1       Running            0          19h
ingress-nginx   default-http-backend-564b9b6c5b-kmv8z     1/1       Running            1          19h
ingress-nginx   nginx-ingress-controller-fp7zt            0/1       CrashLoopBackOff   6          19h
ingress-nginx   nginx-ingress-controller-pj6fn            0/1       CrashLoopBackOff   6          19h
ingress-nginx   nginx-ingress-controller-vhpj6            0/1       CrashLoopBackOff   6          19h
kube-system     canal-dhspz                               1/3       CrashLoopBackOff   8          2m
kube-system     canal-k8rj8                               1/3       CrashLoopBackOff   8          2m
kube-system     canal-rslpt                               1/3       CrashLoopBackOff   8          2m
kube-system     kube-dns-5ccb66df65-gsskw                 2/3       Running            8          19h
kube-system     kube-dns-autoscaler-6c4b786f5-mck8q       1/1       Running            0          19h
kube-system     rke-ingress-controller-deploy-job-bhfnt   0/1       Completed          0          19h
kube-system     rke-kubedns-addon-deploy-job-jp4mt        0/1       Completed          0          19h
kube-system     rke-network-plugin-deploy-job-gjbhp       0/1       Completed          0          19h
kube-system     rke-user-addon-deploy-job-bp4sn           0/1       Completed          0          19h
```

**Comment by harutyundermenjyan** [comment]
now it exit with the following error at the restore time:
`FATA[0022] Failed to run certificate bundle extract, exit status is: 1`

**Comment by shyam** [comment]
+1

I'm also facing the same issue. 

**RKE version:**
````
rke version v0.1.7
````
**Docker version: (`docker version`,`docker info` preferred)**

````
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
````
````
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.5 GiB
Name: test-k8s-etcd03.testserver.de
ID: WUPV:FGNH:XKTY:SFS2:YY54:KXNV:D2DR:ATCO:NBTP:56A5:SLLP:LXCF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
````
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

````
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
````
`4.4.0-116-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

````
#  RKE environment 01

# x.y.205.235  test-k8s-master01.testserver.de test-k8s-master01
# x.y.205.243  test-k8s-master02.testserver.de test-k8s-master02
# x.y.205.135  test-k8s-master03.testserver.de test-k8s-master03
# x.y.205.50   test-k8s-etcd03.testserver.de test-k8s-etcd03
# x.y.205.80   test-k8s-etcd01.testserver.de test-k8s-etcd01
# x.y.205.75   test-k8s-worker03.testserver.de test-k8s-worker03
# x.y.205.61   test-k8s-worker02.testserver.de test-k8s-worker02

nodes:
- address: x.y.205.235
  port: "22"
  internal_address: x.y.205.235
  role:
  - controlplane
  - etcd
  hostname_override: test-k8s-master01.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    app: ingress
- address: x.y.205.243
  port: "22"
  internal_address: x.y.205.243
  role:
  - controlplane
  - etcd
  hostname_override: test-k8s-master02.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    app: ingress
- address: x.y.205.135
  port: "22"
  internal_address: x.y.205.135
  role:
  - controlplane
  - etcd
  hostname_override: test-k8s-master03.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    app: ingress
- address: x.y.205.50
  port: "22"
  internal_address: x.y.205.50
  role:
  - etcd
  hostname_override: test-k8s-etcd03.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
- address: x.y.205.80
  port: "22"
  internal_address: x.y.205.80
  role:
  - etcd
  hostname_override: test-k8s-etcd01.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
- address: x.y.205.75
  port: "22"
  internal_address: x.y.205.75
  role:
  - worker
  hostname_override: test-k8s-worker03.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
- address: x.y.205.61
  port: "22"
  internal_address: x.y.205.61
  role:
  - worker
  hostname_override: test-k8s-worker02.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
services:
  etcd:
    image: rancher/coreos-etcd:v3.1.12
    extra_args: {}
    extra_binds: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
    service_cluster_ip_range: 10.143.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
    cluster_cidr: 10.142.0.0/16
    service_cluster_ip_range: 10.143.0.0/16
  scheduler:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
  kubelet:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {"cgroup-driver":"systemd","fail-swap-on":"false"}
    extra_binds: []
    cluster_domain: testserver.de
    infra_container_image: rancher/pause-amd64:3.1
    cluster_dns_server: 10.143.0.10
    fail_swap_on: false
  kubeproxy:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
network:
  plugin: flannel
  options: {}
authentication:
  strategy: x509
  options: {}
  sans:
    - "test-rke01-master-lb01.testserver.de"
    - "test-rke01-master-lb02.testserver.de"
    - "test-rke01-master-lb.testserver.de"
addons: ""
addons_include: []
ssh_key_path: "~/.ssh/nonprod"
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: "nginx"
  node_selector:
    app: ingress
cluster_name: "test-rke01"
cloud_provider:
  name: ""
  cloud_config: {}
prefix_path: ""
addon_job_timeout: 30
````
**Steps to Reproduce:**

1. Run `rke up` to create the cluster.
2. Create a deployment which deploys some pods across nodes and exposes it as service and ingress.
3. Visit the host set up on ingress ( entries in /etc/hosts may be necessary ). It works.
4. Perform Etcd snapshot by running `rke etcd snapshot-save`
5. Backup `kube_config_cluster.yml` as `kube_config_cluster.yml.backup` 
6. Remove the cluster and cleanup using the gist from @superseb repo ( https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d ) and reboot.
7. Recreate the cluster using `rke up` command.
8. Rename the snapshots as "snapshot" `under /opt/rke/etcd-snapshots` on all nodes under etcd plane.
9. Restore Etcd Snapshot by running `rke etcd snapshot-restore --name snapshot`
10. Restore the earlier `kube_config_cluster.yml` from the `kube_config_cluster.yml.backup`
11. Run `rke up` again.
12. Verify if pods, ingress are running.
13. Visiting the ingress will result in 502 Bad Gateway.
