### ISSUE TITLE
NodePort Not Available Across the Nodes

### ISSUE THREAD

**Issue by eliu** [rancher/rke#640]
We created 3 VMs using vagrant virualbox vm (centos/7) and launch `rke up` to create a Kubernetes cluster. 
```
$ kubectl get node
NAME              STATUS    ROLES               AGE       VERSION
192.168.124.101   Ready     controlplane,etcd   2d        v1.10.1
192.168.124.102   Ready     worker              2d        v1.10.1
192.168.124.103   Ready     worker              2d        v1.10.1
```
All resource status seems fine except the following issues:
1. The NodePort service we created are not available for all kubernetes nodes.
2. All containers managed on worker node do not have network connectivity ( e.g ping www.baidu.com won't work)

application service we deployed:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 1
  selector: 
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: eliu/tomcat:8.5-hap
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: tomcat
```
Try to visit from cotrolplane: http://192.168.124.101:30080 does not work. 

**RKE version:**
`rke version v0.1.6`

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-58.git87f2fab.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      87f2fab/1.13.1
 Built:           Fri May 11 14:30:13 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-58.git87f2fab.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      87f2fab/1.13.1
 Built:           Fri May 11 14:30:13 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
#
# cat /etc/os-release
#
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#
# uname -r
#
3.10.0-693.21.1.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox (Vagrant Box VM)

**cluster.yml file:**
```
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 192.168.124.101
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: vagrant
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /Users/eliuhy/my/vagrant/workspace/rke-lab/.vagrant/machines/node-1/virtualbox/private_key
  labels: {}
- address: 192.168.124.102
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: vagrant
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /Users/eliuhy/my/vagrant/workspace/rke-lab/.vagrant/machines/node-2/virtualbox/private_key
  labels: {}
- address: 192.168.124.103
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: vagrant
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /Users/eliuhy/my/vagrant/workspace/rke-lab/.vagrant/machines/node-3/virtualbox/private_key
  labels: {}
services:
  etcd:
    image: rancher/coreos-etcd:v3.1.12
    extra_args: {}
    extra_binds: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
  kube-api:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
  kubelet:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
    cluster_domain: cluster.local
    infra_container_image: rancher/pause-amd64:3.1
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
network:
  plugin: flannel
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  canal_node: ""
  canal_cni: ""
  canal_flannel: ""
  wave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
  cloud_config: {}
prefix_path: ""
```

**Steps to Reproduce:**
1. create k8s resource using the follwing yaml file:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 1
  selector: 
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: eliu/tomcat:8.5-hap
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: tomcat
```

2. Visit service from host http://192.167.124.101:30001

3. kubectl exec -it <pod-name> ping www.baidu.com

**Results:**
Service not available through controlplane node
Network connectivity not available inside the container on worker nodes.

Please help.

**Comment by eliu** [comment]
I've got the resolution. The default eth0 network interface is NAT type for Vagrant environment. The flannel network plugin will use it by default. Therefore we need explicitly specify eth1 network, the type of which is host-only, in order to make flannel work properly.

Here is the configuration in my cluster.yaml

```yaml
network:
  plugin: flannel
  options: {
    flannel_iface: eth1
  }
```
