### ISSUE TITLE
Cannot set cloud-provider=external on kubelet

### ISSUE THREAD

**Issue by jaxxstorm** [rancher/rke#660]
**RKE version:**

v0.1.7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

coreos-stable

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

DigitalOcean

**cluster.yml file:**

```
ignore_docker_version: true
nodes:
services:
  kube-api:
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
  kube-controller:
  scheduler:
  kubelet:
    cluster_domain: briggs.local
    cloud_provider: external
```

I am trying to add the external cloud provider for DigitalOcean. As per the instructions, the kubelet is the only component that needs to have a cloud provider set https://github.com/digitalocean/digitalocean-cloud-controller-manager#--cloud-providerexternal

I set the cloud provider in my rke config as above, but the configuration option never gets set on the kubelet container.

**Comment by superseb** [comment]
`cloud-provider` is a top level configuration option. If you want to add arguments to services, you can use `extra_args`:

```
services:
  kubelet:
    extra_args:
      cloud-provider: "external"
```

**Comment by jaxxstorm** [comment]
Again, this isn't working. I tried it like so:
```
services:
  kube-api:
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
  kube-controller:
  scheduler:
  kubelet:
    extra_args:
      cloud_provider: "external"
```

And docker inspect looks like this:

```
core@rancher-1 ~ $ docker inspect 5128a458a340 | jq .[].Config.Entrypoint
[
  "/opt/rke/entrypoint.sh",
  "kubelet",
  "--cadvisor-port=0",
  "--enforce-node-allocatable=",
  "--hostname-override=rancher-1.briggs.io",
  "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
  "--feature-gates=MountPropagation=false",
  "--anonymous-auth=false",
  "--volume-plugin-dir=/var/lib/kubelet/volumeplugins",
  "--kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml",
  "--address=0.0.0.0",
  "--network-plugin=cni",
  "--cni-conf-dir=/etc/cni/net.d",
  "--resolv-conf=/etc/resolv.conf",
  "--allow-privileged=true",
  "--root-dir=/opt/rke/var/lib/kubelet",
  "--cluster-domain=cluster.local",
  "--pod-infra-container-image=rancher/pause-amd64:3.1",
  "--cluster-dns=10.43.0.10",
  "--cloud_provider=external",
  "--client-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
  "--fail-swap-on=false",
  "--v=2",
  "--read-only-port=0",
  "--cgroups-per-qos=True",
  "--cni-bin-dir=/opt/cni/bin",
  "--cloud-provider="
]
```
