### ISSUE TITLE
Unable to provision cluster with unsupported docker version

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rke#679]
**RKE version:**
v0.1.8-rc1

**Docker version: (`docker version`,`docker info` preferred)**
17.12.0 ce

Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: austinRke1
ID: QL43:WAZD:4CZC:2BG5:RUXI:PZKM:C5AV:PB3U:V5PU:A54B:VRYQ:ZKDI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**cluster.yml file:**
```
ignore_docker_version: true
network:
  plugin: weave
nodes:
  - address: [IP Adress]
    user: root
    ssh_key_path: /Users/[username]/.ssh/id_rsa
    role: [controlplane,etcd,worker]

  - address: [IP Adress]
    user: root
    ssh_key_path: /Users/[username]/.ssh/id_rsa
    role: [worker]

  - address: [IP Adress]
    user: root
    ssh_key_path: /Users/[username]/.ssh/id_rsa
    role: [worker]
```

**Steps to Reproduce:**
RKE up cluster with provided yml file on a DO nodes with one click app Docker/Ubuntu

**Results:**

Unable to successfully provision cluster. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6e436]

goroutine 243 [running]:
github.com/rancher/rke/services.runHealthcheck(0x29a5f60, 0xc420012480, 0xc4204b6680, 0x20dd273, 0xa, 0x0, 0xc42062c1e0, 0x1e, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/services/healthcheck.go:72 +0x6a6
github.com/rancher/rke/services.runKubeproxy(0x29a5f60, 0xc420012480, 0xc4204b6680, 0x0, 0xc4203fa600, 0x20dd273, 0xa, 0xc4201f4f80, 0x5, 0x8, ...)
	/go/src/github.com/rancher/rke/services/kubeproxy.go:16 +0x422
github.com/rancher/rke/services.doDeployWorkerPlane(0x29a5f60, 0xc420012480, 0xc4204b6680, 0x0, 0xc4203fa600, 0xc4202bfb60, 0xc4203171d0, 0x20f06f7, 0x18, 0xc42058cf88, ...)
	/go/src/github.com/rancher/rke/services/workerplane.go:96 +0x2fe
github.com/rancher/rke/services.RunWorkerPlane.func1(0x8, 0x216a5e0)
	/go/src/github.com/rancher/rke/services/workerplane.go:42 +0x76
github.com/rancher/rke/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420315300, 0xc4206e6f50)
	/go/src/github.com/rancher/rke/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rke/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/rancher/rke/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x66
```
