### ISSUE TITLE
Overide server URL in generated kube_config_cluster.yml

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#705]
**RKE version:**

0.17

**Use case**

I have an external load balancer that setup a virtual IP for all my Kubernetes API endpoints.

When it configures kube_config_cluster.yml, RKE setup the cluster server URL with the first (or the last?) node with the "controlplane" role.

Having an option in cluster.yml config with the URL i want to use would be great.

Thanks

**Comment by galal-hussein** [comment]
@sebastien-prudhomme RKE currently can't configure kube config with the ip of the load balancer, however rke can configure the certificates SAN to include the load balancer dns:
```
authentication:
  strategy: x509
  sans:
  - "10.18.160.10"
  - "my-loadbalancer-1234567890.us-west-2.elb.amazonaws.com"
```

**Comment by sebastien-prudhomme** [comment]
I yet use the "sans" feature. But each time i do an "rke up", i need to manually correct the kube_config_cluster.yml.

Just need an option as the "cluster_name" one. Wish i know Go to implement it :-)

**Comment by lmickh** [comment]
Using the SANs option to put the ELB name into the certs works, but if you don't have direct public access to the API server(s) the outputted kubeconfig "doesn't work".  The user has to edit the kubeconfig file with the externally accessible server address.

I get that RKE doesn't configure the kube config.  It is basically pulling it from the servers after the kube setup process generated.  It might make sense to give the user an edited version that "just works".  I would imagine the easy target would be to find and replace the server address with the `external-hostname` arg in the config when it exists.  When paired with the `sans` option already mentioned, it would give the user a working config file.

```
services:
  kube-api:
    extra_args:  
      external-hostname: my-api-elb.example.com
authentication:
  strategy: x509
  sans:
  - "10.10.10.10"
  - "my-api-elb.example.com"
```

Would result in a kubeconfig file with:
```
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    server: "https://my-api-elb.example.com"
    certificate-authority-data: <snip>
  name: "rke-example"
```

The `external-hostname` option for the api-server is exactly for this use case.  It makes sense to just borrow that value for the kubeconfig file the user can use externally from the cluster in addition to the internal kubeconfig file resulting from the cluster setup.
