### ISSUE TITLE
Allow some more calico configuration

### ISSUE THREAD

**Issue by clkao** [rancher/rke#711]
Right now the calico network config in `cluster.yml` supports only `calico_cloud_provider`.  Is it within rke's scope to support the following opitons:

1. ip detection vs deriving from node ip known to the cluster - this can prevent calico accidentally uses public ip if a node has two interfaces:

```
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: IP
          value: $(NODE_IP)/32

```

2. node ip subnet (where the above `/32` becomes configurable) and ipipmode=cross-subnet
3. install the policy controller

**Comment by myselfghost** [comment]
provide a way to turn off calico's IPINIP

**Comment by m-ferrero** [comment]
Hetzner Cloud provides private networks for virtual machines.
We have deployed a cluster with a public and a private network and would like to force calico using the private one.

Right now IP_AUTODETECTION_METHOD cannot be configured and takes the default value of first-found.

**Comment by cbergmann** [comment]
have you found a way to specify the correct interface or another workaround?

**Comment by craig755** [comment]
@cbergmann and @m-ferrero I not sure if this would help you but I came across the same issue today when trying to setup another interface on my rke host. I managed to get the calico-node to work by applying this
`kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=eth0`

**Comment by antoinetran** [comment]
Hi, we have the same issue. It would be great to not have a random issue because of autodetect.

**Comment by iosifnicolae2** [comment]
Any news here?

**Comment by tlvenn** [comment]
Same issue as @craig755 , as soon as the host has multiple interfaces, there is a big chance that the calico-node will simply not work.

**Comment by tlvenn** [comment]
@Oats87 any chance this issue could be prioritized somewhat ?

**Comment by bashofmann** [comment]
As a workaround I was able to configure the IP_AUTODETECTION_METHOD environment variable by adding this ConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-services-endpoint
  namespace: kube-system
data:
  IP_AUTODETECTION_METHOD: interface=eth0
```

While `kubernetes-services-endpoint` is meant for other purposes, its content is also used as environment variables in the calico-node pods.
