### ISSUE TITLE
Allow using an existing CA

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#728]
Hi, i'd like to do a pull request so that instead of generating a new internal CA, RKE can use a configured CA.

For these feature, i only need to add 2 new config parameters: cluster_ca_cert and cluster_ca_key

Just want to make sure that this feature is usefull for other people.

Thanks

**Comment by HighwayofLife** [comment]
Yes, it would be useful for others. 👍

**Comment by qwylz** [comment]
@sebastien-prudhomme I've just recently begun working on some additional pki enhancements for rke, as well.  I've been working on a new structure in the config that looks something like this so far:

```
pki:
  ca:
    valid_days:
  certs:
    valid_days:
```

The two `valid_days` keys control how many days the internally generated CA certificate and all other certificates (respectively) are valid for.

It would be nice if both your and my work could co-exist.  A structure like the following might work:

```
pki:
  ca:
    cert:
    key:
    valid_days:
  certs:
    valid_days:
```

Where `cert` and `key` are what you propose as `cluster_ca_cert` and `cluster_ca_key`.
