### ISSUE TITLE
rke etcd restore fails on new nodes when the services section with etcd snapshot related field exists in yml file

### ISSUE THREAD

**Issue by soumyalj** [rancher/rke#735]
**RKE version:** rke version v0.1.8-rc7

**Steps to Reproduce:**
1. Create a cluster with the yml file below. Note that services section exists with etcd snapshot related fields
```
auth:
  strategy: x509
nodes:
  - address: abc
    role: [controlplane, etcd]
  #  hostname_override: ""
  - address: def
    role: [worker]
  services:
  etcd:
    snapshot: true
    creation: 5m0s
    retention: 24h

```
2- create few pods
3- take a snapshot
4. Create a new node
5- Add the snapshot and certificate bundle to a new node
6. shut down etcd1
7. Run Restore with the new node in the config file[Remove N1]

Restore fails as below:
```
INFO[0008] [etcd] Successfully started [etcd] container on host [abc] 
INFO[0008] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [abc] 
INFO[0010] [certificates] Successfully started [rke-bundle-cert] container on host [abc] 
FATA[0011] [etcd] Failed to bring up Etcd Plane: Failed to run certificate bundle compress, exit status is: 1 

```
Error from rancher/rke-tools container:

```
root@soumyarkefintest4:/opt/rke/etcd-snapshots# sudo docker logs -f 28b70de07650
tar: /etc/kubernetes/.tmp: No such file or directory
tar: error exit delayed from previous errors
root@soumyarkefintest4:/opt/rke/etcd-snapshots# 

```
