### ISSUE TITLE
kube-apiserver extra_args not override the arguments

### ISSUE THREAD

**Issue by pdhung** [rancher/rke#750]
**RKE version:**
rke version v0.1.7

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7 3.10.0-862.3.2.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM
**cluster.yml file:**
```
kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false  
    service_node_port_range: 30000-32767
    extra_args:      
      v: 4
      etcd-certfile: /etc/kubernetes/ssl/etcd-apiserver.crt
      etcd-keyfile: /etc/kubernetes/ssl/etcd-apiserver.key
      etcd-cafile: /etc/kubernetes/ssl/ca-etcd.crt
```

**Steps to Reproduce:**
Deploy custom etcd cert & key file, and run ./rke up

**Expected Results:**
--etcd-certfile, --etcd-keyfile, --etcd-cafile only show up 1 time in kube-apiserver argument list

**Results:**
Duplicated arguments (--etcd-certfile, --etcd-keyfile, --etcd-cafile) passed to kube-apiserver

```
kube-apiserver ...
**--etcd-certfile=/etc/kubernetes/ssl/etcd-apiserver.crt --etcd-keyfile=/etc/kubernetes/ssl/etcd-apiserver.key --etcd-cafile=/etc/kubernetes/ssl/ca-etcd.crt** 
...
--insecure-port=0 --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem 
**--etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem**
...
```

**Comment by galal-hussein** [comment]
tested with v0.1.8-rc12

I used the following cluster.yml file:
```
services:
  kube-api:
    extra_args:
      etcd-certfile: /foobar
```
After running rke up and inspecting the etcd container, i can see that rke respects the extra args for etcd parameters:
```
"Entrypoint": [
                "/opt/rke/entrypoint.sh",
                "kube-apiserver",
.....
                "--etcd-certfile=/foobar",
.....
```
