### ISSUE TITLE
ssh: rejected: administratively prohibited

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rke#752]
**RKE version:**
0.1.7

**Docker version: (`docker version`,`docker info` preferred)**
1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.5.1805 supported OS, 3.10.0-862.3.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2 autoscaled CloudFormation stack, 3 x c5.large instances

**cluster.yml file:**
```
nodes:
  - address: 10.9.74.200
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/rancher/.ssh/id_rsa
  - address: 10.9.4.231
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/rancher/.ssh/id_rsa
  - address: 10.9.50.182
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/rancher/.ssh/id_rsa

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: |
      [base64 data here]
    tls.key: |
      [base64 data here]
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
      nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
      nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
  spec:
    rules:
    - host: rancher.test.domain.com
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - rancher.test.domain.com
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
```

**Steps to Reproduce:**
SSH keys and configuration files are identical on all 3 instances, I can login from an instance to another with user `rancher`:
```
# getenforce
Enforcing
# ausearch -i -ts recent
<no matches>

# sshd -T | egrep 'allowtcpforwarding|permittunnel'
allowtcpforwarding yes
permittunnel yes

# id rancher
uid=994(rancher) gid=990(rancher) groups=990(rancher)
# ls -lah /home/rancher/.ssh/
total 8.0K
drwx------. 2 rancher rancher   43 Jul  3 22:01 .
drwx------. 3 rancher rancher   95 Jul  4 00:27 ..
-rw-r--r--. 1 rancher rancher  429 Jul  3 22:01 authorized_keys
-rw-------. 1 rancher rancher 1.9K Jul  3 22:01 id_rsa

# rke up --config cluster.yml
```

**Results:**
```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [10.9.74.200]
WARN[0000] Failed to set up SSH tunneling for host [10.9.74.200]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)
INFO[0000] [dialer] Setup tunnel for host [10.9.4.231]
WARN[0001] Failed to set up SSH tunneling for host [10.9.4.231]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)
INFO[0001] [dialer] Setup tunnel for host [10.9.50.182]
WARN[0002] Failed to set up SSH tunneling for host [10.9.50.182]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)
WARN[0002] Removing host [10.9.74.200] from node lists
WARN[0002] Removing host [10.9.4.231] from node lists
WARN[0002] Removing host [10.9.50.182] from node lists
FATA[0002] Cluster must have at least one etcd plane host
```
