### ISSUE TITLE
struggling setup k8s cluster with rke

### ISSUE THREAD

**Issue by willmao** [rancher/rke#756]
**RKE version: v0.1.7

**Docker version: 
```
Containers: 140
 Running: 10
 Paused: 0
 Stopped: 130
Images: 18
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 388
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-117-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.796 GiB
Name: yit-dev-k8s-master-01
ID: XQVY:EDIM:OS6C:G5ZD:K6A6:CL6F:HN5E:D5SD:YN33:M3YA:FCEP:GAPR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: 

```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: AliCloud ecs

**cluster.yml file:
```
network:
  plugin: flannel
  # options:
  #   flannel_iface: eth0

nodes:
  - address: 10.81.182.28
    user: yitops
    role:
      - controlplane
      - etcd
  - address: 10.28.252.77
    user: yitops
    role:
      # - controlplane
      # - etcd
      - worker
  - address: 10.28.254.155
    user: yitops
    role:
      - worker

services:
  kube-api:
    # IP range for any services created on Kubernetes
    # This must match the service_cluster_ip_range in kube-controller
    service_cluster_ip_range: 172.16.0.0/16
    # Expose a different port range for NodePort services
    service_node_port_range: 30000-32767
    pod_security_policy: false
  kube-controller:
    # CIDR pool used to assign IP addresses to pods in the cluster
    cluster_cidr: 172.16.0.0/16
    service_cluster_ip_range: 172.16.0.0/16
  kubelet:
    # Base domain for the cluster
    cluster_domain: cluster.local
    # IP address for the DNS service endpoint
    cluster_dns_server: 172.16.0.1
    # Fail if swap is on
    fail_swap_on: false

ingress:
  provider: nginx
  node_selector:
    app: none

system_images:
  kubernetes: rancher/hyperkube:v1.10.3-rancher2
  etcd: rancher/coreos-etcd:v3.1.12
  alpine: rancher/rke-tools:v0.1.9
  nginx_proxy: rancher/rke-tools:v0.1.9
  cert_downloader: rancher/rke-tools:v0.1.9
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.9
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  pod_infra_container: rancher/pause-amd64:3.1

  # Flannel Networking Options
  flannel: rancher/coreos-flannel:v0.9.1
  flannel_cni: rancher/coreos-flannel-cni:v0.2.0

  # Calico Networking Options
  calico_node: rancher/calico-node:v3.1.1
  calico_cni: rancher/calico-cni:v3.1.1
  calico_ctl: rancher/calico-ctl:v2.0.0

  # Canal Networking Options
  canal_node: rancher/calico-node:v3.1.1
  canal_cni: rancher/calico-cni:v3.1.1
  canal_flannel: rancher/coreos-flannel:v0.9.1

  # Weave Networking Options
  weave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2

  # Ingress Options
  ingress: rancher/nginx-ingress-controller:0.10.2-rancher3
  ingressBackend: rancher/nginx-ingress-controller-defaultbackend:1.4

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/ssl-redirect: "false"        # Disable redirect to ssl
  spec:
    rules:
    - host: dev-rancher.yit.com
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          args:
          - --no-cacerts
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
```

**Steps to Reproduce:
1. prepare 3 k8s server hosts and a cluster control host with rke installed
2. run `rke up` with the cluster.yml setting above

**Results:
1.rke logs show cluster setup successfully but the kubelet logs on 3 server hosts show a lot of errors.

the hosts keep scheduling kube-dns and kube-dns-autoscaler, the kubelet pod show error logs: open /run/flannel/subnet.env: no such file or directory

I am new to rke and k8s, is there config errors in my cluster.yml?

THX!
