### ISSUE TITLE
Failed to get job complete status: <nil>

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rke#758]
**RKE version:**
0.1.7

**Docker version: (`docker version`,`docker info` preferred)**
1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.5.1805 supported OS, 3.10.0-862.3.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2 autoscaled CloudFormation stack, 3 x c5.large instances

**cluster.yml file:**
```
nodes:
  - address: 10.9.74.200
    user: docker
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/docker/.ssh/id_rsa
  - address: 10.9.4.231
    user: docker
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/docker/.ssh/id_rsa
  - address: 10.9.50.182
    user: docker
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/docker/.ssh/id_rsa

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: |
      [base64 data here]
    tls.key: |
      [base64 data here]
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
      nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
      nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
  spec:
    rules:
    - host: rancher.test.domain.com
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - rancher.test.domain.com
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
```

**Steps to Reproduce:**
SSH keys and configuration files are identical on all 3 instances, I can login from an instance to another with user `docker` and do a `docker ps`:
```
# rke up --config cluster.yml
```

**Results:**
```
INFO[0111] [addons] Executing deploy job..
ERRO[0141] Failed to get job complete status: <nil>
WARN[0141] Failed to deploy addon execute job [rke-user-includes-addons]: Failed to get job complete status: <nil>
INFO[0141] Finished building Kubernetes cluster successfully
```

I tried to perform the troubleshooting steps in [your documentation](https://rancher.com/docs/rancher/v2.x/en/installation/troubleshooting-ha/job-complete-status/):
```
# kubectl --kubeconfig kube_config_rancher-cluster.yml logs -l job-name=rke-user-addon-deploy-job -n kube-system
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server localhost:8080 was refused - did you specify the right host or port?

# kubectl cluster-info dump
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Not sure how to generate the `kube_config_rancher-cluster.yml` file?

We are using Entrust wildcard certificates, Base64 encoded:
```
openssl base64 -in <infile> -out <outfile>
```
Do you recommend a different command to encode the certificates?
