### ISSUE TITLE
Failed to deploy network plugin

### ISSUE THREAD

**Issue by akabos** [rancher/rke#778]
**RKE version:**

```
$ rke --version
rke version v0.1.8
```

**Docker version: (`docker version`,`docker info` preferred)**

```
$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker info
Containers: 248
 Running: 7
 Paused: 0
 Stopped: 241
Images: 6
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.32-rancher2
Operating System: RancherOS v1.4.0
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.82 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
$ cat /etc/os-release
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

```
$ uname -r
4.14.32-rancher2
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare metal

**cluster.yml file:**

```
nodes:
  - address: xxx.xxx.74.176
    internal_address: 192.168.74.176
    user: rancher
    role:
      - etcd
      - controlplane
      - worker
  - address: xxx.xxx.74.178
    internal_address: xxx.xxx.74.178
    user: rancher
    role:
      - etcd
      - controlplane
      - worker
  - address: xxx.xxx.74.180
    internal_address: 192.168.74.180
    user: rancher
    role:
      - etcd
      - controlplane
      - worker

ignore_docker_version: false
ssh_agent_auth: true

authentication:
  strategy: x509

authorization:
  mode: rbac

ingress:
  provider: nginx

addon_job_timeout: 300

services:
  etcd:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
    extra_args:
      audit-log-path: "-"
      delete-collection-workers: 3
      v: 4
  kube-controller:
    service_cluster_ip_range: 10.43.0.0/16
    cluster_cidr: 10.42.0.0/16
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
  scheduler:
  kubeproxy:
```

**Steps to Reproduce:**

```
rke up
```

**Results:**

```
INFO[0000] Building Kubernetes cluster
...
INFO[0072] [worker] Successfully started Worker Plane..
INFO[0072] [sync] Syncing nodes Labels and Taints
INFO[0074] [sync] Successfully synced nodes Labels and Taints
INFO[0074] [network] Setting up network plugin: flannel
INFO[0074] [addons] Saving addon ConfigMap to Kubernetes
INFO[0074] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin
INFO[0074] [addons] Executing deploy job..
ERRO[0383] Failed to get job complete status: <nil>
FATA[0383] Failed to get job complete status: <nil>
```

```
$ docker container ls -a | grep network-plugin
61c176b4a171        ba13700c31f8                         "kubectl apply -f ..."   2 seconds ago        Exited (1) Less than a second ago                       k8s_rke-network-plugin-pod_rke-network-plugin-deploy-job-tc5k8_kube-system_e5cdf0ac-89ae-11e8-97e2-801844ed76c8_0
b7dda864faa4        rancher/pause-amd64:3.1              "/pause"                 2 seconds ago        Up 2 seconds                                            k8s_POD_rke-network-plugin-deploy-job-tc5k8_kube-system_e5cdf0ac-89ae-11e8-97e2-801844ed76c8_0
4401a59ec9a5        ba13700c31f8                         "kubectl apply -f ..."   5 seconds ago        Exited (1) 3 seconds ago                                k8s_rke-network-plugin-pod_rke-network-plugin-deploy-job-xc98n_kube-system_e3df067b-89ae-11e8-97e2-801844ed76c8_0
d88b76215996        rancher/pause-amd64:3.1              "/pause"                 6 seconds ago        Exited (0) 2 seconds ago                                k8s_POD_rke-network-plugin-deploy-job-xc98n_kube-system_e3df067b-89ae-11e8-97e2-801844ed76c8_0
```

```
$ docker logs 61c176b4a171
Unable to connect to the server: dial tcp 10.43.0.1:443: getsockopt: no route to host
```
