### ISSUE TITLE
Snapshot Restore Unable to Extract Certs to /opt/rke/etc/kubernetes/.tmp

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rke#783]
**RKE version:** v0.1.8

**Docker version: (`docker version`,`docker info` preferred)** 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** RancherOS v1.4.0

**cluster.yml file:**

```
ignore_docker_version: true

nodes:
  - address: 159.65.102.198
    user: rancher
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: ~/.ssh/id_rsa

  - address: 159.65.107.8
    user: rancher
    role:
      - controlplane
      - worker
    ssh_key_path: ~/.ssh/id_rsa

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 1440m # time increment between shapshots
    retention: 168h # time increment before snapshot purge

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system

  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system

  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io

  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: 
    tls.key: 

  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle

  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  spec:
    rules:
    - host: massimoros.do.rancher.space
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - massimoros.do.rancher.space

  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:v2.0.4
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
```

**Steps to Reproduce:**

1. Deploy a brand new rke cluster using rancher:**v2.0.4**
2. Create etcd snapshot
3. Upgrade to rancher:**v2.0.6**
4. Restore snapshot

**Results:**
FATA[0005] Failed to extract certificate bundle on host [159.65.107.8], please make sure etcd bundle exist in /opt/rke/etcd-snapshots/pki.bundle.tar.gz: Failed to run certificate bundle extract, exit status is: 1,Failed to extract certificate bundle on host [159.65.102.198], please make sure etcd bundle exist in /opt/rke/etcd-snapshots/pki.bundle.tar.gz: Failed to run certificate bundle extract, exit status is: 1

**Summary**:

```
mkdir -p /etc/kubernetes/.tmp/; tar xzvf /backup/pki.bundle.tar.gz -C /opt/rke/etc/kubernetes/.tmp --strip-components 5"

"Binds": [
                "/opt/rke/etc/kubernetes:/etc/kubernetes:z",
                "/opt/rke/etcd-snapshots:/backup:z"
            ],
            
"Mounts": [
            {
                "Type": "bind",
                "Source": "/opt/rke/etc/kubernetes",
                "Destination": "/etc/kubernetes",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/opt/rke/etcd-snapshots",
                "Destination": "/backup",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "ebb6e79c30bb38c8bc58b2537d3dfaff5c2a84b60dfe3ca335d5a1a32e6f8176",
                "Source": "/var/lib/docker/volumes/ebb6e79c30bb38c8bc58b2537d3dfaff5c2a84b60dfe3ca335d5a1a32e6f8176/_data",
                "Destination": "/opt/rke",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
```

The problem is with the **mkdir -p /etc/kubernetes/.tmp/;** 

https://github.com/rancher/rke/blob/master/pki/pki.go#L267

```
tar: can't change directory to '/opt/rke/etc/kubernetes/.tmp': No such file or directory
```

I also had to create the pki cert bundle:

```
[rancher@massimo-rancheros-02 ~]$ docker container rm rke-bundle-cert

[rancher@massimo-rancheros-02 ~]$ docker container run \
  -v /opt/rke/etc/kubernetes:/opt/rke/etc/kubernetes \
  hellyna/tar -zcvf /opt/rke/etc/kubernetes/pki.bundle.tar.gz /opt/rke/etc/kubernetes

[rancher@massimo-rancheros-02 ~]$ sudo mv /opt/rke/etc/kubernetes/pki.bundle.tar.gz /opt/rke/etcd-snapshots/
```
