### ISSUE TITLE
Snapshot Save Unable to Archive Certs to /opt/rke/etcd-snapshots/

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rke#821]
**RKE version:** v0.1.9-rc3

**Docker version: (`docker version`,`docker info` preferred)** 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** RancherOS v1.4.0

**cluster.yml file:**

```
ignore_docker_version: true

nodes:
  - address: 159.65.102.198
    user: rancher
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: ~/.ssh/id_rsa

  - address: 159.65.107.8
    user: rancher
    role:
      - controlplane
      - worker
    ssh_key_path: ~/.ssh/id_rsa

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 1440m # time increment between shapshots
    retention: 168h # time increment before snapshot purge

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system

  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system

  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io

  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: 
    tls.key: 

  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle

  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  spec:
    rules:
    - host: massimoros.do.rancher.space
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - massimoros.do.rancher.space

  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
```

**Steps to Reproduce:**

1. Deploy a brand new rke cluster using rancher:**latest**
2. Create etcd snapshot

**Results:**

The pki.bundle.tar.gz is missing from **/opt/rke/etcd-snapshots/** after **deploying** the cluster and after creating the **snapshot**. If you try to restore the snapshot it will complain about the missing pki bundle. This issue seems to only occur on **RancherOS**.

https://github.com/rancher/rke/blob/master/pki/pki.go#L236

```
path.Join(host.PrefixPath, TempCertPath)
```

That seems to be the issue, I removed **host.PrefixPath** and tested it on RancherOS and the issue was resolved. Now on **Ubuntu 16.04** it seems that host.PrefixPath does not break anything. If I remove it, the same outcome occurs. 

**Summary:**

path.Join(host.PrefixPath, TempCertPath) vs TempCertPath on Ubuntu 16.04 is the same but on RancherOS it appends **/opt/rke** to /etc/kubernetes.

**RancherOS**

```
"Args": [
            "-c",
            "if [ -d /opt/rke/etc/kubernetes/.tmp ] && [ \"$(ls -A /opt/rke/etc/kubernetes/.tmp)\" ]; then tar czvf /backup/pki.bundle.tar.gz /opt/rke/etc/kubernetes/.tmp;fi"
        ],


"Binds": [
                "/opt/rke/etc/kubernetes:/etc/kubernetes:z",
                "/opt/rke/etcd-snapshots:/backup:z"
            ],
```

**Ubuntu 16.04**

```
"Args": [
            "-c",
            "if [ -d /etc/kubernetes/.tmp ] && [ \"$(ls -A /etc/kubernetes/.tmp)\" ]; then tar czvf /backup/pki.bundle.tar.gz /etc/kubernetes/.tmp;fi"
        ],


"Binds": [
                "/opt/rke/etc/kubernetes:/etc/kubernetes:z",
                "/opt/rke/etcd-snapshots:/backup:z"
            ],
```
