### ISSUE TITLE
[Question] RKE doesn't support all official kube-api kube-controller kubelet options?

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rke#823]
**RKE version:** 0.1.8

Hi, 

In the full cluster.yml file I can see we can define a few args to kube-api kube-controller kubelet services, so I changed cluster.yml as this:
```
services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 30000-32767
    pod_security_policy: false
    extra_args:
      audit-log-path: "-"
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
    node_monitor_period: 2s
    node_monitor_grace_period: 16s
    pod_eviction_timeout: 30s    
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    node_status_update_frequency: 4s
    kube_reserved: cpu=500m,memory=1Gi
    system_reserved: cpu=500m,memory=1Gi
```

After rke up, these args are not working, does rke support args only in the sample cluster.yml???

**Comment by hiscal2015** [comment]
done by using extra-args like this:

```
services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 30000-32767
    pod_security_policy: false
    extra_args:
      audit-log-path: "-"
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
    extra_args:
      node-monitor-period: 2s
      node-monitor-grace-period: 16s
      pod-eviction-timeout: 30s    
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    extra_args:
      node-status-update-frequency: 4s
      kube-reserved: cpu=500m,memory=1Gi
      system-reserved: cpu=500m,memory=1Gi
```
