### ISSUE TITLE
/opt/rke/entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#846]
**RKE version:**
rke version v0.1.9-rc9
rke-tools version 0.1.13, forked with a minor change to permissions that I'm testing for the cloud-provider.sh file. I've uploaded this to a private registry as tag:

```
privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CoreOS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**cluster.yml file:**
Kubernetes version: Default (rancher/hyperkube:v1.11.1-rancher1)

```
system_images:
  alpine: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
  nginx_proxy: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
  cert_downloader: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
  kubernetes_services_sidecar: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
```

**Steps to Reproduce:**
```
rke up --disable-port-check
```

**Results:**

```
FATA[0141] [controlPlane] Failed to bring up Control Plane:
  Failed to start [kube-apiserver] container on host [10.18.160.21]:
  Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247:
  starting container process caused \"exec: \\\"/opt/rke/entrypoint.sh\\\":
  stat /opt/rke/entrypoint.sh: no such file or directory\"\n" 
```

This should have hit `/opt/rke-tools/entrypoint.sh`

**Comment by galal-hussein** [comment]
@HighwayofLife can you check if you tagged your image as v0.1.13 instead of v0.1.14 and ran rke up will cause the same error?

**Comment by moelsayed** [comment]
@HighwayofLife I retagged `0.1.13` as `0.1.14` and created a cluster on both CoreOS and ubuntu with the default k8s version. In both cases the process completed successfully. 

Can you please share the cluster file ?

**Comment by HighwayofLife** [comment]
I initially used tag `v0.1.13-1`, and after that failed, retagged and redeployed with `v0.1.14`, but I think it was still trying to use the `v0.1.13-1` version for some reason. I'm attempting to reproduce.

**Comment by HighwayofLife** [comment]
This makes sense now, initially loading in an rke-tools with a tag of `v0.1.13-1` caused the check to default to legacy entrypoint.sh, and loading in the updated version of rke-tools doesn't cause the kube-apiserver to start with a different entrypoint, so that's why it still won't work even after correcting the rke-tools tag.

**Comment by HighwayofLife** [comment]
I destroyed my dev cluster and spun up a completely fresh cluster with the following cluster.yml file, and it came back with the same (incorrect) entrypoint.sh:

```
---
nodes:
- address: 10.18.160.20
  hostname_override: devcluster-master0
  internal_address: 10.18.160.20
  role:
  - controlplane
  - etcd
  user: devadmin
- address: 10.18.160.22
  hostname_override: devcluster-master1
  internal_address: 10.18.160.22
  role:
  - controlplane
  - etcd
  user: devadmin
- address: 10.18.160.21
  hostname_override: devcluster-master2
  internal_address: 10.18.160.21
  role:
  - controlplane
  - etcd
  user: devadmin
- address: 10.18.160.19
  hostname_override: devcluster-worker0
  internal_address: 10.18.160.19
  role:
  - worker
  user: devadmin
  labels:
    app: ingress
- address: 10.18.160.17
  hostname_override: devcluster-worker1
  internal_address: 10.18.160.17
  role:
  - worker
  user: devadmin
  labels:
    app: ingress
- address: 10.18.160.18
  hostname_override: devcluster-worker2
  internal_address: 10.18.160.18
  role:
  - worker
  user: devadmin
  labels:
    app: ingress
private_registries:
- url: privateregistry.azurecr.io
  user: <redacted>
  password: <redacted>
authentication:
  strategy: x509
  sans:
  - 10.18.160.70
ssh_key_path: "../keys/<redacted>"
cloud_provider:
  name: azure
  azureCloudProvider:
    <redacted>
network:
  plugin: canal
authorization:
  mode: rbac
services:
  etcd:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    extra_args:
      oidc-client-id: "spn:<redacted>"
      oidc-issuer-url: "https://sts.windows.net/<redacted>"
      oidc-username-claim: "upn"
      oidc-groups-claim: "groups"
      v: 2
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
    extra_args:
      v: 2
  scheduler:
  kubelet:
    cluster_domain: dev.<redacted>.net
    cluster_dns_server: 10.43.0.10
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args:
      v: 2
      authentication-token-webhook: true
  kubeproxy:
ignore_docker_version: true
cluster_name: "devcluster"
ingress:
  provider: nginx
  node_selector:
    app: ingress

system_images:
  alpine: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
  nginx_proxy: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
  cert_downloader: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14
  kubernetes_services_sidecar: privateregistry.azurecr.io/rancher/rke-tools:v0.1.14

addons_include:
  - ../manifests/azure-ad-kube-rolebind.yml
```
