### ISSUE TITLE
Can't create etcd one-shot backup

### ISSUE THREAD

**Issue by carloscarnero** [rancher/rke#859]
**RKE version:**

```
$ rke --version
rke version v0.1.9
```

**Docker version: (`docker version`,`docker info` preferred)**

```
$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-68.gitdded712.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      dded712/1.13.1
 Built:           Tue Jul 17 18:34:48 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-68.gitdded712.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      dded712/1.13.1
 Built:           Tue Jul 17 18:34:48 2018
 OS/Arch:         linux/amd64
 Experimental:    false

$ docker info
Containers: 46
 Running: 20
 Paused: 0
 Stopped: 26
Images: 15
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 8
Total Memory: 5.827 GiB
Name: cfdd9f3c.<redacted>
ID: 52B6:LIWV:QZEB:RIUZ:KV3T:W6T6:U5XP:WKXS:2SWN:LR4Y:5N7T:V4SA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

The system is a pretty basic (bare) Docker-dedicated CentOS 7 install, updated up to the latest bits available. SELinux is enabled.

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -r
3.10.0-862.9.1.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal (actually, virtual machines under VMware).

**cluster.yml file:**

This is a cluster created with `rke` dedicated to Rancher, built as per the [documentation for an HA deployment](https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install-external-lb/).

```yaml
---
cluster_name: rancher
nodes:
- address: cfdd9f3c.<redacted>
  user: dockeruser
  role:
  - controlplane
  - etcd
  - worker
  ssh_key_path: ~/.ssh/id_rsa
- address: b5833011.<redacted>
  user: dockeruser
  role:
  - controlplane
  - etcd
  - worker
  ssh_key_path: ~/.ssh/id_rsa
- address: 307309d8.<redacted>
  user: dockeruser
  role:
  - controlplane
  - etcd
  - worker
  ssh_key_path: ~/.ssh/id_rsa
addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  spec:
    rules:
    - host: rancher.<redacted>
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: <redacted>:5000/substratum/rancher:v2.0.6
          env:
          - name: CATTLE_AGENT_IMAGE
            value: "<redacted>:5000/substratum/rancher-agent:v2.0.6"
          args:
          - --no-cacerts
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
system_images:
  kubernetes: <redacted>:5000/substratum/hyperkube:v1.10.3-rancher2
  etcd: <redacted>:5000/substratum/coreos-etcd:v3.1.12
  alpine: <redacted>:5000/substratum/rke-tools:v0.1.10
  nginx_proxy: <redacted>:5000/substratum/rke-tools:v0.1.10
  cert_downloader: <redacted>:5000/substratum/rke-tools:v0.1.10
  kubernetes_services_sidecar: <redacted>:5000/substratum/rke-tools:v0.1.10
  kubedns: <redacted>:5000/substratum/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: <redacted>:5000/substratum/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: <redacted>:5000/substratum/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: <redacted>:5000/substratum/cluster-proportional-autoscaler-amd64:1.0.0
  pod_infra_container: <redacted>:5000/substratum/pause-amd64:3.1
  flannel: <redacted>:5000/substratum/coreos-flannel:v0.9.1
  flannel_cni: <redacted>:5000/substratum/coreos-flannel-cni:v0.2.0
  calico_node: <redacted>:5000/substratum/calico-node:v3.1.1
  calico_cni: <redacted>:5000/substratum/calico-cni:v3.1.1
  calico_ctl: <redacted>:5000/substratum/calico-ctl:v2.0.0
  canal_node: <redacted>:5000/substratum/calico-node:v3.1.1
  canal_cni: <redacted>:5000/substratum/calico-cni:v3.1.1
  canal_flannel: <redacted>:5000/substratum/coreos-flannel:v0.9.1
  weave_node: <redacted>:5000/substratum/weave-kube:2.1.2
  weave_cni: <redacted>:5000/substratum/weave-npc:2.1.2
  ingress: <redacted>:5000/substratum/nginx-ingress-controller:0.10.2-rancher3
  ingress_backend: <redacted>:5000/substratum/nginx-ingress-controller-defaultbackend:1.4
  metrics_server: <redacted>:5000/substratum/metrics-server-amd64:v0.2.1
```

The cluster is working properly after many tests:

```
$ kubectl get nodes
NAME                  STATUS    ROLES                      AGE       VERSION
307309d8.<redacted>   Ready     controlplane,etcd,worker   5d        v1.10.3
b5833011.<redacted>   Ready     controlplane,etcd,worker   5d        v1.10.3
cfdd9f3c.<redacted>   Ready     controlplane,etcd,worker   5d        v1.10.3

$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
cattle-system   cattle-557745c69-5hqkv                    1/1       Running     1          3h
cattle-system   cattle-cluster-agent-7b695dcd88-jmwck     1/1       Running     0          3h
cattle-system   cattle-node-agent-6khv4                   1/1       Running     0          3h
cattle-system   cattle-node-agent-8s8cz                   1/1       Running     0          3h
cattle-system   cattle-node-agent-mp5mp                   1/1       Running     0          3h
ingress-nginx   default-http-backend-5568f7fbb9-tl8wd     1/1       Running     1          4d
ingress-nginx   nginx-ingress-controller-8g55g            1/1       Running     1          5d
ingress-nginx   nginx-ingress-controller-c7jq6            1/1       Running     1          5d
ingress-nginx   nginx-ingress-controller-r8c4k            1/1       Running     1          5d
kube-system     canal-268qr                               3/3       Running     3          5h
kube-system     canal-bcl8l                               3/3       Running     3          5h
kube-system     canal-rvh9h                               3/3       Running     3          5h
kube-system     kube-dns-69c948c598-7spmr                 3/3       Running     3          5d
kube-system     kube-dns-autoscaler-79c8f7cbcd-6tfj2      1/1       Running     1          5d
kube-system     metrics-server-56db7f5bc9-x2sfq           1/1       Running     2          5h
kube-system     rke-ingress-controller-deploy-job-ptfp8   0/1       Completed   0          3h
kube-system     rke-kubedns-addon-deploy-job-45dqs        0/1       Completed   0          5d
kube-system     rke-metrics-addon-deploy-job-hbwt8        0/1       Completed   0          5h
kube-system     rke-network-plugin-deploy-job-4pdb7       0/1       Completed   0          5h
kube-system     rke-user-addon-deploy-job-sm7vw           0/1       Completed   0          3h
```

**Steps to Reproduce:**

I'm trying to create a one-shot named etcd backup and very quickly get an error:

```
rke etcd snapshot-save --name test.backup --config rancher-cluster.yml 
INFO[0000] Starting saving snapshot on etcd hosts       
INFO[0000] [dialer] Setup tunnel for host [cfdd9f3c.<redacted>] 
INFO[0001] [dialer] Setup tunnel for host [b5833011.<redacted>] 
INFO[0001] [dialer] Setup tunnel for host [307309d8.<redacted>] 
INFO[0002] [etcd] Saving snapshot [test.backup] on host [cfdd9f3c.<redacted>] 
FATA[0003] Failed to start [etcd-snapshot-once] container on host [cfdd9f3c.<redacted>]: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/opt/rke-tools/rke-etcd-backup\": stat /opt/rke-tools/rke-etcd-backup: no such file or directory"
```

I tried an unnamed backup, but the same error is present. The `rke-tools` image version is `v0.1.10` and I tried running a shell there, and there's no `/opt/rke-tools/rke-etcd-backup` file but `/opt/rke/rke-etcd-backup`:

```
docker run --rm -it <redacted>:5000/substratum/rke-tools:v0.1.10
bash-4.4# ls -l /opt
total 0
drwxr-xr-x    3 root     root            17 Jun 20 18:16 cni
drwxr-xr-x    3 root     root           115 Aug 13 20:34 rke
bash-4.4# ls -l /opt/rke
total 3300
drwxr-xr-x    2 root     root            20 Jun 20 18:16 bin
-rwxr-xr-x    1 root     root          2943 Jun 20 18:15 cloud-provider.sh
-rwxr-xr-x    1 root     root          1658 Jun 20 18:15 entrypoint.sh
-rwxr-xr-x    1 root     root       3366656 Jun 20 18:15 rke-etcd-backup
-rwxr-xr-x    1 root     root           121 Jun 20 18:15 weave-loopback-cni.sh
```

I have not created or configured the automated etcd backup service. Should I?
