### ISSUE TITLE
Allow custom CNI deployments by using "network: none"

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#873]
Currently RKE supports Flannel, Calico, Canal, and Weave as network plugins. For users who have their own (custom) CNI solution, would be good to have a none or "opt-out" option. Could look something like this in the cluster.yml:

```
network:
    plugin: none
```
or
```
network:
    plugin: custom
```

**Comment by dnoland1** [comment]
@alena1108 Here's a little more information on the use case. Before RKE is run, a custom CNI configuration file will be placed in `/etc/cni/net.d/` and a custom CNI binary in `/opt/cni/bin/` on the host. If needed or if it's not the default, can add this into RKE's cluster.yml:
```
services:
  kubelet:
    extra_args:
      cni-conf-dir: "/etc/cni/net.d"
      cni-bin-dir: "/opt/cni/bin"
```
May need bind-args as well to map the above directories on the host into kubelet's container.
So I believe if the above is in place and RKE does not deploy it's own network plugin, pod-to-pod networking should work, including DNS.
