### ISSUE TITLE
rke-port-checker cannot run when user namespaces are enabled 

### ISSUE THREAD

**Issue by hasonhai** [rancher/rke#878]
Hello,
I configured docker to use user mapping to prevent root inside container can breakout and escalate their privileges to host's root. However, rke broke down after the config. I can run other container normally, but for rke, the rke-port-checker contianer cannot run and it stops the depolyment process.
Is there any way to solve this? thanks a lot!

**RKE version:**
rke version v0.1.9-rc6

**Docker version: (`docker version`,`docker info` preferred)**
Docker version
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
Docker info:

```
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: rhel-docker
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 705.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.7 GB
 Metadata Space Used: 421.9 kB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.073 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.75 GiB
Name: DEFR4APP512
ID: JEFZ:NGR6:KOYS:DBQP:DFYH:S2EE:7S7R:JWVJ:GA6O:MDVF:ZCF5:HU7G
Docker Root Dir: /var/lib/docker/100000.100000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
RHEL 7.5 Red Hat Enterprise Linux
3.10.0-862.11.6.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`Hyper-V VMs` 

**cluster.yml file:**

```
---
nodes:
  - address: 10.145.xxx.xx1
    user: sonha
    role:
    - controlplane
    - etcd
    ssh_key_path: /home/sonha/.ssh/login.key
    port: 22
  - address: 10.145.xxx.xx2
    user: sonha
    ssh_key_path: /home/sonha/.ssh/login.key
    internal_address: ""
    port: 22
    role:
    - worker
    labels:
      ingress: true
  - address: 10.145.xxx.xx3
    user: sonha
    ssh_key_path: /home/sonha/.ssh/login.key
    internal_address: ""
    port: 22
    role:
    - worker
    labels:
      ingress: true
  - address: 10.145.xxx.xx4
    user: sonha
    ssh_key_path: /home/sonha/.ssh/login.key
    internal_address: ""
    port: 22
    role:
    - worker
    labels:
      ingress: true

services:
  etcd:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: true
    service_node_port_range: 30000-32767
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
      # Increase number of delete workers
      delete-collection-workers: 3
      # Set the level of log output to debug-level
      v: 4

  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
  kubelet:
    cluster_domain: aap.mycompany
    cluster_dns_server: 10.43.0.10
    infra_container_image: gcr.io/google_containers/pause-amd64:3.1
    # Optionally define additional volume binds to a service
    extra_binds:
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
      - "/lib/modules:/lib/modules"
  kubeproxy:

network:
  plugin: calico
  options: {}

authentication:
  strategy: x509

system_images:
  etcd: quay.io/coreos/etcd:v3.2.18
  kubernetes: rancher/hyperkube:v1.11.1-rancher1
  alpine: rancher/rke-tools:v0.1.12
  nginx_proxy: rancher/rke-tools:v0.1.12
  cert_downloader: rancher/rke-tools:v0.1.12
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.12
  kubedns: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.10
  dnsmasq: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  kubedns_sidecar: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.10
  kubedns_autoscaler: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0
  calico_node: quay.io/calico/node:v3.1.1
  calico_cni: quay.io/calico/cni:v3.1.1
  calico_ctl: quay.io/calico/ctl:v2.0.0
  ingress: rancher/nginx-ingress-controller:0.16.2-rancher1
  ingress_backend: k8s.gcr.io/defaultbackend:1.4
  pod_infra_container: gcr.io/google_containers/pause-amd64:3.1

ssh_key_path: ~/.ssh/

# Kubernetes authorization mode
authorization:
  mode: rbac

# If set to true, rke won't fail when unsupported Docker version is found
ignore_docker_version: false
# The kubernetes version used. For now, this should match the version defined in rancher/types defaults map: https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go#L14
kubernetes_version: v1.11.1-rancher1-1

# addons are deployed using kubernetes jobs. RKE will give up on trying to get the job status after this timeout in seconds..
addon_job_timeout: 30
# If set, this is the cluster name that will be used in the kube config file
# Default value is "local"
cluster_name: aaptest

private_registries:
  - url: registry.com
    user: Username
    password: password

# Bastion/Jump host configuration
bastion_host:
  address: 10.145.xxx.xx5
  user: sonha
  port: 22
  ssh_key_path: /home/sonha/.ssh/login.key
```

**Steps to Reproduce:**
```
./rke_linux-amd64 up --config cluster2.yml
**Results:**
WARN[0000] This is not an officially supported version (v0.1.9-rc6) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [10.145.xxx.xx1]
INFO[0000] [dialer] Setup tunnel for host [10.145.xxx.xx2]
INFO[0001] [dialer] Setup tunnel for host [10.145.xxx.xx3]
INFO[0001] [dialer] Setup tunnel for host [10.145.xxx.xx4]
INFO[0002] [network] Deploying port listener containers
INFO[0002] [network] Port listener containers deployed successfully
INFO[0002] [network] Running control plane -> etcd port checks
FATA[0002] Failed to create [rke-port-checker] container on host [10.145.xxx.xx1]: Error response from daemon: Cannot share the host's network namespace when user namespaces are enabled
```
