### ISSUE TITLE
Enable rke etcd snapshot backups by default.

### ISSUE THREAD

**Issue by jgreat** [rancher/rke#888]
Enable etcd snapshots by default on new clusters.

The documentation makes you go back to enable backups when installing Rancher Server. We could modify the documentation, but less required config the better for guiding users through a new install.

Etcd snapshot files tend to be small (MB in size). There is very little down side and lots of users who may be saved by creating backups automatically at reasonable intervals. 

Since I suggest every 12h with 3 day retention. 

```
services:
  etcd:
    snapshot: true
    retention: 3d
    creation: 12h
```

**RKE version:**
0.1.9

**Comment by alena1108** [comment]
@moelsayed @galal-hussein any implications of enabling etcd snapshots by default?

**Comment by galal-hussein** [comment]
i don't see a problem with enabling it by default except that overtime the snapshot may increase in size and cause disk space issues on the user's servers, i think the user should be fully aware of enabling the rolling snapshots.

**Comment by soumyalj** [comment]
Tested with rke version v0.1.12-rc3 .
1. Created a RKE cluster without etcd snapshot section. There were backups taken every 12 hours as expected. 
2. Also, RKE cluster was created for below cases in the config file to ensure no regressions have occured. 
```
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 5m0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```
3. 
```
services:
  etcd:
    snapshot: false # enables recurring etcd snapshots
    creation: 5m0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```
