### ISSUE TITLE
Support an option to enable specified feature gates in all components

### ISSUE THREAD

**Issue by yasker** [rancher/rke#923]
It's painful to enable feature gates for Kubernetes with RKE. The only way to do it now is the `extra_args`. And the best way to make sure the feature gate has been enabled is to enable it in all the components. It will result in something like this:

```
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    extra_args: 
      feature-gates: "DynamicProvisioningScheduling=true"
    pod_security_policy: false
  kube-controller: 
    extra_args: 
      feature-gates: "DynamicProvisioningScheduling=true"
  kubelet: 
    extra_args: 
      feature-gates: "DynamicProvisioningScheduling=true"
    fail_swap_on: false
  scheduler: 
    extra_args: 
      feature-gates: "DynamicProvisioningScheduling=true"
  kubeproxy: 
    extra_args: 
      feature-gates: "DynamicProvisioningScheduling=true"
```

1. The settings are duplicated.
2. The service names are **random**. There is no way to tell that a user should use `scheduler` instead of `kube-scheduler`, `kubeproxy` instead of `kube-proxy`, `kube-controller` instead of `kube-controller-manager` unless they look into the [code](https://github.com/rancher/rke/blob/1f6e254f6698a26751d2948504d915348d6fda0a/vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go#L150) and found this:
```
type RKEConfigServices struct {
	// Etcd Service
	Etcd ETCDService `yaml:"etcd" json:"etcd,omitempty"`
	// KubeAPI Service
	KubeAPI KubeAPIService `yaml:"kube-api" json:"kubeApi,omitempty"`
	// KubeController Service
	KubeController KubeControllerService `yaml:"kube-controller" json:"kubeController,omitempty"`
	// Scheduler Service
	Scheduler SchedulerService `yaml:"scheduler" json:"scheduler,omitempty"`
	// Kubelet Service
	Kubelet KubeletService `yaml:"kubelet" json:"kubelet,omitempty"`
	// KubeProxy Service
	Kubeproxy KubeproxyService `yaml:"kubeproxy" json:"kubeproxy,omitempty"`
}
```

Besides of the naming issue, I'd like to have a separate option available to the user to enable feature gate for all the components, e.g.
```
services: 
  feature-gates:
  - DynamicProvisioningScheduling=true
  - VolumeSnapshotDataSource=true
  - AppArmor=false
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    pod_security_policy: false
```

Then RKE will apply those feature gates to the all the Kubernetes components, which should ensure that the feature gate setting will be in effect.
