### ISSUE TITLE
Docker version check is ignoring k8s version

### ISSUE THREAD

**Issue by maxkorp** [rancher/rke#931]
**RKE version: Latest (7b771410078bcb2f79f161fc2a1ab1d8294d9dba)**

```
nodes:
    - address: xxx.xxx.xxx.xxx
      internal_address: xxx.xxx.xxx.xxx
      user: ubuntu
      role:
        - controlplane
        - etcd
      ssh_key_path: /Users/maxkorp/.ssh/xxx.pem
    - address: xxx.xxx.xxx.xxx
      internal_address: xxx.xxx.xxx.xxx
      user: ubuntu
      role:
        - worker
      ssh_key_path: /Users/maxkorp/.ssh/xxx.pem
    - address: xxx.xxx.xxx.xxx
      internal_address: 
      user: ubuntu
      role:
        - worker
      ssh_key_path: /Users/maxkorp/.ssh/xxx.pem
kubernetes_version: "v1.12.0-rancher1-1"
```

**Steps to Reproduce:**
try to run `./rke up`

**Results:**
`Unsupported Docker version found [18.06.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]`

Looking in `hosts/tunnel.go`, it appears `K8sVersion` is a const hardcoded to 1.8, rather than being pulled somewhere from the config.
