### ISSUE TITLE
Cannot pull images from private registry in containers

### ISSUE THREAD

**Issue by mmaquevice** [rancher/rke#934]
**RKE version:**
rke version v0.1.9

**Docker version: (`docker version`,`docker info` preferred)**
18.06.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.67-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware

**cluster.yml file:**

```
nodes:
    - address: 192.168.0.21
      hostname_override: kube-1
      user: core
      role:
        - controlplane
        - etcd
    - address: 192.168.0.22
      hostname_override: kube-2
      user: core
      role:
        - worker
    - address: 192.168.0.23
      hostname_override: kube-3
      user: core
      role:
        - worker
      labels:
        app: ingress


# If set to true, RKE will not fail when unsupported Docker version are found
ignore_docker_version: true

# Enable use of SSH agent to use SSH private keys with passphrase
# This requires the environment `SSH_AUTH_SOCK` configured pointing to your SSH agent which has the private key added
ssh_agent_auth: true

private_registries:
    - url: [private proxy registry]
      user: [user]
      password: [password]

system_images:
    kubernetes: [private proxy registry]/rancher/hyperkube:v1.11.1-rancher1
    etcd: [private proxy registry]/rancher/coreos-etcd:v3.2.18
    alpine: [private proxy registry]/rancher/rke-tools:v0.1.13
    nginx_proxy: [private proxy registry]/rancher/rke-tools:v0.1.13
    cert_downloader: [private proxy registry]/rancher/rke-tools:v0.1.13
    kubernetes_services_sidecar: [private proxy registry]/rancher/rke-tools:v0.1.13
    kubedns: [private proxy registry]/rancher/k8s-dns-kube-dns-amd64:1.14.8
    dnsmasq: [private proxy registry]/rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
    kubedns_sidecar: [private proxy registry]/rancher/k8s-dns-sidecar-amd64:1.14.8
    kubedns_autoscaler: [private proxy registry]/rancher/cluster-proportional-autoscaler-amd64:1.0.0
    pod_infra_container: [private proxy registry]/rancher/pause-amd64:3.1
   
    # Flannel Networking Options
    flannel: [private proxy registry]/rancher/coreos-flannel:v0.9.1
    flannel_cni: [private proxy registry]/rancher/coreos-flannel-cni:v0.2.0

    # Calico Networking Options
    calico_node: [private proxy registry]/rancher/calico-node:v3.1.1
    calico_cni: [private proxy registry]/rancher/calico-cni:v3.1.1
    calico_ctl: [private proxy registry]/rancher/calico-ctl:v2.0.0

    # Canal
    canal_node: [private proxy registry]/rancher/calico-node:v3.1.1
    canal_cni: [private proxy registry]/rancher/calico-cni:v3.1.1
    canal_flannel: [private proxy registry]/rancher/coreos-flannel:v0.9.1

    # Weave Networking Options
    weave_node: [private proxy registry]/weaveworks/weave-kube:2.1.2
    weave_cni: [private proxy registry]/weaveworks/weave-npc:2.1.2

    # Ingress Options
    ingress: [private proxy registry]/rancher/nginx-ingress-controller:0.10.2-rancher3
    ingress_backend: [private proxy registry]/rancher/nginx-ingress-controller-defaultbackend:1.4
```

**Steps to Reproduce:**
- `rke up`

**Results:**
Final steps:

```
INFO[0064] [network] Setting up network plugin: canal   
INFO[0064] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0064] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin 
INFO[0064] [addons] Executing deploy job..              
FATA[0094] Failed to get job complete status: <nil> 
```

When I look at the kubelet logs, it seems that it can not pull images from my private registry:

```
E1004 15:43:55.865571    7000 pod_workers.go:186] Error syncing pod 11e4d177-c7ea-11e8-8e3f-005056bc01b3 ("rke-network-plugin-deploy-job-jnblv_kube-system(11e4d177-c7ea-11e8-8e3f-005056bc01b3)"), skipping: failed to "CreatePodSandbox" for "rke-network-plugin-deploy-job-jnblv_kube-system(11e4d177-c7ea-11e8-8e3f-005056bc01b3)" with CreatePodSandboxError: "CreatePodSandbox for pod \"rke-network-plugin-deploy-job-jnblv_kube-system(11e4d177-c7ea-11e8-8e3f-005056bc01b3)\" failed: rpc error: code = Unknown desc = failed pulling image \"[private proxy registry]/rancher/pause-amd64:3.1\": Error response from daemon: Get http://[private proxy registry]/v2/: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x15\\x03\\x03\\x00\\x02\\x02P\""
```

If I execute on the node `docker login...` and then pull the image, it works. But the next image to pull will fail.

Image pulling from inside the containers does not seem to work.

Thanks for your help.
