### ISSUE TITLE
rke etcd restore breaks kube-apiserver

### ISSUE THREAD

**Issue by upskill-mrollins** [rancher/rke#949]
**RKE version:**
```
rke version v0.1.10
```

**Docker version: (`docker version`,`docker info` preferred)**
```Containers: 32
 Running: 23
 Paused: 0
 Stopped: 9
Images: 27
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 258
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1063-aws
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-192-168-10-210
ID: QJOY:GAGS:V4BS:NNDU:HS37:Q7FU:6JVP:T7NB:L5GP:3SKJ:XUJY:AF27
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.4.0-1063-aws
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
``` 
AWS: EC2 - m4.large
```

**cluster.yml file:**
```
cluster_name: rancher.dev.example.com

nodes:
  - address: 192.168.10.210 # hostname or IP to access nodes
    user: admin # root user (usually 'root')
    role: [etcd,controlplane,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file
  - address: 192.168.11.15 # hostname or IP to access nodes
    user: admin # root user (usually 'root')
    role: [etcd,controlplane,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file

authentication:
    strategy: x509
    sans:
      - "192.168.10.210"
      - "192.168.11.15"

network:
    plugin: flannel

# CIDR ranges MUST NOT match host or docker0 range!
services:
  kube-api:
    # IP address range for the services in the cluster
    service_cluster_ip_range: 172.20.0.0/16
  kube-controller:
    # IP address range for the pods in the cluster
    cluster_cidr: 172.19.0.0/16
    # IP address range for the services in the cluster
    service_cluster_ip_range: 172.20.0.0/16
  kubelet:
    # Base domain for the cluster
    cluster_domain: cluster.local
    # IP address for the DNS service endpoint
    cluster_dns_server: 172.20.0.5
    # Expose a Read only port for Datadog to get K8s events
    extra_args:
      read-only-port: 10255
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 12h0s # time increment between snapshots
    retention: 72h # time increment before snapshot purge

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/ssl-redirect: "false"        # Disable redirect to ssl
  spec:
    rules:
    - host: rancher.dev.example.com
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          args:
          - --no-cacerts
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
```

**Steps to Reproduce:**
Run the restore command followed by the up command, as documented here: https://rancher.com/docs/rke/v0.1.x/en/etcd-snapshots/

**Results:**
This results in a broken kube-apiserver which fails with the error:
```FATA[0247] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.168.10.210]: Get https://localhost:6443/healthz: EOF, log: I1010 21:51:26.299738       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.```
