### ISSUE TITLE
nginx ingress controller extra_args definition does not work and causes rke-ingress-controller-deploy-job to fail

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#962]
**RKE version:**
0.1.10

**cluster.yml file:**
```
ingress: 
  extra_args: 
    default-backend-service: "ingress-nginx/pretty-error"
  options: 
    custom-http-errors: "404"
  provider: "nginx"
```
**Steps to Reproduce:**
Attempt to set any `extra_args` in the RKE cluster.yml, when cluster is brought up, the nginx-deploy job will fail because of something similar to 
```
namespace/ingress-nginx configured
configmap/nginx-configuration configured
configmap/tcp-services unchanged
configmap/udp-services unchanged
serviceaccount/nginx-ingress-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/nginx-ingress-clusterrole configured
role.rbac.authorization.k8s.io/nginx-ingress-role unchanged
rolebinding.rbac.authorization.k8s.io/nginx-ingress-role-nisa-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-clusterrole-nisa-binding configured
error: error parsing /etc/config/rke-ingress-controller.yaml: error converting YAML to JSON: yaml: line 50: did not find expected key
```

**Comment by superseb** [comment]
See https://github.com/rancher/rke/issues/945 / https://github.com/rancher/rke/pull/954

**Comment by sangeethah** [comment]
This issue shows up as rke-ingress-controller addons  not being able to start successfully when creating cluster having the following yml configurations for ingress using rancher server version - v2.1.1-rc4.


```
ingress: 
  extra_args: 
    default-backend-service: "ingress-nginx/pretty-error"
  options: 
    custom-http-errors: "404"
  provider: "nginx"
```
Logs from  rke-ingress-controller-deploy-job:

```
clusterrole.rbac.authorization.k8s.io/nginx-ingress-clusterrole configured
role.rbac.authorization.k8s.io/nginx-ingress-role unchanged
rolebinding.rbac.authorization.k8s.io/nginx-ingress-role-nisa-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-clusterrole-nisa-binding configured
error: error parsing /etc/config/rke-ingress-controller.yaml: error converting YAML to JSON: yaml: line 50: did not find expected key```

**Comment by sangeethah** [comment]
Tested with rancher server version - v2.1.1-rc6.
Created a cluster with having the following yml configurations:

```
ingress: 
  extra_args: 
    default-backend-service: "ingress-nginx/pretty-error"
  options: 
    custom-http-errors: "404"
  provider: "nginx"
```

nginx ingress controller is able to start successfully with the extra_args:

```
I1017 00:18:45.340801 7 main.go:227] Running in Kubernetes cluster version v1.11 (v1.11.3) - git (clean) commit a4529464e4629c21224b3d52edfe0ea91b072862 - platform linux/amd64
I1017 00:18:45.345290 7 main.go:100] Validated ingress-nginx/pretty-error as the default backend.
I1017 00:18:45.940343 7 nginx.go:250] Starting NGINX Ingress controller
```
