### ISSUE TITLE
RKE will not finish deployment if certain network mounts exist on the target node.

### ISSUE THREAD

**Issue by emm-dee** [rancher/rke#964]
**RKE version:**
`v0.1.10`

**Docker version: (`docker version`,`docker info` preferred)**
`17.0.3`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`Ubuntu 16.04`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**cluster.yml file:**
```
nodes:
  - address: 10.52.130.8
    user: user
    ssh_key_path: /usr2/user/.ssh/id_rsa
    role: [controlplane,worker,etcd]
  - address: 10.52.130.9
    user: user
    ssh_key_path: /usr2/user/.ssh/id_rsa
    role: [controlplane,worker,etcd]
  - address: 10.52.130.45
    user: user
    ssh_key_path: /usr2/user/.ssh/id_rsa
    role: [controlplane,worker,etcd]
```

**Steps to Reproduce:**
`rke up`

**Results:**
Failed deployment with the following error: 
```
FATA[0191] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.52.130.45]: Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: + umount /var/lib/docker/aufs/mnt/7c3207c585e17eeb80d061352d13e8d2d6677ed5719c42a1cd41c34d52c911be/host/usr/local/doc 
```

**Findings**
End result was that the issue was caused by having a network mount to `/usr/local/doc` on the target nodes. When the user removed the network mount, the `rke up` completed successfully. 

Filing issue as customer requires various network mounts across their systems and it would be ideal if the deployment could ignore if any paths are externally mounted. _(More details and chatter is on internal Slack comms on 10/15/2018)_
