### ISSUE TITLE
RKE is not able to create default-http-backend because of pod security policy

### ISSUE THREAD

**Issue by cimnine** [rancher/rke#965]
**RKE version:**

0.1.9

**Docker version: (`docker version`,`docker info` preferred)**

18.06.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

4.15.0-36-generic
Ubuntu 18.04.1 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare Metal

**cluster.yml file:**

```yaml
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 10.58.0.11
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: controller1
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.12
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: controller2
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.13
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: controller3
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.21
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker1
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.22
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker2
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.23
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker3
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.24
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker4
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
- address: 10.58.0.25
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker5
  user: xyz
  docker_socket: /var/run/docker.sock
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 172.16.0.0/16
    service_node_port_range: ""
    pod_security_policy: true
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 172.17.0.0/16
    service_cluster_ip_range: 172.16.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args:
      max-pods: 250
    extra_binds: []
    extra_env: []
    cluster_domain: xyz.com
    infra_container_image: ""
    cluster_dns_server: 172.16.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.2.18
  alpine: rancher/rke-tools:v0.1.13
  nginx_proxy: rancher/rke-tools:v0.1.13
  cert_downloader: rancher/rke-tools:v0.1.13
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.13
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.10
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.11.1-rancher1
  flannel: rancher/coreos-flannel:v0.9.1
  flannel_cni: rancher/coreos-flannel-cni:v0.2.0
  calico_node: rancher/calico-node:v3.1.1
  calico_cni: rancher/calico-cni:v3.1.1
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.1.1
  canal_cni: rancher/calico-cni:v3.1.1
  canal_flannel: rancher/coreos-flannel:v0.9.1
  wave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.16.2-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
  metrics_server: rancher/metrics-server-amd64:v0.2.1
ssh_agent_auth: true
authorization:
  mode: rbac
  options: {}
ignore_docker_version: true
kubernetes_version: ""
private_registries: []
ingress:
  provider: nginx
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: "xyz.com"
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
monitoring:
  provider: ""
  options: {}
```

**Steps to Reproduce:**

Install a cluster with RBAC and Pod Security Policy.

**Results:**

```
$ kubectl -n ingress-nginx describe replicaset.apps/default-http-backend-797c5bc547 
Name:           default-http-backend-797c5bc547
Namespace:      ingress-nginx
Selector:       app=default-http-backend,pod-template-hash=3537167103
Labels:         app=default-http-backend
                pod-template-hash=3537167103
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/default-http-backend
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=default-http-backend
           pod-template-hash=3537167103
  Containers:
   default-http-backend:
    Image:      rancher/nginx-ingress-controller-defaultbackend:1.4
    Port:       8080/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     10m
      memory:  20Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                  From                   Message
  ----     ------        ----                 ----                   -------
  Warning  FailedCreate  15m (x23 over 104m)  replicaset-controller  Error creating: pods "default-http-backend-797c5bc547-" is forbidden: unable to validate against any pod security policy: []
```

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16119

**Comment by cimnine** [comment]
What finally helped was this:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - default-psp
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
roleRef:
  kind: Role
  name: ingress-nginx
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
```

Not sure if this change was required:

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  - 'NET_BIND_SERVICE' # <--- added this based in the issue linked by superseb
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```
