### ISSUE TITLE
nginx ingress controller wont come up when specifying extra args - enable-ssl-passthrough 

### ISSUE THREAD

**Issue by aemneina** [rancher/rke#978]
**RKE version:**
v0.1.10

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS - cloud provider = none

**cluster.yml file:**
```
nodes:
  - address: some-ip
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: my-key

#cloud_provider:
#    name: aws

ingress:
    provider: nginx
    options:
      map-hash-bucket-size: "128"
      ssl-protocols: SSLv2
    extra_args:
      enable-ssl-passthrough: ""
```

**Steps to Reproduce:**
just passing in enable-ssl-passthrough resulted in no ingress controller being created.

rke throws this warning:
```WARN[0110] Failed to deploy addon execute job [rke-ingress-controller]: Failed to get job complete status: <nil>```

logs from failed ingress controller deploy pod
```
$ kubectl logs pod/rke-ingress-controller-deploy-job-8cmtx -n kube-system
namespace/ingress-nginx created
configmap/nginx-configuration created
configmap/tcp-services created
configmap/udp-services created
serviceaccount/nginx-ingress-serviceaccount created
clusterrole.rbac.authorization.k8s.io/nginx-ingress-clusterrole created
role.rbac.authorization.k8s.io/nginx-ingress-role created
rolebinding.rbac.authorization.k8s.io/nginx-ingress-role-nisa-binding created
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-clusterrole-nisa-binding created
error: error parsing /etc/config/rke-ingress-controller.yaml: error converting YAML to JSON: yaml: line 50: did not find expected key
```
