### ISSUE TITLE
Use recommended admission controllers for clusters

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#995]
**RKE version:**
0.1.11

**cluster.yml file:**
```
addon_job_timeout: 30
authentication:
  strategy: "x509"
bastion_host:
  ssh_agent_auth: false
ignore_docker_version: true
#
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
#
ingress:
  provider: "nginx"
kubernetes_version: "v1.11.3-rancher1-1"
monitoring:
  provider: "metrics-server"
#
#   # If you are using calico on AWS
#
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
#
#   # To specify flannel interface
#
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
#
#   # To specify flannel interface for canal plugin
#
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
#
network:
  options:
    flannel_backend_type: "vxlan"
  plugin: "canal"
#
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
#
services:
  etcd:
    extra_args:
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api:
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kubelet:
    fail_swap_on: false
ssh_agent_auth: false
```
**Steps to Reproduce:**
Try to `rke up` using that cluster.yml with nodes attached, or from within `rancher/rancher`
**Results:**
`docker inspect kube-apiserver` reveals that `MutatingAdmissionWebhook,ValidatingAdmissionWebhook` are not in the list of enabled admission plugins. i.e. 

Wrong:
`--enable-admission-plugins=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds`

vs. 

Desired: 
`--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota`
