### ISSUE TITLE
Update cluster always duplicate nodes in Nodes page

### ISSUE THREAD

**Issue by myclau** [rancher/rke#997]
After add segment to cluster.yml:
```
- address: <host1>
      user: <user>
      role:
        - controlplane
        - etcd
        - worker
      hostname_override: <host1>
```
and run rke up again.

Always will show duplicate nodes in 
https://rancher.mydomain/c/clustername/nodes

other than the nodes create using rke first time will not duplicate.
For the new add nodes will duplicate once on this page.
But if you kubectl get all nodes it is normal

Example:

I use rke create cluster with 3 machine hostA,hostB,hostC

from 
https://rancher.mydomain/c/clustername/nodes

I will see 
hostA
hostB
hostC
total 3 nodes

After that I modify cluster to add hostD hostE, and run rke up again to update the cluster
from 
https://rancher.mydomain/c/clustername/nodes

I will see 
hostA
hostB
hostC
hostD
hostD
hostE
hostE

total 7 nodes 

but it should be 5 nodes.

for my cluster config template can found in:
https://github.com/myclau/Rancher2.0_HA_rke/blob/master/cluster.yml

**Comment by alena1108** [comment]
@myclau could you provide more details: 

* what rke version you are using
* do you provision the cluster with rke using `rke up`, and then import it to rancher? If so, what rancher version are you using

**Comment by myclau** [comment]
``` bash
$rke version
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
rancher version is 2.0.8.

To repo create 4vm:
1 as jumbox & LB
1 as etcd
2 as control & worker

using this cluster.yml
```yml
nodes:
  - address: ip2
    user: xxx
    role: [controlplane,etcd]
    hostname_override: ktest02
  - address: ip3
    user: xxx
    role: [worker]
    hostname_override: ktest03
  - address: ip4
    user: xxx
    role: [worker]
    hostname_override: ktest04

#If set to true, RKE will not fail when unsupported Docker version are found
ignore_docker_version: true

#Cluster level SSH private key
# Used if no ssh information is set for the node
ssh_key_path: ./keys/rancher_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
    extra_args:
      election-timeout: "10000"
      heartbeat-interval: "2000"

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: <crt base64>
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/ssl-redirect: "false"        # Disable redirect to ssl
  spec:
    rules:
    - host: <lb domain>
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        # Rancher install via RKE addons is only supported up to v2.0.8
        - image: rancher/rancher:v2.0.8
          imagePullPolicy: Always
          name: cattle-server
  #       env:
  #       - name: HTTP_PROXY
  #         value: "http://your_proxy_address:port"
  #       - name: HTTPS_PROXY
  #         value: "http://your_proxy_address:port"
  #       - name: NO_PROXY
  #         value: "localhost,127.0.0.1,0.0.0.0,10.43.0.0/16,your_network_ranges_that_dont_need_proxy_to_access"
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
          - containerPort: 80
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
```

Run rke up & helm install....

go to node I will see
```
ktest02
ktest03
ktest04
```

then modify cluster.yml
```yml
nodes:
  - address: ip2
    user: xxx
    role: [controlplane,etcd]
    hostname_override: ktest02
  - address: ip3
    user: xxx
    role: [worker]
    hostname_override: ktest03
#  - address: ip4
#    user: xxx
#    role: [worker]
#    hostname_override: ktest04

#If set to true, RKE will not fail when unsupported Docker version are found
ignore_docker_version: true

#Cluster level SSH private key
# Used if no ssh information is set for the node
ssh_key_path: ./keys/rancher_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
    extra_args:
      election-timeout: "10000"
      heartbeat-interval: "2000"

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: <crt base64>
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/ssl-redirect: "false"        # Disable redirect to ssl
  spec:
    rules:
    - host: <lb domain>
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        # Rancher install via RKE addons is only supported up to v2.0.8
        - image: rancher/rancher:v2.0.8
          imagePullPolicy: Always
          name: cattle-server
  #       env:
  #       - name: HTTP_PROXY
  #         value: "http://your_proxy_address:port"
  #       - name: HTTPS_PROXY
  #         value: "http://your_proxy_address:port"
  #       - name: NO_PROXY
  #         value: "localhost,127.0.0.1,0.0.0.0,10.43.0.0/16,your_network_ranges_that_dont_need_proxy_to_access"
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
          - containerPort: 80
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
```

then run ` rke up --update-only`

go to node I will see
```
ktest02
ktest03
```

Still good here

then uncomment ktest04
then run `rke up --update-only` again
go to node I will see
```
ktest02
ktest03
ktest04
ktest04
```
